name = "es"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "es_db"
database_id = "placeholder-replace-after-wrangler-d1-create"

[[kv_namespaces]]
binding = "KV"
id = "placeholder-replace-after-wrangler-kv-create"
