name = "es"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "es"
database_id = "a6b128d4-5bb1-4b1a-944a-eb82fdf940f0"

[[kv_namespaces]]
binding = "KV"
id = "7c655092954044469ccfc878560a9bd6"
