// Spanish false cognates (false friends) — words that look like English but mean something else

export const FALSE_FRIENDS = [
  {
    spanish: 'embarazada',
    looksLike: 'embarrassed',
    actualMeaning: 'pregnant',
    correctUsage: 'To say embarrassed, use avergonzado/a',
    example: 'Ella está embarazada. — She is pregnant.',
    dangerLevel: 'high',
  },
  {
    spanish: 'actualmente',
    looksLike: 'actually',
    actualMeaning: 'currently / at present',
    correctUsage: 'To say actually, use en realidad or de hecho',
    example: 'Actualmente vivo en Madrid. — I currently live in Madrid.',
    dangerLevel: 'high',
  },
  {
    spanish: 'sensible',
    looksLike: 'sensible',
    actualMeaning: 'sensitive',
    correctUsage: 'To say sensible, use sensato/a or razonable',
    example: 'Ella es muy sensible. — She is very sensitive.',
    dangerLevel: 'high',
  },
  {
    spanish: 'éxito',
    looksLike: 'exit',
    actualMeaning: 'success',
    correctUsage: 'To say exit, use salida',
    example: 'Tuvo mucho éxito. — He had a lot of success.',
    dangerLevel: 'high',
  },
  {
    spanish: 'librería',
    looksLike: 'library',
    actualMeaning: 'bookshop / bookstore',
    correctUsage: 'To say library, use biblioteca',
    example: 'Compré el libro en la librería. — I bought the book at the bookshop.',
    dangerLevel: 'high',
  },
  {
    spanish: 'carpeta',
    looksLike: 'carpet',
    actualMeaning: 'folder / binder',
    correctUsage: 'To say carpet, use alfombra',
    example: 'Guarda los documentos en la carpeta. — Keep the documents in the folder.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'realizar',
    looksLike: 'realize',
    actualMeaning: 'to carry out / to accomplish',
    correctUsage: 'To say realize (become aware), use darse cuenta de',
    example: 'Vamos a realizar el proyecto. — We will carry out the project.',
    dangerLevel: 'high',
  },
  {
    spanish: 'recordar',
    looksLike: 'record',
    actualMeaning: 'to remember / to remind',
    correctUsage: 'To say to record, use grabar',
    example: 'No recuerdo su nombre. — I don\'t remember his name.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'largo',
    looksLike: 'large',
    actualMeaning: 'long',
    correctUsage: 'To say large, use grande',
    example: 'El pasillo es muy largo. — The hallway is very long.',
    dangerLevel: 'high',
  },
  {
    spanish: 'sopa',
    looksLike: 'soap',
    actualMeaning: 'soup',
    correctUsage: 'To say soap, use jabón',
    example: 'La sopa está caliente. — The soup is hot.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'introducir',
    looksLike: 'introduce',
    actualMeaning: 'to insert / to enter (data)',
    correctUsage: 'To say introduce someone, use presentar',
    example: 'Introduce tu contraseña. — Enter your password.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'pretender',
    looksLike: 'pretend',
    actualMeaning: 'to aspire to / to intend',
    correctUsage: 'To say pretend, use fingir',
    example: 'Pretende estudiar medicina. — He intends to study medicine.',
    dangerLevel: 'high',
  },
  {
    spanish: 'asistir',
    looksLike: 'assist',
    actualMeaning: 'to attend',
    correctUsage: 'To say assist (help), use ayudar',
    example: 'Asistí a la conferencia. — I attended the conference.',
    dangerLevel: 'high',
  },
  {
    spanish: 'molestar',
    looksLike: 'molest',
    actualMeaning: 'to bother / to annoy',
    correctUsage: 'It is not as strong as the English word — very common in everyday speech',
    example: '¿Te molesta el ruido? — Does the noise bother you?',
    dangerLevel: 'high',
  },
  {
    spanish: 'constipado',
    looksLike: 'constipated',
    actualMeaning: 'having a cold',
    correctUsage: 'To say constipated, use estreñido/a',
    example: 'Estoy constipado. — I have a cold.',
    dangerLevel: 'high',
  },
  {
    spanish: 'simpático',
    looksLike: 'sympathetic',
    actualMeaning: 'nice / friendly / likeable',
    correctUsage: 'To say sympathetic, use comprensivo/a',
    example: 'Tu profesora es muy simpática. — Your teacher is very nice.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'gracioso',
    looksLike: 'gracious',
    actualMeaning: 'funny / amusing',
    correctUsage: 'To say gracious, use amable or cortés',
    example: 'El chiste fue muy gracioso. — The joke was very funny.',
    dangerLevel: 'low',
  },
  {
    spanish: 'tópico',
    looksLike: 'topic',
    actualMeaning: 'cliché / stereotype (in Spain)',
    correctUsage: 'To say topic, use tema',
    example: 'Es un tópico que todos los españoles duermen la siesta. — It\'s a cliché that all Spaniards take siestas.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'compromiso',
    looksLike: 'compromise',
    actualMeaning: 'commitment / engagement / obligation',
    correctUsage: 'To say compromise (mutual concession), use acuerdo or término medio',
    example: 'Tengo un compromiso el viernes. — I have a commitment on Friday.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'padres',
    looksLike: 'fathers',
    actualMeaning: 'parents',
    correctUsage: 'The plural of padre means parents, not just fathers',
    example: 'Mis padres viven en Sevilla. — My parents live in Seville.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'fábrica',
    looksLike: 'fabric',
    actualMeaning: 'factory',
    correctUsage: 'To say fabric (cloth), use tela',
    example: 'Trabaja en una fábrica de coches. — He works in a car factory.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'colegio',
    looksLike: 'college',
    actualMeaning: 'primary/secondary school',
    correctUsage: 'To say college/university, use universidad',
    example: 'Los niños van al colegio. — The children go to school.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'lectura',
    looksLike: 'lecture',
    actualMeaning: 'reading',
    correctUsage: 'To say lecture, use conferencia or clase magistral',
    example: 'La lectura del texto fue difícil. — Reading the text was difficult.',
    dangerLevel: 'low',
  },
  {
    spanish: 'ropa',
    looksLike: 'rope',
    actualMeaning: 'clothing / clothes',
    correctUsage: 'To say rope, use cuerda',
    example: 'Necesito ropa de invierno. — I need winter clothes.',
    dangerLevel: 'low',
  },
  {
    spanish: 'informal',
    looksLike: 'informal',
    actualMeaning: 'unreliable / untrustworthy (about a person)',
    correctUsage: 'Calling someone informal means they can\'t be counted on, not that they\'re casual',
    example: 'Es muy informal — nunca llega a tiempo. — He\'s very unreliable — he never arrives on time.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'ignorar',
    looksLike: 'to ignore',
    actualMeaning: 'to be unaware of / not to know',
    correctUsage: 'In formal Spanish, ignorar often means "not to know." To say ignore (snub), use hacer caso omiso de.',
    example: 'Ignoro por qué no vino. — I don\'t know why he didn\'t come.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'arena',
    looksLike: 'arena',
    actualMeaning: 'sand',
    correctUsage: 'To say arena (sports venue), use estadio, pabellón, or ruedo (bullfighting).',
    example: 'La playa tiene arena blanca. — The beach has white sand.',
    dangerLevel: 'low',
  },
  {
    spanish: 'discutir',
    looksLike: 'to discuss',
    actualMeaning: 'to argue / to quarrel',
    correctUsage: 'To discuss (calmly), use hablar de or tratar. Discutir usually implies an argument.',
    example: 'Discutieron toda la noche. — They argued all night.',
    dangerLevel: 'high',
  },
  {
    spanish: 'enérgico',
    looksLike: 'energetic',
    actualMeaning: 'forceful / vigorous / firm',
    correctUsage: 'Enérgico describes a strong or firm manner, not necessarily high physical energy. For energetic (lively), use activo or lleno de energía.',
    example: 'Dio una respuesta enérgica. — He gave a firm reply.',
    dangerLevel: 'low',
  },
  {
    spanish: 'sano',
    looksLike: 'sane',
    actualMeaning: 'healthy',
    correctUsage: 'To say sane (mentally sound), use cuerdo or sensato. Sano = physically or generally healthy.',
    example: 'Lleva una vida sana. — She leads a healthy life.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'injuria',
    looksLike: 'injury',
    actualMeaning: 'insult / slur',
    correctUsage: 'To say injury (physical), use herida or lesión. Injuria is a verbal or legal affront.',
    example: 'Le lanzó injurias. — He hurled insults at her.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'trampa',
    looksLike: 'tramp',
    actualMeaning: 'trap / trick / cheat',
    correctUsage: 'To say tramp (vagrant), use vagabundo. Trampa = a trap or a cheat.',
    example: 'Hizo trampa en el examen. — He cheated in the exam.',
    dangerLevel: 'low',
  },
  {
    spanish: 'disgusto',
    looksLike: 'disgust',
    actualMeaning: 'upset / annoyance / displeasure',
    correctUsage: 'Disgusto is milder than English disgust. Strong physical disgust is asco or repugnancia.',
    example: 'Le dio un gran disgusto. — It upset him greatly.',
    dangerLevel: 'low',
  },
  {
    spanish: 'preservar',
    looksLike: 'to preserve',
    actualMeaning: 'to preserve (protect)',
    correctUsage: 'Same meaning as English — BUT preservativo means condom, not preservative (food). Use conservante for food preservative.',
    example: 'Sin conservantes artificiales. — Without artificial preservatives.',
    dangerLevel: 'high',
  },
  {
    spanish: 'actual',
    looksLike: 'actual',
    actualMeaning: 'current / present / today\'s',
    correctUsage: 'To say actual (real/genuine), use real or verdadero. Actual = happening now.',
    example: 'El precio actual es más alto. — The current price is higher.',
    dangerLevel: 'high',
  },
  {
    spanish: 'argumento',
    looksLike: 'argument (dispute)',
    actualMeaning: 'plot / storyline / argument (in writing)',
    correctUsage: 'To say argument (fight/dispute), use discusión or pelea.',
    example: 'El argumento de la novela es complejo. — The plot of the novel is complex.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'eventualmente',
    looksLike: 'eventually',
    actualMeaning: 'possibly / if need be / at some point',
    correctUsage: 'To say eventually (after a long time), use al final, con el tiempo, or finalmente.',
    example: 'Eventualmente podría ocurrir. — It could possibly happen.',
    dangerLevel: 'high',
  },
  {
    spanish: 'emocionante',
    looksLike: 'emotional',
    actualMeaning: 'exciting / thrilling / moving',
    correctUsage: 'To say emotional (showing feelings), use emotivo or sentimental.',
    example: 'Fue un partido muy emocionante. — It was a very exciting match.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'comprensivo',
    looksLike: 'comprehensive',
    actualMeaning: 'understanding / sympathetic',
    correctUsage: 'To say comprehensive, use exhaustivo, completo, or amplio.',
    example: 'Mi jefe es muy comprensivo con los errores. — My boss is very understanding about mistakes.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'intoxicado',
    looksLike: 'intoxicated',
    actualMeaning: 'poisoned / suffering from food poisoning',
    correctUsage: 'To say intoxicated (drunk), use borracho or ebrio. Intoxicado = poisoned.',
    example: 'Estoy intoxicado — comí algo malo. — I have food poisoning — I ate something bad.',
    dangerLevel: 'high',
  },
  {
    spanish: 'once',
    looksLike: 'once (one time)',
    actualMeaning: 'eleven',
    correctUsage: 'To say once (one time), use una vez.',
    example: 'Son las once de la noche. — It\'s eleven o\'clock at night.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'suceso',
    looksLike: 'success',
    actualMeaning: 'event / incident / happening',
    correctUsage: 'To say success, use éxito. Suceso = an event that took place.',
    example: 'El suceso ocurrió a medianoche. — The incident occurred at midnight.',
    dangerLevel: 'high',
  },
  {
    spanish: 'genial',
    looksLike: 'genial (friendly)',
    actualMeaning: 'brilliant / fantastic / great',
    correctUsage: 'To say genial (friendly and cheerful), use amable, afable, or simpático.',
    example: '¡Qué idea tan genial! — What a brilliant idea!',
    dangerLevel: 'low',
  },
  {
    spanish: 'apología',
    looksLike: 'apology',
    actualMeaning: 'defense / justification / glorification',
    correctUsage: 'To say apology, use disculpa or perdón. Apología is a formal defense of something.',
    example: 'Hizo una apología del régimen. — He made a defense of the regime.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'reclamar',
    looksLike: 'to reclaim',
    actualMeaning: 'to complain / to demand / to claim (rights)',
    correctUsage: 'To reclaim (take back), use recuperar or recobrar.',
    example: 'Reclamó su dinero. — She demanded her money back.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'grosería',
    looksLike: 'grocery',
    actualMeaning: 'rudeness / vulgarity / rude word',
    correctUsage: 'To say grocery, use supermercado (supermarket) or tienda de comestibles.',
    example: 'Decir eso es una grosería. — Saying that is rude.',
    dangerLevel: 'low',
  },
  {
    spanish: 'bizarro',
    looksLike: 'bizarre',
    actualMeaning: 'brave / gallant (Spain) / weird / bizarre (Latin America)',
    correctUsage: 'In Spain (literary), bizarro means brave. In Latin America it has shifted to mean bizarre/odd like the English.',
    example: 'Un gesto bizarro de valentía. — A brave/gallant gesture.',
    dangerLevel: 'low',
  },
  {
    spanish: 'cuestión',
    looksLike: 'question',
    actualMeaning: 'matter / issue / affair',
    correctUsage: 'To say question (something asked), use pregunta. Cuestión = a topic or issue under consideration.',
    example: 'Es una cuestión de tiempo. — It\'s a matter of time.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'coraje',
    looksLike: 'courage',
    actualMeaning: 'courage (Spain) / anger / rage (Latin America)',
    correctUsage: 'In Spain, coraje = courage/bravery. In Mexico and much of Latin America, coraje = anger. Use valor for courage to be safe everywhere.',
    example: 'Me da coraje cuando llega tarde. (LatAm) — It makes me angry when he arrives late.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'decepción',
    looksLike: 'deception',
    actualMeaning: 'disappointment',
    correctUsage: 'To say deception or deceit, use engaño or fraude',
    example: 'Fue una gran decepción. — It was a great disappointment.',
    dangerLevel: 'high',
  },
  {
    spanish: 'pie',
    looksLike: 'pie (pastry)',
    actualMeaning: 'foot',
    correctUsage: 'To say pie (the pastry), use pastel, tarta, or empanada depending on the country',
    example: 'Me duele el pie. — My foot hurts.',
    dangerLevel: 'high',
  },
  {
    spanish: 'conductor',
    looksLike: 'conductor (music)',
    actualMeaning: 'driver',
    correctUsage: 'To say conductor (of an orchestra), use director de orquesta',
    example: 'El conductor del autobús frenó de golpe. — The bus driver braked suddenly.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'firma',
    looksLike: 'firm (company)',
    actualMeaning: 'signature',
    correctUsage: 'To say firm/company, use empresa or compañía',
    example: 'Necesito tu firma aquí. — I need your signature here.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'mayor',
    looksLike: 'mayor (city official)',
    actualMeaning: 'greater / older / main / major',
    correctUsage: 'To say city mayor, use alcalde/alcaldesa',
    example: 'Él es mayor que yo. — He is older than me.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'ganga',
    looksLike: 'gang',
    actualMeaning: 'bargain / great deal',
    correctUsage: 'To say gang (criminal), use pandilla or banda',
    example: '¡Qué ganga! — What a bargain!',
    dangerLevel: 'high',
  },
  {
    spanish: 'vaso',
    looksLike: 'vase',
    actualMeaning: 'drinking glass',
    correctUsage: 'To say vase (for flowers), use florero or jarrón',
    example: 'Dame un vaso de agua, por favor. — Give me a glass of water, please.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'pena',
    looksLike: 'pain',
    actualMeaning: 'sorrow / shame / penalty',
    correctUsage: 'To say physical or emotional pain, use dolor. Pena can also mean "pity" or "sentence"',
    example: '¡Qué pena! — What a shame!  |  Siente pena por él. — She feels sorry for him.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'nombre',
    looksLike: 'number',
    actualMeaning: 'name',
    correctUsage: 'To say number, use número',
    example: '¿Cuál es tu nombre? — What is your name?',
    dangerLevel: 'high',
  },
  {
    spanish: 'campo',
    looksLike: 'camp',
    actualMeaning: 'field / countryside',
    correctUsage: 'To say camp (camping), use campamento or campo de camping',
    example: 'Vivía en el campo. — He lived in the countryside.',
    dangerLevel: 'low',
  },
  {
    spanish: 'copa',
    looksLike: 'cup (mug)',
    actualMeaning: 'wine glass / trophy cup',
    correctUsage: 'To say a regular cup/mug, use taza. A drinking glass is vaso',
    example: 'Tomamos una copa de vino. — We had a glass of wine.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'librería',
    looksLike: 'library',
    actualMeaning: 'bookshop',
    correctUsage: 'To say library (where you borrow books), use biblioteca',
    example: 'Compré el libro en la librería. — I bought the book at the bookshop.',
    dangerLevel: 'high',
  },
  {
    spanish: 'carpeta',
    looksLike: 'carpet',
    actualMeaning: 'folder / binder',
    correctUsage: 'To say carpet, use alfombra (rug/carpet) or moqueta (fitted carpet)',
    example: 'Guarda los documentos en esa carpeta. — Keep the documents in that folder.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'largo',
    looksLike: 'large',
    actualMeaning: 'long',
    correctUsage: 'To say large/big, use grande or gran',
    example: 'Es una calle muy larga. — It\'s a very long street.',
    dangerLevel: 'high',
  },
  {
    spanish: 'constipado',
    looksLike: 'constipated',
    actualMeaning: 'having a cold (congested)',
    correctUsage: 'To say constipated, use estreñido/a',
    example: 'Estoy constipado — tengo la nariz tapada. — I have a cold — my nose is blocked.',
    dangerLevel: 'high',
  },
  {
    spanish: 'asistir',
    looksLike: 'to assist',
    actualMeaning: 'to attend / to be present at',
    correctUsage: 'To say to assist/help, use ayudar',
    example: 'Asistí a la reunión. — I attended the meeting.',
    dangerLevel: 'high',
  },
  {
    spanish: 'realizar',
    looksLike: 'to realize (to suddenly understand)',
    actualMeaning: 'to carry out / to achieve / to do',
    correctUsage: 'To say realize (grasp mentally), use darse cuenta de',
    example: 'Realizó un gran proyecto. — She carried out a major project.',
    dangerLevel: 'high',
  },
  {
    spanish: 'molestar',
    looksLike: 'to molest',
    actualMeaning: 'to bother / to annoy / to disturb',
    correctUsage: 'To say molest (in the criminal sense), use abusar or acosar',
    example: '¿Te molesta el ruido? — Does the noise bother you?',
    dangerLevel: 'high',
  },
  {
    spanish: 'soportar',
    looksLike: 'to support (emotionally)',
    actualMeaning: 'to tolerate / to put up with / to bear',
    correctUsage: 'To say support (emotionally or financially), use apoyar or sostener',
    example: 'No lo soporto — es insoportable. — I can\'t stand him — he\'s insufferable.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'lectura',
    looksLike: 'lecture',
    actualMeaning: 'reading / a piece of reading',
    correctUsage: 'To say lecture (a talk), use conferencia or charla',
    example: 'Me gusta la lectura. — I enjoy reading.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'pretender',
    looksLike: 'to pretend',
    actualMeaning: 'to try / to aspire to / to aim to',
    correctUsage: 'To say pretend (act as if), use fingir or hacer como si',
    example: 'Pretende conseguir el primer puesto. — He aims to get first place.',
    dangerLevel: 'high',
  },
  {
    spanish: 'simpático',
    looksLike: 'sympathetic',
    actualMeaning: 'friendly / likeable / nice',
    correctUsage: 'To say sympathetic (feeling sorry for someone), use comprensivo/a or empático/a',
    example: 'Es una persona muy simpática. — She\'s a very friendly person.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'gracioso',
    looksLike: 'gracious',
    actualMeaning: 'funny / amusing',
    correctUsage: 'To say gracious (courteous/kind), use amable, cortés, or gentil',
    example: 'Ese chiste es muy gracioso. — That joke is very funny.',
    dangerLevel: 'low',
  },
  {
    spanish: 'recordar',
    looksLike: 'to record',
    actualMeaning: 'to remember / to remind',
    correctUsage: 'To say record (capture audio/video), use grabar',
    example: 'Recuerda que tienes una cita mañana. — Remember you have an appointment tomorrow.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'parientes',
    looksLike: 'parents',
    actualMeaning: 'relatives / family members',
    correctUsage: 'To say parents (mother and father), use padres',
    example: 'Tengo muchos parientes en el sur. — I have many relatives in the south.',
    dangerLevel: 'high',
  },
  {
    spanish: 'embarazada',
    looksLike: 'embarrassed',
    actualMeaning: 'pregnant',
    correctUsage: 'To say embarrassed, use avergonzado/a or estar avergonzado/a',
    example: 'Está embarazada de cinco meses. — She is five months pregnant.',
    dangerLevel: 'high',
  },
  {
    spanish: 'sensible',
    looksLike: 'sensible',
    actualMeaning: 'sensitive / emotional / tender',
    correctUsage: 'To say sensible (having good judgement), use sensato/a or razonable',
    example: 'Es un niño muy sensible y llora fácilmente. — He is a very sensitive child and cries easily.',
    dangerLevel: 'high',
  },
  {
    spanish: 'introducir',
    looksLike: 'to introduce (a person)',
    actualMeaning: 'to insert / to put in / to bring in (formally)',
    correctUsage: 'To introduce a person, use presentar. Introducir is for objects or concepts.',
    example: 'Introdujo los datos en el sistema. — She entered the data into the system.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'éxito',
    looksLike: 'exit',
    actualMeaning: 'success / hit (song, film)',
    correctUsage: 'To say exit, use salida. Éxito means success, not a way out.',
    example: 'El concierto fue un gran éxito. — The concert was a great success.',
    dangerLevel: 'high',
  },
  {
    spanish: 'actualmente',
    looksLike: 'actually',
    actualMeaning: 'currently / at present / nowadays',
    correctUsage: 'To say actually (in fact / really), use en realidad or de hecho',
    example: 'Actualmente vive en Barcelona. — She currently lives in Barcelona.',
    dangerLevel: 'high',
  },
  {
    spanish: 'bizarro',
    looksLike: 'bizarre',
    actualMeaning: 'brave / gallant (in traditional usage); bizarre/odd (in some LatAm countries)',
    correctUsage: 'In Spain, bizarro means courageous. In Latin America it can mean bizarre. Use raro or extraño for bizarre to be safe.',
    example: 'Un soldado bizarro es valiente. — A gallant soldier is brave.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'compromiso',
    looksLike: 'compromise',
    actualMeaning: 'commitment / obligation / engagement (appointment)',
    correctUsage: 'To say compromise (reaching a middle ground), use llegar a un acuerdo or término medio',
    example: 'Tengo un compromiso esta tarde. — I have a commitment this afternoon.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'eventual',
    looksLike: 'eventual',
    actualMeaning: 'possible / contingent / temporary (of a contract)',
    correctUsage: 'To say eventual (final/ultimate), use final or definitivo. Eventual in Spanish means contingent or possible.',
    example: 'Es un trabajador eventual, no fijo. — He is a temporary worker, not permanent.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'discutir',
    looksLike: 'to discuss',
    actualMeaning: 'to argue / to quarrel / to dispute',
    correctUsage: 'To say discuss (talk something over calmly), use hablar de, tratar, or debatir',
    example: 'Estaban discutiendo en voz alta. — They were arguing loudly.',
    dangerLevel: 'high',
  },
  {
    spanish: 'salvar',
    looksLike: 'to salve / to soothe',
    actualMeaning: 'to save / to rescue',
    correctUsage: 'To soothe or apply a salve, use calmar or aliviar. Salvar means to save a life or rescue.',
    example: 'Los bomberos salvaron a la familia. — The firefighters saved the family.',
    dangerLevel: 'low',
  },
  {
    spanish: 'formidable',
    looksLike: 'formidable (frightening)',
    actualMeaning: 'wonderful / fantastic / terrific',
    correctUsage: 'In English, formidable usually means impressive and intimidating. In Spanish it means great or wonderful.',
    example: '¡Qué actuación tan formidable! — What a fantastic performance!',
    dangerLevel: 'medium',
  },
  {
    spanish: 'trampa',
    looksLike: 'trampoline',
    actualMeaning: 'trap / trick / cheating',
    correctUsage: 'For trampoline, use cama elástica or trampolín (the sports diving board). Trampa means a trap or doing something dishonest.',
    example: 'Hizo trampa en el examen. — She cheated on the exam.',
    dangerLevel: 'low',
  },
  {
    spanish: 'preservar',
    looksLike: 'to preserve (food)',
    actualMeaning: 'to preserve / to protect / to conserve',
    correctUsage: 'In Spanish, preservar means to protect or maintain. For food preservation, use conservar.',
    example: 'Debemos preservar el medioambiente. — We must protect the environment.',
    dangerLevel: 'low',
  },
  {
    spanish: 'relativo',
    looksLike: 'relative (family member)',
    actualMeaning: 'relative (adj.) / relating to / not absolute',
    correctUsage: 'For a family relative, use pariente (see above) or familiar. Relativo means related to or not absolute.',
    example: 'Todo es relativo en la vida. — Everything is relative in life.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'extrañar',
    looksLike: 'to be strange',
    actualMeaning: 'to miss (a person or place) / to find strange',
    correctUsage: 'Extrañar can mean both to miss something/someone AND to find something odd. Context clarifies.',
    example: 'Te extraño mucho. — I miss you a lot.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'renta',
    looksLike: 'rent (for housing)',
    actualMeaning: 'income / revenue / tax return',
    correctUsage: 'For housing rent, use alquiler. Renta usually refers to income or a tax declaration.',
    example: 'Tengo que hacer la declaración de la renta. — I have to file my income tax return.',
    dangerLevel: 'medium',
  },
];

export function getByDangerLevel(level) {
  return FALSE_FRIENDS.filter(f => f.dangerLevel === level);
}

export function getRandom(n = 5) {
  const shuffled = [...FALSE_FRIENDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
