// Spanish false cognates (false friends) — words that look like English but mean something else

export const FALSE_FRIENDS = [
  {
    spanish: 'embarazada',
    looksLike: 'embarrassed',
    actualMeaning: 'pregnant',
    correctUsage: 'To say embarrassed, use avergonzado/a',
    example: 'Ella está embarazada. — She is pregnant.',
    dangerLevel: 'high',
  },
  {
    spanish: 'actualmente',
    looksLike: 'actually',
    actualMeaning: 'currently / at present',
    correctUsage: 'To say actually, use en realidad or de hecho',
    example: 'Actualmente vivo en Madrid. — I currently live in Madrid.',
    dangerLevel: 'high',
  },
  {
    spanish: 'sensible',
    looksLike: 'sensible',
    actualMeaning: 'sensitive',
    correctUsage: 'To say sensible, use sensato/a or razonable',
    example: 'Ella es muy sensible. — She is very sensitive.',
    dangerLevel: 'high',
  },
  {
    spanish: 'éxito',
    looksLike: 'exit',
    actualMeaning: 'success',
    correctUsage: 'To say exit, use salida',
    example: 'Tuvo mucho éxito. — He had a lot of success.',
    dangerLevel: 'high',
  },
  {
    spanish: 'librería',
    looksLike: 'library',
    actualMeaning: 'bookshop / bookstore',
    correctUsage: 'To say library, use biblioteca',
    example: 'Compré el libro en la librería. — I bought the book at the bookshop.',
    dangerLevel: 'high',
  },
  {
    spanish: 'carpeta',
    looksLike: 'carpet',
    actualMeaning: 'folder / binder',
    correctUsage: 'To say carpet, use alfombra',
    example: 'Guarda los documentos en la carpeta. — Keep the documents in the folder.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'realizar',
    looksLike: 'realize',
    actualMeaning: 'to carry out / to accomplish',
    correctUsage: 'To say realize (become aware), use darse cuenta de',
    example: 'Vamos a realizar el proyecto. — We will carry out the project.',
    dangerLevel: 'high',
  },
  {
    spanish: 'recordar',
    looksLike: 'record',
    actualMeaning: 'to remember / to remind',
    correctUsage: 'To say to record, use grabar',
    example: 'No recuerdo su nombre. — I don\'t remember his name.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'largo',
    looksLike: 'large',
    actualMeaning: 'long',
    correctUsage: 'To say large, use grande',
    example: 'El pasillo es muy largo. — The hallway is very long.',
    dangerLevel: 'high',
  },
  {
    spanish: 'sopa',
    looksLike: 'soap',
    actualMeaning: 'soup',
    correctUsage: 'To say soap, use jabón',
    example: 'La sopa está caliente. — The soup is hot.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'introducir',
    looksLike: 'introduce',
    actualMeaning: 'to insert / to enter (data)',
    correctUsage: 'To say introduce someone, use presentar',
    example: 'Introduce tu contraseña. — Enter your password.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'pretender',
    looksLike: 'pretend',
    actualMeaning: 'to aspire to / to intend',
    correctUsage: 'To say pretend, use fingir',
    example: 'Pretende estudiar medicina. — He intends to study medicine.',
    dangerLevel: 'high',
  },
  {
    spanish: 'asistir',
    looksLike: 'assist',
    actualMeaning: 'to attend',
    correctUsage: 'To say assist (help), use ayudar',
    example: 'Asistí a la conferencia. — I attended the conference.',
    dangerLevel: 'high',
  },
  {
    spanish: 'molestar',
    looksLike: 'molest',
    actualMeaning: 'to bother / to annoy',
    correctUsage: 'It is not as strong as the English word — very common in everyday speech',
    example: '¿Te molesta el ruido? — Does the noise bother you?',
    dangerLevel: 'high',
  },
  {
    spanish: 'constipado',
    looksLike: 'constipated',
    actualMeaning: 'having a cold',
    correctUsage: 'To say constipated, use estreñido/a',
    example: 'Estoy constipado. — I have a cold.',
    dangerLevel: 'high',
  },
  {
    spanish: 'simpático',
    looksLike: 'sympathetic',
    actualMeaning: 'nice / friendly / likeable',
    correctUsage: 'To say sympathetic, use comprensivo/a',
    example: 'Tu profesora es muy simpática. — Your teacher is very nice.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'gracioso',
    looksLike: 'gracious',
    actualMeaning: 'funny / amusing',
    correctUsage: 'To say gracious, use amable or cortés',
    example: 'El chiste fue muy gracioso. — The joke was very funny.',
    dangerLevel: 'low',
  },
  {
    spanish: 'tópico',
    looksLike: 'topic',
    actualMeaning: 'cliché / stereotype (in Spain)',
    correctUsage: 'To say topic, use tema',
    example: 'Es un tópico que todos los españoles duermen la siesta. — It\'s a cliché that all Spaniards take siestas.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'compromiso',
    looksLike: 'compromise',
    actualMeaning: 'commitment / engagement / obligation',
    correctUsage: 'To say compromise (mutual concession), use acuerdo or término medio',
    example: 'Tengo un compromiso el viernes. — I have a commitment on Friday.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'padres',
    looksLike: 'fathers',
    actualMeaning: 'parents',
    correctUsage: 'The plural of padre means parents, not just fathers',
    example: 'Mis padres viven en Sevilla. — My parents live in Seville.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'fábrica',
    looksLike: 'fabric',
    actualMeaning: 'factory',
    correctUsage: 'To say fabric (cloth), use tela',
    example: 'Trabaja en una fábrica de coches. — He works in a car factory.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'colegio',
    looksLike: 'college',
    actualMeaning: 'primary/secondary school',
    correctUsage: 'To say college/university, use universidad',
    example: 'Los niños van al colegio. — The children go to school.',
    dangerLevel: 'medium',
  },
  {
    spanish: 'lectura',
    looksLike: 'lecture',
    actualMeaning: 'reading',
    correctUsage: 'To say lecture, use conferencia or clase magistral',
    example: 'La lectura del texto fue difícil. — Reading the text was difficult.',
    dangerLevel: 'low',
  },
  {
    spanish: 'ropa',
    looksLike: 'rope',
    actualMeaning: 'clothing / clothes',
    correctUsage: 'To say rope, use cuerda',
    example: 'Necesito ropa de invierno. — I need winter clothes.',
    dangerLevel: 'low',
  },
  {
    spanish: 'informal',
    looksLike: 'informal',
    actualMeaning: 'unreliable / untrustworthy (about a person)',
    correctUsage: 'Calling someone informal means they can\'t be counted on, not that they\'re casual',
    example: 'Es muy informal — nunca llega a tiempo. — He\'s very unreliable — he never arrives on time.',
    dangerLevel: 'medium',
  },
];

export function getByDangerLevel(level) {
  return FALSE_FRIENDS.filter(f => f.dangerLevel === level);
}

export function getRandom(n = 5) {
  const shuffled = [...FALSE_FRIENDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, n);
}
