// Common Spanish idioms — register: colloquial | informal | neutral | formal

export const IDIOMS = [
  {
    idiom: 'costar un ojo de la cara',
    literal: 'to cost an eye from the face',
    meaning: 'to cost a fortune / to be very expensive',
    example: 'Las entradas costaron un ojo de la cara.',
    exampleEn: 'The tickets cost a fortune.',
    register: 'colloquial',
    category: 'money',
  },
  {
    idiom: 'no hay mal que por bien no venga',
    literal: 'there is no bad from which good doesn\'t come',
    meaning: 'every cloud has a silver lining',
    example: 'Perdí el trabajo, pero encontré uno mejor. No hay mal que por bien no venga.',
    exampleEn: 'I lost my job but found a better one. Every cloud has a silver lining.',
    register: 'neutral',
    category: 'life',
  },
  {
    idiom: 'matar dos pájaros de un tiro',
    literal: 'to kill two birds with one shot',
    meaning: 'to kill two birds with one stone',
    example: 'Fui al banco y al supermercado — maté dos pájaros de un tiro.',
    exampleEn: 'I went to the bank and the supermarket — killed two birds with one stone.',
    register: 'informal',
    category: 'efficiency',
  },
  {
    idiom: 'ni hablar',
    literal: 'not even to talk',
    meaning: 'no way / out of the question',
    example: '—¿Me prestas el coche? —Ni hablar.',
    exampleEn: 'Can I borrow your car? — No way.',
    register: 'colloquial',
    category: 'refusal',
  },
  {
    idiom: 'estar en las nubes',
    literal: 'to be in the clouds',
    meaning: 'to have one\'s head in the clouds / to be daydreaming',
    example: 'Siempre está en las nubes durante la clase.',
    exampleEn: 'He\'s always daydreaming during class.',
    register: 'informal',
    category: 'mind',
  },
  {
    idiom: 'tomar el pelo',
    literal: 'to take the hair',
    meaning: 'to pull someone\'s leg / to tease',
    example: '¿Me estás tomando el pelo?',
    exampleEn: 'Are you pulling my leg?',
    register: 'colloquial',
    category: 'deception',
  },
  {
    idiom: 'no pegar ojo',
    literal: 'not to stick an eye',
    meaning: 'to not sleep a wink',
    example: 'Anoche no pegué ojo por el ruido.',
    exampleEn: 'Last night I didn\'t sleep a wink because of the noise.',
    register: 'colloquial',
    category: 'sleep',
  },
  {
    idiom: 'meter la pata',
    literal: 'to stick the paw in',
    meaning: 'to put one\'s foot in it / to make a blunder',
    example: 'Metí la pata cuando pregunté si estaba embarazada.',
    exampleEn: 'I put my foot in it when I asked if she was pregnant.',
    register: 'colloquial',
    category: 'mistakes',
  },
  {
    idiom: 'ponerse las pilas',
    literal: 'to put in the batteries',
    meaning: 'to get one\'s act together / to pull one\'s socks up',
    example: 'Si quieres aprobar, tienes que ponerte las pilas.',
    exampleEn: 'If you want to pass, you need to get your act together.',
    register: 'colloquial',
    category: 'effort',
  },
  {
    idiom: 'ser pan comido',
    literal: 'to be eaten bread',
    meaning: 'to be a piece of cake / very easy',
    example: 'El examen fue pan comido.',
    exampleEn: 'The exam was a piece of cake.',
    register: 'informal',
    category: 'ease',
  },
  {
    idiom: 'estar hasta las narices',
    literal: 'to be up to the nostrils',
    meaning: 'to be fed up / to have had it up to here',
    example: 'Estoy hasta las narices de este trabajo.',
    exampleEn: 'I\'m fed up with this job.',
    register: 'colloquial',
    category: 'frustration',
  },
  {
    idiom: 'no dar abasto',
    literal: 'not to give supply',
    meaning: 'to be unable to cope / to not be able to keep up',
    example: 'El restaurante no daba abasto durante el fin de semana.',
    exampleEn: 'The restaurant couldn\'t keep up during the weekend.',
    register: 'informal',
    category: 'work',
  },
  {
    idiom: 'llueve sobre mojado',
    literal: 'it rains on the wet',
    meaning: 'it never rains but it pours',
    example: 'Se rompió el coche y encima me puse enfermo. Llueve sobre mojado.',
    exampleEn: 'The car broke down and on top of that I got sick. It never rains but it pours.',
    register: 'neutral',
    category: 'misfortune',
  },
  {
    idiom: 'coger el toro por los cuernos',
    literal: 'to grab the bull by the horns',
    meaning: 'to take the bull by the horns / to face a problem directly',
    example: 'Hay que coger el toro por los cuernos y hablar con el jefe.',
    exampleEn: 'We need to take the bull by the horns and talk to the boss.',
    register: 'neutral',
    category: 'courage',
  },
  {
    idiom: 'echar una mano',
    literal: 'to throw a hand',
    meaning: 'to give a hand / to help out',
    example: '¿Me echas una mano con esto?',
    exampleEn: 'Can you give me a hand with this?',
    register: 'informal',
    category: 'help',
  },
  {
    idiom: 'no es para tanto',
    literal: 'it\'s not for that much',
    meaning: 'it\'s not a big deal / don\'t make such a fuss',
    example: '—¡Me duele mucho! —No es para tanto.',
    exampleEn: 'It hurts so much! — It\'s not a big deal.',
    register: 'colloquial',
    category: 'reactions',
  },
  {
    idiom: 'a última hora',
    literal: 'at the last hour',
    meaning: 'at the last minute',
    example: 'Siempre lo deja todo para última hora.',
    exampleEn: 'He always leaves everything to the last minute.',
    register: 'neutral',
    category: 'time',
  },
  {
    idiom: 'quedarse con la boca abierta',
    literal: 'to remain with the mouth open',
    meaning: 'to be left speechless / to be amazed',
    example: 'Me quedé con la boca abierta cuando vi el precio.',
    exampleEn: 'I was left speechless when I saw the price.',
    register: 'informal',
    category: 'surprise',
  },
  {
    idiom: 'dar en el clavo',
    literal: 'to hit the nail',
    meaning: 'to hit the nail on the head',
    example: 'Diste en el clavo con esa observación.',
    exampleEn: 'You hit the nail on the head with that observation.',
    register: 'neutral',
    category: 'accuracy',
  },
  {
    idiom: 'no tener pelos en la lengua',
    literal: 'to have no hairs on the tongue',
    meaning: 'to not mince words / to speak one\'s mind',
    example: 'María no tiene pelos en la lengua — dice lo que piensa.',
    exampleEn: 'María doesn\'t mince words — she says what she thinks.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'ser un hueso duro de roer',
    literal: 'to be a hard bone to gnaw',
    meaning: 'to be a tough nut to crack',
    example: 'El subjuntivo es un hueso duro de roer.',
    exampleEn: 'The subjunctive is a tough nut to crack.',
    register: 'informal',
    category: 'difficulty',
  },
  {
    idiom: 'a ver',
    literal: 'to see',
    meaning: 'let\'s see / well / come on (filler expression)',
    example: 'A ver, ¿qué quieres decir exactamente?',
    exampleEn: 'Let\'s see, what exactly do you mean?',
    register: 'colloquial',
    category: 'fillers',
  },
  {
    idiom: 'al pie de la letra',
    literal: 'at the foot of the letter',
    meaning: 'to the letter / exactly as said',
    example: 'Siguió las instrucciones al pie de la letra.',
    exampleEn: 'She followed the instructions to the letter.',
    register: 'neutral',
    category: 'precision',
  },
  {
    idiom: 'estar en forma',
    literal: 'to be in form',
    meaning: 'to be in shape / to be fit',
    example: 'Hace deporte para estar en forma.',
    exampleEn: 'She exercises to stay in shape.',
    register: 'neutral',
    category: 'health',
  },
  {
    idiom: 'perder la cabeza',
    literal: 'to lose the head',
    meaning: 'to lose one\'s mind / to go crazy',
    example: 'Has perdido la cabeza si crees eso.',
    exampleEn: 'You\'ve lost your mind if you believe that.',
    register: 'informal',
    category: 'mind',
  },
  {
    idiom: 'de vez en cuando',
    literal: 'from time to time',
    meaning: 'from time to time / occasionally',
    example: 'De vez en cuando me apetece un helado.',
    exampleEn: 'From time to time I feel like having ice cream.',
    register: 'neutral',
    category: 'frequency',
  },
  {
    idiom: 'no cabe duda',
    literal: 'there\'s no room for doubt',
    meaning: 'there\'s no doubt / without doubt',
    example: 'No cabe duda de que es el mejor.',
    exampleEn: 'There\'s no doubt that he\'s the best.',
    register: 'neutral',
    category: 'certainty',
  },
  {
    idiom: 'poner al día',
    literal: 'to put to the day',
    meaning: 'to bring up to date / to catch up',
    example: 'Ponme al día de las noticias.',
    exampleEn: 'Fill me in on the news.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'en el fondo',
    literal: 'at the bottom',
    meaning: 'deep down / at heart / basically',
    example: 'En el fondo, es una buena persona.',
    exampleEn: 'Deep down, he\'s a good person.',
    register: 'neutral',
    category: 'truth',
  },
  {
    idiom: 'a lo mejor',
    literal: 'at the best',
    meaning: 'maybe / perhaps',
    example: 'A lo mejor viene esta tarde.',
    exampleEn: 'Maybe she\'ll come this afternoon.',
    register: 'informal',
    category: 'probability',
  },
  {
    idiom: 'hacer falta',
    literal: 'to make lack',
    meaning: 'to be needed / to need',
    example: 'Me hace falta un diccionario.',
    exampleEn: 'I need a dictionary.',
    register: 'neutral',
    category: 'need',
  },
  {
    idiom: 'tener buena/mala pinta',
    literal: 'to have good/bad appearance',
    meaning: 'to look good/bad / to seem promising or not',
    example: 'Ese plato tiene muy buena pinta.',
    exampleEn: 'That dish looks really good.',
    register: 'colloquial',
    category: 'appearances',
  },
  {
    idiom: 'ser un rollo',
    literal: 'to be a roll',
    meaning: 'to be boring / a drag',
    example: 'Esta reunión es un rollo.',
    exampleEn: 'This meeting is such a drag.',
    register: 'colloquial',
    category: 'boredom',
  },
  {
    idiom: 'tomar la delantera',
    literal: 'to take the front',
    meaning: 'to get ahead / to take the lead',
    example: 'Hay que tomar la delantera en el mercado.',
    exampleEn: 'We need to take the lead in the market.',
    register: 'neutral',
    category: 'competition',
  },
  {
    idiom: 'no pasa nada',
    literal: 'nothing happens',
    meaning: 'don\'t worry about it / it\'s all good / no problem',
    example: '—Lo siento mucho. —No pasa nada.',
    exampleEn: 'I\'m so sorry. — Don\'t worry about it.',
    register: 'colloquial',
    category: 'reassurance',
  },
  {
    idiom: 'valer la pena',
    literal: 'to be worth the pain',
    meaning: 'to be worth it',
    example: 'Aprender español vale la pena.',
    exampleEn: 'Learning Spanish is worth it.',
    register: 'neutral',
    category: 'value',
  },
  {
    idiom: 'a grandes rasgos',
    literal: 'in broad strokes',
    meaning: 'broadly speaking / in general terms',
    example: 'A grandes rasgos, el plan funciona.',
    exampleEn: 'Broadly speaking, the plan works.',
    register: 'neutral',
    category: 'summary',
  },
  {
    idiom: 'con las manos en la masa',
    literal: 'with hands in the dough',
    meaning: 'red-handed / in the act',
    example: 'Lo pillaron con las manos en la masa.',
    exampleEn: 'They caught him red-handed.',
    register: 'informal',
    category: 'crime',
  },
  {
    idiom: 'dar la lata',
    literal: 'to give the tin',
    meaning: 'to be a nuisance / to pester',
    example: 'Deja de dar la lata con eso.',
    exampleEn: 'Stop being a nuisance about that.',
    register: 'colloquial',
    category: 'annoyance',
  },
  {
    idiom: 'en un abrir y cerrar de ojos',
    literal: 'in an opening and closing of eyes',
    meaning: 'in the blink of an eye',
    example: 'Lo hizo en un abrir y cerrar de ojos.',
    exampleEn: 'He did it in the blink of an eye.',
    register: 'neutral',
    category: 'speed',
  },
  {
    idiom: 'no dar pie con bola',
    literal: 'not to hit a ball with one\'s foot',
    meaning: 'to be unable to do anything right',
    example: 'Hoy no doy pie con bola — todo me sale mal.',
    exampleEn: 'Today I can\'t do anything right — everything goes wrong.',
    register: 'colloquial',
    category: 'failure',
  },
  {
    idiom: 'ponerse las pilas',
    literal: 'to put one\'s batteries in',
    meaning: 'to get one\'s act together / to get a move on',
    example: '¡Ponte las pilas si quieres terminar a tiempo!',
    exampleEn: 'Get your act together if you want to finish on time!',
    register: 'informal',
    category: 'motivation',
  },
  {
    idiom: 'estar en las nubes',
    literal: 'to be in the clouds',
    meaning: 'to have one\'s head in the clouds / to daydream',
    example: 'No me escucha — siempre está en las nubes.',
    exampleEn: 'He doesn\'t listen to me — he\'s always daydreaming.',
    register: 'informal',
    category: 'distraction',
  },
  {
    idiom: 'tirar la casa por la ventana',
    literal: 'to throw the house out of the window',
    meaning: 'to go all out / to spare no expense',
    example: 'Para la boda tiraron la casa por la ventana.',
    exampleEn: 'For the wedding they spared no expense.',
    register: 'informal',
    category: 'money',
  },
  {
    idiom: 'estar hasta las narices',
    literal: 'to be up to one\'s nose',
    meaning: 'to be fed up / to have had enough',
    example: 'Estoy hasta las narices de esperar.',
    exampleEn: 'I\'m fed up with waiting.',
    register: 'colloquial',
    category: 'annoyance',
  },
  {
    idiom: 'echar una mano',
    literal: 'to throw a hand',
    meaning: 'to lend a hand / to help out',
    example: '¿Me puedes echar una mano con esto?',
    exampleEn: 'Can you lend me a hand with this?',
    register: 'informal',
    category: 'help',
  },
  {
    idiom: 'meter la pata',
    literal: 'to stick one\'s paw in',
    meaning: 'to put one\'s foot in it / to mess up',
    example: 'Metí la pata con ese comentario.',
    exampleEn: 'I put my foot in it with that comment.',
    register: 'colloquial',
    category: 'mistakes',
  },
  {
    idiom: 'llevarse como el perro y el gato',
    literal: 'to get along like a dog and a cat',
    meaning: 'to fight like cat and dog',
    example: 'Mis hermanos se llevan como el perro y el gato.',
    exampleEn: 'My siblings fight like cat and dog.',
    register: 'informal',
    category: 'relationships',
  },
  {
    idiom: 'no hay mal que cien años dure',
    literal: 'there is no hardship that lasts a hundred years',
    meaning: 'this too shall pass / nothing lasts forever',
    example: '¡Ánimo! No hay mal que cien años dure.',
    exampleEn: 'Cheer up! This too shall pass.',
    register: 'neutral',
    category: 'life',
  },
  {
    idiom: 'quemar las naves',
    literal: 'to burn the ships',
    meaning: 'to burn one\'s bridges / to commit fully with no way back',
    example: 'Dejó su trabajo y quemó las naves.',
    exampleEn: 'He quit his job and burned his bridges.',
    register: 'neutral',
    category: 'decisions',
  },
  {
    idiom: 'ver los toros desde la barrera',
    literal: 'to watch the bulls from behind the barrier',
    meaning: 'to watch from the sidelines / to play it safe',
    example: 'Prefiere ver los toros desde la barrera y no comprometerse.',
    exampleEn: 'He prefers to play it safe and not commit.',
    register: 'neutral',
    category: 'caution',
  },
  {
    idiom: 'buscarle tres pies al gato',
    literal: 'to look for three feet on a cat',
    meaning: 'to complicate things unnecessarily / to look for trouble',
    example: 'No le busques tres pies al gato — la solución es simple.',
    exampleEn: 'Don\'t overcomplicate things — the solution is simple.',
    register: 'informal',
    category: 'problems',
  },
  {
    idiom: 'a buenas horas, mangas verdes',
    literal: 'at fine hours, green sleeves',
    meaning: 'too little, too late',
    example: 'A buenas horas, mangas verdes — ya terminamos sin ti.',
    exampleEn: 'Too little, too late — we already finished without you.',
    register: 'colloquial',
    category: 'time',
  },
  {
    idiom: 'dormir a pierna suelta',
    literal: 'to sleep with a loose leg',
    meaning: 'to sleep like a log / to sleep soundly',
    example: 'Después del viaje dormí a pierna suelta.',
    exampleEn: 'After the trip I slept like a log.',
    register: 'informal',
    category: 'sleep',
  },
  {
    idiom: 'en boca cerrada no entran moscas',
    literal: 'in a closed mouth no flies enter',
    meaning: 'silence is golden / keep your mouth shut',
    example: 'Mejor no digas nada — en boca cerrada no entran moscas.',
    exampleEn: 'Better say nothing — silence is golden.',
    register: 'neutral',
    category: 'advice',
  },
  {
    idiom: 'tener mano izquierda',
    literal: 'to have a left hand',
    meaning: 'to be tactful / to have good people skills',
    example: 'Tiene mucha mano izquierda para resolver conflictos.',
    exampleEn: 'She has great tact when resolving conflicts.',
    register: 'informal',
    category: 'personality',
  },
  {
    idiom: 'a lo hecho, pecho',
    literal: 'to what\'s done, chest (face it)',
    meaning: 'what\'s done is done — face it',
    example: 'No te arrepientas — a lo hecho, pecho.',
    exampleEn: 'Don\'t regret it — what\'s done is done.',
    register: 'informal',
    category: 'acceptance',
  },
  {
    idiom: 'dar en el clavo',
    literal: 'to hit the nail',
    meaning: 'to hit the nail on the head / to be exactly right',
    example: 'Con ese análisis has dado en el clavo.',
    exampleEn: 'With that analysis you\'ve hit the nail on the head.',
    register: 'neutral',
    category: 'accuracy',
  },
  {
    idiom: 'no tener pelos en la lengua',
    literal: 'to have no hairs on one\'s tongue',
    meaning: 'to be outspoken / to not mince words',
    example: 'No tiene pelos en la lengua — dice lo que piensa.',
    exampleEn: 'She doesn\'t mince words — she says what she thinks.',
    register: 'informal',
    category: 'honesty',
  },
];

export const CATEGORIES = [...new Set(IDIOMS.map(i => i.category))].sort();
export const REGISTERS = ['colloquial', 'informal', 'neutral', 'formal'];

export function getByCategory(category) {
  return IDIOMS.filter(i => i.category === category);
}

export function getByRegister(register) {
  return IDIOMS.filter(i => i.register === register);
}

export function getRandom(n = 5) {
  return [...IDIOMS].sort(() => Math.random() - 0.5).slice(0, n);
}
