// Common Spanish idioms — register: colloquial | informal | neutral | formal

export const IDIOMS = [
  {
    idiom: 'costar un ojo de la cara',
    literal: 'to cost an eye from the face',
    meaning: 'to cost a fortune / to be very expensive',
    example: 'Las entradas costaron un ojo de la cara.',
    exampleEn: 'The tickets cost a fortune.',
    register: 'colloquial',
    category: 'money',
  },
  {
    idiom: 'no hay mal que por bien no venga',
    literal: 'there is no bad from which good doesn\'t come',
    meaning: 'every cloud has a silver lining',
    example: 'Perdí el trabajo, pero encontré uno mejor. No hay mal que por bien no venga.',
    exampleEn: 'I lost my job but found a better one. Every cloud has a silver lining.',
    register: 'neutral',
    category: 'life',
  },
  {
    idiom: 'matar dos pájaros de un tiro',
    literal: 'to kill two birds with one shot',
    meaning: 'to kill two birds with one stone',
    example: 'Fui al banco y al supermercado — maté dos pájaros de un tiro.',
    exampleEn: 'I went to the bank and the supermarket — killed two birds with one stone.',
    register: 'informal',
    category: 'efficiency',
  },
  {
    idiom: 'ni hablar',
    literal: 'not even to talk',
    meaning: 'no way / out of the question',
    example: '—¿Me prestas el coche? —Ni hablar.',
    exampleEn: 'Can I borrow your car? — No way.',
    register: 'colloquial',
    category: 'refusal',
  },
  {
    idiom: 'estar en las nubes',
    literal: 'to be in the clouds',
    meaning: 'to have one\'s head in the clouds / to be daydreaming',
    example: 'Siempre está en las nubes durante la clase.',
    exampleEn: 'He\'s always daydreaming during class.',
    register: 'informal',
    category: 'mind',
  },
  {
    idiom: 'tomar el pelo',
    literal: 'to take the hair',
    meaning: 'to pull someone\'s leg / to tease',
    example: '¿Me estás tomando el pelo?',
    exampleEn: 'Are you pulling my leg?',
    register: 'colloquial',
    category: 'deception',
  },
  {
    idiom: 'no pegar ojo',
    literal: 'not to stick an eye',
    meaning: 'to not sleep a wink',
    example: 'Anoche no pegué ojo por el ruido.',
    exampleEn: 'Last night I didn\'t sleep a wink because of the noise.',
    register: 'colloquial',
    category: 'sleep',
  },
  {
    idiom: 'meter la pata',
    literal: 'to stick the paw in',
    meaning: 'to put one\'s foot in it / to make a blunder',
    example: 'Metí la pata cuando pregunté si estaba embarazada.',
    exampleEn: 'I put my foot in it when I asked if she was pregnant.',
    register: 'colloquial',
    category: 'mistakes',
  },
  {
    idiom: 'ponerse las pilas',
    literal: 'to put in the batteries',
    meaning: 'to get one\'s act together / to pull one\'s socks up',
    example: 'Si quieres aprobar, tienes que ponerte las pilas.',
    exampleEn: 'If you want to pass, you need to get your act together.',
    register: 'colloquial',
    category: 'effort',
  },
  {
    idiom: 'ser pan comido',
    literal: 'to be eaten bread',
    meaning: 'to be a piece of cake / very easy',
    example: 'El examen fue pan comido.',
    exampleEn: 'The exam was a piece of cake.',
    register: 'informal',
    category: 'ease',
  },
  {
    idiom: 'estar hasta las narices',
    literal: 'to be up to the nostrils',
    meaning: 'to be fed up / to have had it up to here',
    example: 'Estoy hasta las narices de este trabajo.',
    exampleEn: 'I\'m fed up with this job.',
    register: 'colloquial',
    category: 'frustration',
  },
  {
    idiom: 'no dar abasto',
    literal: 'not to give supply',
    meaning: 'to be unable to cope / to not be able to keep up',
    example: 'El restaurante no daba abasto durante el fin de semana.',
    exampleEn: 'The restaurant couldn\'t keep up during the weekend.',
    register: 'informal',
    category: 'work',
  },
  {
    idiom: 'llueve sobre mojado',
    literal: 'it rains on the wet',
    meaning: 'it never rains but it pours',
    example: 'Se rompió el coche y encima me puse enfermo. Llueve sobre mojado.',
    exampleEn: 'The car broke down and on top of that I got sick. It never rains but it pours.',
    register: 'neutral',
    category: 'misfortune',
  },
  {
    idiom: 'coger el toro por los cuernos',
    literal: 'to grab the bull by the horns',
    meaning: 'to take the bull by the horns / to face a problem directly',
    example: 'Hay que coger el toro por los cuernos y hablar con el jefe.',
    exampleEn: 'We need to take the bull by the horns and talk to the boss.',
    register: 'neutral',
    category: 'courage',
  },
  {
    idiom: 'echar una mano',
    literal: 'to throw a hand',
    meaning: 'to give a hand / to help out',
    example: '¿Me echas una mano con esto?',
    exampleEn: 'Can you give me a hand with this?',
    register: 'informal',
    category: 'help',
  },
  {
    idiom: 'no es para tanto',
    literal: 'it\'s not for that much',
    meaning: 'it\'s not a big deal / don\'t make such a fuss',
    example: '—¡Me duele mucho! —No es para tanto.',
    exampleEn: 'It hurts so much! — It\'s not a big deal.',
    register: 'colloquial',
    category: 'reactions',
  },
  {
    idiom: 'a última hora',
    literal: 'at the last hour',
    meaning: 'at the last minute',
    example: 'Siempre lo deja todo para última hora.',
    exampleEn: 'He always leaves everything to the last minute.',
    register: 'neutral',
    category: 'time',
  },
  {
    idiom: 'quedarse con la boca abierta',
    literal: 'to remain with the mouth open',
    meaning: 'to be left speechless / to be amazed',
    example: 'Me quedé con la boca abierta cuando vi el precio.',
    exampleEn: 'I was left speechless when I saw the price.',
    register: 'informal',
    category: 'surprise',
  },
  {
    idiom: 'dar en el clavo',
    literal: 'to hit the nail',
    meaning: 'to hit the nail on the head',
    example: 'Diste en el clavo con esa observación.',
    exampleEn: 'You hit the nail on the head with that observation.',
    register: 'neutral',
    category: 'accuracy',
  },
  {
    idiom: 'no tener pelos en la lengua',
    literal: 'to have no hairs on the tongue',
    meaning: 'to not mince words / to speak one\'s mind',
    example: 'María no tiene pelos en la lengua — dice lo que piensa.',
    exampleEn: 'María doesn\'t mince words — she says what she thinks.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'ser un hueso duro de roer',
    literal: 'to be a hard bone to gnaw',
    meaning: 'to be a tough nut to crack',
    example: 'El subjuntivo es un hueso duro de roer.',
    exampleEn: 'The subjunctive is a tough nut to crack.',
    register: 'informal',
    category: 'difficulty',
  },
  {
    idiom: 'a ver',
    literal: 'to see',
    meaning: 'let\'s see / well / come on (filler expression)',
    example: 'A ver, ¿qué quieres decir exactamente?',
    exampleEn: 'Let\'s see, what exactly do you mean?',
    register: 'colloquial',
    category: 'fillers',
  },
  {
    idiom: 'al pie de la letra',
    literal: 'at the foot of the letter',
    meaning: 'to the letter / exactly as said',
    example: 'Siguió las instrucciones al pie de la letra.',
    exampleEn: 'She followed the instructions to the letter.',
    register: 'neutral',
    category: 'precision',
  },
  {
    idiom: 'estar en forma',
    literal: 'to be in form',
    meaning: 'to be in shape / to be fit',
    example: 'Hace deporte para estar en forma.',
    exampleEn: 'She exercises to stay in shape.',
    register: 'neutral',
    category: 'health',
  },
  {
    idiom: 'perder la cabeza',
    literal: 'to lose the head',
    meaning: 'to lose one\'s mind / to go crazy',
    example: 'Has perdido la cabeza si crees eso.',
    exampleEn: 'You\'ve lost your mind if you believe that.',
    register: 'informal',
    category: 'mind',
  },
  {
    idiom: 'de vez en cuando',
    literal: 'from time to time',
    meaning: 'from time to time / occasionally',
    example: 'De vez en cuando me apetece un helado.',
    exampleEn: 'From time to time I feel like having ice cream.',
    register: 'neutral',
    category: 'frequency',
  },
  {
    idiom: 'no cabe duda',
    literal: 'there\'s no room for doubt',
    meaning: 'there\'s no doubt / without doubt',
    example: 'No cabe duda de que es el mejor.',
    exampleEn: 'There\'s no doubt that he\'s the best.',
    register: 'neutral',
    category: 'certainty',
  },
  {
    idiom: 'poner al día',
    literal: 'to put to the day',
    meaning: 'to bring up to date / to catch up',
    example: 'Ponme al día de las noticias.',
    exampleEn: 'Fill me in on the news.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'en el fondo',
    literal: 'at the bottom',
    meaning: 'deep down / at heart / basically',
    example: 'En el fondo, es una buena persona.',
    exampleEn: 'Deep down, he\'s a good person.',
    register: 'neutral',
    category: 'truth',
  },
  {
    idiom: 'a lo mejor',
    literal: 'at the best',
    meaning: 'maybe / perhaps',
    example: 'A lo mejor viene esta tarde.',
    exampleEn: 'Maybe she\'ll come this afternoon.',
    register: 'informal',
    category: 'probability',
  },
  {
    idiom: 'hacer falta',
    literal: 'to make lack',
    meaning: 'to be needed / to need',
    example: 'Me hace falta un diccionario.',
    exampleEn: 'I need a dictionary.',
    register: 'neutral',
    category: 'need',
  },
  {
    idiom: 'tener buena/mala pinta',
    literal: 'to have good/bad appearance',
    meaning: 'to look good/bad / to seem promising or not',
    example: 'Ese plato tiene muy buena pinta.',
    exampleEn: 'That dish looks really good.',
    register: 'colloquial',
    category: 'appearances',
  },
  {
    idiom: 'ser un rollo',
    literal: 'to be a roll',
    meaning: 'to be boring / a drag',
    example: 'Esta reunión es un rollo.',
    exampleEn: 'This meeting is such a drag.',
    register: 'colloquial',
    category: 'boredom',
  },
  {
    idiom: 'tomar la delantera',
    literal: 'to take the front',
    meaning: 'to get ahead / to take the lead',
    example: 'Hay que tomar la delantera en el mercado.',
    exampleEn: 'We need to take the lead in the market.',
    register: 'neutral',
    category: 'competition',
  },
  {
    idiom: 'no pasa nada',
    literal: 'nothing happens',
    meaning: 'don\'t worry about it / it\'s all good / no problem',
    example: '—Lo siento mucho. —No pasa nada.',
    exampleEn: 'I\'m so sorry. — Don\'t worry about it.',
    register: 'colloquial',
    category: 'reassurance',
  },
  {
    idiom: 'valer la pena',
    literal: 'to be worth the pain',
    meaning: 'to be worth it',
    example: 'Aprender español vale la pena.',
    exampleEn: 'Learning Spanish is worth it.',
    register: 'neutral',
    category: 'value',
  },
  {
    idiom: 'a grandes rasgos',
    literal: 'in broad strokes',
    meaning: 'broadly speaking / in general terms',
    example: 'A grandes rasgos, el plan funciona.',
    exampleEn: 'Broadly speaking, the plan works.',
    register: 'neutral',
    category: 'summary',
  },
  {
    idiom: 'con las manos en la masa',
    literal: 'with hands in the dough',
    meaning: 'red-handed / in the act',
    example: 'Lo pillaron con las manos en la masa.',
    exampleEn: 'They caught him red-handed.',
    register: 'informal',
    category: 'crime',
  },
  {
    idiom: 'dar la lata',
    literal: 'to give the tin',
    meaning: 'to be a nuisance / to pester',
    example: 'Deja de dar la lata con eso.',
    exampleEn: 'Stop being a nuisance about that.',
    register: 'colloquial',
    category: 'annoyance',
  },
  {
    idiom: 'en un abrir y cerrar de ojos',
    literal: 'in an opening and closing of eyes',
    meaning: 'in the blink of an eye',
    example: 'Lo hizo en un abrir y cerrar de ojos.',
    exampleEn: 'He did it in the blink of an eye.',
    register: 'neutral',
    category: 'speed',
  },
  {
    idiom: 'no dar pie con bola',
    literal: 'not to hit a ball with one\'s foot',
    meaning: 'to be unable to do anything right',
    example: 'Hoy no doy pie con bola — todo me sale mal.',
    exampleEn: 'Today I can\'t do anything right — everything goes wrong.',
    register: 'colloquial',
    category: 'failure',
  },
  {
    idiom: 'tirar la casa por la ventana',
    literal: 'to throw the house out of the window',
    meaning: 'to go all out / to spare no expense',
    example: 'Para la boda tiraron la casa por la ventana.',
    exampleEn: 'For the wedding they spared no expense.',
    register: 'informal',
    category: 'money',
  },
  {
    idiom: 'llevarse como el perro y el gato',
    literal: 'to get along like a dog and a cat',
    meaning: 'to fight like cat and dog',
    example: 'Mis hermanos se llevan como el perro y el gato.',
    exampleEn: 'My siblings fight like cat and dog.',
    register: 'informal',
    category: 'relationships',
  },
  {
    idiom: 'no hay mal que cien años dure',
    literal: 'there is no hardship that lasts a hundred years',
    meaning: 'this too shall pass / nothing lasts forever',
    example: '¡Ánimo! No hay mal que cien años dure.',
    exampleEn: 'Cheer up! This too shall pass.',
    register: 'neutral',
    category: 'life',
  },
  {
    idiom: 'quemar las naves',
    literal: 'to burn the ships',
    meaning: 'to burn one\'s bridges / to commit fully with no way back',
    example: 'Dejó su trabajo y quemó las naves.',
    exampleEn: 'He quit his job and burned his bridges.',
    register: 'neutral',
    category: 'decisions',
  },
  {
    idiom: 'ver los toros desde la barrera',
    literal: 'to watch the bulls from behind the barrier',
    meaning: 'to watch from the sidelines / to play it safe',
    example: 'Prefiere ver los toros desde la barrera y no comprometerse.',
    exampleEn: 'He prefers to play it safe and not commit.',
    register: 'neutral',
    category: 'caution',
  },
  {
    idiom: 'buscarle tres pies al gato',
    literal: 'to look for three feet on a cat',
    meaning: 'to complicate things unnecessarily / to look for trouble',
    example: 'No le busques tres pies al gato — la solución es simple.',
    exampleEn: 'Don\'t overcomplicate things — the solution is simple.',
    register: 'informal',
    category: 'problems',
  },
  {
    idiom: 'a buenas horas, mangas verdes',
    literal: 'at fine hours, green sleeves',
    meaning: 'too little, too late',
    example: 'A buenas horas, mangas verdes — ya terminamos sin ti.',
    exampleEn: 'Too little, too late — we already finished without you.',
    register: 'colloquial',
    category: 'time',
  },
  {
    idiom: 'dormir a pierna suelta',
    literal: 'to sleep with a loose leg',
    meaning: 'to sleep like a log / to sleep soundly',
    example: 'Después del viaje dormí a pierna suelta.',
    exampleEn: 'After the trip I slept like a log.',
    register: 'informal',
    category: 'sleep',
  },
  {
    idiom: 'en boca cerrada no entran moscas',
    literal: 'in a closed mouth no flies enter',
    meaning: 'silence is golden / keep your mouth shut',
    example: 'Mejor no digas nada — en boca cerrada no entran moscas.',
    exampleEn: 'Better say nothing — silence is golden.',
    register: 'neutral',
    category: 'advice',
  },
  {
    idiom: 'tener mano izquierda',
    literal: 'to have a left hand',
    meaning: 'to be tactful / to have good people skills',
    example: 'Tiene mucha mano izquierda para resolver conflictos.',
    exampleEn: 'She has great tact when resolving conflicts.',
    register: 'informal',
    category: 'personality',
  },
  {
    idiom: 'a lo hecho, pecho',
    literal: 'to what\'s done, chest (face it)',
    meaning: 'what\'s done is done — face it',
    example: 'No te arrepientas — a lo hecho, pecho.',
    exampleEn: 'Don\'t regret it — what\'s done is done.',
    register: 'informal',
    category: 'acceptance',
  },
  {
    idiom: 'hacer de tripas corazón',
    literal: 'to make heart out of guts',
    meaning: 'to steel oneself / to grit one\'s teeth and carry on',
    example: 'Hizo de tripas corazón y presentó el informe.',
    exampleEn: 'She steeled herself and delivered the report.',
    register: 'informal',
    category: 'courage',
  },
  {
    idiom: 'no saber ni papa',
    literal: 'to not even know a potato',
    meaning: 'to not have a clue / to know absolutely nothing',
    example: 'No sé ni papa de informática.',
    exampleEn: 'I don\'t have a clue about computing.',
    register: 'colloquial',
    category: 'knowledge',
  },
  {
    idiom: 'andarse por las ramas',
    literal: 'to walk around the branches',
    meaning: 'to beat around the bush',
    example: 'Deja de andarte por las ramas y dime la verdad.',
    exampleEn: 'Stop beating around the bush and tell me the truth.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'estar como una cabra',
    literal: 'to be like a goat',
    meaning: 'to be crazy / off one\'s rocker',
    example: 'Se pone a cantar a las 3 de la mañana — está como una cabra.',
    exampleEn: 'He starts singing at 3am — he\'s off his rocker.',
    register: 'colloquial',
    category: 'personality',
  },
  {
    idiom: 'a rajatabla',
    literal: 'at split-board',
    meaning: 'strictly / to the letter / without exception',
    example: 'Cumplió las normas a rajatabla.',
    exampleEn: 'She followed the rules to the letter.',
    register: 'informal',
    category: 'precision',
  },
  {
    idiom: 'estar entre la espada y la pared',
    literal: 'to be between the sword and the wall',
    meaning: 'to be between a rock and a hard place / in an impossible situation',
    example: 'Me dejó entre la espada y la pared.',
    exampleEn: 'He left me between a rock and a hard place.',
    register: 'neutral',
    category: 'dilemmas',
  },
  {
    idiom: 'poner el dedo en la llaga',
    literal: 'to put one\'s finger on the wound',
    meaning: 'to hit a raw nerve / to pinpoint the exact problem',
    example: 'Con esa pregunta puso el dedo en la llaga.',
    exampleEn: 'With that question he hit a raw nerve.',
    register: 'informal',
    category: 'truth',
  },
  {
    idiom: 'salir el tiro por la culata',
    literal: 'for the shot to come out of the butt',
    meaning: 'to backfire',
    example: 'El plan le salió por la culata.',
    exampleEn: 'The plan backfired on her.',
    register: 'informal',
    category: 'failure',
  },
  {
    idiom: 'no hay dos sin tres',
    literal: 'there\'s no two without three',
    meaning: 'bad things (or events) come in threes',
    example: 'Van dos retrasos esta semana — no hay dos sin tres.',
    exampleEn: 'That\'s two delays this week — things come in threes.',
    register: 'informal',
    category: 'patterns',
  },
  {
    idiom: 'más vale tarde que nunca',
    literal: 'better late than never',
    meaning: 'better to arrive late or do something belatedly than not at all',
    example: 'Llegó con dos horas de retraso, pero más vale tarde que nunca.',
    exampleEn: 'She arrived two hours late, but better late than never.',
    register: 'neutral',
    category: 'time',
  },
  {
    idiom: 'no todo el monte es orégano',
    literal: 'not all the hillside is oregano',
    meaning: 'it\'s not all sunshine and roses / things are more complicated than they seem',
    example: 'Te llevarás una sorpresa — no todo el monte es orégano.',
    exampleEn: 'You\'ll be in for a surprise — it\'s not all sunshine and roses.',
    register: 'informal',
    category: 'reality',
  },
  {
    idiom: 'poner toda la carne en el asador',
    literal: 'to put all the meat on the grill',
    meaning: 'to go all in / to give it everything you\'ve got',
    example: 'Para el examen final, puso toda la carne en el asador.',
    exampleEn: 'For the final exam, she gave it everything she had.',
    register: 'informal',
    category: 'effort',
  },
  {
    idiom: 'echar leña al fuego',
    literal: 'to throw wood on the fire',
    meaning: 'to add fuel to the fire / to make a bad situation worse',
    example: 'Sus comentarios solo echaron leña al fuego.',
    exampleEn: 'His comments only added fuel to the fire.',
    register: 'informal',
    category: 'conflict',
  },
  {
    idiom: 'quedarse en blanco',
    literal: 'to go blank / white',
    meaning: 'to draw a blank / to go blank (forget completely)',
    example: 'En el examen me quedé en blanco.',
    exampleEn: 'In the exam I drew a blank.',
    register: 'informal',
    category: 'mind',
  },
  {
    idiom: 'a trancas y barrancas',
    literal: 'with bars and ravines',
    meaning: 'with great difficulty / overcoming many obstacles',
    example: 'Logró terminar el proyecto a trancas y barrancas.',
    exampleEn: 'She managed to finish the project despite all the obstacles.',
    register: 'informal',
    category: 'difficulty',
  },
  {
    idiom: 'tener la cabeza en su sitio',
    literal: 'to have one\'s head in its place',
    meaning: 'to have one\'s head screwed on / to be level-headed',
    example: 'Es joven, pero tiene la cabeza en su sitio.',
    exampleEn: 'She\'s young, but she has her head screwed on.',
    register: 'informal',
    category: 'sense',
  },
  {
    idiom: 'meterse en camisa de once varas',
    literal: 'to get into an eleven-vara shirt',
    meaning: 'to get into unnecessary trouble / to complicate things needlessly',
    example: 'No te metas en camisa de once varas — déjalo estar.',
    exampleEn: 'Don\'t get into unnecessary trouble — just let it go.',
    register: 'informal',
    category: 'problems',
  },
  {
    idiom: 'a pie juntillas',
    literal: 'with feet joined together',
    meaning: 'firmly / unquestioningly / without a shadow of a doubt',
    example: 'Se cree todo a pie juntillas.',
    exampleEn: 'She believes everything unquestioningly.',
    register: 'informal',
    category: 'belief',
  },
  {
    idiom: 'tomar las de Villadiego',
    literal: 'to take the things from Villadiego',
    meaning: 'to make a run for it / to flee quickly',
    example: 'Cuando vio al inspector, tomó las de Villadiego.',
    exampleEn: 'When he saw the inspector, he made a run for it.',
    register: 'colloquial',
    category: 'escape',
  },
  {
    idiom: 'subírsele los humos a la cabeza',
    literal: 'for the fumes to rise to one\'s head',
    meaning: 'to get too big for one\'s boots / to let success go to one\'s head',
    example: 'Desde que le ascendieron se le subieron los humos a la cabeza.',
    exampleEn: 'Since his promotion, success has gone to his head.',
    register: 'colloquial',
    category: 'personality',
  },
  {
    idiom: 'estar como pez en el agua',
    literal: 'to be like a fish in water',
    meaning: 'to be in one\'s element / to feel completely at home',
    example: 'En el escenario está como pez en el agua.',
    exampleEn: 'On stage she\'s completely in her element.',
    register: 'informal',
    category: 'comfort',
  },
  {
    idiom: 'a otro perro con ese hueso',
    literal: 'go to another dog with that bone',
    meaning: 'tell it to someone who\'ll believe it / pull the other one',
    example: '—No tengo dinero. —A otro perro con ese hueso.',
    exampleEn: 'I have no money. — Pull the other one.',
    register: 'colloquial',
    category: 'disbelief',
  },
  {
    idiom: 'llevar la voz cantante',
    literal: 'to carry the singing voice',
    meaning: 'to call the shots / to be in charge',
    example: 'En esta empresa siempre ha llevado la voz cantante.',
    exampleEn: 'She\'s always called the shots in this company.',
    register: 'neutral',
    category: 'power',
  },
  {
    idiom: 'no hay tu tía',
    literal: 'there\'s no your aunt',
    meaning: 'there\'s no way around it / nothing doing',
    example: 'No hay tu tía — tendrás que hacerlo tú mismo.',
    exampleEn: 'There\'s no way around it — you\'ll have to do it yourself.',
    register: 'colloquial',
    category: 'impossibility',
  },
  {
    idiom: 'caérsele el alma a los pies',
    literal: 'for one\'s soul to fall to one\'s feet',
    meaning: 'to have one\'s heart sink / to be crushed by bad news',
    example: 'Se me cayó el alma a los pies cuando supe la noticia.',
    exampleEn: 'My heart sank when I heard the news.',
    register: 'informal',
    category: 'emotion',
  },
  {
    idiom: 'hacer la vista gorda',
    literal: 'to make the fat view',
    meaning: 'to turn a blind eye / to pretend not to notice',
    example: 'El jefe hacía la vista gorda con los retrasos.',
    exampleEn: 'The boss turned a blind eye to the lateness.',
    register: 'informal',
    category: 'ignorance',
  },
  {
    idiom: 'tirarse a la piscina',
    literal: 'to throw oneself into the swimming pool',
    meaning: 'to take the plunge / to go for it despite the risk',
    example: 'Por fin me tiré a la piscina y le pedí trabajo.',
    exampleEn: 'I finally took the plunge and asked for a job.',
    register: 'informal',
    category: 'courage',
  },
  {
    idiom: 'no dar un palo al agua',
    literal: 'to not give a stick to the water',
    meaning: 'to not do a stroke of work / to be bone idle',
    example: 'Ese chico no da un palo al agua en todo el día.',
    exampleEn: 'That guy doesn\'t do a stroke of work all day.',
    register: 'colloquial',
    category: 'laziness',
  },
  {
    idiom: 'a buenas horas mangas verdes',
    literal: 'at a good hour, green sleeves',
    meaning: 'better late than never (ironic) / too little too late',
    example: '¡A buenas horas mangas verdes! Ya hemos terminado sin ti.',
    exampleEn: 'Better late than never! We already finished without you.',
    register: 'colloquial',
    category: 'timing',
  },
  {
    idiom: 'hablar por los codos',
    literal: 'to speak through one\'s elbows',
    meaning: 'to talk nineteen to the dozen / to be a chatterbox',
    example: 'Mi vecina habla por los codos; no para nunca.',
    exampleEn: 'My neighbour talks nineteen to the dozen; she never stops.',
    register: 'colloquial',
    category: 'speech',
  },
  {
    idiom: 'costar sangre, sudor y lágrimas',
    literal: 'to cost blood, sweat, and tears',
    meaning: 'to cost blood, sweat, and tears / to require great effort',
    example: 'Conseguir ese trabajo le costó sangre, sudor y lágrimas.',
    exampleEn: 'Getting that job cost him blood, sweat, and tears.',
    register: 'neutral',
    category: 'effort',
  },
  {
    idiom: 'tener la sartén por el mango',
    literal: 'to hold the frying pan by the handle',
    meaning: 'to be in control / to call the shots / to have the upper hand',
    example: 'En esa empresa ella tiene la sartén por el mango.',
    exampleEn: 'In that company she calls the shots.',
    register: 'informal',
    category: 'power',
  },
  {
    idiom: 'estar con el agua al cuello',
    literal: 'to have water up to the neck',
    meaning: 'to be up to one\'s neck / to be in a very difficult situation',
    example: 'Estamos con el agua al cuello con estas deudas.',
    exampleEn: 'We\'re up to our necks with these debts.',
    register: 'informal',
    category: 'difficulty',
  },
  {
    idiom: 'ir al grano',
    literal: 'to go to the grain',
    meaning: 'to get to the point / to cut to the chase',
    example: 'Deja de rodeos y ve al grano.',
    exampleEn: 'Stop beating around the bush and get to the point.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'echar de menos',
    literal: 'to throw from less',
    meaning: 'to miss (someone or something)',
    example: 'Echo mucho de menos a mis amigos del instituto.',
    exampleEn: 'I really miss my friends from secondary school.',
    register: 'neutral',
    category: 'emotion',
  },
  {
    idiom: 'romper el hielo',
    literal: 'to break the ice',
    meaning: 'to break the ice / to ease the tension in a new social situation',
    example: 'Contó un chiste para romper el hielo al principio de la reunión.',
    exampleEn: 'He told a joke to break the ice at the start of the meeting.',
    register: 'neutral',
    category: 'social',
  },
  {
    idiom: 'nadar entre dos aguas',
    literal: 'to swim between two waters',
    meaning: 'to sit on the fence / to avoid committing to either side',
    example: 'Siempre nada entre dos aguas y nunca toma partido.',
    exampleEn: 'She always sits on the fence and never takes a side.',
    register: 'informal',
    category: 'decisions',
  },
  {
    idiom: 'pedir peras al olmo',
    literal: 'to ask pears from the elm tree',
    meaning: 'to ask for the impossible / to expect something from someone incapable of it',
    example: 'Pedirle puntualidad a Juan es pedir peras al olmo.',
    exampleEn: 'Expecting punctuality from Juan is asking for the impossible.',
    register: 'informal',
    category: 'impossibility',
  },
  {
    idiom: 'saltar a la vista',
    literal: 'to jump to the sight',
    meaning: 'to be obvious / to be plain to see',
    example: 'Salta a la vista que no ha dormido bien.',
    exampleEn: 'It\'s plain to see that he hasn\'t slept well.',
    register: 'neutral',
    category: 'obviousness',
  },
  {
    idiom: 'dar calabazas',
    literal: 'to give pumpkins',
    meaning: 'to reject / to dump someone / to turn someone down (romantically or in an exam)',
    example: 'Le propuso salir y ella le dio calabazas.',
    exampleEn: 'He asked her out and she turned him down.',
    register: 'colloquial',
    category: 'relationships',
  },
  {
    idiom: 'irse por las ramas',
    literal: 'to go off through the branches',
    meaning: 'to beat around the bush / to go off on a tangent',
    example: 'No te vayas por las ramas — dime exactamente qué pasó.',
    exampleEn: 'Don\'t beat around the bush — tell me exactly what happened.',
    register: 'informal',
    category: 'communication',
  },
  {
    idiom: 'meter las narices',
    literal: 'to stick one\'s nostrils in',
    meaning: 'to poke one\'s nose in / to meddle in other people\'s business',
    example: 'Siempre está metiendo las narices en los asuntos ajenos.',
    exampleEn: 'She\'s always poking her nose into other people\'s business.',
    register: 'colloquial',
    category: 'meddling',
  },
  {
    idiom: 'ser un gallina',
    literal: 'to be a hen',
    meaning: 'to be a coward / to chicken out',
    example: '¡No seas gallina! Salta al agua, que no está fría.',
    exampleEn: 'Don\'t be a coward! Jump in the water, it\'s not cold.',
    register: 'colloquial',
    category: 'courage',
  },
  {
    idiom: 'estar a dos velas',
    literal: 'to be at two candles',
    meaning: 'to be flat broke / to be penniless',
    example: 'No puedo salir esta semana — estoy a dos velas.',
    exampleEn: 'I can\'t go out this week — I\'m flat broke.',
    register: 'colloquial',
    category: 'money',
  },
  {
    idiom: 'costar un riñón',
    literal: 'to cost a kidney',
    meaning: 'to cost an arm and a leg / to be very expensive',
    example: 'Ese abrigo me costó un riñón, pero merece la pena.',
    exampleEn: 'That coat cost me an arm and a leg, but it\'s worth it.',
    register: 'colloquial',
    category: 'money',
  },
  {
    idiom: 'perder los papeles',
    literal: 'to lose one\'s papers',
    meaning: 'to lose one\'s temper / to lose it / to blow one\'s top',
    example: 'Perdió los papeles cuando se enteró de la verdad.',
    exampleEn: 'He lost his temper when he found out the truth.',
    register: 'colloquial',
    category: 'emotion',
  },
  {
    idiom: 'estar en las últimas',
    literal: 'to be in the last ones',
    meaning: 'to be on one\'s last legs / to be at death\'s door / to be nearly done',
    example: 'La batería del móvil está en las últimas.',
    exampleEn: 'The phone battery is on its last legs.',
    register: 'informal',
    category: 'condition',
  },
  {
    idiom: 'hacer el agosto',
    literal: 'to make August',
    meaning: 'to make a killing / to cash in / to make a lot of money',
    example: 'Los hoteles hicieron el agosto este verano.',
    exampleEn: 'The hotels made a killing this summer.',
    register: 'informal',
    category: 'money',
  },
  {
    idiom: 'tener mucha cara',
    literal: 'to have a lot of face',
    meaning: 'to have a lot of nerve / to have a cheek / to be very cheeky',
    example: 'Tienes mucha cara de pedirme dinero después de lo que hiciste.',
    exampleEn: 'You\'ve got a lot of nerve asking me for money after what you did.',
    register: 'colloquial',
    category: 'audacity',
  },
  {
    idiom: 'más sabe el diablo por viejo que por diablo',
    literal: 'the devil knows more from being old than from being the devil',
    meaning: 'wisdom comes with experience / with age comes wisdom',
    example: 'Escúchala — más sabe el diablo por viejo que por diablo.',
    exampleEn: 'Listen to her — wisdom comes with experience.',
    register: 'neutral',
    category: 'wisdom',
  },
  {
    idiom: 'cortar el bacalao',
    literal: 'to cut the cod',
    meaning: 'to call the shots / to be the boss / to run the show',
    example: 'Aquí quien corta el bacalao es el director general.',
    exampleEn: 'Around here it\'s the managing director who calls the shots.',
    register: 'colloquial',
    category: 'power',
  },
  {
    idiom: 'quien mucho abarca poco aprieta',
    literal: 'who grasps much squeezes little',
    meaning: 'don\'t bite off more than you can chew / jack of all trades, master of none',
    example: 'Llevas demasiados proyectos — quien mucho abarca poco aprieta.',
    exampleEn: 'You\'re taking on too many projects — don\'t bite off more than you can chew.',
    register: 'neutral',
    category: 'caution',
  },
  {
    idiom: 'ponerse morado',
    literal: 'to turn purple',
    meaning: 'to stuff oneself / to gorge / to eat or drink to excess',
    example: 'Nos pusimos morados de paella en la fiesta.',
    exampleEn: 'We stuffed ourselves with paella at the party.',
    register: 'colloquial',
    category: 'food',
  },
  {
    idiom: 'estar hecho polvo',
    literal: 'to be made of dust',
    meaning: 'to be shattered / to be exhausted / to be in a terrible state',
    example: 'Después del maratón estaba hecho polvo.',
    exampleEn: 'After the marathon he was completely shattered.',
    register: 'colloquial',
    category: 'exhaustion',
  },
  {
    idiom: 'ganarse las habichuelas',
    literal: 'to earn one\'s beans',
    meaning: 'to earn a living / to bring home the bacon',
    example: 'Trabajo doce horas al día para ganarme las habichuelas.',
    exampleEn: 'I work twelve hours a day to earn a living.',
    register: 'informal',
    category: 'work',
  },
  {
    idiom: 'hacer la pelota',
    literal: 'to make the ball',
    meaning: 'to suck up / to brown-nose / to butter someone up',
    example: 'Siempre le hace la pelota al jefe para conseguir los mejores turnos.',
    exampleEn: 'He always sucks up to the boss to get the best shifts.',
    register: 'colloquial',
    category: 'work',
  },
  {
    idiom: 'estar quemado',
    literal: 'to be burned',
    meaning: 'to be burned out / to be exhausted from overwork',
    example: 'Lleva cinco años sin vacaciones y está totalmente quemado.',
    exampleEn: 'He\'s gone five years without a holiday and is totally burned out.',
    register: 'informal',
    category: 'work',
  },
  {
    idiom: 'currárselo',
    literal: 'to really work it',
    meaning: 'to put real effort in / to work hard at something',
    example: 'Se lo curraron mucho con la presentación y se notó.',
    exampleEn: 'They really worked hard on the presentation and it showed.',
    register: 'colloquial',
    category: 'work',
  },
  {
    idiom: 'estar pachucho',
    literal: 'to be overripe / wilted',
    meaning: 'to be under the weather / to feel off / to be a bit ill',
    example: 'Hoy no voy a trabajar — me siento un poco pachucho.',
    exampleEn: 'I\'m not going to work today — I feel a bit under the weather.',
    register: 'informal',
    category: 'health',
  },
  {
    idiom: 'estar como un toro',
    literal: 'to be like a bull',
    meaning: 'to be in peak condition / to be strong as an ox',
    example: 'Tiene setenta años pero está como un toro.',
    exampleEn: 'He\'s seventy years old but he\'s strong as an ox.',
    register: 'informal',
    category: 'health',
  },
  {
    idiom: 'no estar para muchos trotes',
    literal: 'to not be up to many trots',
    meaning: 'to not be up to much / to have seen better days / to not have the energy',
    example: 'Después de la operación no estaba para muchos trotes.',
    exampleEn: 'After the operation she wasn\'t up to much.',
    register: 'informal',
    category: 'health',
  },
  {
    idiom: 'no ser plato de buen gusto',
    literal: 'to not be a dish of good taste',
    meaning: 'to be unpleasant / to be hard to take / not a nice thing to deal with',
    example: 'Dar malas noticias nunca es plato de buen gusto.',
    exampleEn: 'Giving bad news is never a pleasant thing.',
    register: 'neutral',
    category: 'food',
  },
  {
    idiom: 'en todas partes cuecen habas',
    literal: 'everywhere they cook beans',
    meaning: 'it\'s the same everywhere / every place has its problems',
    example: 'Pensaba que en la nueva empresa sería distinto, pero en todas partes cuecen habas.',
    exampleEn: 'I thought the new company would be different, but it\'s the same everywhere.',
    register: 'neutral',
    category: 'food',
  },
  {
    idiom: 'quedarse de piedra',
    literal: 'to turn to stone',
    meaning: 'to be gobsmacked / to be completely stunned or speechless',
    example: 'Cuando me dijeron que había ganado el premio me quedé de piedra.',
    exampleEn: 'When they told me I\'d won the prize I was completely gobsmacked.',
    register: 'informal',
    category: 'reactions',
  },
  {
    idiom: 'flipar en colores',
    literal: 'to flip out in colours',
    meaning: 'to be totally blown away / to be absolutely gobsmacked',
    example: 'Cuando vi el precio del apartamento flipé en colores.',
    exampleEn: 'When I saw the apartment price I was absolutely blown away.',
    register: 'colloquial',
    category: 'reactions',
  },
  {
    idiom: 'ponérsele los pelos de punta',
    literal: 'for one\'s hairs to stand on end',
    meaning: 'to make one\'s hair stand on end / to be terrifying or thrilling',
    example: 'La película de terror me puso los pelos de punta.',
    exampleEn: 'The horror film made my hair stand on end.',
    register: 'informal',
    category: 'reactions',
  },
  {
    idiom: 'de chiripa',
    literal: 'by chiripa (billiard fluke)',
    meaning: 'by a fluke / by sheer luck / by a lucky accident',
    example: 'Aprobé el examen de chiripa — ni había estudiado.',
    exampleEn: 'I passed the exam by sheer luck — I hadn\'t even studied.',
    register: 'colloquial',
    category: 'probability',
  },
  {
    idiom: 'de milagro',
    literal: 'by miracle',
    meaning: 'by a miracle / by the skin of one\'s teeth / barely avoiding disaster',
    example: 'Llegué al aeropuerto de milagro — el avión salía en cinco minutos.',
    exampleEn: 'I made it to the airport by the skin of my teeth — the plane left in five minutes.',
    register: 'informal',
    category: 'probability',
  },
  {
    idiom: 'más vale prevenir que curar',
    literal: 'better to prevent than to cure',
    meaning: 'better safe than sorry / prevention is better than cure',
    example: 'Lleva paraguas aunque no parezca que vaya a llover — más vale prevenir que curar.',
    exampleEn: 'Take an umbrella even if it doesn\'t look like rain — better safe than sorry.',
    register: 'neutral',
    category: 'advice',
  },
  {
    idiom: 'a caballo regalado no le mires el diente',
    literal: 'don\'t look at a gifted horse\'s tooth',
    meaning: 'don\'t look a gift horse in the mouth',
    example: 'La habitación era pequeña, pero a caballo regalado no le mires el diente.',
    exampleEn: 'The room was small, but don\'t look a gift horse in the mouth.',
    register: 'neutral',
    category: 'advice',
  },
  {
    idiom: 'hablar con el corazón en la mano',
    literal: 'to speak with one\'s heart in one\'s hand',
    meaning: 'to speak from the heart / to be completely open and honest',
    example: 'Te lo digo con el corazón en la mano: me preocupa tu actitud.',
    exampleEn: 'I\'m telling you from the heart: your attitude worries me.',
    register: 'informal',
    category: 'honesty',
  },
  {
    idiom: 'estar en la flor de la vida',
    literal: 'to be in the flower of life',
    meaning: 'to be in the prime of life / to be at one\'s peak',
    example: 'Tenía treinta años y estaba en la flor de la vida.',
    exampleEn: 'She was thirty and in the prime of her life.',
    register: 'neutral',
    category: 'age',
  },
  // ── EMOTION ──────────────────────────────────────────────────────────────
  {
    idiom: 'tener el corazón en un puño',
    literal: 'to have the heart in a fist',
    meaning: 'to have one\'s heart in one\'s mouth / to be gripped with anxiety',
    example: 'Mientras esperábamos los resultados, teníamos el corazón en un puño.',
    exampleEn: 'While we waited for the results, our hearts were in our mouths.',
    register: 'informal',
    category: 'emotion',
  },
  {
    idiom: 'estar con el alma en vilo',
    literal: 'to have one\'s soul hanging',
    meaning: 'to be on tenterhooks / to be in suspense',
    example: 'Estuvimos con el alma en vilo durante toda la operación.',
    exampleEn: 'We were on tenterhooks throughout the whole operation.',
    register: 'informal',
    category: 'emotion',
  },
  // ── DECEPTION ────────────────────────────────────────────────────────────
  {
    idiom: 'dar gato por liebre',
    literal: 'to give cat instead of hare',
    meaning: 'to sell someone a pup / to pass something inferior off as quality',
    example: 'Le dieron gato por liebre: el coche tenía más problemas de los que dijeron.',
    exampleEn: 'They sold him a pup: the car had more problems than they let on.',
    register: 'colloquial',
    category: 'deception',
  },
  {
    idiom: 'hacerse el loco',
    literal: 'to play the madman',
    meaning: 'to play dumb / to pretend not to notice',
    example: 'Le pregunté por el dinero y se hizo el loco.',
    exampleEn: 'I asked him about the money and he played dumb.',
    register: 'colloquial',
    category: 'deception',
  },
  // ── MISTAKES ─────────────────────────────────────────────────────────────
  {
    idiom: 'errar es de humanos',
    literal: 'to err is human',
    meaning: 'to err is human / everyone makes mistakes',
    example: 'No te preocupes tanto — errar es de humanos.',
    exampleEn: 'Don\'t worry so much — to err is human.',
    register: 'neutral',
    category: 'mistakes',
  },
  {
    idiom: 'tirar la piedra y esconder la mano',
    literal: 'to throw the stone and hide the hand',
    meaning: 'to make a move and then act innocent / to stir up trouble anonymously',
    example: 'Él empezó el rumor pero tira la piedra y esconde la mano.',
    exampleEn: 'He started the rumour but throws the stone and hides his hand.',
    register: 'colloquial',
    category: 'deception',
  },
  // ── FRUSTRATION ──────────────────────────────────────────────────────────
  {
    idiom: 'subírsele los humos',
    literal: 'for the fumes to go to one\'s head',
    meaning: 'to let success go to one\'s head / to get too big for one\'s boots',
    example: 'Desde que le ascendieron se le han subido los humos.',
    exampleEn: 'Since the promotion, success has gone to his head.',
    register: 'informal',
    category: 'frustration',
  },
  {
    idiom: 'estar hasta la coronilla',
    literal: 'to be up to the crown of the head',
    meaning: 'to be completely fed up / to be at the end of one\'s rope',
    example: 'Estoy hasta la coronilla de repetir lo mismo.',
    exampleEn: 'I\'m completely fed up with repeating the same thing.',
    register: 'colloquial',
    category: 'frustration',
  },
  // ── SURPRISE ─────────────────────────────────────────────────────────────
  {
    idiom: 'no dar crédito',
    literal: 'to not give credit',
    meaning: 'to not believe one\'s eyes or ears / to be incredulous',
    example: 'No daba crédito cuando vi las notas del examen.',
    exampleEn: 'I couldn\'t believe my eyes when I saw the exam results.',
    register: 'informal',
    category: 'surprise',
  },
  // ── SPEED ────────────────────────────────────────────────────────────────
  {
    idiom: 'a toda pastilla',
    literal: 'at full pill',
    meaning: 'at full speed / flat out',
    example: 'Iba a toda pastilla por la autopista.',
    exampleEn: 'He was going flat out on the motorway.',
    register: 'colloquial',
    category: 'speed',
  },
  {
    idiom: 'sin perder ni un segundo',
    literal: 'without losing a single second',
    meaning: 'without wasting a moment / immediately',
    example: 'En cuanto sonó la alarma, actuaron sin perder ni un segundo.',
    exampleEn: 'As soon as the alarm went off, they acted without losing a moment.',
    register: 'neutral',
    category: 'speed',
  },
  // ── RELATIONSHIPS ─────────────────────────────────────────────────────────
  {
    idiom: 'hacer buenas migas',
    literal: 'to make good crumbs',
    meaning: 'to hit it off / to get on well with someone from the start',
    example: 'Mis amigos hicieron buenas migas desde el primer momento.',
    exampleEn: 'My friends hit it off from the very first moment.',
    register: 'informal',
    category: 'relationships',
  },
  {
    idiom: 'guardar las distancias',
    literal: 'to keep the distances',
    meaning: 'to keep one\'s distance / to maintain a professional boundary',
    example: 'Es amable, pero siempre guarda las distancias con los clientes.',
    exampleEn: 'She is friendly but always keeps her distance from clients.',
    register: 'neutral',
    category: 'relationships',
  },
  // ── FORMAL REGISTER ──────────────────────────────────────────────────────
  {
    idiom: 'poner de manifiesto',
    literal: 'to put in manifest',
    meaning: 'to make evident / to bring to light / to reveal',
    example: 'El informe pone de manifiesto los fallos estructurales del sistema.',
    exampleEn: 'The report brings to light the structural flaws in the system.',
    register: 'formal',
    category: 'communication',
  },
  {
    idiom: 'dar lugar a',
    literal: 'to give place to',
    meaning: 'to give rise to / to lead to / to result in',
    example: 'La nueva ley dio lugar a una oleada de protestas.',
    exampleEn: 'The new law gave rise to a wave of protests.',
    register: 'formal',
    category: 'cause',
  },
  {
    idiom: 'en aras de',
    literal: 'in the altars of',
    meaning: 'for the sake of / in the interest of',
    example: 'En aras de la transparencia, todos los datos son públicos.',
    exampleEn: 'In the interest of transparency, all data is made public.',
    register: 'formal',
    category: 'purpose',
  },
  {
    idiom: 'llevar a cabo',
    literal: 'to carry to the end / to the cape',
    meaning: 'to carry out / to implement / to accomplish',
    example: 'El equipo llevó a cabo el proyecto en tiempo récord.',
    exampleEn: 'The team carried out the project in record time.',
    register: 'formal',
    category: 'work',
  },
  {
    idiom: 'hacer hincapié en',
    literal: 'to make emphasis in',
    meaning: 'to emphasise / to stress / to highlight',
    example: 'El director hizo hincapié en la importancia del trabajo en equipo.',
    exampleEn: 'The director stressed the importance of teamwork.',
    register: 'formal',
    category: 'communication',
  },
];

export const CATEGORIES = [...new Set(IDIOMS.map(i => i.category))].sort();
export const REGISTERS = ['colloquial', 'informal', 'neutral', 'formal'];

export function getByCategory(category) {
  return IDIOMS.filter(i => i.category === category);
}

export function getByRegister(register) {
  return IDIOMS.filter(i => i.register === register);
}

export function getRandom(n = 5) {
  return [...IDIOMS].sort(() => Math.random() - 0.5).slice(0, n);
}
