// Common Spanish idioms — register: colloquial | informal | neutral | formal

export const IDIOMS = [
  {
    idiom: 'costar un ojo de la cara',
    literal: 'to cost an eye from the face',
    meaning: 'to cost a fortune / to be very expensive',
    example: 'Las entradas costaron un ojo de la cara.',
    exampleEn: 'The tickets cost a fortune.',
    register: 'colloquial',
    category: 'money',
    cefr: 'B1',
  },
  {
    idiom: 'no hay mal que por bien no venga',
    literal: 'there is no bad from which good doesn\'t come',
    meaning: 'every cloud has a silver lining',
    example: 'Perdí el trabajo, pero encontré uno mejor. No hay mal que por bien no venga.',
    exampleEn: 'I lost my job but found a better one. Every cloud has a silver lining.',
    register: 'neutral',
    category: 'life',
    cefr: 'B2',
  },
  {
    idiom: 'matar dos pájaros de un tiro',
    literal: 'to kill two birds with one shot',
    meaning: 'to kill two birds with one stone',
    example: 'Fui al banco y al supermercado — maté dos pájaros de un tiro.',
    exampleEn: 'I went to the bank and the supermarket — killed two birds with one stone.',
    register: 'informal',
    category: 'efficiency',
    cefr: 'B1',
  },
  {
    idiom: 'ni hablar',
    literal: 'not even to talk',
    meaning: 'no way / out of the question',
    example: '—¿Me prestas el coche? —Ni hablar.',
    exampleEn: 'Can I borrow your car? — No way.',
    register: 'colloquial',
    category: 'refusal',
    cefr: 'A2',
  },
  {
    idiom: 'estar en las nubes',
    literal: 'to be in the clouds',
    meaning: 'to have one\'s head in the clouds / to be daydreaming',
    example: 'Siempre está en las nubes durante la clase.',
    exampleEn: 'He\'s always daydreaming during class.',
    register: 'informal',
    category: 'mind',
    cefr: 'B1',
  },
  {
    idiom: 'tomar el pelo',
    literal: 'to take the hair',
    meaning: 'to pull someone\'s leg / to tease',
    example: '¿Me estás tomando el pelo?',
    exampleEn: 'Are you pulling my leg?',
    register: 'colloquial',
    category: 'deception',
    cefr: 'B1',
  },
  {
    idiom: 'no pegar ojo',
    literal: 'not to stick an eye',
    meaning: 'to not sleep a wink',
    example: 'Anoche no pegué ojo por el ruido.',
    exampleEn: 'Last night I didn\'t sleep a wink because of the noise.',
    register: 'colloquial',
    category: 'sleep',
    cefr: 'B2',
  },
  {
    idiom: 'meter la pata',
    literal: 'to stick the paw in',
    meaning: 'to put one\'s foot in it / to make a blunder',
    example: 'Metí la pata cuando pregunté si estaba embarazada.',
    exampleEn: 'I put my foot in it when I asked if she was pregnant.',
    register: 'colloquial',
    category: 'mistakes',
    cefr: 'B1',
  },
  {
    idiom: 'ponerse las pilas',
    literal: 'to put in the batteries',
    meaning: 'to get one\'s act together / to pull one\'s socks up',
    example: 'Si quieres aprobar, tienes que ponerte las pilas.',
    exampleEn: 'If you want to pass, you need to get your act together.',
    register: 'colloquial',
    category: 'effort',
    cefr: 'B1',
  },
  {
    idiom: 'ser pan comido',
    literal: 'to be eaten bread',
    meaning: 'to be a piece of cake / very easy',
    example: 'El examen fue pan comido.',
    exampleEn: 'The exam was a piece of cake.',
    register: 'informal',
    category: 'ease',
    cefr: 'B1',
  },
  {
    idiom: 'estar hasta las narices',
    literal: 'to be up to the nostrils',
    meaning: 'to be fed up / to have had it up to here',
    example: 'Estoy hasta las narices de este trabajo.',
    exampleEn: 'I\'m fed up with this job.',
    register: 'colloquial',
    category: 'frustration',
    cefr: 'B2',
  },
  {
    idiom: 'no dar abasto',
    literal: 'not to give supply',
    meaning: 'to be unable to cope / to not be able to keep up',
    example: 'El restaurante no daba abasto durante el fin de semana.',
    exampleEn: 'The restaurant couldn\'t keep up during the weekend.',
    register: 'informal',
    category: 'work',
    cefr: 'B2',
  },
  {
    idiom: 'llueve sobre mojado',
    literal: 'it rains on the wet',
    meaning: 'it never rains but it pours',
    example: 'Se rompió el coche y encima me puse enfermo. Llueve sobre mojado.',
    exampleEn: 'The car broke down and on top of that I got sick. It never rains but it pours.',
    register: 'neutral',
    category: 'misfortune',
    cefr: 'C1',
  },
  {
    idiom: 'coger el toro por los cuernos',
    literal: 'to grab the bull by the horns',
    meaning: 'to take the bull by the horns / to face a problem directly',
    example: 'Hay que coger el toro por los cuernos y hablar con el jefe.',
    exampleEn: 'We need to take the bull by the horns and talk to the boss.',
    register: 'neutral',
    category: 'courage',
    cefr: 'B1',
  },
  {
    idiom: 'echar una mano',
    literal: 'to throw a hand',
    meaning: 'to give a hand / to help out',
    example: '¿Me echas una mano con esto?',
    exampleEn: 'Can you give me a hand with this?',
    register: 'informal',
    category: 'help',
    cefr: 'A2',
  },
  {
    idiom: 'no es para tanto',
    literal: 'it\'s not for that much',
    meaning: 'it\'s not a big deal / don\'t make such a fuss',
    example: '—¡Me duele mucho! —No es para tanto.',
    exampleEn: 'It hurts so much! — It\'s not a big deal.',
    register: 'colloquial',
    category: 'reactions',
    cefr: 'A2',
  },
  {
    idiom: 'a última hora',
    literal: 'at the last hour',
    meaning: 'at the last minute',
    example: 'Siempre lo deja todo para última hora.',
    exampleEn: 'He always leaves everything to the last minute.',
    register: 'neutral',
    category: 'time',
    cefr: 'A2',
  },
  {
    idiom: 'quedarse con la boca abierta',
    literal: 'to remain with the mouth open',
    meaning: 'to be left speechless / to be amazed',
    example: 'Me quedé con la boca abierta cuando vi el precio.',
    exampleEn: 'I was left speechless when I saw the price.',
    register: 'informal',
    category: 'surprise',
    cefr: 'B1',
  },
  {
    idiom: 'dar en el clavo',
    literal: 'to hit the nail',
    meaning: 'to hit the nail on the head',
    example: 'Diste en el clavo con esa observación.',
    exampleEn: 'You hit the nail on the head with that observation.',
    register: 'neutral',
    category: 'accuracy',
    cefr: 'B2',
  },
  {
    idiom: 'no tener pelos en la lengua',
    literal: 'to have no hairs on the tongue',
    meaning: 'to not mince words / to speak one\'s mind',
    example: 'María no tiene pelos en la lengua — dice lo que piensa.',
    exampleEn: 'María doesn\'t mince words — she says what she thinks.',
    register: 'informal',
    category: 'communication',
    cefr: 'B2',
  },
  {
    idiom: 'ser un hueso duro de roer',
    literal: 'to be a hard bone to gnaw',
    meaning: 'to be a tough nut to crack',
    example: 'El subjuntivo es un hueso duro de roer.',
    exampleEn: 'The subjunctive is a tough nut to crack.',
    register: 'informal',
    category: 'difficulty',
    cefr: 'B2',
  },
  {
    idiom: 'a ver',
    literal: 'to see',
    meaning: 'let\'s see / well / come on (filler expression)',
    example: 'A ver, ¿qué quieres decir exactamente?',
    exampleEn: 'Let\'s see, what exactly do you mean?',
    register: 'colloquial',
    category: 'fillers',
    cefr: 'A1',
  },
  {
    idiom: 'al pie de la letra',
    literal: 'at the foot of the letter',
    meaning: 'to the letter / exactly as said',
    example: 'Siguió las instrucciones al pie de la letra.',
    exampleEn: 'She followed the instructions to the letter.',
    register: 'neutral',
    category: 'precision',
    cefr: 'B2',
  },
  {
    idiom: 'estar en forma',
    literal: 'to be in form',
    meaning: 'to be in shape / to be fit',
    example: 'Hace deporte para estar en forma.',
    exampleEn: 'She exercises to stay in shape.',
    register: 'neutral',
    category: 'health',
    cefr: 'A2',
  },
  {
    idiom: 'perder la cabeza',
    literal: 'to lose the head',
    meaning: 'to lose one\'s mind / to go crazy',
    example: 'Has perdido la cabeza si crees eso.',
    exampleEn: 'You\'ve lost your mind if you believe that.',
    register: 'informal',
    category: 'mind',
    cefr: 'B1',
  },
  {
    idiom: 'de vez en cuando',
    literal: 'from time to time',
    meaning: 'from time to time / occasionally',
    example: 'De vez en cuando me apetece un helado.',
    exampleEn: 'From time to time I feel like having ice cream.',
    register: 'neutral',
    category: 'frequency',
    cefr: 'A2',
  },
  {
    idiom: 'no cabe duda',
    literal: 'there\'s no room for doubt',
    meaning: 'there\'s no doubt / without doubt',
    example: 'No cabe duda de que es el mejor.',
    exampleEn: 'There\'s no doubt that he\'s the best.',
    register: 'neutral',
    category: 'certainty',
    cefr: 'B2',
  },
  {
    idiom: 'poner al día',
    literal: 'to put to the day',
    meaning: 'to bring up to date / to catch up',
    example: 'Ponme al día de las noticias.',
    exampleEn: 'Fill me in on the news.',
    register: 'informal',
    category: 'communication',
    cefr: 'B2',
  },
  {
    idiom: 'en el fondo',
    literal: 'at the bottom',
    meaning: 'deep down / at heart / basically',
    example: 'En el fondo, es una buena persona.',
    exampleEn: 'Deep down, he\'s a good person.',
    register: 'neutral',
    category: 'truth',
    cefr: 'B2',
  },
  {
    idiom: 'a lo mejor',
    literal: 'at the best',
    meaning: 'maybe / perhaps',
    example: 'A lo mejor viene esta tarde.',
    exampleEn: 'Maybe she\'ll come this afternoon.',
    register: 'informal',
    category: 'probability',
    cefr: 'A2',
  },
  {
    idiom: 'hacer falta',
    literal: 'to make lack',
    meaning: 'to be needed / to need',
    example: 'Me hace falta un diccionario.',
    exampleEn: 'I need a dictionary.',
    register: 'neutral',
    category: 'need',
    cefr: 'A2',
  },
  {
    idiom: 'tener buena/mala pinta',
    literal: 'to have good/bad appearance',
    meaning: 'to look good/bad / to seem promising or not',
    example: 'Ese plato tiene muy buena pinta.',
    exampleEn: 'That dish looks really good.',
    register: 'colloquial',
    category: 'appearances',
    cefr: 'B1',
  },
  {
    idiom: 'ser un rollo',
    literal: 'to be a roll',
    meaning: 'to be boring / a drag',
    example: 'Esta reunión es un rollo.',
    exampleEn: 'This meeting is such a drag.',
    register: 'colloquial',
    category: 'boredom',
    cefr: 'B1',
  },
  {
    idiom: 'tomar la delantera',
    literal: 'to take the front',
    meaning: 'to get ahead / to take the lead',
    example: 'Hay que tomar la delantera en el mercado.',
    exampleEn: 'We need to take the lead in the market.',
    register: 'neutral',
    category: 'competition',
    cefr: 'B2',
  },
  {
    idiom: 'no pasa nada',
    literal: 'nothing happens',
    meaning: 'don\'t worry about it / it\'s all good / no problem',
    example: '—Lo siento mucho. —No pasa nada.',
    exampleEn: 'I\'m so sorry. — Don\'t worry about it.',
    register: 'colloquial',
    category: 'reassurance',
    cefr: 'A2',
  },
  {
    idiom: 'valer la pena',
    literal: 'to be worth the pain',
    meaning: 'to be worth it',
    example: 'Aprender español vale la pena.',
    exampleEn: 'Learning Spanish is worth it.',
    register: 'neutral',
    category: 'value',
    cefr: 'B1',
  },
  {
    idiom: 'a grandes rasgos',
    literal: 'in broad strokes',
    meaning: 'broadly speaking / in general terms',
    example: 'A grandes rasgos, el plan funciona.',
    exampleEn: 'Broadly speaking, the plan works.',
    register: 'neutral',
    category: 'summary',
    cefr: 'B2',
  },
  {
    idiom: 'con las manos en la masa',
    literal: 'with hands in the dough',
    meaning: 'red-handed / in the act',
    example: 'Lo pillaron con las manos en la masa.',
    exampleEn: 'They caught him red-handed.',
    register: 'informal',
    category: 'crime',
    cefr: 'B2',
  },
  {
    idiom: 'dar la lata',
    literal: 'to give the tin',
    meaning: 'to be a nuisance / to pester',
    example: 'Deja de dar la lata con eso.',
    exampleEn: 'Stop being a nuisance about that.',
    register: 'colloquial',
    category: 'annoyance',
    cefr: 'B2',
  },
  {
    idiom: 'en un abrir y cerrar de ojos',
    literal: 'in an opening and closing of eyes',
    meaning: 'in the blink of an eye',
    example: 'Lo hizo en un abrir y cerrar de ojos.',
    exampleEn: 'He did it in the blink of an eye.',
    register: 'neutral',
    category: 'speed',
    cefr: 'B2',
  },
  {
    idiom: 'no dar pie con bola',
    literal: 'not to hit a ball with one\'s foot',
    meaning: 'to be unable to do anything right',
    example: 'Hoy no doy pie con bola — todo me sale mal.',
    exampleEn: 'Today I can\'t do anything right — everything goes wrong.',
    register: 'colloquial',
    category: 'failure',
    cefr: 'C1',
  },
  {
    idiom: 'tirar la casa por la ventana',
    literal: 'to throw the house out of the window',
    meaning: 'to go all out / to spare no expense',
    example: 'Para la boda tiraron la casa por la ventana.',
    exampleEn: 'For the wedding they spared no expense.',
    register: 'informal',
    category: 'money',
    cefr: 'B2',
  },
  {
    idiom: 'llevarse como el perro y el gato',
    literal: 'to get along like a dog and a cat',
    meaning: 'to fight like cat and dog',
    example: 'Mis hermanos se llevan como el perro y el gato.',
    exampleEn: 'My siblings fight like cat and dog.',
    register: 'informal',
    category: 'relationships',
    cefr: 'B1',
  },
  {
    idiom: 'no hay mal que cien años dure',
    literal: 'there is no hardship that lasts a hundred years',
    meaning: 'this too shall pass / nothing lasts forever',
    example: '¡Ánimo! No hay mal que cien años dure.',
    exampleEn: 'Cheer up! This too shall pass.',
    register: 'neutral',
    category: 'life',
    cefr: 'C1',
  },
  {
    idiom: 'quemar las naves',
    literal: 'to burn the ships',
    meaning: 'to burn one\'s bridges / to commit fully with no way back',
    example: 'Dejó su trabajo y quemó las naves.',
    exampleEn: 'He quit his job and burned his bridges.',
    register: 'neutral',
    category: 'decisions',
    cefr: 'C1',
  },
  {
    idiom: 'ver los toros desde la barrera',
    literal: 'to watch the bulls from behind the barrier',
    meaning: 'to watch from the sidelines / to play it safe',
    example: 'Prefiere ver los toros desde la barrera y no comprometerse.',
    exampleEn: 'He prefers to play it safe and not commit.',
    register: 'neutral',
    category: 'caution',
    cefr: 'C1',
  },
  {
    idiom: 'buscarle tres pies al gato',
    literal: 'to look for three feet on a cat',
    meaning: 'to complicate things unnecessarily / to look for trouble',
    example: 'No le busques tres pies al gato — la solución es simple.',
    exampleEn: 'Don\'t overcomplicate things — the solution is simple.',
    register: 'informal',
    category: 'problems',
    cefr: 'B2',
  },
  {
    idiom: 'dormir a pierna suelta',
    literal: 'to sleep with a loose leg',
    meaning: 'to sleep like a log / to sleep soundly',
    example: 'Después del viaje dormí a pierna suelta.',
    exampleEn: 'After the trip I slept like a log.',
    register: 'informal',
    category: 'sleep',
    cefr: 'B2',
  },
  {
    idiom: 'en boca cerrada no entran moscas',
    literal: 'in a closed mouth no flies enter',
    meaning: 'silence is golden / keep your mouth shut',
    example: 'Mejor no digas nada — en boca cerrada no entran moscas.',
    exampleEn: 'Better say nothing — silence is golden.',
    register: 'neutral',
    category: 'advice',
    cefr: 'B2',
  },
  {
    idiom: 'tener mano izquierda',
    literal: 'to have a left hand',
    meaning: 'to be tactful / to have good people skills',
    example: 'Tiene mucha mano izquierda para resolver conflictos.',
    exampleEn: 'She has great tact when resolving conflicts.',
    register: 'informal',
    category: 'personality',
    cefr: 'B2',
  },
  {
    idiom: 'a lo hecho, pecho',
    literal: 'to what\'s done, chest (face it)',
    meaning: 'what\'s done is done — face it',
    example: 'No te arrepientas — a lo hecho, pecho.',
    exampleEn: 'Don\'t regret it — what\'s done is done.',
    register: 'informal',
    category: 'acceptance',
    cefr: 'B2',
  },
  {
    idiom: 'hacer de tripas corazón',
    literal: 'to make heart out of guts',
    meaning: 'to steel oneself / to grit one\'s teeth and carry on',
    example: 'Hizo de tripas corazón y presentó el informe.',
    exampleEn: 'She steeled herself and delivered the report.',
    register: 'informal',
    category: 'courage',
    cefr: 'C1',
  },
  {
    idiom: 'no saber ni papa',
    literal: 'to not even know a potato',
    meaning: 'to not have a clue / to know absolutely nothing',
    example: 'No sé ni papa de informática.',
    exampleEn: 'I don\'t have a clue about computing.',
    register: 'colloquial',
    category: 'knowledge',
    cefr: 'B2',
  },
  {
    idiom: 'andarse por las ramas',
    literal: 'to walk around the branches',
    meaning: 'to beat around the bush',
    example: 'Deja de andarte por las ramas y dime la verdad.',
    exampleEn: 'Stop beating around the bush and tell me the truth.',
    register: 'informal',
    category: 'communication',
    cefr: 'B2',
  },
  {
    idiom: 'estar como una cabra',
    literal: 'to be like a goat',
    meaning: 'to be crazy / off one\'s rocker',
    example: 'Se pone a cantar a las 3 de la mañana — está como una cabra.',
    exampleEn: 'He starts singing at 3am — he\'s off his rocker.',
    register: 'colloquial',
    category: 'personality',
    cefr: 'B1',
  },
  {
    idiom: 'a rajatabla',
    literal: 'at split-board',
    meaning: 'strictly / to the letter / without exception',
    example: 'Cumplió las normas a rajatabla.',
    exampleEn: 'She followed the rules to the letter.',
    register: 'neutral',
    category: 'precision',
    cefr: 'B2',
  },
  {
    idiom: 'estar entre la espada y la pared',
    literal: 'to be between the sword and the wall',
    meaning: 'to be between a rock and a hard place / in an impossible situation',
    example: 'Me dejó entre la espada y la pared.',
    exampleEn: 'He left me between a rock and a hard place.',
    register: 'neutral',
    category: 'dilemmas',
    cefr: 'B1',
  },
  {
    idiom: 'poner el dedo en la llaga',
    literal: 'to put one\'s finger on the wound',
    meaning: 'to hit a raw nerve / to pinpoint the exact problem',
    example: 'Con esa pregunta puso el dedo en la llaga.',
    exampleEn: 'With that question he hit a raw nerve.',
    register: 'informal',
    category: 'truth',
    cefr: 'B2',
  },
  {
    idiom: 'salir el tiro por la culata',
    literal: 'for the shot to come out of the butt',
    meaning: 'to backfire',
    example: 'El plan le salió por la culata.',
    exampleEn: 'The plan backfired on her.',
    register: 'informal',
    category: 'failure',
    cefr: 'B2',
  },
  {
    idiom: 'no hay dos sin tres',
    literal: 'there\'s no two without three',
    meaning: 'these things come in threes (used for both good and bad repeated events)',
    example: 'Van dos retrasos esta semana — no hay dos sin tres.',
    exampleEn: 'That\'s two delays this week — these things come in threes.',
    register: 'informal',
    category: 'patterns',
    cefr: 'B2',
  },
  {
    idiom: 'más vale tarde que nunca',
    literal: 'better late than never',
    meaning: 'better to arrive late or do something belatedly than not at all',
    example: 'Llegó con dos horas de retraso, pero más vale tarde que nunca.',
    exampleEn: 'She arrived two hours late, but better late than never.',
    register: 'neutral',
    category: 'time',
    cefr: 'A2',
  },
  {
    idiom: 'no todo el monte es orégano',
    literal: 'not all the hillside is oregano',
    meaning: 'it\'s not all sunshine and roses / things are more complicated than they seem',
    example: 'Te llevarás una sorpresa — no todo el monte es orégano.',
    exampleEn: 'You\'ll be in for a surprise — it\'s not all sunshine and roses.',
    register: 'informal',
    category: 'reality',
    cefr: 'C1',
  },
  {
    idiom: 'poner toda la carne en el asador',
    literal: 'to put all the meat on the grill',
    meaning: 'to go all in / to give it everything you\'ve got',
    example: 'Para el examen final, puso toda la carne en el asador.',
    exampleEn: 'For the final exam, she gave it everything she had.',
    register: 'informal',
    category: 'effort',
    cefr: 'B2',
  },
  {
    idiom: 'echar leña al fuego',
    literal: 'to throw wood on the fire',
    meaning: 'to add fuel to the fire / to make a bad situation worse',
    example: 'Sus comentarios solo echaron leña al fuego.',
    exampleEn: 'His comments only added fuel to the fire.',
    register: 'informal',
    category: 'conflict',
    cefr: 'B2',
  },
  {
    idiom: 'quedarse en blanco',
    literal: 'to go blank / white',
    meaning: 'to draw a blank / to go blank (forget completely)',
    example: 'En el examen me quedé en blanco.',
    exampleEn: 'In the exam I drew a blank.',
    register: 'informal',
    category: 'mind',
    cefr: 'B1',
  },
  {
    idiom: 'a trancas y barrancas',
    literal: 'with bars and ravines',
    meaning: 'with great difficulty / overcoming many obstacles',
    example: 'Logró terminar el proyecto a trancas y barrancas.',
    exampleEn: 'She managed to finish the project despite all the obstacles.',
    register: 'informal',
    category: 'difficulty',
    cefr: 'C1',
  },
  {
    idiom: 'tener la cabeza en su sitio',
    literal: 'to have one\'s head in its place',
    meaning: 'to have one\'s head screwed on / to be level-headed',
    example: 'Es joven, pero tiene la cabeza en su sitio.',
    exampleEn: 'She\'s young, but she has her head screwed on.',
    register: 'informal',
    category: 'sense',
    cefr: 'B2',
  },
  {
    idiom: 'meterse en camisa de once varas',
    literal: 'to get into an eleven-vara shirt',
    meaning: 'to get into unnecessary trouble / to complicate things needlessly',
    example: 'No te metas en camisa de once varas — déjalo estar.',
    exampleEn: 'Don\'t get into unnecessary trouble — just let it go.',
    register: 'informal',
    category: 'problems',
    cefr: 'C2',
  },
  {
    idiom: 'a pie juntillas',
    literal: 'with feet joined together',
    meaning: 'firmly / unquestioningly / without a shadow of a doubt',
    example: 'Se cree todo a pie juntillas.',
    exampleEn: 'She believes everything unquestioningly.',
    register: 'informal',
    category: 'belief',
    cefr: 'C2',
  },
  {
    idiom: 'tomar las de Villadiego',
    literal: 'to take the things from Villadiego',
    meaning: 'to make a run for it / to flee quickly',
    example: 'Cuando vio al inspector, tomó las de Villadiego.',
    exampleEn: 'When he saw the inspector, he made a run for it.',
    register: 'colloquial',
    category: 'escape',
    cefr: 'C2',
  },
  {
    idiom: 'subírsele los humos a la cabeza',
    literal: 'for the fumes to rise to one\'s head',
    meaning: 'to get too big for one\'s boots / to let success go to one\'s head',
    example: 'Desde que le ascendieron se le subieron los humos a la cabeza.',
    exampleEn: 'Since his promotion, success has gone to his head.',
    register: 'colloquial',
    category: 'personality',
    cefr: 'B2',
  },
  {
    idiom: 'estar como pez en el agua',
    literal: 'to be like a fish in water',
    meaning: 'to be in one\'s element / to feel completely at home',
    example: 'En el escenario está como pez en el agua.',
    exampleEn: 'On stage she\'s completely in her element.',
    register: 'informal',
    category: 'comfort',
    cefr: 'B1',
  },
  {
    idiom: 'a otro perro con ese hueso',
    literal: 'go to another dog with that bone',
    meaning: 'tell it to someone who\'ll believe it / pull the other one',
    example: '—No tengo dinero. —A otro perro con ese hueso.',
    exampleEn: 'I have no money. — Pull the other one.',
    register: 'colloquial',
    category: 'disbelief',
    cefr: 'B2',
  },
  {
    idiom: 'llevar la voz cantante',
    literal: 'to carry the singing voice',
    meaning: 'to call the shots / to be in charge',
    example: 'En esta empresa siempre ha llevado la voz cantante.',
    exampleEn: 'She\'s always called the shots in this company.',
    register: 'neutral',
    category: 'power',
    cefr: 'B2',
  },
  {
    idiom: 'no hay tu tía',
    literal: 'there\'s no your aunt',
    meaning: 'there\'s no way around it / nothing doing',
    example: 'No hay tu tía — tendrás que hacerlo tú mismo.',
    exampleEn: 'There\'s no way around it — you\'ll have to do it yourself.',
    register: 'colloquial',
    category: 'impossibility',
    cefr: 'C2',
  },
  {
    idiom: 'caérsele el alma a los pies',
    literal: 'for one\'s soul to fall to one\'s feet',
    meaning: 'to have one\'s heart sink / to be crushed by bad news',
    example: 'Se me cayó el alma a los pies cuando supe la noticia.',
    exampleEn: 'My heart sank when I heard the news.',
    register: 'informal',
    category: 'emotion',
    cefr: 'B2',
  },
  {
    idiom: 'hacer la vista gorda',
    literal: 'to make the fat view',
    meaning: 'to turn a blind eye / to pretend not to notice',
    example: 'El jefe hacía la vista gorda con los retrasos.',
    exampleEn: 'The boss turned a blind eye to the lateness.',
    register: 'informal',
    category: 'ignorance',
    cefr: 'B1',
  },
  {
    idiom: 'tirarse a la piscina',
    literal: 'to throw oneself into the swimming pool',
    meaning: 'to take the plunge / to go for it despite the risk',
    example: 'Por fin me tiré a la piscina y le pedí trabajo.',
    exampleEn: 'I finally took the plunge and asked for a job.',
    register: 'informal',
    category: 'courage',
    cefr: 'B1',
  },
  {
    idiom: 'no dar un palo al agua',
    literal: 'to not give a stick to the water',
    meaning: 'to not do a stroke of work / to be bone idle',
    example: 'Ese chico no da un palo al agua en todo el día.',
    exampleEn: 'That guy doesn\'t do a stroke of work all day.',
    register: 'colloquial',
    category: 'laziness',
    cefr: 'B2',
  },
  {
    idiom: 'a buenas horas mangas verdes',
    literal: 'at a good hour, green sleeves',
    meaning: 'too little, too late (said sarcastically when help or a solution arrives after it\'s no longer needed)',
    example: '¡A buenas horas mangas verdes! Ya hemos terminado sin ti.',
    exampleEn: 'Oh, NOW you show up! We already finished without you.',
    register: 'colloquial',
    category: 'timing',
    cefr: 'C2',
  },
  {
    idiom: 'hablar por los codos',
    literal: 'to speak through one\'s elbows',
    meaning: 'to talk nineteen to the dozen / to be a chatterbox',
    example: 'Mi vecina habla por los codos; no para nunca.',
    exampleEn: 'My neighbour talks nineteen to the dozen; she never stops.',
    register: 'colloquial',
    category: 'speech',
    cefr: 'B1',
  },
  {
    idiom: 'costar sangre, sudor y lágrimas',
    literal: 'to cost blood, sweat, and tears',
    meaning: 'to cost blood, sweat, and tears / to require great effort',
    example: 'Conseguir ese trabajo le costó sangre, sudor y lágrimas.',
    exampleEn: 'Getting that job cost him blood, sweat, and tears.',
    register: 'neutral',
    category: 'effort',
    cefr: 'B1',
  },
  {
    idiom: 'tener la sartén por el mango',
    literal: 'to hold the frying pan by the handle',
    meaning: 'to be in control / to call the shots / to have the upper hand',
    example: 'En esa empresa ella tiene la sartén por el mango.',
    exampleEn: 'In that company she calls the shots.',
    register: 'informal',
    category: 'power',
    cefr: 'B2',
  },
  {
    idiom: 'estar con el agua al cuello',
    literal: 'to have water up to the neck',
    meaning: 'to be up to one\'s neck / to be in a very difficult situation',
    example: 'Estamos con el agua al cuello con estas deudas.',
    exampleEn: 'We\'re up to our necks with these debts.',
    register: 'informal',
    category: 'difficulty',
    cefr: 'B1',
  },
  {
    idiom: 'ir al grano',
    literal: 'to go to the grain',
    meaning: 'to get to the point / to cut to the chase',
    example: 'Deja de rodeos y ve al grano.',
    exampleEn: 'Stop beating around the bush and get to the point.',
    register: 'informal',
    category: 'communication',
    cefr: 'A2',
  },
  {
    idiom: 'echar de menos',
    literal: 'to throw from less',
    meaning: 'to miss (someone or something)',
    example: 'Echo mucho de menos a mis amigos del instituto.',
    exampleEn: 'I really miss my friends from secondary school.',
    register: 'neutral',
    category: 'emotion',
    cefr: 'A2',
  },
  {
    idiom: 'romper el hielo',
    literal: 'to break the ice',
    meaning: 'to break the ice / to ease the tension in a new social situation',
    example: 'Contó un chiste para romper el hielo al principio de la reunión.',
    exampleEn: 'He told a joke to break the ice at the start of the meeting.',
    register: 'neutral',
    category: 'social',
    cefr: 'A2',
  },
  {
    idiom: 'nadar entre dos aguas',
    literal: 'to swim between two waters',
    meaning: 'to sit on the fence / to avoid committing to either side',
    example: 'Siempre nada entre dos aguas y nunca toma partido.',
    exampleEn: 'She always sits on the fence and never takes a side.',
    register: 'informal',
    category: 'decisions',
    cefr: 'B2',
  },
  {
    idiom: 'pedir peras al olmo',
    literal: 'to ask pears from the elm tree',
    meaning: 'to ask for the impossible / to expect something from someone incapable of it',
    example: 'Pedirle puntualidad a Juan es pedir peras al olmo.',
    exampleEn: 'Expecting punctuality from Juan is asking for the impossible.',
    register: 'informal',
    category: 'impossibility',
    cefr: 'B2',
  },
  {
    idiom: 'saltar a la vista',
    literal: 'to jump to the sight',
    meaning: 'to be obvious / to be plain to see',
    example: 'Salta a la vista que no ha dormido bien.',
    exampleEn: 'It\'s plain to see that he hasn\'t slept well.',
    register: 'neutral',
    category: 'obviousness',
    cefr: 'B1',
  },
  {
    idiom: 'dar calabazas',
    literal: 'to give pumpkins',
    meaning: 'to reject / to dump someone / to turn someone down (romantically or in an exam)',
    example: 'Le propuso salir y ella le dio calabazas.',
    exampleEn: 'He asked her out and she turned him down.',
    register: 'colloquial',
    category: 'relationships',
    cefr: 'C1',
  },
  {
    idiom: 'irse por las ramas',
    literal: 'to go off through the branches',
    meaning: 'to beat around the bush / to go off on a tangent',
    example: 'No te vayas por las ramas — dime exactamente qué pasó.',
    exampleEn: 'Don\'t beat around the bush — tell me exactly what happened.',
    register: 'informal',
    category: 'communication',
    cefr: 'B2',
  },
  {
    idiom: 'meter las narices',
    literal: 'to stick one\'s nostrils in',
    meaning: 'to poke one\'s nose in / to meddle in other people\'s business',
    example: 'Siempre está metiendo las narices en los asuntos ajenos.',
    exampleEn: 'She\'s always poking her nose into other people\'s business.',
    register: 'colloquial',
    category: 'meddling',
    cefr: 'B1',
  },
  {
    idiom: 'ser un gallina',
    literal: 'to be a hen',
    meaning: 'to be a coward / to chicken out',
    example: '¡No seas gallina! Salta al agua, que no está fría.',
    exampleEn: 'Don\'t be a coward! Jump in the water, it\'s not cold.',
    register: 'colloquial',
    category: 'courage',
    cefr: 'B1',
  },
  {
    idiom: 'estar a dos velas',
    literal: 'to be at two candles',
    meaning: 'to be flat broke / to be penniless',
    example: 'No puedo salir esta semana — estoy a dos velas.',
    exampleEn: 'I can\'t go out this week — I\'m flat broke.',
    register: 'colloquial',
    category: 'money',
    cefr: 'B2',
  },
  {
    idiom: 'costar un riñón',
    literal: 'to cost a kidney',
    meaning: 'to cost an arm and a leg / to be very expensive',
    example: 'Ese abrigo me costó un riñón, pero merece la pena.',
    exampleEn: 'That coat cost me an arm and a leg, but it\'s worth it.',
    register: 'colloquial',
    category: 'money',
    cefr: 'B1',
  },
  {
    idiom: 'perder los papeles',
    literal: 'to lose one\'s papers',
    meaning: 'to lose one\'s temper / to lose it / to blow one\'s top',
    example: 'Perdió los papeles cuando se enteró de la verdad.',
    exampleEn: 'He lost his temper when he found out the truth.',
    register: 'colloquial',
    category: 'emotion',
    cefr: 'B1',
  },
  {
    idiom: 'estar en las últimas',
    literal: 'to be in the last ones',
    meaning: 'to be on one\'s last legs / to be at death\'s door / to be nearly done',
    example: 'La batería del móvil está en las últimas.',
    exampleEn: 'The phone battery is on its last legs.',
    register: 'informal',
    category: 'condition',
    cefr: 'B2',
  },
  {
    idiom: 'hacer el agosto',
    literal: 'to make August',
    meaning: 'to make a killing / to cash in / to make a lot of money',
    example: 'Los hoteles hicieron el agosto este verano.',
    exampleEn: 'The hotels made a killing this summer.',
    register: 'informal',
    category: 'money',
    cefr: 'C1',
  },
  {
    idiom: 'tener mucha cara',
    literal: 'to have a lot of face',
    meaning: 'to have a lot of nerve / to have a cheek / to be very cheeky',
    example: 'Tienes mucha cara de pedirme dinero después de lo que hiciste.',
    exampleEn: 'You\'ve got a lot of nerve asking me for money after what you did.',
    register: 'colloquial',
    category: 'audacity',
    cefr: 'B1',
  },
  {
    idiom: 'más sabe el diablo por viejo que por diablo',
    literal: 'the devil knows more from being old than from being the devil',
    meaning: 'wisdom comes with experience / with age comes wisdom',
    example: 'Escúchala — más sabe el diablo por viejo que por diablo.',
    exampleEn: 'Listen to her — wisdom comes with experience.',
    register: 'neutral',
    category: 'wisdom',
    cefr: 'C2',
  },
  {
    idiom: 'cortar el bacalao',
    literal: 'to cut the cod',
    meaning: 'to call the shots / to be the boss / to run the show',
    example: 'Aquí quien corta el bacalao es el director general.',
    exampleEn: 'Around here it\'s the managing director who calls the shots.',
    register: 'colloquial',
    category: 'power',
    cefr: 'C1',
  },
  {
    idiom: 'quien mucho abarca poco aprieta',
    literal: 'who grasps much squeezes little',
    meaning: 'don\'t bite off more than you can chew / jack of all trades, master of none',
    example: 'Llevas demasiados proyectos — quien mucho abarca poco aprieta.',
    exampleEn: 'You\'re taking on too many projects — don\'t bite off more than you can chew.',
    register: 'neutral',
    category: 'caution',
    cefr: 'B2',
  },
  {
    idiom: 'ponerse morado',
    literal: 'to turn purple',
    meaning: 'to stuff oneself / to gorge / to eat or drink to excess',
    example: 'Nos pusimos morados de paella en la fiesta.',
    exampleEn: 'We stuffed ourselves with paella at the party.',
    register: 'colloquial',
    category: 'food',
    cefr: 'B2',
  },
  {
    idiom: 'estar hecho polvo',
    literal: 'to be made of dust',
    meaning: 'to be shattered / to be exhausted / to be in a terrible state',
    example: 'Después del maratón estaba hecho polvo.',
    exampleEn: 'After the marathon he was completely shattered.',
    register: 'colloquial',
    category: 'exhaustion',
    cefr: 'B1',
  },
  {
    idiom: 'ganarse las habichuelas',
    literal: 'to earn one\'s beans',
    meaning: 'to earn a living / to bring home the bacon',
    example: 'Trabajo doce horas al día para ganarme las habichuelas.',
    exampleEn: 'I work twelve hours a day to earn a living.',
    register: 'informal',
    category: 'work',
    cefr: 'C1',
  },
  {
    idiom: 'hacer la pelota',
    literal: 'to make the ball',
    meaning: 'to suck up / to brown-nose / to butter someone up',
    example: 'Siempre le hace la pelota al jefe para conseguir los mejores turnos.',
    exampleEn: 'He always sucks up to the boss to get the best shifts.',
    register: 'colloquial',
    category: 'work',
    cefr: 'B1',
  },
  {
    idiom: 'estar quemado',
    literal: 'to be burned',
    meaning: 'to be burned out / to be exhausted from overwork',
    example: 'Lleva cinco años sin vacaciones y está totalmente quemado.',
    exampleEn: 'He\'s gone five years without a holiday and is totally burned out.',
    register: 'informal',
    category: 'work',
    cefr: 'B1',
  },
  {
    idiom: 'currárselo',
    literal: 'to really work it',
    meaning: 'to put real effort in / to work hard at something',
    example: 'Se lo curraron mucho con la presentación y se notó.',
    exampleEn: 'They really worked hard on the presentation and it showed.',
    register: 'colloquial',
    category: 'work',
    cefr: 'C1',
  },
  {
    idiom: 'estar pachucho',
    literal: 'to be overripe / wilted',
    meaning: 'to be under the weather / to feel off / to be a bit ill',
    example: 'Hoy no voy a trabajar — me siento un poco pachucho.',
    exampleEn: 'I\'m not going to work today — I feel a bit under the weather.',
    register: 'informal',
    category: 'health',
    cefr: 'B2',
  },
  {
    idiom: 'estar como un toro',
    literal: 'to be like a bull',
    meaning: 'to be in peak condition / to be strong as an ox',
    example: 'Tiene setenta años pero está como un toro.',
    exampleEn: 'He\'s seventy years old but he\'s strong as an ox.',
    register: 'informal',
    category: 'health',
    cefr: 'B2',
  },
  {
    idiom: 'no estar para muchos trotes',
    literal: 'to not be up to many trots',
    meaning: 'to not be up to much / to have seen better days / to not have the energy',
    example: 'Después de la operación no estaba para muchos trotes.',
    exampleEn: 'After the operation she wasn\'t up to much.',
    register: 'informal',
    category: 'health',
    cefr: 'C1',
  },
  {
    idiom: 'no ser plato de buen gusto',
    literal: 'to not be a dish of good taste',
    meaning: 'to be unpleasant / to be hard to take / not a nice thing to deal with',
    example: 'Dar malas noticias nunca es plato de buen gusto.',
    exampleEn: 'Giving bad news is never a pleasant thing.',
    register: 'neutral',
    category: 'food',
    cefr: 'B2',
  },
  {
    idiom: 'en todas partes cuecen habas',
    literal: 'everywhere they cook beans',
    meaning: 'it\'s the same everywhere / every place has its problems',
    example: 'Pensaba que en la nueva empresa sería distinto, pero en todas partes cuecen habas.',
    exampleEn: 'I thought the new company would be different, but it\'s the same everywhere.',
    register: 'neutral',
    category: 'food',
    cefr: 'B2',
  },
  {
    idiom: 'quedarse de piedra',
    literal: 'to turn to stone',
    meaning: 'to be gobsmacked / to be completely stunned or speechless',
    example: 'Cuando me dijeron que había ganado el premio me quedé de piedra.',
    exampleEn: 'When they told me I\'d won the prize I was completely gobsmacked.',
    register: 'informal',
    category: 'reactions',
    cefr: 'B1',
  },
  {
    idiom: 'flipar en colores',
    literal: 'to flip out in colours',
    meaning: 'to be totally blown away / to be absolutely gobsmacked',
    example: 'Cuando vi el precio del apartamento flipé en colores.',
    exampleEn: 'When I saw the apartment price I was absolutely blown away.',
    register: 'colloquial',
    category: 'reactions',
    cefr: 'C1',
  },
  {
    idiom: 'ponérsele los pelos de punta',
    literal: 'for one\'s hairs to stand on end',
    meaning: 'to make one\'s hair stand on end / to be terrifying or thrilling',
    example: 'La película de terror me puso los pelos de punta.',
    exampleEn: 'The horror film made my hair stand on end.',
    register: 'informal',
    category: 'reactions',
    cefr: 'B1',
  },
  {
    idiom: 'de chiripa',
    literal: 'by chiripa (billiard fluke)',
    meaning: 'by a fluke / by sheer luck / by a lucky accident',
    example: 'Aprobé el examen de chiripa — ni había estudiado.',
    exampleEn: 'I passed the exam by sheer luck — I hadn\'t even studied.',
    register: 'colloquial',
    category: 'probability',
    cefr: 'B2',
  },
  {
    idiom: 'de milagro',
    literal: 'by miracle',
    meaning: 'by a miracle / by the skin of one\'s teeth / barely avoiding disaster',
    example: 'Llegué al aeropuerto de milagro — el avión salía en cinco minutos.',
    exampleEn: 'I made it to the airport by the skin of my teeth — the plane left in five minutes.',
    register: 'informal',
    category: 'probability',
    cefr: 'B1',
  },
  {
    idiom: 'más vale prevenir que curar',
    literal: 'better to prevent than to cure',
    meaning: 'better safe than sorry / prevention is better than cure',
    example: 'Lleva paraguas aunque no parezca que vaya a llover — más vale prevenir que curar.',
    exampleEn: 'Take an umbrella even if it doesn\'t look like rain — better safe than sorry.',
    register: 'neutral',
    category: 'advice',
    cefr: 'A2',
  },
  {
    idiom: 'a caballo regalado no le mires el diente',
    literal: 'don\'t look at a gifted horse\'s tooth',
    meaning: 'don\'t look a gift horse in the mouth',
    example: 'La habitación era pequeña, pero a caballo regalado no le mires el diente.',
    exampleEn: 'The room was small, but don\'t look a gift horse in the mouth.',
    register: 'neutral',
    category: 'advice',
    cefr: 'B1',
  },
  {
    idiom: 'hablar con el corazón en la mano',
    literal: 'to speak with one\'s heart in one\'s hand',
    meaning: 'to speak from the heart / to be completely open and honest',
    example: 'Te lo digo con el corazón en la mano: me preocupa tu actitud.',
    exampleEn: 'I\'m telling you from the heart: your attitude worries me.',
    register: 'informal',
    category: 'honesty',
    cefr: 'B2',
  },
  {
    idiom: 'estar en la flor de la vida',
    literal: 'to be in the flower of life',
    meaning: 'to be in the prime of life / to be at one\'s peak',
    example: 'Tenía treinta años y estaba en la flor de la vida.',
    exampleEn: 'She was thirty and in the prime of her life.',
    register: 'neutral',
    category: 'age',
    cefr: 'B2',
  },
  // ── EMOTION ──────────────────────────────────────────────────────────────
  {
    idiom: 'tener el corazón en un puño',
    literal: 'to have the heart in a fist',
    meaning: 'to have one\'s heart in one\'s mouth / to be gripped with anxiety',
    example: 'Mientras esperábamos los resultados, teníamos el corazón en un puño.',
    exampleEn: 'While we waited for the results, our hearts were in our mouths.',
    register: 'informal',
    category: 'emotion',
    cefr: 'B2',
  },
  {
    idiom: 'estar con el alma en vilo',
    literal: 'to have one\'s soul hanging',
    meaning: 'to be on tenterhooks / to be in suspense',
    example: 'Estuvimos con el alma en vilo durante toda la operación.',
    exampleEn: 'We were on tenterhooks throughout the whole operation.',
    register: 'informal',
    category: 'emotion',
    cefr: 'B2',
  },
  // ── DECEPTION ────────────────────────────────────────────────────────────
  {
    idiom: 'dar gato por liebre',
    literal: 'to give cat instead of hare',
    meaning: 'to sell someone a pup / to pass something inferior off as quality',
    example: 'Le dieron gato por liebre: el coche tenía más problemas de los que dijeron.',
    exampleEn: 'They sold him a pup: the car had more problems than they let on.',
    register: 'colloquial',
    category: 'deception',
    cefr: 'C1',
  },
  {
    idiom: 'hacerse el loco',
    literal: 'to play the madman',
    meaning: 'to play dumb / to pretend not to notice',
    example: 'Le pregunté por el dinero y se hizo el loco.',
    exampleEn: 'I asked him about the money and he played dumb.',
    register: 'colloquial',
    category: 'deception',
    cefr: 'B1',
  },
  // ── MISTAKES ─────────────────────────────────────────────────────────────
  {
    idiom: 'errar es de humanos',
    literal: 'to err is human',
    meaning: 'to err is human / everyone makes mistakes',
    example: 'No te preocupes tanto — errar es de humanos.',
    exampleEn: 'Don\'t worry so much — to err is human.',
    register: 'neutral',
    category: 'mistakes',
    cefr: 'B1',
  },
  {
    idiom: 'tirar la piedra y esconder la mano',
    literal: 'to throw the stone and hide the hand',
    meaning: 'to make a move and then act innocent / to stir up trouble anonymously',
    example: 'Él empezó el rumor pero tira la piedra y esconde la mano.',
    exampleEn: 'He started the rumour but throws the stone and hides his hand.',
    register: 'colloquial',
    category: 'deception',
    cefr: 'B2',
  },
  // ── FRUSTRATION ──────────────────────────────────────────────────────────
  {
    idiom: 'subírsele los humos',
    literal: 'for the fumes to go to one\'s head',
    meaning: 'to let success go to one\'s head / to get too big for one\'s boots',
    example: 'Desde que le ascendieron se le han subido los humos.',
    exampleEn: 'Since the promotion, success has gone to his head.',
    register: 'informal',
    category: 'frustration',
    cefr: 'B2',
  },
  {
    idiom: 'estar hasta la coronilla',
    literal: 'to be up to the crown of the head',
    meaning: 'to be completely fed up / to be at the end of one\'s rope',
    example: 'Estoy hasta la coronilla de repetir lo mismo.',
    exampleEn: 'I\'m completely fed up with repeating the same thing.',
    register: 'colloquial',
    category: 'frustration',
    cefr: 'B2',
  },
  // ── SURPRISE ─────────────────────────────────────────────────────────────
  {
    idiom: 'no dar crédito',
    literal: 'to not give credit',
    meaning: 'to not believe one\'s eyes or ears / to be incredulous',
    example: 'No daba crédito cuando vi las notas del examen.',
    exampleEn: 'I couldn\'t believe my eyes when I saw the exam results.',
    register: 'informal',
    category: 'surprise',
    cefr: 'B1',
  },
  // ── SPEED ────────────────────────────────────────────────────────────────
  {
    idiom: 'a toda pastilla',
    literal: 'at full pill',
    meaning: 'at full speed / flat out',
    example: 'Iba a toda pastilla por la autopista.',
    exampleEn: 'He was going flat out on the motorway.',
    register: 'colloquial',
    category: 'speed',
    cefr: 'B2',
  },
  {
    idiom: 'sin perder ni un segundo',
    literal: 'without losing a single second',
    meaning: 'without wasting a moment / immediately',
    example: 'En cuanto sonó la alarma, actuaron sin perder ni un segundo.',
    exampleEn: 'As soon as the alarm went off, they acted without losing a moment.',
    register: 'neutral',
    category: 'speed',
    cefr: 'A2',
  },
  // ── RELATIONSHIPS ─────────────────────────────────────────────────────────
  {
    idiom: 'hacer buenas migas',
    literal: 'to make good crumbs',
    meaning: 'to hit it off / to get on well with someone from the start',
    example: 'Mis amigos hicieron buenas migas desde el primer momento.',
    exampleEn: 'My friends hit it off from the very first moment.',
    register: 'informal',
    category: 'relationships',
    cefr: 'B2',
  },
  {
    idiom: 'guardar las distancias',
    literal: 'to keep the distances',
    meaning: 'to keep one\'s distance / to maintain a professional boundary',
    example: 'Es amable, pero siempre guarda las distancias con los clientes.',
    exampleEn: 'She is friendly but always keeps her distance from clients.',
    register: 'neutral',
    category: 'relationships',
    cefr: 'B1',
  },
  // ── FORMAL REGISTER ──────────────────────────────────────────────────────
  {
    idiom: 'poner de manifiesto',
    literal: 'to put in manifest',
    meaning: 'to make evident / to bring to light / to reveal',
    example: 'El informe pone de manifiesto los fallos estructurales del sistema.',
    exampleEn: 'The report brings to light the structural flaws in the system.',
    register: 'formal',
    category: 'communication',
    cefr: 'C1',
  },
  {
    idiom: 'dar lugar a',
    literal: 'to give place to',
    meaning: 'to give rise to / to lead to / to result in',
    example: 'La nueva ley dio lugar a una oleada de protestas.',
    exampleEn: 'The new law gave rise to a wave of protests.',
    register: 'formal',
    category: 'cause',
    cefr: 'B2',
  },
  {
    idiom: 'en aras de',
    literal: 'in the altars of',
    meaning: 'for the sake of / in the interest of',
    example: 'En aras de la transparencia, todos los datos son públicos.',
    exampleEn: 'In the interest of transparency, all data is made public.',
    register: 'formal',
    category: 'purpose',
    cefr: 'C1',
  },
  {
    idiom: 'llevar a cabo',
    literal: 'to carry to the end / to the cape',
    meaning: 'to carry out / to implement / to accomplish',
    example: 'El equipo llevó a cabo el proyecto en tiempo récord.',
    exampleEn: 'The team carried out the project in record time.',
    register: 'formal',
    category: 'work',
    cefr: 'B2',
  },
  {
    idiom: 'hacer hincapié en',
    literal: 'to plant one\'s foot firmly in',
    meaning: 'to emphasise / to stress / to highlight',
    example: 'El director hizo hincapié en la importancia del trabajo en equipo.',
    exampleEn: 'The director stressed the importance of teamwork.',
    register: 'formal',
    category: 'communication',
    cefr: 'B2',
  },
  // ── UNDERREPRESENTED CATEGORIES (round 2) ───────────────────────────────
  {
    idiom: 'más vale pájaro en mano que ciento volando',
    literal: 'a bird in hand is worth more than a hundred flying',
    meaning: 'a bird in the hand is worth two in the bush',
    example: 'No dejes ese trabajo seguro por una promesa; más vale pájaro en mano que ciento volando.',
    exampleEn: 'Don\'t leave that secure job for a promise; a bird in the hand is worth two in the bush.',
    register: 'neutral',
    category: 'wisdom',
    cefr: 'B1',
  },
  {
    idiom: 'el saber no ocupa lugar',
    literal: 'knowing doesn\'t take up space',
    meaning: 'it never hurts to learn something new / knowledge is never wasted',
    example: 'Apúntate al curso, total, el saber no ocupa lugar.',
    exampleEn: 'Sign up for the course — after all, it never hurts to learn something new.',
    register: 'neutral',
    category: 'knowledge',
    cefr: 'B2',
  },
  {
    idiom: 'decir las verdades del barquero',
    literal: 'to tell someone the ferryman\'s truths',
    meaning: 'to tell someone the plain, unvarnished truth / to speak bluntly and honestly',
    example: 'Le dije las verdades del barquero, aunque le sentaran mal.',
    exampleEn: 'I told him the plain truth, even though he didn\'t like hearing it.',
    register: 'colloquial',
    category: 'honesty',
    cefr: 'C2',
  },
  {
    idiom: 'hacer el vago',
    literal: 'to play the lazy one',
    meaning: 'to laze around / to slack off',
    example: 'En vacaciones no pienso hacer nada, solo hacer el vago todo el día.',
    exampleEn: 'On vacation I don\'t plan to do anything, just laze around all day.',
    register: 'colloquial',
    category: 'laziness',
    cefr: 'B1',
  },
  {
    idiom: 'no tener ni pajolera idea',
    literal: 'to not have even a "pajolera" idea',
    meaning: 'to not have the faintest idea / to have no clue',
    example: 'No tengo ni pajolera idea de dónde dejé las llaves.',
    exampleEn: 'I have no clue where I left my keys.',
    register: 'colloquial',
    category: 'ignorance',
    cefr: 'C1',
  },
  {
    idiom: 'luchar a brazo partido',
    literal: 'to fight arm to arm, unarmed',
    meaning: 'to fight tooth and nail / to struggle with all one\'s might',
    example: 'Los dos equipos lucharon a brazo partido por el título.',
    exampleEn: 'Both teams fought tooth and nail for the title.',
    register: 'informal',
    category: 'competition',
    cefr: 'B2',
  },
  {
    idiom: 'tener mala pata',
    literal: 'to have a bad paw',
    meaning: 'to have bad luck',
    example: 'Tengo tan mala pata que siempre me toca la fila más lenta.',
    exampleEn: 'I have such bad luck that I always end up in the slowest line.',
    register: 'colloquial',
    category: 'misfortune',
    cefr: 'B1',
  },
  {
    idiom: 'no es el fin del mundo',
    literal: 'it is not the end of the world',
    meaning: 'it\'s not the end of the world / things could be worse',
    example: 'Suspendiste un examen, pero no es el fin del mundo.',
    exampleEn: 'You failed one exam, but it\'s not the end of the world.',
    register: 'neutral',
    category: 'reassurance',
    cefr: 'A2',
  },
  {
    idiom: 'hacer novillos',
    literal: 'to make young bulls',
    meaning: 'to play truant / to skip school',
    example: 'De adolescente, hacía novillos casi todos los viernes.',
    exampleEn: 'As a teenager, I played truant almost every Friday.',
    register: 'colloquial',
    category: 'escape',
    cefr: 'C1',
  },
  {
    idiom: 'poner los puntos sobre las íes',
    literal: 'to put the dots over the i\'s',
    meaning: 'to clarify something precisely / to spell things out so there\'s no room for doubt',
    example: 'Antes de firmar, quiero poner los puntos sobre las íes.',
    exampleEn: 'Before signing, I want to spell everything out clearly.',
    register: 'neutral',
    category: 'precision',
    cefr: 'B2',
  },
  {
    idiom: 'no dejar títere con cabeza',
    literal: 'to not leave a puppet with a head',
    meaning: 'to spare no one / to criticize or tear apart everything and everyone',
    example: 'En su crítica no dejó títere con cabeza.',
    exampleEn: 'In his review, he tore everything and everyone apart.',
    register: 'informal',
    category: 'conflict',
    cefr: 'C1',
  },
  {
    idiom: 'cortar por lo sano',
    literal: 'to cut through the healthy part',
    meaning: 'to take drastic action / to cut to the chase and resolve a problem decisively',
    example: 'Como no se ponían de acuerdo, decidió cortar por lo sano y despedir a los dos.',
    exampleEn: 'Since they couldn\'t agree, he decided to take drastic action and fire them both.',
    register: 'informal',
    category: 'decisions',
    cefr: 'B2',
  },
  {
    idiom: 'hacerse de rogar',
    literal: 'to make oneself be begged',
    meaning: 'to play hard to get / to need a lot of persuading before agreeing to something',
    example: 'No te hagas de rogar y ven a la fiesta.',
    exampleEn: 'Don\'t play hard to get — come to the party.',
    register: 'informal',
    category: 'refusal',
    cefr: 'B2',
  },
  {
    idiom: 'por si las moscas',
    literal: 'for if the flies',
    meaning: 'just in case / to be on the safe side',
    example: 'Llévate un paraguas, por si las moscas.',
    exampleEn: 'Take an umbrella, just in case.',
    register: 'colloquial',
    category: 'caution',
    cefr: 'B1',
  },
  {
    idiom: 'tocar las narices',
    literal: 'to touch the noses',
    meaning: 'to annoy / to bother someone',
    example: 'Deja de tocarme las narices con esa cancioncita.',
    exampleEn: 'Stop annoying me with that little song.',
    register: 'colloquial',
    category: 'annoyance',
    cefr: 'B1',
  },
  {
    idiom: 'estar más claro que el agua',
    literal: 'to be clearer than water',
    meaning: 'to be crystal clear / obvious',
    example: 'Está más claro que el agua que no le interesa el proyecto.',
    exampleEn: 'It\'s crystal clear he\'s not interested in the project.',
    register: 'informal',
    category: 'obviousness',
    cefr: 'B1',
  },
  {
    idiom: 'no valer un pimiento',
    literal: 'to not be worth a pepper',
    meaning: 'to be worthless',
    example: 'Esa promesa no vale un pimiento si no la cumple.',
    exampleEn: 'That promise isn\'t worth a thing if he doesn\'t keep it.',
    register: 'colloquial',
    category: 'value',
    cefr: 'B1',
  },
  {
    idiom: 'vivir a cuerpo de rey',
    literal: 'to live at a king\'s body',
    meaning: 'to live like a king / in great comfort and luxury',
    example: 'Desde que ganó la lotería, vive a cuerpo de rey.',
    exampleEn: 'Ever since he won the lottery, he\'s been living like a king.',
    register: 'informal',
    category: 'comfort',
    cefr: 'B2',
  },
  {
    idiom: 'estar en el ajo',
    literal: 'to be in the garlic',
    meaning: 'to be in the loop / to be involved in a plan or secret',
    example: 'No sabía nada del plan, pero está claro que ella está en el ajo.',
    exampleEn: 'I didn\'t know anything about the plan, but it\'s clear she\'s in the loop.',
    register: 'colloquial',
    category: 'social',
    cefr: 'B2',
  },
  {
    idiom: 'con miras a',
    literal: 'with views to',
    meaning: 'with the aim of / with a view to',
    example: 'Se reunieron con miras a firmar el acuerdo antes de fin de año.',
    exampleEn: 'They met with a view to signing the agreement before the end of the year.',
    register: 'formal',
    category: 'purpose',
    cefr: 'C1',
  },
  {
    idiom: 'a raíz de',
    literal: 'at the root of',
    meaning: 'as a result of / following from',
    example: 'A raíz del escándalo, dos directivos dimitieron.',
    exampleEn: 'As a result of the scandal, two executives resigned.',
    register: 'formal',
    category: 'cause',
    cefr: 'B2',
  },
  {
    idiom: 'a río revuelto, ganancia de pescadores',
    literal: 'in a stirred-up river, fishermen\'s gain',
    meaning: 'some people profit from confusion or chaos',
    example: 'Bajaron los precios de golpe y algunos compraron barato: a río revuelto, ganancia de pescadores.',
    exampleEn: 'Prices dropped suddenly and some people bought cheap: it\'s an ill wind that blows nobody good.',
    register: 'neutral',
    category: 'wisdom',
    cefr: 'C2',
  },
  {
    idiom: 'meter baza',
    literal: 'to put in a trick (card-game term)',
    meaning: 'to get a word in / to chime into a conversation',
    example: 'Hablan tan rápido que no puedo meter baza.',
    exampleEn: 'They talk so fast that I can\'t get a word in.',
    register: 'informal',
    category: 'speech',
    cefr: 'C1',
  },
  {
    idiom: 'aburrirse como una ostra',
    literal: 'to get bored like an oyster',
    meaning: 'to be bored stiff',
    example: 'La película era tan lenta que me aburrí como una ostra.',
    exampleEn: 'The movie was so slow that I was bored stiff.',
    register: 'colloquial',
    category: 'boredom',
    cefr: 'B2',
  },
  {
    idiom: 'aquí hay gato encerrado',
    literal: 'there is a cat locked up here',
    meaning: 'something fishy is going on / there\'s more to this than meets the eye',
    example: 'Nos ofrecen el piso muy barato... aquí hay gato encerrado.',
    exampleEn: 'They\'re offering us the apartment really cheap... something fishy is going on.',
    register: 'informal',
    category: 'disbelief',
    cefr: 'B2',
  },
  {
    idiom: 'quien fue a Sevilla perdió su silla',
    literal: 'whoever went to Seville lost their chair',
    meaning: 'if you leave your spot, don\'t be surprised if someone else takes it / you snooze, you lose',
    example: 'Me levanté un segundo del sofá y mi hermano se sentó ahí. Quien fue a Sevilla perdió su silla.',
    exampleEn: 'I got up from the couch for one second and my brother sat there. You snooze, you lose.',
    register: 'informal',
    category: 'opportunity',
    cefr: 'C2',
  },
  {
    idiom: 'cría cuervos y te sacarán los ojos',
    literal: 'raise ravens and they will pluck out your eyes',
    meaning: 'no good deed goes unpunished / watch who you help, they may turn on you',
    example: 'Le pagué los estudios y ahora ni me llama. Cría cuervos y te sacarán los ojos.',
    exampleEn: 'I paid for his studies and now he doesn\'t even call. No good deed goes unpunished.',
    register: 'neutral',
    category: 'wisdom',
    cefr: 'C2',
  },
  {
    idiom: 'el que no llora no mama',
    literal: 'he who doesn\'t cry doesn\'t nurse',
    meaning: 'the squeaky wheel gets the grease / if you don\'t ask, you don\'t get',
    example: 'Pide el aumento sin miedo — el que no llora no mama.',
    exampleEn: 'Ask for the raise without fear — the squeaky wheel gets the grease.',
    register: 'colloquial',
    category: 'assertiveness',
    cefr: 'C2',
  },
  {
    idiom: 'estar en la cuerda floja',
    literal: 'to be on the loose rope',
    meaning: 'to be in a precarious situation / hanging by a thread',
    example: 'Su puesto de trabajo está en la cuerda floja desde los recortes.',
    exampleEn: 'Her job has been hanging by a thread since the cutbacks.',
    register: 'neutral',
    category: 'risk',
    cefr: 'C2',
  },
  {
    idiom: 'hacer de la necesidad virtud',
    literal: 'to make virtue out of necessity',
    meaning: 'to make the best of a bad situation / turn a forced circumstance into an advantage',
    example: 'No teníamos coche, así que hicimos de la necesidad virtud y descubrimos la ciudad a pie.',
    exampleEn: 'We didn\'t have a car, so we made the best of it and discovered the city on foot.',
    register: 'neutral',
    category: 'wisdom',
    cefr: 'C2',
  },
  {
    idiom: 'írsele el santo al cielo',
    literal: 'for the saint to go up to heaven on someone',
    meaning: 'to completely forget what one was about to say or do / to go blank',
    example: 'Iba a contarte algo importante, pero se me fue el santo al cielo.',
    exampleEn: 'I was going to tell you something important, but it completely slipped my mind.',
    register: 'colloquial',
    category: 'memory',
    cefr: 'C2',
  },
  {
    idiom: 'no dar su brazo a torcer',
    literal: 'to not let one\'s arm be twisted',
    meaning: 'to refuse to back down / to stand one\'s ground stubbornly',
    example: 'Sabe que se ha equivocado, pero no da su brazo a torcer.',
    exampleEn: 'He knows he\'s wrong, but he won\'t back down.',
    register: 'neutral',
    category: 'stubbornness',
    cefr: 'C2',
  },
  {
    idiom: 'tirar de la manta',
    literal: 'to pull the blanket',
    meaning: 'to expose a hidden truth / to blow the whistle on a cover-up',
    example: 'Si tira de la manta, salpicará a medio ayuntamiento.',
    exampleEn: 'If he blows the whistle, it\'ll implicate half the city council.',
    register: 'informal',
    category: 'secrets',
    cefr: 'C2',
  },
  {
    idiom: 'dar la campanada',
    literal: 'to ring the bell',
    meaning: 'to cause a sensation / to shock everyone by doing something unexpected',
    example: 'El desconocido dio la campanada al ganar el premio más importante del certamen.',
    exampleEn: 'The unknown contestant caused a sensation by winning the contest\'s top prize.',
    register: 'neutral',
    category: 'scandal',
    cefr: 'C2',
  },
  {
    idiom: 'montar un pollo',
    literal: 'to mount a chicken',
    meaning: 'to make a scene / to kick up a fuss',
    example: 'Montó un pollo en el restaurante porque tardaron en traerle la cuenta.',
    exampleEn: 'He made a huge scene at the restaurant because the bill took a while to arrive.',
    register: 'colloquial',
    category: 'conflict',
    cefr: 'C2',
  },
  {
    idiom: 'írsele la olla',
    literal: 'for the pot to go on someone',
    meaning: 'to lose control and say or do something reckless / to flip out',
    example: 'Se le fue la olla y le dijo al jefe lo que pensaba de verdad.',
    exampleEn: 'He lost it and told his boss what he really thought.',
    register: 'colloquial',
    category: 'mind',
    cefr: 'C2',
  },
  {
    idiom: 'no tener dos dedos de frente',
    literal: 'to not have two fingers of forehead',
    meaning: 'to have no common sense / to not be very bright',
    example: 'No tiene dos dedos de frente — se dejó todo el dinero en la primera hora.',
    exampleEn: 'He doesn\'t have an ounce of common sense — he spent all his money in the first hour.',
    register: 'colloquial',
    category: 'intelligence',
    cefr: 'C2',
  },
  {
    idiom: 'hilar fino',
    literal: 'to spin thin thread',
    meaning: 'to be extremely precise and careful with details / to split hairs skillfully',
    example: 'Para explicar la diferencia hay que hilar fino.',
    exampleEn: 'To explain the difference you have to be very precise.',
    register: 'neutral',
    category: 'precision',
    cefr: 'C2',
  },
  {
    idiom: 'dorar la píldora',
    literal: 'to gild the pill',
    meaning: 'to sugarcoat something / to soften bad news',
    example: 'No me dores la píldora, dime la verdad.',
    exampleEn: 'Don\'t sugarcoat it, tell me the truth.',
    register: 'informal',
    category: 'tact',
    cefr: 'C2',
  },
  {
    idiom: 'quedarse en agua de borrajas',
    literal: 'to be left as borage water',
    meaning: 'to come to nothing / to fizzle out (of a plan or hope)',
    example: 'El proyecto prometía mucho, pero se quedó en agua de borrajas.',
    exampleEn: 'The project promised a lot, but it fizzled out to nothing.',
    register: 'neutral',
    category: 'disappointment',
    cefr: 'C2',
  },
];

export const CATEGORIES = [...new Set(IDIOMS.map(i => i.category))].sort();
export const CEFR_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
