// Reading passages — original short-story content for the Readings section.
// Each passage's Spanish paragraphs are rendered through ClickableSpanish
// in vocab-only mode (see src/lib/dictionary.js's segmentSpanish), so every
// word with a real vocabulary.js entry is clickable for a definition —
// no curated glossary, no invented data. English paragraphs are shown
// behind a "show translation" toggle so a learner reads the Spanish cold
// first, the way ES.md's prose-writing process describes.
//
// CEFR discipline for this content follows ES.md's punch-list items on
// prose writing: every grammar structure used is checked against
// concepts.js before a level is claimed (no object pronouns, no
// preterite, no relative clauses, no present progressive, no comparatives,
// no imperative, no nada/nadie/nunca/tampoco negation in any A1 passage
// here), and every glossed word is a real, sourced vocabulary.js entry,
// not an estimate — any word a passage needs that vocabulary.js doesn't
// already have gets researched and added before the passage ships (ES.md
// process step 12, a hard rule, not a suggestion).
//
// Each passage's optional `questions` array holds comprehension exercises
// (not grammar drills) rendered via the shared ExerciseCard/Feedback
// components on the passage page — multiple_choice questions in Spanish,
// plus a couple of free-text `comprehension`-type questions with English
// answers, self-graded client-side with no backend persistence.
//
// `summary` is the Spanish-language preview shown on the Readings list
// page — hold it to the exact same CEFR discipline as the passage's own
// `level` (an A1 passage's summary follows the same "no object pronouns,
// no preterite, no relative clauses..." rules above, not just simplified
// vocabulary; a B2 passage's summary should read like B2 prose). It's
// still learner-facing Spanish, not an internal English note.
//
// `written` is the real date the passage was authored/shipped (ISO
// 'YYYY-MM-DD'), shown on the passage's own page and used to sort the
// Readings list. A hard rule, not a suggestion, same as the vocab-gap
// rule above: every new passage gets a real `written` date at the moment
// it ships — use today's actual date, never a placeholder or a guess.
// The 19 passages present as of 07-11-2026 were dated retroactively from
// git history (`git log --follow -S"id: 'the-passage-id'"`), not
// estimated by eye.

export const PASSAGES = [
  {
    id: 'pan-de-cada-manana',
    written: '2026-07-09',
    title: 'El pan de cada mañana',
    level: 'A1',
    format: 'standalone',
    summary: 'Un panadero no tiene pan para su clienta de siempre — una escena de la vida diaria.',
    paragraphs: [
    { es: "Mateo trabaja en una panadería pequeña, en la calle Aurora. Abre la puerta a las seis de la mañana. Afuera hace frío todavía.", en: "Mateo works at a small bakery, on Aurora Street. He opens the door at six in the morning. Outside, it's still cold." },
    { es: "A las siete, siempre llega la misma clienta: la señora Pilar. Vive sola, cerca de la plaza. Compra dos cosas, nunca más: un pan y un café con leche.", en: "At seven, the same customer always arrives: Mrs. Pilar. She lives alone, near the square. She buys two things, never more: a loaf of bread and a coffee with milk." },
    { es: "—Buenos días, Mateo — dice ella, y deja las monedas exactas en el mostrador.", en: "\"Good morning, Mateo,\" she says, leaving the exact coins on the counter." },
    { es: "—Buenos días, señora Pilar — contesta él.", en: "\"Good morning, Mrs. Pilar,\" he answers." },
    { es: "Pero hoy no hay pan todavía. El horno está roto.", en: "But today there's no bread yet. The oven is broken." },
    { es: "La señora Pilar mira el mostrador vacío. Mira a Mateo. No dice nada, solo espera.", en: "Mrs. Pilar looks at the empty counter. She looks at Mateo. She doesn't say anything, she just waits." },
    { es: "Mateo piensa un momento. Saca una magdalena de la vitrina y pone la magdalena en una bolsa.", en: "Mateo thinks for a moment. He takes a muffin out of the display case and puts the muffin in a bag." },
    { es: "—Hoy invita la casa — dice, y da la bolsa a la señora Pilar. Sonríe, un poco nervioso.", en: "\"Today it's on the house,\" he says, and hands Mrs. Pilar the bag. He smiles, a little nervous." },
    { es: "La señora Pilar abre la bolsa. Huele la magdalena. Sonríe también.", en: "Mrs. Pilar opens the bag. She smells the muffin. She smiles too." },
    { es: "—Mañana el pan, entonces — contesta, y se va con su café.", en: "\"Tomorrow the bread, then,\" she answers, and leaves with her coffee." },
    { es: "Mateo mira el horno roto. Después mira la calle, vacía todavía. Y piensa: mañana necesita el pan listo antes de las siete.", en: "Mateo looks at the broken oven. Then he looks at the street, still empty. And he thinks: tomorrow he needs the bread ready before seven." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Dónde trabaja Mateo?',
        options: ['En una panadería', 'En un banco', 'En un café', 'En una escuela'],
        answer: 'En una panadería',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué compra siempre la señora Pilar?',
        options: ['Un pan y un café con leche', 'Una magdalena y un té', 'Dos cafés', 'Un pastel'],
        answer: 'Un pan y un café con leche',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le pasa al horno hoy?',
        options: ['Está roto', 'Está limpio', 'Está nuevo', 'Está abierto'],
        answer: 'Está roto',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le da Mateo a la señora Pilar en vez de pan?',
        options: ['Una magdalena', 'Un café', 'Un pastel', 'Nada'],
        answer: 'Una magdalena',
      },
      {
        type: 'comprehension',
        prompt: 'How does Mrs. Pilar react when Mateo gives her the muffin instead of bread?',
        answer: 'she smiles',
        altAnswers: ['she smiled', 'smiles', 'smiled', 'she smiles too'],
      },
    ],
  },
  {
    id: 'blahaj-ch1',
    written: '2026-07-09',
    title: 'Las Aventuras de Blahaj — Capítulo 1: El tiburón de peluche',
    level: 'A1',
    format: 'story',
    story: 'blahaj',
    chapter: 1,
    summary: 'Lucía decide mandar a Blahaj, su tiburón de peluche, de viaje por el mundo.',
    paragraphs: [
    { es: "Lucía tiene un tiburón. No es un tiburón de verdad — es de peluche, gris y azul, con una sonrisa un poco tonta. Se llama Blahaj.", en: "Lucía has a shark. Not a real shark — a stuffed one, grey and blue, with a slightly goofy smile. His name is Blahaj." },
    { es: "Blahaj vive en la cama de Lucía, al lado de la almohada. Por la noche, Lucía lee un libro y Blahaj escucha. Por la mañana, Lucía se va a trabajar y Blahaj se queda solo, mirando la ventana.", en: "Blahaj lives on Lucía's bed, next to the pillow. At night, Lucía reads a book and Blahaj listens. In the morning, Lucía goes to work and Blahaj stays behind, looking out the window." },
    { es: "Un sábado, Lucía está en el sofá con su computadora. Busca algo en internet: \"grupos para intercambiar peluches\". Encuentra una página con miles de personas. Todas tienen un peluche parecido a Blahaj. Todas mandan sus peluches por correo a otras casas, a otras ciudades, a otros países.", en: "One Saturday, Lucía is on the couch with her laptop. She searches for something online: \"plushie exchange groups.\" She finds a page with thousands of people. They all have a plush toy like Blahaj. They all mail their plush toys to other houses, other cities, other countries." },
    { es: "Una chica de Chile escribe: \"Mi tiburón viaja mucho. ¡Doce países este año!\" Un chico de México escribe: \"El mío está ahora mismo en Japón.\" Lucía mira las fotos. Un tiburón de peluche en la playa. Otro en un tren. Otro, con gafas de sol, delante de una montaña.", en: "A girl in Chile writes: \"My shark travels a lot. Twelve countries this year!\" A boy in Mexico writes: \"Mine's in Japan right now.\" Lucía looks at the photos. A stuffed shark on the beach. Another on a train. Another, wearing sunglasses, in front of a mountain." },
    { es: "Lucía mira a Blahaj. Blahaj mira a Lucía, con su sonrisa tonta de siempre.", en: "Lucía looks at Blahaj. Blahaj looks at Lucía, with his same goofy smile." },
    { es: "—¿Quieres viajar? — pregunta Lucía.", en: "\"Do you want to travel?\" asks Lucía." },
    { es: "Blahaj no contesta, claro. Pero Lucía ya sabe la respuesta.", en: "Blahaj doesn't answer, obviously. But Lucía already knows the answer." },
    { es: "Esa noche, escribe su primer mensaje en el grupo: \"Hola. Me llamo Lucía. Tengo un tiburón. Se llama Blahaj. Es su primer viaje. ¿Alguien quiere recibir a Blahaj?\"", en: "That night, she writes her first message in the group: \"Hi. My name's Lucía. I have a shark. His name is Blahaj. It's his first trip. Does anyone want to host Blahaj?\"" },
    { es: "Contesta alguien en cinco minutos.", en: "Someone replies in five minutes." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cómo se llama el tiburón de peluche de Lucía?',
        options: ['Blahaj', 'Tiburón', 'Pilar', 'Mateo'],
        answer: 'Blahaj',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué busca Lucía en internet?',
        options: ['Grupos para intercambiar peluches', 'Recetas de pan', 'Un trabajo nuevo', 'Un libro'],
        answer: 'Grupos para intercambiar peluches',
      },
      {
        type: 'multiple_choice',
        prompt: '¿De dónde es la chica que escribe sobre su tiburón viajero?',
        options: ['Chile', 'México', 'Japón', 'España'],
        answer: 'Chile',
      },
      {
        type: 'comprehension',
        prompt: 'What does Blahaj do all day while Lucía is at work?',
        answer: 'looks out the window',
        altAnswers: ['look out the window', 'watches the window', 'looking out the window', 'he looks out the window'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué pregunta Lucía a Blahaj?',
        options: ['¿Quieres viajar?', '¿Tienes hambre?', '¿Estás bien?', '¿Quieres dormir?'],
        answer: '¿Quieres viajar?',
      },
    ],
  },
  {
    id: 'blahaj-ch2',
    written: '2026-07-10',
    title: 'Las Aventuras de Blahaj — Capítulo 2: El viaje a Buenos Aires',
    level: 'A1',
    format: 'story',
    story: 'blahaj',
    chapter: 2,
    summary: 'Diego, de Argentina, se ofrece a recibir a Blahaj — y Lucía prepara su primer viaje.',
    paragraphs: [
    { es: 'Diego contesta primero. Vive en Buenos Aires, Argentina, con su familia. Escribe: "Hola, Lucía. Blahaj puede venir a mi casa. Aquí en julio hace mucho frío. Un tiburón de peluche necesita compañía."', en: 'Diego answers first. He lives in Buenos Aires, Argentina, with his family. He writes: "Hi, Lucía. Blahaj can come to my house. Here in July it\'s very cold. A stuffed shark needs company."' },
    { es: 'Lucía y Diego escriben mensajes toda la semana. Hablan de la fecha, la dirección, y el paquete. Diego manda fotos de su casa y de su gato, Simón.', en: 'Lucía and Diego write messages all week. They talk about the date, the address, and the package. Diego sends photos of his house and his cat, Simón.' },
    { es: 'El sábado, Lucía prepara todo: una caja pequeña, papel, y una nota para Diego. En la nota escribe: "Blahaj es tímido, pero es un buen amigo."', en: 'On Saturday, Lucía prepares everything: a small box, paper, and a note for Diego. In the note she writes: "Blahaj is shy, but he\'s a good friend."' },
    { es: 'Pone a Blahaj en la caja, con la nota y una foto de su habitación. Cierra la caja y va al correo.', en: 'She puts Blahaj in the box, with the note and a photo of his room. She closes the box and goes to the post office.' },
    { es: 'En el correo, una mujer pesa la caja y pregunta: "¿Qué hay adentro?" Lucía sonríe y contesta: "Un tiburón, pero de peluche."', en: 'At the post office, a woman weighs the box and asks: "What\'s inside?" Lucía smiles and answers: "A shark, but a stuffed one."' },
    { es: 'Pasan diez días. Lucía no recibe noticias de Diego y está un poco nerviosa. Piensa mucho en Blahaj: "¿Está bien? ¿Llega pronto?"', en: 'Ten days pass. Lucía doesn\'t get any news from Diego and is a little nervous. She thinks about Blahaj a lot: "Is he OK? Will he arrive soon?"' },
    { es: 'Por fin, llega un mensaje de Diego: "¡Blahaj está aquí! Todo bien. Ahora duerme en mi cama, al lado de Simón."', en: 'Finally, a message arrives from Diego: "Blahaj is here! Everything\'s fine. Now he sleeps in my bed, next to Simón."' },
    { es: 'Diego manda una foto: Blahaj, con una bufanda pequeña, entre Simón y una ventana con lluvia.', en: 'Diego sends a photo: Blahaj, wearing a small scarf, between Simón and a window with rain.' },
    { es: 'Lucía mira la foto muchas veces. Piensa: "¿Dónde va Blahaj en el próximo viaje?"', en: 'Lucía looks at the photo many times. She thinks: "Where will Blahaj go on his next trip?"' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿De qué país es Diego?',
        options: ['Argentina', 'México', 'Chile', 'España'],
        answer: 'Argentina',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace la mujer en el correo?',
        options: ['Pesa la caja', 'Abre la caja', 'Pierde la caja', 'Rompe la caja'],
        answer: 'Pesa la caja',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde duerme Blahaj en la casa de Diego?',
        options: ['En la cama, al lado de Simón', 'En una caja', 'En la cocina', 'Afuera'],
        answer: 'En la cama, al lado de Simón',
      },
      {
        type: 'comprehension',
        prompt: "How does Lucía feel while she's waiting for news from Diego?",
        answer: 'a little nervous',
        altAnswers: ['nervous', 'a bit nervous', 'she is nervous', 'she feels nervous'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué lleva Blahaj en la foto que manda Diego?',
        options: ['Una bufanda', 'Un sombrero', 'Gafas de sol', 'Una camiseta'],
        answer: 'Una bufanda',
      },
    ],
  },
  {
    id: 'domingo-en-el-parque',
    written: '2026-07-10',
    title: 'El domingo en el parque',
    level: 'A1',
    format: 'standalone',
    summary: 'Sara y su perro se encuentran con el mismo desconocido cada domingo en el lago del parque.',
    paragraphs: [
    { es: 'Sara vive cerca de un parque grande, con muchos árboles y un lago pequeño. Los domingos, camina al parque con su perro, Tobi.', en: 'Sara lives near a big park, with lots of trees and a small lake. On Sundays, she walks to the park with her dog, Tobi.' },
    { es: 'Siempre se sienta en el mismo lugar, cerca del lago. Allí, casi siempre, hay un hombre mayor. Lee el periódico y toma café.', en: "She always sits in the same spot, near the lake. There, almost always, there's an older man. He reads the newspaper and drinks coffee." },
    { es: '—Buenos días — dice Sara. El hombre sonríe y contesta: —Buenos días, señorita. ¿Y Tobi? ¿Bien?', en: '"Good morning," says Sara. The man smiles and answers: "Good morning, miss. And Tobi? Doing well?"' },
    { es: 'Tobi corre hacia el lago y ladra a los patos. Los patos nadan rápido, lejos del perro.', en: 'Tobi runs toward the lake and barks at the ducks. The ducks swim fast, away from the dog.' },
    { es: 'El hombre mira y se ríe un poco. —Tu perro quiere un amigo pato — dice.', en: 'The man watches and laughs a little. "Your dog wants a duck friend," he says.' },
    { es: 'Sara llama a Tobi. El perro vuelve, cansado y feliz. Los tres, Sara, Tobi y el hombre, miran el lago juntos, en silencio.', en: 'Sara calls Tobi. The dog comes back, tired and happy. The three of them, Sara, Tobi, and the man, look at the lake together, in silence.' },
    { es: 'Antes de irse, Sara pregunta el nombre del hombre. —Me llamo Andrés — contesta él. —Hasta el domingo, Andrés — dice ella, y camina a casa con Tobi.', en: 'Before leaving, Sara asks the man\'s name. "My name is Andrés," he answers. "See you Sunday, Andrés," she says, and walks home with Tobi.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Con quién camina Sara al parque?',
        options: ['Con su perro', 'Con su hermano', 'Con una amiga', 'Sola'],
        answer: 'Con su perro',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace el hombre en el parque?',
        options: ['Lee el periódico y toma café', 'Corre con su perro', 'Nada en el lago', 'Duerme'],
        answer: 'Lee el periódico y toma café',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace Tobi cuando ve los patos?',
        options: ['Ladra y corre hacia ellos', 'Duerme', 'Nada con ellos', 'Los mira en silencio'],
        answer: 'Ladra y corre hacia ellos',
      },
      {
        type: 'comprehension',
        prompt: 'What does Sara ask the man before she leaves?',
        answer: 'his name',
        altAnswers: ['his name', 'what his name is', 'for his name', 'she asks his name', "what's your name", 'what is your name', 'what is his name'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo se llama el hombre del parque?',
        options: ['Andrés', 'Diego', 'Javier', 'Mateo'],
        answer: 'Andrés',
      },
    ],
  },
  {
    id: 'planes-para-el-sabado',
    written: '2026-07-10',
    title: 'Planes para el sábado',
    level: 'A1',
    format: 'standalone',
    summary: 'Marta llama a su amigo Javier para hacer planes para una fiesta — un diálogo telefónico.',
    paragraphs: [
    { es: 'Marta llama a su amigo Javier por teléfono. Quiere hacer planes para el sábado.', en: 'Marta calls her friend Javier on the phone. She wants to make plans for Saturday.' },
    { es: '—¿Sí? — contesta Javier. —Hola, Javier, soy Marta. ¿Qué haces el sábado? — pregunta ella.', en: '"Hello?" answers Javier. "Hi Javier, it\'s Marta. What are you doing Saturday?" she asks.' },
    { es: '—No sé todavía. ¿Por qué? — dice Javier. —Hay una fiesta en casa de Carla. ¿Quieres ir? — contesta Marta.', en: '"I don\'t know yet. Why?" says Javier. "There\'s a party at Carla\'s house. Do you want to go?" answers Marta.' },
    { es: '—¡Claro que sí! ¿A qué hora empieza? — pregunta Javier, contento.', en: '"Of course! What time does it start?" asks Javier, happy.' },
    { es: '—A las ocho. Yo llego a las siete y media, para ayudar con la comida — contesta Marta. —Perfecto. Puedo llevar música — dice Javier.', en: '"At eight. I\'m arriving at seven thirty, to help with the food," answers Marta. "Perfect. I can bring music," says Javier.' },
    { es: '—Buena idea. Nos vemos el sábado, entonces — dice Marta. —Nos vemos. ¡Gracias, Marta! — contesta Javier, y cuelga el teléfono.', en: '"Good idea. See you Saturday, then," says Marta. "See you. Thanks, Marta!" answers Javier, and hangs up the phone.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Por qué llama Marta a Javier?',
        options: ['Para hacer planes para el sábado', 'Para pedir dinero', 'Para cancelar una cita', 'Para invitarlo a cenar hoy'],
        answer: 'Para hacer planes para el sábado',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde es la fiesta?',
        options: ['En casa de Carla', 'En casa de Marta', 'En un restaurante', 'En el parque'],
        answer: 'En casa de Carla',
      },
      {
        type: 'multiple_choice',
        prompt: '¿A qué hora llega Marta a la fiesta?',
        options: ['A las siete y media', 'A las ocho', 'A las nueve', 'A las seis'],
        answer: 'A las siete y media',
      },
      {
        type: 'comprehension',
        prompt: 'What does Javier offer to bring to the party?',
        answer: 'music',
        altAnswers: ['music', 'some music', 'he offers music'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo contesta Javier al final?',
        options: ['Nos vemos. ¡Gracias, Marta!', 'No puedo ir', 'Voy a llegar tarde', 'No sé todavía'],
        answer: 'Nos vemos. ¡Gracias, Marta!',
      },
    ],
  },
  {
    id: 'como-llego-a-la-estacion',
    written: '2026-07-10',
    title: '¿Cómo llego a la estación?',
    level: 'A1',
    format: 'standalone',
    summary: 'Elena pregunta cómo llegar a la estación de tren en una ciudad desconocida.',
    paragraphs: [
    { es: 'Elena está en una ciudad nueva. Busca la estación de tren, pero no sabe el camino. Ve a una mujer en la calle.', en: "Elena is in a new city. She's looking for the train station, but doesn't know the way. She sees a woman on the street." },
    { es: '—Perdón, señora. ¿Sabe dónde está la estación de tren? — pregunta Elena. —Sí, claro — contesta la mujer—. Está bastante cerca.', en: '"Excuse me, ma\'am. Do you know where the train station is?" asks Elena. "Yes, of course," answers the woman. "It\'s pretty close."' },
    { es: '—Puede seguir todo derecho por esta calle, hasta el semáforo — explica la mujer—. Después, tiene que doblar a la derecha. La estación está enfrente de un banco grande.', en: '"You can keep going straight down this street, to the traffic light," the woman explains. "After that, you have to turn right. The station is in front of a big bank."' },
    { es: '—Muchas gracias, señora. Es usted muy amable — dice Elena. —De nada. ¡Buen viaje! — contesta la mujer, y camina de nuevo por la calle.', en: '"Thank you very much, ma\'am. You\'re very kind," says Elena. "You\'re welcome. Have a good trip!" answers the woman, and walks on down the street again.' },
    { es: 'Elena camina por la calle, hasta el semáforo. Dobla a la derecha. Allí está la estación, enfrente del banco, exactamente como dice la mujer.', en: "Elena walks down the street, to the traffic light. She turns right. There's the station, in front of the bank, exactly as the woman said." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué busca Elena?',
        options: ['La estación de tren', 'Un banco', 'Un restaurante', 'Su casa'],
        answer: 'La estación de tren',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Hacia dónde tiene que doblar Elena?',
        options: ['A la derecha', 'A la izquierda', 'Todo derecho solamente', 'Hacia atrás'],
        answer: 'A la derecha',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hay enfrente de la estación?',
        options: ['Un banco grande', 'Un parque', 'Una panadería', 'Un semáforo'],
        answer: 'Un banco grande',
      },
      {
        type: 'comprehension',
        prompt: 'What does Elena say to thank the woman?',
        answer: 'thank you very much',
        altAnswers: ['thank you', 'thanks a lot', 'many thanks', "thank you very much, ma'am"],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué dice la mujer para despedirse?',
        options: ['¡Buen viaje!', '¡Hasta mañana!', '¡Buena suerte!', '¡Nos vemos!'],
        answer: '¡Buen viaje!',
      },
    ],
  },
  {
    id: 'blahaj-ch3',
    written: '2026-07-10',
    title: 'Las Aventuras de Blahaj — Capítulo 3: El regreso',
    level: 'A1',
    format: 'story',
    story: 'blahaj',
    chapter: 3,
    summary: 'El viaje de Blahaj con Diego termina, y Blahaj vuelve a casa con Lucía.',
    paragraphs: [
    { es: 'Pasan tres semanas. Un día, Diego escribe: "Lucía, el viaje de Blahaj termina pronto. ¿Está lista tu casa para recibir a Blahaj otra vez?"', en: 'Three weeks pass. One day, Diego writes: "Lucía, Blahaj\'s trip is ending soon. Is your house ready to have Blahaj again?"' },
    { es: 'Lucía sonríe. Escribe: "¡Sí! Su cama está lista, al lado de la almohada, como siempre."', en: 'Lucía smiles. She writes: "Yes! His bed is ready, next to the pillow, like always."' },
    { es: 'Diego prepara la caja otra vez. Pone a Blahaj adentro, con la bufanda de regalo y una nota nueva.', en: 'Diego prepares the box again. He puts Blahaj inside, with the scarf as a gift and a new note.' },
    { es: 'En la nota escribe: "Gracias por Blahaj. Simón está triste, pero entiende. ¡Hasta el próximo viaje!"', en: 'In the note he writes: "Thanks for Blahaj. Simón is sad, but he understands. Until the next trip!"' },
    { es: 'Pasan cinco días. Lucía mira el buzón cada mañana, antes de ir a trabajar.', en: 'Five days pass. Lucía checks the mailbox every morning, before going to work.' },
    { es: 'Por fin, el sábado, llega la caja. Lucía abre la caja rápido. ¡Allí está Blahaj, con su sonrisa tonta de siempre!', en: "Finally, on Saturday, the box arrives. Lucía opens the box quickly. There's Blahaj, with his same goofy smile!" },
    { es: 'Pone a Blahaj en la cama, al lado de la almohada. Blahaj mira la ventana, feliz de estar en casa.', en: "She puts Blahaj on the bed, next to the pillow. Blahaj looks at the window, happy to be home." },
    { es: 'Esa noche, Lucía escribe en el grupo: "Blahaj ya está en casa. ¡Gracias, Diego! Ahora tiene una historia para contar."', en: 'That night, Lucía writes in the group: "Blahaj is home now. Thanks, Diego! Now he has a story to tell."' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué pregunta Diego a Lucía?',
        options: ['Si su casa está lista para Blahaj', 'Si quiere visitar Buenos Aires', 'Si Blahaj está triste', 'Si necesita dinero'],
        answer: 'Si su casa está lista para Blahaj',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué manda Diego a Blahaj de regalo?',
        options: ['Una bufanda', 'Un libro', 'Una foto', 'Un juguete'],
        answer: 'Una bufanda',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo está Simón cuando Blahaj se va?',
        options: ['Triste, pero entiende', 'Muy feliz', 'Enojado', 'No le importa'],
        answer: 'Triste, pero entiende',
      },
      {
        type: 'comprehension',
        prompt: 'Where does Lucía put Blahaj when he comes home?',
        answer: 'on the bed, next to the pillow',
        altAnswers: ['on her bed', 'next to the pillow', 'on the bed next to the pillow', 'in bed next to the pillow'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué escribe Lucía al final, en el grupo?',
        options: ['Blahaj ya está en casa. ¡Gracias, Diego!', 'Blahaj está perdido', 'Quiero mandar a Blahaj otra vez', 'Blahaj no quiere volver'],
        answer: 'Blahaj ya está en casa. ¡Gracias, Diego!',
      },
    ],
  },
  {
    id: 'la-farmacia-de-la-esquina',
    written: '2026-07-10',
    title: 'La farmacia de la esquina',
    level: 'A1',
    format: 'standalone',
    summary: 'Marcos tiene dolor de cabeza y va a la farmacia de la esquina a buscar una solución.',
    paragraphs: [
    { es: 'Marcos vive cerca de la farmacia de la esquina. Hoy tiene dolor de cabeza y necesita medicina.', en: 'Marcos lives near the corner pharmacy. Today he has a headache and needs medicine.' },
    { es: 'Entra en la farmacia. Detrás del mostrador, hay una mujer amable.', en: "He goes into the pharmacy. Behind the counter, there's a kind woman." },
    { es: '—Buenas tardes — dice Marcos—. Tengo dolor de cabeza. ¿Tiene algo para eso?', en: '"Good afternoon," says Marcos. "I have a headache. Do you have something for that?"' },
    { es: '—Claro — contesta ella—. Esta medicina es muy buena. Puede tomar una pastilla cada ocho horas. También es bueno descansar un poco.', en: '"Of course," she answers. "This medicine is very good. You can take one pill every eight hours. It\'s also good to rest a little."' },
    { es: '—Perfecto, gracias — dice Marcos, y paga en el mostrador.', en: '"Perfect, thanks," says Marcos, and pays at the counter.' },
    { es: 'Después, camina a casa. En media hora, ya no tiene dolor de cabeza.', en: 'Afterward, he walks home. In half an hour, he no longer has a headache.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué le pasa a Marcos?',
        options: ['Tiene dolor de cabeza', 'Tiene hambre', 'Está cansado', 'Tiene frío'],
        answer: 'Tiene dolor de cabeza',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde entra Marcos?',
        options: ['En la farmacia', 'En la panadería', 'En el banco', 'En la escuela'],
        answer: 'En la farmacia',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cada cuánto tiempo tiene que tomar la pastilla?',
        options: ['Cada ocho horas', 'Cada hora', 'Una vez a la semana', 'Cada dos días'],
        answer: 'Cada ocho horas',
      },
      {
        type: 'comprehension',
        prompt: 'How does Marcos feel after half an hour?',
        answer: 'no headache',
        altAnswers: ['no more headache', "he doesn't have a headache anymore", 'better', 'no headache anymore', 'he feels better'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace Marcos después de comprar la medicina?',
        options: ['Camina a casa', 'Va al parque', 'Llama a un amigo', 'Duerme en la farmacia'],
        answer: 'Camina a casa',
      },
    ],
  },
  {
    id: 'en-el-cafe',
    written: '2026-07-10',
    title: 'En el café',
    level: 'A1',
    format: 'standalone',
    summary: 'Valentina pide un café y prueba un pastel nuevo en una cafetería pequeña cerca de su trabajo.',
    paragraphs: [
    { es: 'Valentina entra en un café pequeño, cerca de su trabajo. Tiene hambre y quiere un café.', en: "Valentina goes into a small café, near her work. She's hungry and wants a coffee." },
    { es: '—Buenos días — dice el camarero—. ¿Qué desea?', en: '"Good morning," says the waiter. "What would you like?"' },
    { es: '—Un café con leche, por favor. Y... ¿qué es esto? — pregunta Valentina, y señala un pastel en el mostrador.', en: '"A coffee with milk, please. And... what is this?" asks Valentina, and points to a pastry on the counter.' },
    { es: '—Es una tarta de manzana, muy popular aquí — contesta el camarero—. ¿Quiere probar un pedazo?', en: '"It\'s an apple tart, very popular here," answers the waiter. "Do you want to try a piece?"' },
    { es: '—Sí, gracias — dice Valentina. Prueba la tarta. —¡Está muy rica! — dice.', en: '"Yes, thanks," says Valentina. She tries the tart. "It\'s so good!" she says.' },
    { es: '—Entonces quiero un pedazo, también — dice ella. El camarero prepara todo.', en: '"Then I want a piece too," she says. The waiter prepares everything.' },
    { es: 'Valentina paga y se sienta cerca de la ventana. El café y la tarta están perfectos.', en: 'Valentina pays and sits down near the window. The coffee and the tart are perfect.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué quiere tomar Valentina?',
        options: ['Un café con leche', 'Un té', 'Un jugo', 'Agua'],
        answer: 'Un café con leche',
      },
      {
        type: 'multiple_choice',
        prompt: '¿De qué es la tarta?',
        options: ['De manzana', 'De chocolate', 'De limón', 'De queso'],
        answer: 'De manzana',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué dice Valentina después de probar la tarta?',
        options: ['¡Está muy rica!', 'No me gusta', 'Está fría', 'Es muy grande'],
        answer: '¡Está muy rica!',
      },
      {
        type: 'comprehension',
        prompt: 'What does Valentina decide to order after trying the tart?',
        answer: 'a piece of the tart',
        altAnswers: ['a piece', 'a piece of tart', 'she orders a piece too', 'another piece'],
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde se sienta Valentina?',
        options: ['Cerca de la ventana', 'Cerca de la puerta', 'En el mostrador', 'Afuera'],
        answer: 'Cerca de la ventana',
      },
    ],
  },
  {
    id: 'el-gato-perdido',
    written: '2026-07-10',
    title: 'El gato perdido',
    level: 'A1',
    format: 'standalone',
    summary: 'Luna, la gata de Elena, desaparece una mañana — un vecino ayuda a buscarla por el jardín.',
    paragraphs: [
    { es: 'Elena vive en un edificio pequeño, con un jardín detrás. Tiene una gata negra. Se llama Luna.', en: 'Elena lives in a small building, with a garden behind it. She has a black cat. Her name is Luna.' },
    { es: 'Todas las mañanas, Luna desayuna en la cocina y después duerme en el sofá, cerca de la ventana.', en: 'Every morning, Luna eats breakfast in the kitchen and afterward sleeps on the sofa, near the window.' },
    { es: 'Pero hoy la ventana está abierta. Y Luna no está en el sofá.', en: 'But today the window is open. And Luna is not on the sofa.' },
    { es: '—¿Luna? ¿Dónde estás? — pregunta Elena, y busca en cada habitación.', en: '"Luna? Where are you?" asks Elena, and she looks in every room.' },
    { es: 'Elena no encuentra a Luna. Sale al jardín, un poco nerviosa.', en: "Elena doesn't find Luna. She goes out to the garden, a little nervous." },
    { es: 'Óscar, su vecino, está en el jardín también, con un café en la mano.', en: 'Óscar, her neighbor, is in the garden too, with a coffee in his hand.' },
    { es: '—Buenos días, Elena. ¿Todo bien? — pregunta él.', en: '"Good morning, Elena. Is everything okay?" he asks.' },
    { es: '—No encuentro a Luna, mi gata. Es negra, con ojos verdes — contesta Elena.', en: '"I can\'t find Luna, my cat. She\'s black, with green eyes," answers Elena.' },
    { es: '—Yo te ayudo — dice Óscar, y deja el café en la mesa.', en: '"I\'ll help you," says Óscar, and he sets the coffee on the table.' },
    { es: 'Los dos buscan detrás de las plantas, debajo de los coches, entre las flores.', en: 'The two of them search behind the plants, under the cars, among the flowers.' },
    { es: 'Después de unos minutos, Óscar mira debajo de un coche.', en: 'After a few minutes, Óscar looks under a car.' },
    { es: '—¡Elena! ¡Aquí está! — dice Óscar, y sonríe.', en: '"Elena! Here she is!" says Óscar, and smiles.' },
    { es: 'Luna está debajo del coche, tranquila, y mira a Elena con ojos grandes.', en: 'Luna is under the car, calm, and looks at Elena with big eyes.' },
    { es: '—¡Luna! — dice Elena, y la gata camina hacia Elena despacio.', en: '"Luna!" says Elena, and the cat walks toward Elena slowly.' },
    { es: 'Elena toma a Luna en los brazos. —Gracias, Óscar. Eres un buen vecino — dice, y sonríe.', en: 'Elena takes Luna in her arms. "Thank you, Óscar. You\'re a good neighbor," she says, and smiles.' },
    { es: 'Óscar sonríe también y toma su café, ya frío. —De nada. Los vecinos están para eso — contesta.', en: 'Óscar smiles too and picks up his coffee, already cold. "You\'re welcome. That\'s what neighbors are for," he answers.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cómo se llama la gata de Elena?',
        options: ['Luna', 'Tobi', 'Pilar', 'Carmen'],
        answer: 'Luna',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde busca Elena primero?',
        options: ['En cada habitación', 'En el jardín', 'En la calle', 'En el coche'],
        answer: 'En cada habitación',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Quién ayuda a Elena a buscar a Luna?',
        options: ['Óscar, su vecino', 'Javier, su amigo', 'Mateo, el panadero', 'Diego, su hermano'],
        answer: 'Óscar, su vecino',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde encuentran a Luna?',
        options: ['Debajo de un coche', 'Detrás de las plantas', 'Entre las flores', 'En el sofá'],
        answer: 'Debajo de un coche',
      },
      {
        type: 'comprehension',
        prompt: 'What does Elena say about Óscar at the end?',
        answer: "he's a good neighbor",
        altAnswers: ['a good neighbor', 'he is a good neighbor', 'good neighbor', "that he's a good neighbor"],
      },
    ],
  },
  {
    id: 'el-regalo-de-cumpleanos',
    written: '2026-07-10',
    title: 'El regalo de cumpleaños',
    level: 'A1',
    format: 'standalone',
    summary: 'Diego busca un regalo perfecto para el cumpleaños de su hermana en una tienda pequeña.',
    paragraphs: [
    { es: 'Mañana es el cumpleaños de Carmen, la hermana de Diego. Diego todavía no tiene un regalo.', en: "Tomorrow is Carmen's birthday, Diego's sister. Diego doesn't have a gift yet." },
    { es: 'Después del trabajo, entra en una tienda pequeña en el centro.', en: 'After work, he goes into a small shop downtown.' },
    { es: '—Buenas tardes. ¿Busca algo especial? — pregunta la vendedora.', en: '"Good afternoon. Are you looking for something special?" asks the shop assistant.' },
    { es: '—Sí, un regalo para mi hermana. Ella lee mucho y escucha música todos los días — contesta Diego.', en: '"Yes, a gift for my sister. She reads a lot and listens to music every day," answers Diego.' },
    { es: '—Tenemos libros nuevos aquí, y también música — dice la vendedora, y camina hacia una estantería.', en: '"We have new books here, and music too," says the assistant, and walks toward a shelf.' },
    { es: 'Diego mira los libros, uno por uno. Hay novelas, libros de cocina, libros de viajes.', en: 'Diego looks at the books, one by one. There are novels, cookbooks, travel books.' },
    { es: 'Carmen viaja mucho. Siempre visita ciudades nuevas.', en: 'Carmen travels a lot. She always visits new cities.' },
    { es: 'Diego encuentra un libro sobre las ciudades de España, con fotos grandes y bonitas.', en: 'Diego finds a book about the cities of Spain, with big, beautiful photos.' },
    { es: '—Este libro es perfecto — piensa, y sonríe.', en: '"This book is perfect," he thinks, and smiles.' },
    { es: '—¿Este libro, por favor? — pregunta Diego a la vendedora.', en: '"This book, please?" Diego asks the shop assistant.' },
    { es: '—Buena elección. ¿Necesita papel de regalo también? — pregunta ella.', en: '"Good choice. Do you need gift wrap too?" she asks.' },
    { es: '—Sí, por favor — contesta Diego.', en: '"Yes, please," answers Diego.' },
    { es: 'La vendedora envuelve el libro con papel azul y una cinta blanca.', en: 'The assistant wraps the book in blue paper with a white ribbon.' },
    { es: 'Diego sale de la tienda con el regalo en las manos y camina a casa, con una sonrisa pequeña.', en: "Diego leaves the shop with the gift in his hands and walks home, with a small smile." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Para quién es el regalo?',
        options: ['Para su hermana', 'Para su madre', 'Para su amigo', 'Para su vecina'],
        answer: 'Para su hermana',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué compra Diego?',
        options: ['Un libro sobre las ciudades de España', 'Un libro de cocina', 'Una novela', 'Música'],
        answer: 'Un libro sobre las ciudades de España',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le pregunta la vendedora a Diego al final?',
        options: ['Si necesita papel de regalo', 'Si quiere un descuento', 'Si tiene más dinero', 'Si quiere otro libro'],
        answer: 'Si necesita papel de regalo',
      },
      {
        type: 'multiple_choice',
        prompt: '¿De qué color es el papel de regalo?',
        options: ['Azul', 'Rojo', 'Verde', 'Amarillo'],
        answer: 'Azul',
      },
      {
        type: 'comprehension',
        prompt: 'Why is Diego happy at the end of the story?',
        answer: 'he found the perfect gift',
        altAnswers: ['he found a perfect gift', 'because he found the perfect gift', 'he has a gift for his sister', 'he found the right book'],
      },
    ],
  },
  {
    id: 'un-dia-de-lluvia',
    written: '2026-07-10',
    title: 'Un día de lluvia',
    level: 'A1',
    format: 'standalone',
    summary: 'Un sábado de lluvia cambia los planes de Rosa, pero el día termina bien de todos modos.',
    paragraphs: [
    { es: 'Es sábado por la mañana. Rosa mira por la ventana: llueve mucho.', en: "It's Saturday morning. Rosa looks out the window: it's raining a lot." },
    { es: 'Sus planes para hoy son simples: caminar por el parque con su amiga Inés.', en: "Her plans for today are simple: walk through the park with her friend Inés." },
    { es: 'Pero con esta lluvia, el parque no es una buena idea.', en: "But with this rain, the park isn't a good idea." },
    { es: 'Rosa llama a Inés por teléfono. —Hola, Inés. Aquí llueve mucho. ¿Caminamos otro día? — pregunta.', en: 'Rosa calls Inés on the phone. "Hi, Inés. It\'s raining a lot here. Should we walk another day?" she asks.' },
    { es: '—Buena idea — contesta Inés—. ¿Qué hacemos en vez de caminar?', en: '"Good idea," answers Inés. "What should we do instead of walking?"' },
    { es: '—No sé. ¿Quieres venir a mi casa? Tengo té y muchos libros — dice Rosa.', en: '"I don\'t know. Do you want to come to my house? I have tea and lots of books," says Rosa.' },
    { es: '—Perfecto. Llego en veinte minutos — contesta Inés.', en: '"Perfect. I\'ll arrive in twenty minutes," answers Inés.' },
    { es: 'Inés llega con un paraguas amarillo y una sonrisa grande.', en: 'Inés arrives with a yellow umbrella and a big smile.' },
    { es: 'Las dos preparan té caliente y se sientan cerca de la ventana. Afuera, la lluvia continúa.', en: 'The two of them make hot tea and sit near the window. Outside, the rain continues.' },
    { es: '—Este libro es muy bueno — dice Rosa, y da un libro a Inés.', en: '"This book is very good," says Rosa, and hands Inés a book.' },
    { es: 'Pasan la tarde así: té, libros, y conversación. La lluvia ya no importa.', en: "They spend the afternoon like this: tea, books, and conversation. The rain doesn't matter anymore." },
    { es: 'Antes de irse, Inés mira por la ventana. —Todavía llueve — dice, y toma su paraguas—. Gracias por el té, Rosa. Nos vemos pronto.', en: 'Before leaving, Inés looks out the window. "It\'s still raining," she says, and picks up her umbrella. "Thanks for the tea, Rosa. See you soon."' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué planes tiene Rosa para el sábado?',
        options: ['Caminar por el parque con Inés', 'Ir de compras', 'Trabajar', 'Ver una película'],
        answer: 'Caminar por el parque con Inés',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Por qué cambian los planes?',
        options: ['Porque llueve mucho', 'Porque Inés está enferma', 'Porque el parque está cerrado', 'Porque Rosa trabaja'],
        answer: 'Porque llueve mucho',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hacen Rosa e Inés en vez de caminar?',
        options: ['Toman té y leen libros', 'Ven una película', 'Cocinan juntas', 'Van de compras'],
        answer: 'Toman té y leen libros',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Con qué llega Inés a casa de Rosa?',
        options: ['Con un paraguas amarillo', 'Con un libro', 'Con un pastel', 'Con flores'],
        answer: 'Con un paraguas amarillo',
      },
      {
        type: 'comprehension',
        prompt: 'What does Inés thank Rosa for before leaving?',
        answer: 'the tea',
        altAnswers: ['tea', 'for the tea', 'she thanks her for the tea'],
      },
    ],
  },
  {
    id: 'la-parada-del-autobus',
    written: '2026-07-10',
    title: 'La parada del autobús',
    level: 'A1',
    format: 'standalone',
    summary: 'Un hombre y una mujer esperan el mismo autobús, tarde, y hablan un poco mientras esperan.',
    paragraphs: [
    { es: 'Son las ocho de la mañana. Laura espera el autobús número doce, en la esquina de su calle.', en: "It's eight in the morning. Laura is waiting for bus number twelve, on the corner of her street." },
    { es: 'El autobús normalmente llega a las ocho y cinco. Hoy no.', en: "The bus normally arrives at eight-oh-five. Today, no." },
    { es: 'Un hombre con un maletín negro también espera, cerca de Laura.', en: 'A man with a black briefcase is also waiting, near Laura.' },
    { es: '—Perdón, ¿el autobús doce pasa por aquí? — pregunta el hombre.', en: '"Excuse me, does bus twelve stop here?" asks the man.' },
    { es: '—Sí, pero hoy llega tarde. Ya son las ocho y quince — contesta Laura, y mira su reloj.', en: '"Yes, but today it\'s late. It\'s already eight-fifteen," answers Laura, and looks at her watch.' },
    { es: '—Qué extraño. Tengo una reunión importante a las ocho y media — dice el hombre, un poco nervioso.', en: '"How strange. I have an important meeting at eight-thirty," says the man, a little nervous.' },
    { es: '—Yo también tengo prisa. Trabajo en el hospital, cerca del centro — contesta Laura.', en: "\"I'm also in a hurry. I work at the hospital, near downtown,\" answers Laura." },
    { es: '—¿Eres enfermera? — pregunta él, con curiosidad.', en: '"Are you a nurse?" he asks, curiously.' },
    { es: '—Sí, trabajo allí. Me llamo Laura — contesta ella, y sonríe un poco.', en: '"Yes, I work there. I\'m Laura," she answers, and smiles a little.' },
    { es: '—Yo soy Pablo. Mucho gusto — dice él.', en: '"I\'m Pablo. Nice to meet you," he says.' },
    { es: 'En ese momento, el autobús aparece al final de la calle.', en: 'At that moment, the bus appears at the end of the street.' },
    { es: '—¡Por fin! — dice Pablo. Los dos suben al autobús juntos.', en: '"Finally!" says Pablo. The two of them get on the bus together.' },
    { es: '—Buena suerte con tu reunión — dice Laura, antes de sentarse. —Gracias. Buen día en el hospital — contesta Pablo, y los dos sonríen.', en: '"Good luck with your meeting," says Laura, before sitting down. "Thanks. Have a good day at the hospital," Pablo answers, and they both smile.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué número de autobús espera Laura?',
        options: ['El doce', 'El cinco', 'El ocho', 'El veinte'],
        answer: 'El doce',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde trabaja Laura?',
        options: ['En un hospital', 'En una tienda', 'En una escuela', 'En un banco'],
        answer: 'En un hospital',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Por qué está nervioso Pablo?',
        options: ['Tiene una reunión importante', 'Perdió su maletín', 'No tiene dinero', 'Llega tarde al trabajo'],
        answer: 'Tiene una reunión importante',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le pregunta Pablo a Laura?',
        options: ['Si es enfermera', 'Si tiene hora', 'Si conoce el barrio', 'Si vive cerca'],
        answer: 'Si es enfermera',
      },
      {
        type: 'comprehension',
        prompt: 'What does Laura say to Pablo before sitting down?',
        answer: 'good luck with his meeting',
        altAnswers: ['good luck with your meeting', 'good luck', 'she wishes him good luck', 'good luck with the meeting'],
      },
    ],
  },
  {
    id: 'la-pizza-del-viernes',
    written: '2026-07-10',
    title: 'La pizza del viernes',
    level: 'A1',
    format: 'standalone',
    summary: 'Cada viernes, la familia de Tomás pide pizza por teléfono — una pequeña tradición familiar.',
    paragraphs: [
    { es: 'Todos los viernes, la familia de Tomás pide pizza. Es una tradición especial en su casa.', en: "Every Friday, Tomás's family orders pizza. It's a special tradition in their house." },
    { es: 'A las siete, Tomás llama a la pizzería de la esquina.', en: 'At seven, Tomás calls the pizzeria on the corner.' },
    { es: '—Pizzería Roma, buenas noches — contesta una voz—. Hola, quiero pedir dos pizzas, por favor — dice Tomás.', en: '"Pizzería Roma, good evening," answers a voice. "Hi, I\'d like to order two pizzas, please," says Tomás.' },
    { es: '—Claro. ¿Qué pizzas quiere?', en: '"Sure. What pizzas would you like?"' },
    { es: '—Una pizza de queso, para mis hijos, y una pizza de verduras, para mi esposa y para mí — contesta Tomás.', en: '"One cheese pizza, for my kids, and one vegetable pizza, for my wife and me," answers Tomás.' },
    { es: '—Perfecto. ¿Su dirección, por favor?', en: '"Perfect. Your address, please?"' },
    { es: 'Tomás da su dirección y su número de teléfono.', en: 'Tomás gives his address and phone number.' },
    { es: '—Las pizzas llegan en treinta minutos — dice la voz, y cuelga.', en: '"The pizzas will arrive in thirty minutes," says the voice, and hangs up.' },
    { es: 'Los hijos de Tomás, Sofía y Martín, esperan en la sala. Sofía mira la puerta cada minuto.', en: "Tomás's children, Sofía and Martín, wait in the living room. Sofía looks at the door every minute." },
    { es: '—¿Cuánto tiempo falta? — pregunta Sofía, cada cinco minutos.', en: '"How much longer?" asks Sofía, every five minutes.' },
    { es: 'Por fin, suena el timbre. Martín corre a la puerta.', en: 'Finally, the doorbell rings. Martín runs to the door.' },
    { es: 'La familia se sienta a la mesa, con las pizzas calientes en el centro. Martín ya tiene un pedazo en la mano.', en: "The family sits at the table, with the hot pizzas in the center. Martín already has a slice in his hand." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué día pide pizza la familia de Tomás?',
        options: ['El viernes', 'El sábado', 'El domingo', 'El lunes'],
        answer: 'El viernes',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cuántas pizzas pide Tomás?',
        options: ['Dos', 'Una', 'Tres', 'Cuatro'],
        answer: 'Dos',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué pizza es para los hijos de Tomás?',
        options: ['Pizza de queso', 'Pizza de verduras', 'Pizza de jamón', 'Pizza de champiñones'],
        answer: 'Pizza de queso',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Quién corre a la puerta cuando suena el timbre?',
        options: ['Martín', 'Sofía', 'Tomás', 'La esposa de Tomás'],
        answer: 'Martín',
      },
      {
        type: 'comprehension',
        prompt: 'How long does the pizzeria say the pizzas will take to arrive?',
        answer: 'thirty minutes',
        altAnswers: ['30 minutes', 'thirty minutes', 'in thirty minutes', 'half an hour'],
      },
    ],
  },
  {
    id: 'el-primer-dia-de-trabajo',
    written: '2026-07-11',
    title: 'El primer día de trabajo',
    level: 'A2',
    format: 'standalone',
    summary: 'Ana empieza un nuevo trabajo y sus compañeros le dan una bienvenida amable.',
    paragraphs: [
    { es: 'Ana empieza un nuevo trabajo en una oficina pequeña hoy, un poco nerviosa.', en: "Ana starts a new job at a small office today, a little nervous." },
    { es: 'Llegó a las ocho y media, quince minutos antes de la hora. La recepcionista la saludó con una sonrisa.', en: 'She arrived at eight-thirty, fifteen minutes before the time. The receptionist greeted her with a smile.' },
    { es: '—Bienvenida, Ana. Te presento a tu equipo — dijo, y caminaron juntas por el pasillo.', en: '"Welcome, Ana. Let me introduce you to your team," she said, and they walked together down the hallway.' },
    { es: 'En la sala de reuniones, cuatro personas se levantaron cuando Ana entró, y todos la saludaron con la mano.', en: 'In the meeting room, four people stood up when Ana walked in, and everyone waved hello to her.' },
    { es: '—Hola a todos. Soy Ana, la nueva diseñadora.', en: '"Hi everyone. I\'m Ana, the new designer."' },
    { es: 'Un hombre alto se acercó y le dio la mano. —Me llamo Carlos, del equipo de marketing.', en: 'A tall man came over and shook her hand. "My name is Carlos, from the marketing team."' },
    { es: 'Ana pasó la mañana conociendo a todo el equipo, sala por sala.', en: 'Ana spent the morning meeting the whole team, room by room.' },
    { es: 'A mediodía, Carlos la invitó a comer con el equipo, en un restaurante cerca de la oficina.', en: 'At noon, Carlos invited her to eat with the team, at a restaurant near the office.' },
    { es: '—¿Qué tal tu primera mañana? — preguntó Carlos, durante la comida.', en: '"How was your first morning?" asked Carlos, during lunch.' },
    { es: '—Mejor de lo que pensé. Todos son muy amables — contestó Ana, ya más relajada.', en: '"Better than I thought. Everyone is very kind," answered Ana, more relaxed now.' },
    { es: 'Ya por la tarde, Ana empezó su primer proyecto y trabajó concentrada hasta las seis.', en: 'By the afternoon, Ana started her first project and worked with focus until six.' },
    { es: 'Cuando salió de la oficina, miró hacia atrás una vez y sonrió.', en: 'When she left the office, she looked back once and smiled.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿A qué hora llegó Ana a la oficina?',
        options: ['A las ocho y media', 'A las nueve', 'A las ocho', 'A las siete y media'],
        answer: 'A las ocho y media',
      },
      {
        type: 'multiple_choice',
        prompt: '¿En qué equipo trabaja Carlos?',
        options: ['Marketing', 'Diseño', 'Ventas', 'Recepción'],
        answer: 'Marketing',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Adónde van a comer Ana y el equipo?',
        options: ['A un restaurante cerca de la oficina', 'A la sala de reuniones', 'A casa de Carlos', 'No comen juntos'],
        answer: 'A un restaurante cerca de la oficina',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Hasta qué hora trabajó Ana por la tarde?',
        options: ['Hasta las seis', 'Hasta las cinco', 'Hasta las siete', 'Hasta las ocho'],
        answer: 'Hasta las seis',
      },
      {
        type: 'comprehension',
        prompt: 'How does Ana feel about her first day by the time she leaves the office?',
        answer: 'better than she expected',
        altAnswers: ['better than expected', 'good', 'happy', 'it went better than she thought', 'relaxed'],
      },
    ],
  },
  {
    id: 'una-sorpresa-de-cumpleanos',
    written: '2026-07-11',
    title: 'Una sorpresa de cumpleaños',
    level: 'A2',
    format: 'standalone',
    summary: 'Los amigos de Marta organizan una fiesta sorpresa y guardan el secreto perfectamente.',
    paragraphs: [
    { es: 'Es el cumpleaños de Marta, pero ella no lo sabe todavía. Sus amigos organizaron una fiesta sorpresa.', en: "It's Marta's birthday, but she doesn't know it yet. Her friends organized a surprise party." },
    { es: 'Nadie le dijo nada a Marta. Todos guardaron el secreto durante dos semanas.', en: 'No one told Marta anything. Everyone kept the secret for two weeks.' },
    { es: 'Su amiga Sonia la llamó por la mañana. —¿Quieres cenar conmigo esta noche? — le preguntó, con voz normal.', en: 'Her friend Sonia called her in the morning. "Do you want to have dinner with me tonight?" she asked her, in a normal voice.' },
    { es: '—Claro, me parece perfecto — contestó Marta, sin sospechar nada.', en: '"Sure, sounds perfect," answered Marta, without suspecting anything.' },
    { es: 'Por la noche, Sonia la recogió en coche y la llevó a un restaurante donde Marta nunca comió.', en: "In the evening, Sonia picked her up by car and took her to a restaurant where Marta had never eaten." },
    { es: 'Marta abrió la puerta del restaurante. No vio a nadie.', en: "Marta opened the restaurant door. She didn't see anyone." },
    { es: 'De repente, las luces se encendieron y treinta personas gritaron: —¡Sorpresa!', en: 'Suddenly, the lights turned on and thirty people shouted: "Surprise!"' },
    { es: 'Marta se llevó las manos a la cara, sin poder decir nada.', en: 'Marta put her hands to her face, unable to say anything.' },
    { es: 'Sus amigos la abrazaron uno por uno. Sonia le dio un regalo grande, envuelto en papel azul.', en: 'Her friends hugged her one by one. Sonia gave her a big gift, wrapped in blue paper.' },
    { es: '—No puedo creer esto. ¡Nadie me dijo nada! — dijo Marta, con lágrimas de felicidad.', en: '"I can\'t believe this. Nobody told me anything!" said Marta, with tears of happiness.' },
    { es: 'Sonia sonrió. —Guardamos el secreto muy bien, ¿no? — preguntó.', en: 'Sonia smiled. "We kept the secret well, right?" she asked.' },
    { es: 'Marta miró a todos sus amigos, todavía con las manos en la cara, y empezó a reír.', en: 'Marta looked at all her friends, her hands still on her face, and started to laugh.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cuánto tiempo guardaron el secreto los amigos de Marta?',
        options: ['Dos semanas', 'Una semana', 'Un mes', 'Tres días'],
        answer: 'Dos semanas',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Quién llamó a Marta por la mañana?',
        options: ['Sonia', 'Su madre', 'Su hermana', 'Nadie'],
        answer: 'Sonia',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le dio Sonia a Marta?',
        options: ['Un regalo grande envuelto en papel azul', 'Flores', 'Un pastel', 'Dinero'],
        answer: 'Un regalo grande envuelto en papel azul',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo reacciona Marta cuando ve a sus amigos?',
        options: ['Se queda completamente sorprendida', 'Se enoja', 'No dice nada y se va', 'No la sorprende'],
        answer: 'Se queda completamente sorprendida',
      },
      {
        type: 'comprehension',
        prompt: 'How does Marta react right after she opens the restaurant door and the lights come on?',
        answer: 'she puts her hands to her face',
        altAnswers: ['hands to her face', 'she covers her face', 'puts hands over face', 'she puts her hands over her face'],
      },
    ],
  },
  {
    id: 'el-vuelo-cancelado',
    written: '2026-07-11',
    title: 'El vuelo cancelado',
    level: 'A2',
    format: 'standalone',
    summary: 'El vuelo de Diego se cancela por mal tiempo, pero su hermana lo ayuda esa noche.',
    paragraphs: [
    { es: 'Diego está esperando su vuelo a Barcelona en el aeropuerto. Factura su maleta y camina hacia la puerta de embarque.', en: "Diego is waiting for his flight to Barcelona at the airport. He checks his suitcase and walks toward the boarding gate." },
    { es: "En la pantalla, ve un mensaje: 'Vuelo cancelado por mal tiempo.' Diego no puede creerlo.", en: "On the screen, he sees a message: 'Flight cancelled due to bad weather.' Diego can't believe it." },
    { es: 'Va directamente al mostrador de la aerolínea. Hay una fila larga de pasajeros enojados.', en: 'He goes straight to the airline counter. There is a long line of angry passengers.' },
    { es: '—Perdón, ¿qué pasa con mi vuelo a Barcelona? — pregunta Diego a la empleada.', en: '"Excuse me, what\'s happening with my flight to Barcelona?" Diego asks the employee.' },
    { es: '—Lo siento mucho, señor. Todos los vuelos de la tarde están cancelados por la tormenta — contesta ella.', en: '"I\'m very sorry, sir. All the afternoon flights are cancelled because of the storm," she answers.' },
    { es: 'Diego debe esperar hasta mañana para el próximo vuelo disponible. No está contento, pero no tiene otra opción.', en: "Diego has to wait until tomorrow for the next available flight. He's not happy, but he has no other option." },
    { es: 'Llama a su hermana por teléfono para contarle la mala noticia.', en: 'He calls his sister on the phone to tell her the bad news.' },
    { es: '—Voy a dormir en el aeropuerto esta noche — le dice, cansado.', en: '"I\'m going to sleep at the airport tonight," he tells her, tired.' },
    { es: 'Su hermana no está de acuerdo. —Ven a mi casa. Vivo a veinte minutos del aeropuerto — le dice ella.', en: 'His sister disagrees. "Come to my place. I live twenty minutes from the airport," she tells him.' },
    { es: 'Diego acepta la oferta, agradecido. Toma un taxi y llega a la casa de su hermana en media hora.', en: "Diego accepts the offer, grateful. He takes a taxi and arrives at his sister's house in half an hour." },
    { es: 'Su hermana le prepara la cena y hablan de su día horrible en el aeropuerto.', en: 'His sister makes him dinner and they talk about his terrible day at the airport.' },
    { es: '—Mañana vas a tomar el vuelo temprano — dice ella—. Todo va a salir bien.', en: '"Tomorrow you\'re going to take the early flight," she says. "Everything is going to be fine."' },
    { es: 'Diego sonríe, más tranquilo, y prueba la cena de su hermana.', en: "Diego smiles, calmer now, and tries his sister's dinner." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Por qué se cancela el vuelo de Diego?',
        options: ['Por mal tiempo', 'Por un problema técnico', 'Porque no hay pasajeros', 'Porque el avión está lleno'],
        answer: 'Por mal tiempo',
      },
      {
        type: 'multiple_choice',
        prompt: '¿A quién llama Diego para contarle la noticia?',
        options: ['A su hermana', 'A su madre', 'A un amigo', 'A la aerolínea otra vez'],
        answer: 'A su hermana',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le ofrece la hermana de Diego?',
        options: ['Ir a su casa', 'Dinero para un hotel', 'Llevarlo en coche a otro aeropuerto', 'Nada'],
        answer: 'Ir a su casa',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo llega Diego a la casa de su hermana?',
        options: ['En taxi', 'En autobús', 'Caminando', 'En metro'],
        answer: 'En taxi',
      },
      {
        type: 'comprehension',
        prompt: 'What does Diego\'s sister say will happen tomorrow?',
        answer: "he'll take the early flight and everything will be fine",
        altAnswers: ['he takes the early flight', 'everything will be fine', 'he will fly early', 'the early flight'],
      },
    ],
  },
  {
    id: 'la-entrevista',
    written: '2026-07-11',
    title: 'La entrevista',
    level: 'A2',
    format: 'standalone',
    summary: 'Valeria tiene una entrevista de trabajo importante y contesta las preguntas con confianza.',
    paragraphs: [
    { es: 'Valeria tiene una entrevista de trabajo importante hoy. Está muy nerviosa, aunque normalmente es una persona tranquila.', en: "Valeria has an important job interview today. She's very nervous, even though she's normally a calm person." },
    { es: 'Llega a la empresa diez minutos antes. La oficina es moderna, con paredes de vidrio y plantas por todas partes.', en: 'She arrives at the company ten minutes early. The office is modern, with glass walls and plants everywhere.' },
    { es: '—Hola, usted es Valeria, ¿verdad? El director la está esperando — dice un hombre en la recepción.', en: '"Hi, you\'re Valeria, right? The director is waiting for you," says a man at reception.' },
    { es: 'Valeria entra en la oficina del director. Él es un hombre mayor, muy amable.', en: 'Valeria walks into the director\'s office. He is an older man, very kind.' },
    { es: '—Gracias por venir hoy. Conozco su trabajo anterior y me parece excelente — dice el director.', en: '"Thank you for coming today. I know your previous work and I find it excellent," says the director.' },
    { es: '—Gracias. Sé que esta empresa tiene muy buena reputación — contesta Valeria.', en: '"Thank you. I know this company has a very good reputation," answers Valeria.' },
    { es: 'El director le hace muchas preguntas sobre su experiencia. Valeria contesta con confianza, más relajada ahora.', en: 'The director asks her many questions about her experience. Valeria answers with confidence, more relaxed now.' },
    { es: '—Su experiencia es impresionante. También trabaja bien en equipo, según su currículum.', en: '"Your experience is impressive. You also work well in a team, according to your résumé."' },
    { es: '—Sí, me gusta mucho colaborar con otras personas — responde Valeria.', en: '"Yes, I really like collaborating with other people," responds Valeria.' },
    { es: '—La vamos a llamar la próxima semana con la decisión — añade él, ya de pie.', en: '"We\'re going to call you next week with the decision," he adds, now standing.' },
    { es: 'Valeria sale de la oficina, más tranquila que antes, aunque todavía no sabe si consiguió el trabajo.', en: "Valeria leaves the office, calmer than before, although she still doesn't know if she got the job." },
    { es: 'Camina hacia la salida y sonríe.', en: 'She walks toward the exit and smiles.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cómo es Valeria normalmente, según el texto?',
        options: ['Una persona tranquila', 'Una persona muy nerviosa', 'Una persona impuntual', 'Una persona tímida'],
        answer: 'Una persona tranquila',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué sabe el director sobre Valeria antes de la entrevista?',
        options: ['Conoce su trabajo anterior', 'No sabe nada de ella', 'Solo sabe su nombre', 'Conoce a su familia'],
        answer: 'Conoce su trabajo anterior',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué le gusta hacer a Valeria, según ella misma?',
        options: ['Colaborar con otras personas', 'Trabajar sola', 'Viajar por trabajo', 'Dar entrevistas'],
        answer: 'Colaborar con otras personas',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cuándo va a llamar el director a Valeria?',
        options: ['La próxima semana', 'Mañana', 'Esa misma tarde', 'No la va a llamar'],
        answer: 'La próxima semana',
      },
      {
        type: 'comprehension',
        prompt: 'Does Valeria know if she got the job by the end of the story?',
        answer: 'no, she does not know yet',
        altAnswers: ['no', 'not yet', "she doesn't know", 'no she does not know'],
      },
    ],
  },
  {
    id: 'perdidos-en-la-ciudad',
    written: '2026-07-11',
    title: 'Perdidos en la ciudad',
    level: 'A2',
    format: 'standalone',
    summary: 'Dos turistas se pierden en una ciudad desconocida y una mujer amable los ayuda a encontrar su hotel.',
    paragraphs: [
    { es: 'Marina y Luis están de vacaciones en una ciudad que no conocen bien. Caminan sin mapa, solo con una foto de la calle donde está su hotel.', en: "Marina and Luis are on vacation in a city they don't know well. They walk without a map, only with a photo of the street where their hotel is." },
    { es: 'Después de una hora, están completamente perdidos. Ninguna calle se parece a la de la foto.', en: 'After an hour, they are completely lost. No street looks like the one in the photo.' },
    { es: '—Vamos a preguntar a alguien — dice Marina, un poco frustrada.', en: '"Let\'s ask someone," says Marina, a little frustrated.' },
    { es: 'Ven a una mujer que camina un perro cerca de un parque pequeño.', en: 'They see a woman walking a dog near a small park.' },
    { es: '—Perdón, buscamos un hotel que está entre una farmacia y una panadería. ¿Sabe dónde está? — pregunta Luis.', en: '"Excuse me, we\'re looking for a hotel that\'s between a pharmacy and a bakery. Do you know where it is?" asks Luis.' },
    { es: 'La mujer piensa un momento. —Ah, sí. Ese hotel está a diez minutos de aquí, por esa calle — contesta, y señala con la mano.', en: 'The woman thinks for a moment. "Ah, yes. That hotel is ten minutes from here, down that street," she answers, and points with her hand.' },
    { es: '—Tiene que caminar por esta calle, doblar a la izquierda en la esquina, y va a ver el hotel enfrente de una plaza — explica ella.', en: '"You have to walk down this street, turn left at the corner, and you\'ll see the hotel across from a square," she explains.' },
    { es: 'Marina y Luis le dan las gracias y caminan en la dirección correcta.', en: 'Marina and Luis thank her and walk in the right direction.' },
    { es: 'Diez minutos después, ven el hotel exactamente donde la mujer dijo.', en: 'Ten minutes later, they see the hotel exactly where the woman said.' },
    { es: '—Por fin — dice Luis, aliviado—. Esa mujer nos ayudó mucho.', en: '"Finally," says Luis, relieved. "That woman helped us a lot."' },
    { es: 'Entran en el hotel, cansados pero felices. Marina mira hacia la calle una vez más, buscando a la mujer del parque, pero ya no está.', en: 'They walk into the hotel, tired but happy. Marina looks back at the street once more, looking for the woman from the park, but she\'s gone.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Con qué caminan Marina y Luis por la ciudad?',
        options: ['Solo con una foto de la calle', 'Con un mapa', 'Con el teléfono de un amigo', 'Con un guía turístico'],
        answer: 'Solo con una foto de la calle',
      },
      {
        type: 'multiple_choice',
        prompt: '¿A quién le preguntan el camino?',
        options: ['A una mujer que camina un perro', 'A un policía', 'A otro turista', 'A un taxista'],
        answer: 'A una mujer que camina un perro',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde está el hotel, según la descripción de Luis?',
        options: ['Entre una farmacia y una panadería', 'Cerca del parque', 'Al lado del aeropuerto', 'En la plaza principal'],
        answer: 'Entre una farmacia y una panadería',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué deben hacer Marina y Luis para llegar al hotel?',
        options: ['Caminar por la calle y doblar a la izquierda', 'Tomar un autobús', 'Cruzar el parque', 'Doblar a la derecha dos veces'],
        answer: 'Caminar por la calle y doblar a la izquierda',
      },
      {
        type: 'comprehension',
        prompt: 'How does Luis feel when they finally find the hotel?',
        answer: 'relieved',
        altAnswers: ['relief', 'happy and relieved', 'relieved and grateful', 'glad'],
      },
    ],
  },
  {
    id: 'el-partido-importante',
    written: '2026-07-11',
    title: 'El partido importante',
    level: 'A1',
    format: 'standalone',
    summary: 'Diego y su hija Sofía van al estadio a ver el partido de su equipo favorito.',
    paragraphs: [
    { es: 'Diego y su hija Sofía van al estadio el sábado. Su equipo favorito juega un partido importante.', en: 'Diego and his daughter Sofía go to the stadium on Saturday. Their favorite team is playing an important match.' },
    { es: 'Compran dos entradas y buscan sus asientos. El estadio está lleno de aficionados con camisetas azules.', en: 'They buy two tickets and look for their seats. The stadium is full of fans wearing blue jerseys.' },
    { es: '—Papá, ¿cuál es tu jugador favorito? — pregunta Sofía.', en: '"Dad, who\'s your favorite player?" asks Sofía.' },
    { es: '—El número nueve. Corre muy rápido y mete muchos goles — contesta Diego.', en: '"Number nine. He runs very fast and scores a lot of goals," answers Diego.' },
    { es: 'El partido empieza. Los dos equipos juegan muy bien.', en: 'The match begins. Both teams play very well.' },
    { es: 'En el primer tiempo, el otro equipo mete un gol. Los aficionados de Diego y Sofía están tristes.', en: "In the first half, the other team scores a goal. Diego and Sofía's fans are sad." },
    { es: '—No importa. Todavía tenemos el segundo tiempo — dice Diego con una sonrisa.', en: '"It doesn\'t matter. We still have the second half," says Diego with a smile.' },
    { es: 'En el segundo tiempo, el número nueve corre hacia la portería y mete un gol.', en: 'In the second half, number nine runs toward the goal and scores.' },
    { es: 'Todos los aficionados gritan de alegría. Sofía salta de su asiento y abraza a su papá.', en: 'All the fans shout with joy. Sofía jumps out of her seat and hugs her dad.' },
    { es: 'El partido termina, uno a uno. —¡Qué partido! — dice Diego.', en: 'The match ends, one to one. "What a match!" says Diego.' },
    { es: 'Sofía guarda la entrada en su mochila. Quiere recordar este día para siempre.', en: 'Sofía keeps the ticket in her backpack. She wants to remember this day forever.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Con quién va Diego al estadio?',
        options: ['Con su hija Sofía', 'Con su esposa', 'Con un amigo', 'Solo'],
        answer: 'Con su hija Sofía',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Quién mete el primer gol del partido?',
        options: ['El otro equipo', 'El número nueve', 'Sofía', 'Nadie'],
        answer: 'El otro equipo',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace Sofía cuando su equipo mete un gol?',
        options: ['Salta de su asiento y abraza a su papá', 'Llora', 'Se va del estadio', 'Duerme'],
        answer: 'Salta de su asiento y abraza a su papá',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo termina el partido?',
        options: ['Uno a uno', 'Dos a cero', 'Cero a cero', 'Tres a uno'],
        answer: 'Uno a uno',
      },
      {
        type: 'comprehension',
        prompt: 'What does Sofía do with the ticket at the end of the story?',
        answer: 'keeps it in her backpack',
        altAnswers: ['puts it in her backpack', 'saves it in her backpack', 'keeps the ticket in her bag'],
      },
    ],
  },
  {
    id: 'la-tienda-de-flores',
    written: '2026-07-11',
    title: 'La tienda de flores',
    level: 'A1',
    format: 'standalone',
    summary: 'Carmen abre su propia tienda de flores en el barrio — su primer día como dueña.',
    paragraphs: [
    { es: 'Carmen tiene un sueño: abrir su propio negocio. Hoy abre su tienda de flores por primera vez.', en: "Carmen has a dream: to open her own business. Today she opens her flower shop for the first time." },
    { es: 'La tienda está en una calle tranquila, entre una farmacia y una panadería.', en: "The shop is on a quiet street, between a pharmacy and a bakery." },
    { es: 'Carmen decora la ventana con flores de muchos colores.', en: 'Carmen decorates the window with flowers of many colors.' },
    { es: 'A las diez de la mañana, llega la primera clienta.', en: 'At ten in the morning, the first customer arrives.' },
    { es: '—Buenos días. Busco un ramo para el cumpleaños de mi madre — dice la mujer.', en: '"Good morning. I\'m looking for a bouquet for my mother\'s birthday," says the woman.' },
    { es: '—Tengo flores de muchos colores. ¿Cuál es su color favorito? — pregunta Carmen.', en: '"I have flowers of many colors. What\'s her favorite color?" asks Carmen.' },
    { es: '—El amarillo — contesta la clienta.', en: '"Yellow," answers the customer.' },
    { es: 'Carmen prepara un ramo bonito con flores amarillas y blancas. La clienta paga y sonríe.', en: 'Carmen prepares a pretty bouquet with yellow and white flowers. The customer pays and smiles.' },
    { es: 'Durante el día, muchas personas del barrio visitan la tienda nueva. Todos quieren ver las flores nuevas.', en: "During the day, many people from the neighborhood visit the new shop. Everyone wants to see the new flowers." },
    { es: 'Por la noche, Carmen cierra la tienda. Guarda las monedas del día en una caja pequeña y apaga la luz.', en: "At night, Carmen closes the shop. She puts the day's coins in a small box and turns off the light." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Qué tipo de tienda abre Carmen?',
        options: ['Una tienda de flores', 'Una panadería', 'Una farmacia', 'Una tienda de ropa'],
        answer: 'Una tienda de flores',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Dónde está la tienda de Carmen?',
        options: ['Entre una farmacia y una panadería', 'Cerca del estadio', 'En el centro del barrio', 'Al lado de un banco'],
        answer: 'Entre una farmacia y una panadería',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué busca la primera clienta?',
        options: ['Un ramo para el cumpleaños de su madre', 'Flores para su casa', 'Un regalo para su hija', 'Flores amarillas para ella'],
        answer: 'Un ramo para el cumpleaños de su madre',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace Carmen antes de cerrar la tienda?',
        options: ['Guarda las monedas y apaga la luz', 'Llama a su madre', 'Compra más flores', 'Habla con un vecino'],
        answer: 'Guarda las monedas y apaga la luz',
      },
      {
        type: 'comprehension',
        prompt: "What color flowers does the first customer's mother like?",
        answer: 'yellow',
        altAnswers: ['yellow flowers'],
      },
    ],
  },
  {
    id: 'el-telefono-nuevo',
    written: '2026-07-11',
    title: 'El teléfono nuevo',
    level: 'A1',
    format: 'standalone',
    summary: 'Mateo estrena un teléfono nuevo. Su hermana Valentina ayuda con la configuración.',
    paragraphs: [
    { es: 'Mateo llega a casa con un teléfono nuevo. Es su primer teléfono con una pantalla grande.', en: "Mateo arrives home with a new phone. It's his first phone with a big screen." },
    { es: '—¿Me ayudas con el teléfono? — pregunta Mateo a su hermana Valentina.', en: '"Can you help me with the phone?" Mateo asks his sister Valentina.' },
    { es: '—Claro. Primero necesitamos wifi — contesta ella, y escribe la contraseña en la pantalla.', en: '"Sure. First we need wifi," she answers, and types the password on the screen.' },
    { es: 'Mientras el teléfono carga, los dos hermanos hablan de la escuela y de sus amigos.', en: 'While the phone charges, the two siblings talk about school and their friends.' },
    { es: 'Después de una hora, el teléfono está listo. Mateo descarga una aplicación de música y otra de fotos.', en: 'After an hour, the phone is ready. Mateo downloads a music app and a photo app.' },
    { es: '—Vamos a tomar una foto juntos — dice Valentina, y busca un lugar con buena luz.', en: '"Let\'s take a photo together," says Valentina, and looks for a spot with good light.' },
    { es: 'Mateo toca la pantalla y toma la primera foto de los dos. Sale un poco borrosa, y los dos se ríen.', en: 'Mateo taps the screen and takes the first photo of the two of them. It comes out a little blurry, and they both laugh.' },
    { es: 'Prueban otra vez, y la segunda foto es muy buena.', en: 'They try again, and the second photo is very good.' },
    { es: 'Esa noche, Mateo manda la foto a sus amigos con su teléfono nuevo.', en: 'That night, Mateo sends the photo to his friends with his new phone.' },
    { es: 'Guarda el teléfono en la mesa, cerca de la cama, listo para mañana.', en: 'He puts the phone on the table, near the bed, ready for tomorrow.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Quién ayuda a Mateo con el teléfono?',
        options: ['Su hermana Valentina', 'Su madre', 'Un amigo', 'Nadie, lo hace solo'],
        answer: 'Su hermana Valentina',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué necesitan primero para configurar el teléfono?',
        options: ['Wifi', 'Una aplicación de música', 'Una batería nueva', 'Un mensaje'],
        answer: 'Wifi',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cómo sale la primera foto?',
        options: ['Un poco borrosa', 'Perfecta', 'Muy oscura', 'No sale'],
        answer: 'Un poco borrosa',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hacen los hermanos mientras el teléfono carga?',
        options: ['Hablan de la escuela y de sus amigos', 'Miran una película', 'Duermen', 'Salen de casa'],
        answer: 'Hablan de la escuela y de sus amigos',
      },
      {
        type: 'comprehension',
        prompt: 'What does Mateo do with the photo that night?',
        answer: 'sends it to his friends',
        altAnswers: ['sends the photo to his friends', 'mails it to his friends', 'shares it with his friends'],
      },
    ],
  },
  {
    id: 'las-elecciones-del-barrio',
    written: '2026-07-11',
    title: 'Las elecciones del barrio',
    level: 'A1',
    format: 'standalone',
    summary: 'Hoy hay elecciones en el barrio de Rosa, y ella decide por quién votar.',
    paragraphs: [
    { es: 'Hoy hay elecciones en el barrio de Rosa. Cada dos años, los vecinos eligen un representante nuevo.', en: "Today there are elections in Rosa's neighborhood. Every two years, the neighbors elect a new representative." },
    { es: 'Este año, hay dos candidatos: el señor Aguilar y la señora Reyes.', en: 'This year, there are two candidates: Mr. Aguilar and Mrs. Reyes.' },
    { es: 'Rosa camina hasta el centro del barrio a las nueve de la mañana.', en: 'Rosa walks to the neighborhood center at nine in the morning.' },
    { es: 'En la puerta, hay una mesa con papeles y una caja grande.', en: 'At the door, there is a table with papers and a big box.' },
    { es: '—Buenos días. ¿Ya sabe por quién va a votar? — pregunta un vecino a Rosa.', en: '"Good morning. Do you already know who you\'re going to vote for?" a neighbor asks Rosa.' },
    { es: '—Todavía no. Primero quiero leer sobre los dos candidatos — contesta ella.', en: '"Not yet. First I want to read about the two candidates," she answers.' },
    { es: 'Rosa lee la información en la pared: el señor Aguilar quiere parques nuevos, mientras la señora Reyes prefiere una biblioteca nueva.', en: 'Rosa reads the information on the wall: Mr. Aguilar wants new parks, while Mrs. Reyes prefers a new library.' },
    { es: 'Rosa piensa un momento, marca su papel, y pone el papel doblado en la caja.', en: 'Rosa thinks for a moment, marks her paper, and puts the folded paper in the box.' },
    { es: '—Gracias por votar — dice una mujer en la mesa.', en: '"Thank you for voting," says a woman at the table.' },
    { es: 'Afuera, varios vecinos hacen fila para votar también.', en: 'Outside, several neighbors are lining up to vote too.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cada cuánto tiempo eligen los vecinos un representante nuevo?',
        options: ['Cada dos años', 'Cada año', 'Cada mes', 'Cada cuatro años'],
        answer: 'Cada dos años',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cuántos candidatos hay este año?',
        options: ['Dos', 'Uno', 'Tres', 'Cuatro'],
        answer: 'Dos',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace Rosa antes de votar?',
        options: ['Lee sobre los dos candidatos', 'Habla con el señor Aguilar', 'Pregunta a sus vecinos', 'Se va a casa'],
        answer: 'Lee sobre los dos candidatos',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué prefiere la señora Reyes?',
        options: ['Una biblioteca nueva', 'Parques nuevos', 'Un estadio nuevo', 'Una tienda nueva'],
        answer: 'Una biblioteca nueva',
      },
      {
        type: 'comprehension',
        prompt: 'What are the other neighbors doing outside, at the end of the story?',
        answer: 'lining up to vote',
        altAnswers: ['waiting in line to vote', 'standing in line to vote', 'forming a line to vote'],
      },
    ],
  },
  {
    id: 'el-concierto-de-luna-rios',
    written: '2026-07-11',
    title: 'El concierto de Luna Ríos',
    level: 'A1',
    format: 'standalone',
    summary: 'Valentina va al concierto de su cantante favorita con su amiga Camila.',
    paragraphs: [
    { es: 'Valentina tiene la entrada del concierto de Luna Ríos desde hace tres meses. Hoy es el día.', en: "Valentina has had the ticket to Luna Ríos's concert for three months. Today is the day." },
    { es: 'Valentina y su amiga Camila llegan al estadio dos horas antes. Ya hay una fila muy larga.', en: 'Valentina and her friend Camila arrive at the stadium two hours early. There is already a very long line.' },
    { es: '—¡Estoy muy emocionada! — dice Valentina, y salta de alegría.', en: '"I\'m so excited!" says Valentina, and jumps with joy.' },
    { es: 'Después de esperar, las dos amigas entran y buscan sus asientos.', en: 'After waiting, the two friends go in and look for their seats.' },
    { es: 'A las ocho, apagan las luces y la música empieza. Luna Ríos camina hacia el escenario.', en: 'At eight, they turn off the lights and the music starts. Luna Ríos walks toward the stage.' },
    { es: 'El público grita y canta cada canción con ella.', en: 'The audience shouts and sings every song with her.' },
    { es: '—¡Esta es mi canción favorita! — grita Camila, y canta muy fuerte.', en: '"This is my favorite song!" shouts Camila, and sings very loudly.' },
    { es: 'Durante dos horas, Luna Ríos canta muchas canciones diferentes.', en: 'For two hours, Luna Ríos sings many different songs.' },
    { es: 'Al final, Valentina compra una camiseta del concierto. Se pone la camiseta esa misma noche.', en: 'At the end, Valentina buys a concert t-shirt. She puts it on that same night.' },
    { es: 'Vuelve a casa con la camiseta puesta y la voz un poco ronca de tanto cantar.', en: 'She goes home wearing the t-shirt, her voice a little hoarse from all the singing.' },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cuánto tiempo hace que Valentina tiene la entrada del concierto?',
        options: ['Tres meses', 'Una semana', 'Un año', 'Un mes'],
        answer: 'Tres meses',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hace el público durante el concierto?',
        options: ['Grita y canta cada canción', 'Se queda en silencio', 'Se va temprano', 'Duerme'],
        answer: 'Grita y canta cada canción',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Cuánto tiempo canta Luna Ríos?',
        options: ['Dos horas', 'Una hora', 'Treinta minutos', 'Toda la noche'],
        answer: 'Dos horas',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué compra Valentina al final del concierto?',
        options: ['Una camiseta', 'Un disco', 'Una foto', 'Un póster'],
        answer: 'Una camiseta',
      },
      {
        type: 'comprehension',
        prompt: 'Why is Valentina\'s voice a little hoarse on the way home?',
        answer: 'from singing so much',
        altAnswers: ['from all the singing', 'because she sang so much', 'she sang too much at the concert'],
      },
    ],
  },
  {
    id: 'el-parque-nuevo-del-barrio',
    written: '2026-07-11',
    title: 'El parque nuevo del barrio',
    level: 'A1',
    format: 'standalone',
    summary: 'La ciudad construye un parque nuevo, y hoy es el día de la inauguración.',
    paragraphs: [
    { es: 'Hace un mes, la ciudad empieza a construir un parque nuevo cerca de la casa de Iván.', en: "A month ago, the city starts building a new park near Iván's house." },
    { es: 'Todos los días, Iván camina por la calle y mira el parque nuevo. Hay muchos trabajadores.', en: 'Every day, Iván walks down the street and watches the new park. There are many workers.' },
    { es: 'Por fin, hoy es el día de la inauguración. El parque está listo.', en: "Finally, today is opening day. The park is ready." },
    { es: 'Iván camina hasta el parque con su perro. Está curioso por ver el parque terminado.', en: 'Iván walks to the park with his dog. He is curious to see the finished park.' },
    { es: 'El parque tiene árboles nuevos, una fuente grande y un lugar para niños.', en: 'The park has new trees, a big fountain, and a place for children.' },
    { es: 'Muchos vecinos del barrio caminan por el parque también. Dos niños ya suben a un árbol nuevo.', en: 'Many neighbors from the area walk through the park too. Two children are already climbing a new tree.' },
    { es: '—Este parque es perfecto para el barrio — dice una vecina a Iván.', en: '"This park is perfect for the neighborhood," a neighbor says to Iván.' },
    { es: 'Iván sonríe y se sienta en un banco nuevo.', en: 'Iván smiles and sits down on a new bench.' },
    { es: 'Su perro corre por la hierba, y varios niños juegan cerca de la fuente.', en: 'His dog runs through the grass, and several children play near the fountain.' },
    { es: 'El sol empieza a bajar, pero Iván no quiere irse todavía.', en: "The sun starts to go down, but Iván doesn't want to leave yet." },
    ],
    questions: [
      {
        type: 'multiple_choice',
        prompt: '¿Cuánto tiempo tarda la ciudad en construir el parque?',
        options: ['Un mes', 'Una semana', 'Un año', 'Dos meses'],
        answer: 'Un mes',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Con quién camina Iván hasta el parque nuevo?',
        options: ['Con su perro', 'Con su hermana', 'Con un vecino', 'Solo'],
        answer: 'Con su perro',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué tiene el parque nuevo?',
        options: ['Árboles, una fuente y un lugar para niños', 'Solo árboles', 'Una tienda y un banco', 'Un estadio pequeño'],
        answer: 'Árboles, una fuente y un lugar para niños',
      },
      {
        type: 'multiple_choice',
        prompt: '¿Qué hacen los niños en el parque?',
        options: ['Suben a un árbol y juegan cerca de la fuente', 'Duermen en un banco', 'Buscan a Iván', 'Corren hacia la calle'],
        answer: 'Suben a un árbol y juegan cerca de la fuente',
      },
      {
        type: 'comprehension',
        prompt: 'What is the sun doing at the end of the story?',
        answer: 'going down',
        altAnswers: ['setting', 'starting to set', 'starting to go down'],
      },
    ],
  },
];

export function getPassage(id) {
  return PASSAGES.find(p => p.id === id) ?? null;
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

// Formats a `written` ISO date ('YYYY-MM-DD') for display. Parses the
// string directly rather than going through `new Date(iso)` +
// toLocaleDateString — the latter parses as UTC midnight and can render as
// the *previous* day in negative-UTC-offset timezones once the browser
// converts it back to local time.
export function formatWrittenDate(iso) {
  if (!iso) return null;
  const [y, m, d] = iso.split('-').map(Number);
  return `${MONTH_NAMES[m - 1]} ${d}, ${y}`;
}

// For a story-format passage, finds the immediately adjacent chapter (by
// chapter number) of the same story, if one exists — powers the prev/next
// chapter links on the passage page. Returns null for standalone passages
// or when there's no adjacent chapter (first/last in the story so far).
export function getAdjacentChapter(passage, direction) {
  if (!passage?.story) return null;
  const targetChapter = passage.chapter + (direction === 'next' ? 1 : -1);
  return PASSAGES.find(p => p.story === passage.story && p.chapter === targetChapter) ?? null;
}
