// Regional Spanish differences — Spain (Castilian) vs Latin America
// Organised by category with side-by-side comparisons

export const REGIONAL_SECTIONS = [
  {
    id: 'vosotros',
    category: 'Pronouns',
    title: 'Vosotros vs. Ustedes',
    summary: 'Spain uses vosotros (informal plural "you"); Latin America uses ustedes for both formal and informal.',
    comparisons: [
      { context: 'Talking to friends (plural)',        spain: 'Vosotros tenéis razón.', latam: 'Ustedes tienen razón.' },
      { context: 'Asking friends (plural)',             spain: '¿Adónde vais?',         latam: '¿Adónde van?' },
      { context: 'Imperative (plural informal)',        spain: '¡Comed despacio!',       latam: '¡Coman despacio!' },
      { context: 'Reflexive (plural informal)',         spain: 'Sentaos.',               latam: 'Siéntense.' },
    ],
    tip: 'If you learn vosotros, you\'ll be understood everywhere. If you skip it, use ustedes — Latin Americans never use vosotros.',
  },
  {
    id: 'vos',
    category: 'Pronouns',
    title: 'Vos (Argentina, Uruguay, Central America)',
    summary: 'In Argentina, Uruguay, and much of Central America, vos replaces tú. It has its own conjugation.',
    comparisons: [
      { context: 'Present (hablar)',   spain: 'tú hablas',    latam: 'vos hablás (AR/UY)' },
      { context: 'Present (tener)',    spain: 'tú tienes',    latam: 'vos tenés' },
      { context: 'Present (ir)',       spain: 'tú vas',       latam: 'vos vas (same)' },
      { context: 'Present (ser)',      spain: 'tú eres',      latam: 'vos sos' },
      { context: 'Imperative',        spain: 'habla (tú)',    latam: 'hablá (vos)' },
    ],
    tip: 'Vos conjugation: drop the -r from infinitive, add stress on final syllable — habla→hablás, tene→tenés, veni→venís.',
  },
  {
    id: 'pronunciation',
    category: 'Pronunciation',
    title: 'Seseo, Ceceo & Distinción',
    summary: 'Spain (most regions) distinguishes s/z sounds. Latin America uses seseo — c/z are pronounced like s.',
    comparisons: [
      { context: 'zapato (shoe)',   spain: 'tha-PAH-toh (z=θ)',     latam: 'sah-PAH-toh (z=s)' },
      { context: 'cerveza (beer)', spain: 'ther-VEH-tha',           latam: 'ser-VEH-sah' },
      { context: 'gracias',        spain: 'GRAH-thyahs',            latam: 'GRAH-syahs' },
      { context: 'ciudad',         spain: 'thyoo-DAHD',             latam: 'syoo-DAHD' },
    ],
    tip: 'Southern Spain (Andalucía) and the Canary Islands use seseo like Latin America. Only central/northern Spain uses the θ sound.',
  },
  {
    id: 'll_y',
    category: 'Pronunciation',
    title: 'Lleísmo vs. Yeísmo',
    summary: 'Most of Latin America (and much of Spain) merges ll and y into the same sound (yeísmo). Rio Plata Spanish (Argentina/Uruguay) pronounces both like "sh" or "zh".',
    comparisons: [
      { context: 'llover (to rain)',   spain: 'ʎo-VER (traditional)', latam: 'yo-VER (most) / sho-VER (AR)' },
      { context: 'yo (I)',             spain: 'yo',                    latam: 'yo / sho (AR/UY)' },
      { context: 'pollo (chicken)',    spain: 'POH-ʎo',               latam: 'POH-yo / POH-sho (AR)' },
      { context: 'calle (street)',     spain: 'KAH-ʎe',               latam: 'KAH-ye / KAH-she (AR)' },
    ],
    tip: 'Argentina\'s distinctive "sh" sound (sheísmo) is one of the most recognisable accents in Spanish.',
  },
  {
    id: 'perfecto_preterite',
    category: 'Grammar',
    title: 'Present Perfect vs. Preterite',
    summary: 'Spain uses the present perfect (he comido) for recent past events. Latin America uses the preterite (comí) for the same situations.',
    comparisons: [
      { context: 'I already ate',         spain: 'Ya he comido.',         latam: 'Ya comí.' },
      { context: 'I saw him today',       spain: 'Le he visto hoy.',      latam: 'Lo vi hoy.' },
      { context: 'She just arrived',      spain: 'Acaba de llegar / Ha llegado.', latam: 'Llegó.' },
      { context: 'We\'ve finished',       spain: 'Ya hemos terminado.',   latam: 'Ya terminamos.' },
    ],
    tip: 'This is one of the biggest grammar differences. In Latin America, the preterite does the heavy lifting even for very recent events.',
  },
  {
    id: 'le_lo',
    category: 'Grammar',
    title: 'Leísmo (Spain)',
    summary: 'In Spain, le is often used instead of lo as a direct object pronoun when the referent is a male person. Latin America follows the standard lo rule.',
    comparisons: [
      { context: 'I saw him (a man)',  spain: 'Le vi. (leísmo, accepted)', latam: 'Lo vi.' },
      { context: 'I called him',      spain: 'Le llamé.',                  latam: 'Lo llamé.' },
      { context: 'I met him',         spain: 'Le conocí.',                 latam: 'Lo conocí.' },
    ],
    tip: 'RAE officially accepts personal leísmo in Spain. In Latin America le is strictly for indirect objects only.',
  },
  {
    id: 'vocab_common',
    category: 'Vocabulary',
    title: 'Common vocabulary differences',
    summary: 'Many everyday words differ between Spain and Latin America. Neither is wrong — they\'re regional standards.',
    comparisons: [
      { context: 'Car',            spain: 'el coche',       latam: 'el carro / el auto' },
      { context: 'Computer',       spain: 'el ordenador',   latam: 'la computadora / el computador' },
      { context: 'Mobile phone',   spain: 'el móvil',       latam: 'el celular' },
      { context: 'Apartment',      spain: 'el piso',        latam: 'el apartamento / el departamento' },
      { context: 'Potato',         spain: 'la patata',      latam: 'la papa' },
      { context: 'Bus',            spain: 'el autobús',     latam: 'el camión (MX) / la micro (CL) / el colectivo (AR)' },
      { context: 'Pen',            spain: 'el bolígrafo (boli)', latam: 'la pluma (MX) / el lapicero (PE) / la birome (AR)' },
      { context: 'Juice',          spain: 'el zumo',        latam: 'el jugo' },
      { context: 'Popcorn',        spain: 'las palomitas',  latam: 'las pochoclos (AR) / las cotufas (VE) / el popcorn (MX)' },
      { context: 'Swimming pool',  spain: 'la piscina',     latam: 'la pileta (AR) / la alberca (MX) / la piscina' },
    ],
    tip: 'Latin America itself has significant internal variation — Mexican, Argentine, and Colombian Spanish all differ from each other.',
  },
  {
    id: 'slang_spain',
    category: 'Vocabulary',
    title: 'Spanish slang (Spain)',
    summary: 'Common colloquial expressions from Spain that may not be understood in Latin America.',
    comparisons: [
      { context: 'Cool / great',    spain: 'mola / guay / chachi',  latam: 'chévere (VE/CO) / bacán (AR) / padre (MX)' },
      { context: 'Kid',             spain: 'chaval/a',              latam: 'chico/a / pibe (AR) / chamaco (MX)' },
      { context: 'Drunk',           spain: 'borracho / pedo',       latam: 'borracho / cuete (MX)' },
      { context: 'Money',           spain: 'pasta / guita',         latam: 'plata / lana (MX)' },
      { context: 'Friend',          spain: 'tío/tía (informal)',    latam: 'mano/a (MX) / pana (VE) / che (AR)' },
      { context: 'Party',           spain: 'juerga / fiesta',       latam: 'fiesta / pachanga' },
    ],
    tip: 'Tío/tía in Spain = mate/pal (not aunt/uncle in slang context). In Latin America calling someone tío still just means aunt/uncle.',
  },
  {
    id: 'tuteo',
    category: 'Grammar',
    title: 'Imperative: tú commands',
    summary: 'Informal (tú) imperatives work the same across most regions, but vos imperatives in Argentina/Uruguay differ.',
    comparisons: [
      { context: 'Speak! (hablar)', spain: '¡Habla! (tú)',       latam: '¡Hablá! (vos AR/UY) · ¡Habla! (tú elsewhere)' },
      { context: 'Come! (venir)',   spain: '¡Ven! (tú)',         latam: '¡Vení! (vos) · ¡Ven! (tú)' },
      { context: 'Go! (ir)',        spain: '¡Ve! / ¡Vete!',      latam: '¡Andá! (vos AR) · ¡Ve! (tú)' },
      { context: 'Sit! (sentar)',   spain: '¡Siéntate!',         latam: '¡Sentate! (vos) · ¡Siéntate! (tú)' },
    ],
    tip: 'Vos imperatives: drop the -r and add a stress accent — habla→hablá, veni→vení, senti→sentite.',
  },
  {
    id: 'caribbean',
    category: 'Pronunciation',
    title: 'Caribbean Spanish — consonant weakening',
    summary: 'Cuban, Dominican, and Puerto Rican Spanish weaken or drop final consonants. S before a consonant or at the end of a word is often aspirated to /h/ or dropped entirely.',
    comparisons: [
      { context: 'estos (these)',          spain: 'ES-tos',              latam: 'EH-toh (Caribbean: s→h or silent)' },
      { context: 'más (more)',             spain: 'más',                 latam: 'máh / má (Caribbean)' },
      { context: 'hablar (to speak)',      spain: 'ha-BLAR',             latam: 'ha-BLAH (Caribbean: final r weakens)' },
      { context: 'verdad (truth)',         spain: 'ver-DAHD',            latam: 'ver-DÁ (Caribbean: final d drops)' },
      { context: 'Puerto Rico (R)',        spain: 'strong trill /r/',    latam: 'Puerto Rico: /r/ often velar (like French r)' },
    ],
    tip: 'Caribbean speech is faster and more "musical" than Castilian. Learners often find Caribbean speakers hard to understand at first — exposure is the only fix.',
  },
  {
    id: 'mexico_vocab',
    category: 'Vocabulary',
    title: 'Mexican Spanish — unique vocabulary',
    summary: 'Mexico has a rich vocabulary influenced by Nahuatl (the Aztec language) and local slang. Many words are unknown outside Mexico.',
    comparisons: [
      { context: 'OK / sure',               spain: 'vale / de acuerdo',      latam: 'órale (MX — informal, also "hurry up!")' },
      { context: 'Kid / child',             spain: 'niño/a, chaval',         latam: 'chamaco/a, escuincle (MX, informal)' },
      { context: 'Annoying / pain',         spain: 'pesado/a, plomo',        latam: 'fregón (MX — also means "awesome" in positive context!)' },
      { context: 'Avocado',                 spain: 'aguacate',               latam: 'aguacate (most) / palta (AR, CL, PE)' },
      { context: 'Chilli / hot pepper',     spain: 'guindilla, chile',       latam: 'chile (MX), ají (South America)' },
      { context: 'To eat / gobble up',      spain: 'comer',                  latam: 'jalar / jamar (MX slang for eating)' },
      { context: 'Cool / great (slang)',    spain: 'guay / mola',            latam: 'padre / chido (MX), chévere (VE/CO), copado (AR)' },
      { context: 'A bit / a little',        spain: 'un poco',                latam: 'tantito (MX diminutive — very soft/affectionate)' },
    ],
    tip: 'Many Mexican words come from Nahuatl: chocolate, tomate, aguacate, chile, cacahuate (peanut), copal, nopal. These words entered world languages via Mexico.',
  },
  {
    id: 'diminutives_regional',
    category: 'Grammar',
    title: 'Diminutives — frequency by region',
    summary: 'Spanish uses diminutive suffixes (-ito/a, -illo/a, -ico/a) to indicate small size, affection, or politeness. Their frequency and preferred form vary sharply by region.',
    comparisons: [
      { context: 'Little table',          spain: 'mesita / mesilla',       latam: 'mesita (most of LatAm)' },
      { context: 'A moment (just a sec)', spain: 'un momentito',           latam: 'un momentico (CO/VE) · un momentito (everywhere)' },
      { context: 'Right now (softer)',    spain: 'ahorita (rare)',          latam: 'ahorita (MX — common; means "very soon" to some, "right now" to others)' },
      { context: 'Diminutive suffix',     spain: '-ito/a most common',     latam: '-ico/a (CO/VE/CR/CU); -ito/a elsewhere' },
    ],
    tip: '"Ahorita" in Mexico is famously ambiguous — it can mean right now, soon, or eventually. Context and tone determine which. If you need something immediately, say "ahora mismo."',
  },
  {
    id: 'ser_estar_regional',
    category: 'Grammar',
    title: 'Ser/estar regional usage drift',
    summary: 'While the core ser/estar distinction is stable, some regions use estar where Spain prefers ser, and vice versa.',
    comparisons: [
      { context: 'He is dead',            spain: 'Está muerto.',            latam: 'Está muerto. (same everywhere)' },
      { context: 'It\'s delicious',       spain: 'Está bueno/rico.',        latam: 'Está buenísimo. (same; but MX may say "está muy rico")' },
      { context: 'Where is the party?',   spain: 'La fiesta es en casa.',   latam: 'La fiesta es / está en casa. (both used in LatAm)' },
      { context: 'He\'s nervous (trait)', spain: 'Él es nervioso.',         latam: 'Some speakers use "está nervioso" as a quasi-trait in informal speech' },
    ],
    tip: 'The fundamental PERMANENT (ser) vs TEMPORARY (estar) rule holds everywhere, but boundary cases vary. When in doubt, follow the traditional rule — you\'ll always be understood.',
  },
  {
    id: 'chile_vocab',
    category: 'Vocabulary',
    title: 'Chilean Spanish — vocabulary & slang',
    summary: 'Chilean Spanish is known for its fast pace, heavily reduced syllables, and unique slang. Many Chilean words are unintelligible to other Spanish speakers at first.',
    comparisons: [
      { context: 'Great / cool',             spain: 'guay / mola',         latam: 'bacán (CL/PE) — "¡Qué bacán!"' },
      { context: 'Boyfriend/girlfriend',     spain: 'novio / novia',       latam: 'pololo / polola (CL) — used at all ages' },
      { context: 'To understand / get it',   spain: 'entender',            latam: 'cachar (CL) — borrowed from English "to catch"' },
      { context: 'Boring / lame',            spain: 'aburrido / soso',     latam: 'fome (CL) — "Esa película es muy fome."' },
      { context: 'Right away / immediately', spain: 'enseguida / ahora',   latam: 'altiro (CL) — from "al tiro" (lit. "at the shot")' },
      { context: 'Dude (informal, m)',       spain: 'tío',                 latam: 'huevón / weon (CL) — very informal; neutral or friendly among peers' },
      { context: 'Bus',                      spain: 'autobús',             latam: 'micro (CL), colectivo (AR), camión (MX)' },
      { context: 'Apartment',               spain: 'piso',                latam: 'departamento (CL/MX/AR), apartamento (CO/VE)' },
    ],
    tip: 'Chilean pronunciation drops syllables heavily: "para" → "pa\'", "está" → "tá", "ustedes" → "ustés". The letter d often disappears between vowels: "cansado" → "cansao", "todo" → "tó".',
  },
  {
    id: 'food_regional',
    category: 'Vocabulary',
    title: 'Food — names vary by country',
    summary: 'Common foods have different names across the Spanish-speaking world. Using the Spanish term in Latin America (or vice versa) can cause confusion.',
    comparisons: [
      { context: 'Tortilla',          spain: 'tortilla = potato omelette',           latam: 'tortilla = flatbread / wrap (MX); omelette is tortilla de huevos' },
      { context: 'Avocado',           spain: 'aguacate',                             latam: 'palta (AR, CL, PE, BO) — aguacate elsewhere' },
      { context: 'Sweetcorn / maize', spain: 'maíz (grain), mazorca (cob)',          latam: 'choclo (South America), elote (MX)' },
      { context: 'Cake',              spain: 'tarta',                                latam: 'torta (AR, MX); pastel (MX, CO); queque (CL)' },
      { context: 'Peas',              spain: 'guisantes',                            latam: 'chícharos (MX), arvejas (South America)' },
      { context: 'Peach',             spain: 'melocotón',                            latam: 'durazno (most of LatAm)' },
      { context: 'Drinking straw',    spain: 'pajita / cañita',                      latam: 'popote (MX), pitillo (CO/VE), sorbete (some)' },
      { context: 'Potato',            spain: 'patata',                               latam: 'papa (all of LatAm — also in the Canary Islands)' },
    ],
    tip: 'The tortilla confusion trips up every learner. In Spain, "una tortilla" is always a potato omelette unless specified otherwise. In Mexico, it\'s always a flatbread — the omelette is "tortilla de huevos" or simply "huevos revueltos".',
  },
  {
    id: 'colombia_usted',
    category: 'Pronouns',
    title: 'Colombia — usted used with family and friends',
    summary: 'In Colombia (especially Bogotá, Medellín, and Antioquia), usted is used routinely between close friends and family — including between parents and children. This contrasts sharply with Spain and most other Latin American countries.',
    comparisons: [
      { context: 'Parents to children',    spain: '¿Qué quieres tú, cariño?',         latam: '¿Qué quiere usted, mi amor? (CO — affectionate)' },
      { context: 'Between close friends',  spain: 'Oye, ¿tú qué piensas?',            latam: 'Oiga, ¿usted qué piensa? (CO — friendly)' },
      { context: 'Couple (informal)',       spain: '¿A dónde quieres ir tú?',          latam: '¿A dónde quiere ir usted? (CO)' },
      { context: 'Older person to youth',  spain: 'tú (most of Spain)',               latam: 'usted (CO — mark of care, not distance)' },
    ],
    tip: 'In Colombia, usted does NOT mean you are being formal or cold. It can be deeply affectionate. "Lo quiero mucho, usted sabe" said by a Colombian parent to their child is warm and loving. Don\'t be startled if a new Colombian friend immediately addresses you with usted.',
  },
  {
    id: 'rioplatense_intonation',
    category: 'Pronunciation',
    title: 'Río de la Plata — Italian-influenced intonation',
    summary: 'Argentine and Uruguayan Spanish (Rioplatense) has a distinctive musical rise-and-fall intonation inherited from massive Italian immigration in the 19th and 20th centuries. It sounds noticeably different from both Castilian and other Latin American varieties.',
    comparisons: [
      { context: 'Question intonation',   spain: 'flat or mild rise — ¿Dónde vas?',   latam: 'strong rise then fall — ¿Dónde VAS? (AR — Italian-like)' },
      { context: 'Sentence melody',       spain: 'relatively flat, final fall',        latam: 'rhythmic stress peaks, more melodic (AR/UY)' },
      { context: 'Italian loanwords',     spain: 'N/A',                                latam: 'laburo (work ← Italian lavoro), pibe (kid ← Italian pive), mina (woman)' },
      { context: 'Word shortening',       spain: 'la peli, la bici, la tele',          latam: 'same + el faso (cigarette), el bondi (bus ← "bondinho"), el coso (thing)' },
      { context: 'sh/zh sound',           spain: 'll = /ʎ/ or /j/',                   latam: 'll = /ʃ/ (sh) or /ʒ/ (zh) in AR/UY — "yo" sounds like "sho"' },
    ],
    tip: 'Argentine Spanish sounds "Italian" to other Spanish speakers — and that\'s not accidental. Buenos Aires received massive Italian immigration. An estimated 60% of Argentines have Italian ancestry. The intonation, some vocabulary, and even gestures reflect this heritage.',
  },
];

export const CATEGORIES = [...new Set(REGIONAL_SECTIONS.map(s => s.category))];
