// Spanish verb conjugation tables — 60 key verbs (regular, stem-changing, irregular), A1–B2

export const VERB_TYPES = ['irregular', 'stem-changing', 'reflexive', 'regular'];
export const TENSES = ['present', 'preterite', 'imperfect', 'future', 'conditional', 'subjunctive'];
export const TENSE_LABELS = {
  present: 'Present', preterite: 'Preterite', imperfect: 'Imperfect',
  future: 'Future', conditional: 'Conditional', subjunctive: 'Subjunctive (pres.)',
};
export const FORMS = ['yo', 'tú', 'él/ella', 'nosotros', 'vosotros', 'ellos/ellas'];
export const FORM_KEYS = ['yo', 'tu', 'el', 'nosotros', 'vosotros', 'ellos'];

export const VERBS = [
  {
    infinitive: 'ser',
    meaning: 'to be (identity/permanent)',
    type: 'irregular',
    cefr: 'A1',
    note: 'Ser and estar both mean "to be" but are not interchangeable.',
    present:     { yo:'soy',    tu:'eres',    el:'es',      nosotros:'somos',    vosotros:'sois',      ellos:'son'      },
    preterite:   { yo:'fui',    tu:'fuiste',  el:'fue',     nosotros:'fuimos',   vosotros:'fuisteis',  ellos:'fueron'   },
    imperfect:   { yo:'era',    tu:'eras',    el:'era',     nosotros:'éramos',   vosotros:'erais',     ellos:'eran'     },
    future:      { yo:'seré',   tu:'serás',   el:'será',    nosotros:'seremos',  vosotros:'seréis',    ellos:'serán'    },
    conditional: { yo:'sería',  tu:'serías',  el:'sería',   nosotros:'seríamos', vosotros:'seríais',   ellos:'serían'   },
    subjunctive: { yo:'sea',    tu:'seas',    el:'sea',     nosotros:'seamos',   vosotros:'seáis',     ellos:'sean'     },
  },
  {
    infinitive: 'estar',
    meaning: 'to be (state/location)',
    type: 'irregular',
    cefr: 'A1',
    note: 'Use estar for temporary states, emotions, locations, and progressive tenses.',
    present:     { yo:'estoy',    tu:'estás',    el:'está',    nosotros:'estamos',    vosotros:'estáis',    ellos:'están'    },
    preterite:   { yo:'estuve',   tu:'estuviste', el:'estuvo',  nosotros:'estuvimos',  vosotros:'estuvisteis', ellos:'estuvieron' },
    imperfect:   { yo:'estaba',   tu:'estabas',  el:'estaba',  nosotros:'estábamos',  vosotros:'estabais',  ellos:'estaban'  },
    future:      { yo:'estaré',   tu:'estarás',  el:'estará',  nosotros:'estaremos',  vosotros:'estaréis',  ellos:'estarán'  },
    conditional: { yo:'estaría',  tu:'estarías', el:'estaría', nosotros:'estaríamos', vosotros:'estaríais', ellos:'estarían' },
    subjunctive: { yo:'esté',     tu:'estés',    el:'esté',    nosotros:'estemos',    vosotros:'estéis',    ellos:'estén'    },
  },
  {
    infinitive: 'tener',
    meaning: 'to have',
    type: 'irregular',
    cefr: 'A1',
    note: 'Tener que + infinitive = to have to do something.',
    present:     { yo:'tengo',   tu:'tienes',   el:'tiene',   nosotros:'tenemos',   vosotros:'tenéis',   ellos:'tienen'   },
    preterite:   { yo:'tuve',    tu:'tuviste',  el:'tuvo',    nosotros:'tuvimos',   vosotros:'tuvisteis', ellos:'tuvieron' },
    imperfect:   { yo:'tenía',   tu:'tenías',   el:'tenía',   nosotros:'teníamos',  vosotros:'teníais',  ellos:'tenían'   },
    future:      { yo:'tendré',  tu:'tendrás',  el:'tendrá',  nosotros:'tendremos', vosotros:'tendréis', ellos:'tendrán'  },
    conditional: { yo:'tendría', tu:'tendrías', el:'tendría', nosotros:'tendríamos',vosotros:'tendríais',ellos:'tendrían' },
    subjunctive: { yo:'tenga',   tu:'tengas',   el:'tenga',   nosotros:'tengamos',  vosotros:'tengáis',  ellos:'tengan'   },
  },
  {
    infinitive: 'ir',
    meaning: 'to go',
    type: 'irregular',
    cefr: 'A1',
    note: 'Ir a + infinitive forms the near future. Preterite identical to ser.',
    present:     { yo:'voy',   tu:'vas',    el:'va',    nosotros:'vamos',   vosotros:'vais',     ellos:'van'     },
    preterite:   { yo:'fui',   tu:'fuiste', el:'fue',   nosotros:'fuimos',  vosotros:'fuisteis', ellos:'fueron'  },
    imperfect:   { yo:'iba',   tu:'ibas',   el:'iba',   nosotros:'íbamos',  vosotros:'ibais',    ellos:'iban'    },
    future:      { yo:'iré',   tu:'irás',   el:'irá',   nosotros:'iremos',  vosotros:'iréis',    ellos:'irán'    },
    conditional: { yo:'iría',  tu:'irías',  el:'iría',  nosotros:'iríamos', vosotros:'iríais',   ellos:'irían'   },
    subjunctive: { yo:'vaya',  tu:'vayas',  el:'vaya',  nosotros:'vayamos', vosotros:'vayáis',   ellos:'vayan'   },
  },
  {
    infinitive: 'hacer',
    meaning: 'to do / to make',
    type: 'irregular',
    cefr: 'A1',
    note: 'Hacer is used in weather expressions: hace calor, hace frío.',
    present:     { yo:'hago',   tu:'haces',   el:'hace',   nosotros:'hacemos',   vosotros:'hacéis',   ellos:'hacen'   },
    preterite:   { yo:'hice',   tu:'hiciste', el:'hizo',   nosotros:'hicimos',   vosotros:'hicisteis',ellos:'hicieron'},
    imperfect:   { yo:'hacía',  tu:'hacías',  el:'hacía',  nosotros:'hacíamos',  vosotros:'hacíais',  ellos:'hacían'  },
    future:      { yo:'haré',   tu:'harás',   el:'hará',   nosotros:'haremos',   vosotros:'haréis',   ellos:'harán'   },
    conditional: { yo:'haría',  tu:'harías',  el:'haría',  nosotros:'haríamos',  vosotros:'haríais',  ellos:'harían'  },
    subjunctive: { yo:'haga',   tu:'hagas',   el:'haga',   nosotros:'hagamos',   vosotros:'hagáis',   ellos:'hagan'   },
  },
  {
    infinitive: 'poder',
    meaning: 'to be able to / can',
    type: 'stem-changing',
    cefr: 'A1',
    note: 'O→UE stem change in present (except nosotros/vosotros).',
    present:     { yo:'puedo',    tu:'puedes',   el:'puede',   nosotros:'podemos',   vosotros:'podéis',   ellos:'pueden'   },
    preterite:   { yo:'pude',     tu:'pudiste',  el:'pudo',    nosotros:'pudimos',   vosotros:'pudisteis',ellos:'pudieron' },
    imperfect:   { yo:'podía',    tu:'podías',   el:'podía',   nosotros:'podíamos',  vosotros:'podíais',  ellos:'podían'   },
    future:      { yo:'podré',    tu:'podrás',   el:'podrá',   nosotros:'podremos',  vosotros:'podréis',  ellos:'podrán'   },
    conditional: { yo:'podría',   tu:'podrías',  el:'podría',  nosotros:'podríamos', vosotros:'podríais', ellos:'podrían'  },
    subjunctive: { yo:'pueda',    tu:'puedas',   el:'pueda',   nosotros:'podamos',   vosotros:'podáis',   ellos:'puedan'   },
  },
  {
    infinitive: 'querer',
    meaning: 'to want / to love',
    type: 'stem-changing',
    cefr: 'A1',
    note: 'E→IE stem change in present. Querer a = to love a person.',
    present:     { yo:'quiero',   tu:'quieres',  el:'quiere',  nosotros:'queremos',  vosotros:'queréis',  ellos:'quieren'  },
    preterite:   { yo:'quise',    tu:'quisiste', el:'quiso',   nosotros:'quisimos',  vosotros:'quisisteis',ellos:'quisieron'},
    imperfect:   { yo:'quería',   tu:'querías',  el:'quería',  nosotros:'queríamos', vosotros:'queríais', ellos:'querían'  },
    future:      { yo:'querré',   tu:'querrás',  el:'querrá',  nosotros:'querremos', vosotros:'querréis', ellos:'querrán'  },
    conditional: { yo:'querría',  tu:'querrías', el:'querría', nosotros:'querríamos',vosotros:'querríais',ellos:'querrían' },
    subjunctive: { yo:'quiera',   tu:'quieras',  el:'quiera',  nosotros:'queramos',  vosotros:'queráis',  ellos:'quieran'  },
  },
  {
    infinitive: 'saber',
    meaning: 'to know (facts/how to)',
    type: 'irregular',
    cefr: 'A2',
    note: 'Saber = know a fact or how to do something. Conocer = know a person/place.',
    present:     { yo:'sé',     tu:'sabes',   el:'sabe',   nosotros:'sabemos',  vosotros:'sabéis',  ellos:'saben'   },
    preterite:   { yo:'supe',   tu:'supiste', el:'supo',   nosotros:'supimos',  vosotros:'supisteis',ellos:'supieron'},
    imperfect:   { yo:'sabía',  tu:'sabías',  el:'sabía',  nosotros:'sabíamos', vosotros:'sabíais', ellos:'sabían'  },
    future:      { yo:'sabré',  tu:'sabrás',  el:'sabrá',  nosotros:'sabremos', vosotros:'sabréis', ellos:'sabrán'  },
    conditional: { yo:'sabría', tu:'sabrías', el:'sabría', nosotros:'sabríamos',vosotros:'sabríais',ellos:'sabrían' },
    subjunctive: { yo:'sepa',   tu:'sepas',   el:'sepa',   nosotros:'sepamos',  vosotros:'sepáis',  ellos:'sepan'   },
  },
  {
    infinitive: 'venir',
    meaning: 'to come',
    type: 'irregular',
    cefr: 'A2',
    note: 'Venir de = to come from. Note irregular yo form.',
    present:     { yo:'vengo',   tu:'vienes',   el:'viene',   nosotros:'venimos',   vosotros:'venís',    ellos:'vienen'   },
    preterite:   { yo:'vine',    tu:'viniste',  el:'vino',    nosotros:'vinimos',   vosotros:'vinisteis',ellos:'vinieron' },
    imperfect:   { yo:'venía',   tu:'venías',   el:'venía',   nosotros:'veníamos',  vosotros:'veníais',  ellos:'venían'   },
    future:      { yo:'vendré',  tu:'vendrás',  el:'vendrá',  nosotros:'vendremos', vosotros:'vendréis', ellos:'vendrán'  },
    conditional: { yo:'vendría', tu:'vendrías', el:'vendría', nosotros:'vendríamos',vosotros:'vendríais',ellos:'vendrían' },
    subjunctive: { yo:'venga',   tu:'vengas',   el:'venga',   nosotros:'vengamos',  vosotros:'vengáis',  ellos:'vengan'   },
  },
  {
    infinitive: 'decir',
    meaning: 'to say / to tell',
    type: 'irregular',
    cefr: 'A2',
    note: 'E→I stem change. Irregular future/conditional stem (dir-).',
    present:     { yo:'digo',   tu:'dices',   el:'dice',   nosotros:'decimos',  vosotros:'decís',   ellos:'dicen'   },
    preterite:   { yo:'dije',   tu:'dijiste', el:'dijo',   nosotros:'dijimos',  vosotros:'dijisteis',ellos:'dijeron' },
    imperfect:   { yo:'decía',  tu:'decías',  el:'decía',  nosotros:'decíamos', vosotros:'decíais', ellos:'decían'  },
    future:      { yo:'diré',   tu:'dirás',   el:'dirá',   nosotros:'diremos',  vosotros:'diréis',  ellos:'dirán'   },
    conditional: { yo:'diría',  tu:'dirías',  el:'diría',  nosotros:'diríamos', vosotros:'diríais', ellos:'dirían'  },
    subjunctive: { yo:'diga',   tu:'digas',   el:'diga',   nosotros:'digamos',  vosotros:'digáis',  ellos:'digan'   },
  },
  {
    infinitive: 'poner',
    meaning: 'to put / to place',
    type: 'irregular',
    cefr: 'A2',
    note: 'Reflexive ponerse = to put on (clothing) / to become (emotion).',
    present:     { yo:'pongo',   tu:'pones',   el:'pone',   nosotros:'ponemos',   vosotros:'ponéis',   ellos:'ponen'   },
    preterite:   { yo:'puse',    tu:'pusiste', el:'puso',   nosotros:'pusimos',   vosotros:'pusisteis',ellos:'pusieron'},
    imperfect:   { yo:'ponía',   tu:'ponías',  el:'ponía',  nosotros:'poníamos',  vosotros:'poníais',  ellos:'ponían'  },
    future:      { yo:'pondré',  tu:'pondrás', el:'pondrá', nosotros:'pondremos', vosotros:'pondréis', ellos:'pondrán' },
    conditional: { yo:'pondría', tu:'pondrías',el:'pondría',nosotros:'pondríamos',vosotros:'pondríais',ellos:'pondrían'},
    subjunctive: { yo:'ponga',   tu:'pongas',  el:'ponga',  nosotros:'pongamos',  vosotros:'pongáis',  ellos:'pongan'  },
  },
  {
    infinitive: 'traer',
    meaning: 'to bring',
    type: 'irregular',
    cefr: 'A2',
    note: 'Irregular yo present (traigo) and preterite (traje).',
    present:     { yo:'traigo',  tu:'traes',   el:'trae',   nosotros:'traemos',  vosotros:'traéis',  ellos:'traen'   },
    preterite:   { yo:'traje',   tu:'trajiste',el:'trajo',  nosotros:'trajimos', vosotros:'trajisteis',ellos:'trajeron'},
    imperfect:   { yo:'traía',   tu:'traías',  el:'traía',  nosotros:'traíamos', vosotros:'traíais', ellos:'traían'  },
    future:      { yo:'traeré',  tu:'traerás', el:'traerá', nosotros:'traeremos',vosotros:'traeréis',ellos:'traerán' },
    conditional: { yo:'traería', tu:'traerías',el:'traería',nosotros:'traeríamos',vosotros:'traeríais',ellos:'traerían'},
    subjunctive: { yo:'traiga',  tu:'traigas', el:'traiga', nosotros:'traigamos',vosotros:'traigáis',ellos:'traigan' },
  },
  {
    infinitive: 'dar',
    meaning: 'to give',
    type: 'irregular',
    cefr: 'A2',
    note: 'Monosyllabic — no accent on preterite di/dio. Used in many fixed expressions.',
    present:     { yo:'doy',  tu:'das',    el:'da',    nosotros:'damos',  vosotros:'dais',   ellos:'dan'    },
    preterite:   { yo:'di',   tu:'diste',  el:'dio',   nosotros:'dimos',  vosotros:'disteis',ellos:'dieron' },
    imperfect:   { yo:'daba', tu:'dabas',  el:'daba',  nosotros:'dábamos',vosotros:'dabais', ellos:'daban'  },
    future:      { yo:'daré', tu:'darás',  el:'dará',  nosotros:'daremos',vosotros:'daréis', ellos:'darán'  },
    conditional: { yo:'daría',tu:'darías', el:'daría', nosotros:'daríamos',vosotros:'daríais',ellos:'darían' },
    subjunctive: { yo:'dé',   tu:'des',    el:'dé',    nosotros:'demos',  vosotros:'deis',   ellos:'den'    },
  },
  {
    infinitive: 'ver',
    meaning: 'to see',
    type: 'irregular',
    cefr: 'A2',
    note: 'Unusual imperfect: veía, etc. (keeps the -e- from old form "veer").',
    present:     { yo:'veo',   tu:'ves',    el:'ve',    nosotros:'vemos',  vosotros:'veis',   ellos:'ven'    },
    preterite:   { yo:'vi',    tu:'viste',  el:'vio',   nosotros:'vimos',  vosotros:'visteis',ellos:'vieron' },
    imperfect:   { yo:'veía',  tu:'veías',  el:'veía',  nosotros:'veíamos',vosotros:'veíais', ellos:'veían'  },
    future:      { yo:'veré',  tu:'verás',  el:'verá',  nosotros:'veremos',vosotros:'veréis', ellos:'verán'  },
    conditional: { yo:'vería', tu:'verías', el:'vería', nosotros:'veríamos',vosotros:'veríais',ellos:'verían' },
    subjunctive: { yo:'vea',   tu:'veas',   el:'vea',   nosotros:'veamos', vosotros:'veáis',  ellos:'vean'   },
  },
  {
    infinitive: 'salir',
    meaning: 'to leave / to go out',
    type: 'irregular',
    cefr: 'A2',
    note: 'Irregular yo only in present (salgo). Salir con = to date someone.',
    present:     { yo:'salgo',   tu:'sales',   el:'sale',   nosotros:'salimos',   vosotros:'salís',    ellos:'salen'   },
    preterite:   { yo:'salí',    tu:'saliste', el:'salió',  nosotros:'salimos',   vosotros:'salisteis',ellos:'salieron'},
    imperfect:   { yo:'salía',   tu:'salías',  el:'salía',  nosotros:'salíamos',  vosotros:'salíais',  ellos:'salían'  },
    future:      { yo:'saldré',  tu:'saldrás', el:'saldrá', nosotros:'saldremos', vosotros:'saldréis', ellos:'saldrán' },
    conditional: { yo:'saldría', tu:'saldrías',el:'saldría',nosotros:'saldríamos',vosotros:'saldríais',ellos:'saldrían'},
    subjunctive: { yo:'salga',   tu:'salgas',  el:'salga',  nosotros:'salgamos',  vosotros:'salgáis',  ellos:'salgan'  },
  },
  {
    infinitive: 'conocer',
    meaning: 'to know (people/places)',
    type: 'irregular',
    cefr: 'A2',
    note: 'Only irregular in yo present (conozco). Conocer = acquaintance; saber = knowledge.',
    present:     { yo:'conozco',  tu:'conoces',  el:'conoce',  nosotros:'conocemos',  vosotros:'conocéis',  ellos:'conocen'  },
    preterite:   { yo:'conocí',   tu:'conociste',el:'conoció', nosotros:'conocimos',  vosotros:'conocisteis',ellos:'conocieron'},
    imperfect:   { yo:'conocía',  tu:'conocías', el:'conocía', nosotros:'conocíamos', vosotros:'conocíais', ellos:'conocían' },
    future:      { yo:'conoceré', tu:'conocerás',el:'conocerá',nosotros:'conoceremos',vosotros:'conoceréis',ellos:'conocerán'},
    conditional: { yo:'conocería',tu:'conocerías',el:'conocería',nosotros:'conoceríamos',vosotros:'conoceríais',ellos:'conocerían'},
    subjunctive: { yo:'conozca',  tu:'conozcas', el:'conozca', nosotros:'conozcamos', vosotros:'conozcáis', ellos:'conozcan' },
  },
  {
    infinitive: 'sentir',
    meaning: 'to feel / to regret',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'E→IE in present, E→I in preterite (3rd person) and subjunctive.',
    present:     { yo:'siento',  tu:'sientes',  el:'siente',  nosotros:'sentimos',  vosotros:'sentís',  ellos:'sienten' },
    preterite:   { yo:'sentí',   tu:'sentiste', el:'sintió',  nosotros:'sentimos',  vosotros:'sentisteis',ellos:'sintieron'},
    imperfect:   { yo:'sentía',  tu:'sentías',  el:'sentía',  nosotros:'sentíamos', vosotros:'sentíais',ellos:'sentían' },
    future:      { yo:'sentiré', tu:'sentirás', el:'sentirá', nosotros:'sentiremos',vosotros:'sentiréis',ellos:'sentirán'},
    conditional: { yo:'sentiría',tu:'sentirías',el:'sentiría',nosotros:'sentiríamos',vosotros:'sentiríais',ellos:'sentirían'},
    subjunctive: { yo:'sienta',  tu:'sientas',  el:'sienta',  nosotros:'sintamos',  vosotros:'sintáis', ellos:'sientan' },
  },
  {
    infinitive: 'dormir',
    meaning: 'to sleep',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'O→UE in present, O→U in preterite (3rd person) and subjunctive.',
    present:     { yo:'duermo',   tu:'duermes',  el:'duerme',  nosotros:'dormimos',  vosotros:'dormís',   ellos:'duermen' },
    preterite:   { yo:'dormí',    tu:'dormiste', el:'durmió',  nosotros:'dormimos',  vosotros:'dormisteis',ellos:'durmieron'},
    imperfect:   { yo:'dormía',   tu:'dormías',  el:'dormía',  nosotros:'dormíamos', vosotros:'dormíais', ellos:'dormían' },
    future:      { yo:'dormiré',  tu:'dormirás', el:'dormirá', nosotros:'dormiremos',vosotros:'dormiréis',ellos:'dormirán'},
    conditional: { yo:'dormiría', tu:'dormirías',el:'dormiría',nosotros:'dormiríamos',vosotros:'dormiríais',ellos:'dormirían'},
    subjunctive: { yo:'duerma',   tu:'duermas',  el:'duerma',  nosotros:'durmamos',  vosotros:'durmáis',  ellos:'duerman' },
  },
  {
    infinitive: 'jugar',
    meaning: 'to play (game/sport)',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'U→UE stem change in present. Jugar a = to play a sport.',
    present:     { yo:'juego',   tu:'juegas',  el:'juega',  nosotros:'jugamos',  vosotros:'jugáis',  ellos:'juegan'  },
    preterite:   { yo:'jugué',   tu:'jugaste', el:'jugó',   nosotros:'jugamos',  vosotros:'jugasteis',ellos:'jugaron' },
    imperfect:   { yo:'jugaba',  tu:'jugabas', el:'jugaba', nosotros:'jugábamos',vosotros:'jugabais',ellos:'jugaban' },
    future:      { yo:'jugaré',  tu:'jugarás', el:'jugará', nosotros:'jugaremos',vosotros:'jugaréis',ellos:'jugarán' },
    conditional: { yo:'jugaría', tu:'jugarías',el:'jugaría',nosotros:'jugaríamos',vosotros:'jugaríais',ellos:'jugarían'},
    subjunctive: { yo:'juegue',  tu:'juegues', el:'juegue', nosotros:'juguemos', vosotros:'juguéis', ellos:'jueguen' },
  },
  {
    infinitive: 'pedir',
    meaning: 'to ask for / to order',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'E→I in present (yo/tú/él/ellos) and preterite (3rd person). Also pedir prestado = to borrow.',
    present:     { yo:'pido',   tu:'pides',   el:'pide',   nosotros:'pedimos',  vosotros:'pedís',   ellos:'piden'   },
    preterite:   { yo:'pedí',   tu:'pediste', el:'pidió',  nosotros:'pedimos',  vosotros:'pedisteis',ellos:'pidieron'},
    imperfect:   { yo:'pedía',  tu:'pedías',  el:'pedía',  nosotros:'pedíamos', vosotros:'pedíais', ellos:'pedían'  },
    future:      { yo:'pediré', tu:'pedirás', el:'pedirá', nosotros:'pediremos',vosotros:'pediréis',ellos:'pedirán' },
    conditional: { yo:'pediría',tu:'pedirías',el:'pediría',nosotros:'pediríamos',vosotros:'pediríais',ellos:'pedirían'},
    subjunctive: { yo:'pida',   tu:'pidas',   el:'pida',   nosotros:'pidamos',  vosotros:'pidáis',  ellos:'pidan'   },
  },
  {
    infinitive: 'seguir',
    meaning: 'to follow / to continue',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'E→I. Yo present: sigo (gu→g before a/o). Seguir + gerund = to keep doing.',
    present:     { yo:'sigo',    tu:'sigues',   el:'sigue',   nosotros:'seguimos',  vosotros:'seguís',   ellos:'siguen'  },
    preterite:   { yo:'seguí',   tu:'seguiste', el:'siguió',  nosotros:'seguimos',  vosotros:'seguisteis',ellos:'siguieron'},
    imperfect:   { yo:'seguía',  tu:'seguías',  el:'seguía',  nosotros:'seguíamos', vosotros:'seguíais', ellos:'seguían' },
    future:      { yo:'seguiré', tu:'seguirás', el:'seguirá', nosotros:'seguiremos',vosotros:'seguiréis',ellos:'seguirán'},
    conditional: { yo:'seguiría',tu:'seguirías',el:'seguiría',nosotros:'seguiríamos',vosotros:'seguiríais',ellos:'seguirían'},
    subjunctive: { yo:'siga',    tu:'sigas',    el:'siga',    nosotros:'sigamos',   vosotros:'sigáis',   ellos:'sigan'   },
  },
  {
    infinitive: 'oír',
    meaning: 'to hear',
    type: 'irregular',
    cefr: 'B1',
    note: 'I→Y before stressed vowel. Oír ≠ escuchar (oír = perceive sound, escuchar = listen actively).',
    present:     { yo:'oigo',  tu:'oyes',   el:'oye',   nosotros:'oímos',  vosotros:'oís',    ellos:'oyen'   },
    preterite:   { yo:'oí',    tu:'oíste',  el:'oyó',   nosotros:'oímos',  vosotros:'oísteis',ellos:'oyeron' },
    imperfect:   { yo:'oía',   tu:'oías',   el:'oía',   nosotros:'oíamos', vosotros:'oíais',  ellos:'oían'   },
    future:      { yo:'oiré',  tu:'oirás',  el:'oirá',  nosotros:'oiremos',vosotros:'oiréis', ellos:'oirán'  },
    conditional: { yo:'oiría', tu:'oirías', el:'oiría', nosotros:'oiríamos',vosotros:'oiríais',ellos:'oirían' },
    subjunctive: { yo:'oiga',  tu:'oigas',  el:'oiga',  nosotros:'oigamos',vosotros:'oigáis', ellos:'oigan'  },
  },
  {
    infinitive: 'caer',
    meaning: 'to fall',
    type: 'irregular',
    cefr: 'B1',
    note: 'Caer bien/mal = to like/dislike (a person). Caerse = to fall over (reflexive).',
    present:     { yo:'caigo',  tu:'caes',   el:'cae',   nosotros:'caemos',  vosotros:'caéis',  ellos:'caen'   },
    preterite:   { yo:'caí',    tu:'caíste', el:'cayó',  nosotros:'caímos',  vosotros:'caísteis',ellos:'cayeron'},
    imperfect:   { yo:'caía',   tu:'caías',  el:'caía',  nosotros:'caíamos', vosotros:'caíais', ellos:'caían'  },
    future:      { yo:'caeré',  tu:'caerás', el:'caerá', nosotros:'caeremos',vosotros:'caeréis',ellos:'caerán' },
    conditional: { yo:'caería', tu:'caerías',el:'caería',nosotros:'caeríamos',vosotros:'caeríais',ellos:'caerían'},
    subjunctive: { yo:'caiga',  tu:'caigas', el:'caiga', nosotros:'caigamos',vosotros:'caigáis',ellos:'caigan' },
  },
  {
    infinitive: 'volver',
    meaning: 'to return / to come back',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'O→UE in present. Volver a + infinitive = to do something again.',
    present:     { yo:'vuelvo',   tu:'vuelves',  el:'vuelve',  nosotros:'volvemos',  vosotros:'volvéis',  ellos:'vuelven' },
    preterite:   { yo:'volví',    tu:'volviste', el:'volvió',  nosotros:'volvimos',  vosotros:'volvisteis',ellos:'volvieron'},
    imperfect:   { yo:'volvía',   tu:'volvías',  el:'volvía',  nosotros:'volvíamos', vosotros:'volvíais', ellos:'volvían' },
    future:      { yo:'volveré',  tu:'volverás', el:'volverá', nosotros:'volveremos',vosotros:'volveréis',ellos:'volverán'},
    conditional: { yo:'volvería', tu:'volverías',el:'volvería',nosotros:'volveríamos',vosotros:'volveríais',ellos:'volverían'},
    subjunctive: { yo:'vuelva',   tu:'vuelvas',  el:'vuelva',  nosotros:'volvamos',  vosotros:'volváis',  ellos:'vuelvan' },
  },
  {
    infinitive: 'haber',
    meaning: 'to have (auxiliary)',
    type: 'irregular',
    cefr: 'B1',
    note: 'Used only as auxiliary (he comido = I have eaten). Hay = there is/are (impersonal).',
    present:     { yo:'he',      tu:'has',     el:'ha',     nosotros:'hemos',    vosotros:'habéis',   ellos:'han'      },
    preterite:   { yo:'hube',    tu:'hubiste', el:'hubo',   nosotros:'hubimos',  vosotros:'hubisteis',ellos:'hubieron' },
    imperfect:   { yo:'había',   tu:'habías',  el:'había',  nosotros:'habíamos', vosotros:'habíais',  ellos:'habían'   },
    future:      { yo:'habré',   tu:'habrás',  el:'habrá',  nosotros:'habremos', vosotros:'habréis',  ellos:'habrán'   },
    conditional: { yo:'habría',  tu:'habrías', el:'habría', nosotros:'habríamos',vosotros:'habríais', ellos:'habrían'  },
    subjunctive: { yo:'haya',    tu:'hayas',   el:'haya',   nosotros:'hayamos',  vosotros:'hayáis',   ellos:'hayan'    },
  },
  {
    infinitive: 'morir',
    meaning: 'to die',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'O→UE in present, O→U in preterite (3rd). Past participle: muerto.',
    present:     { yo:'muero',   tu:'mueres',  el:'muere',  nosotros:'morimos',  vosotros:'morís',   ellos:'mueren'  },
    preterite:   { yo:'morí',    tu:'moriste', el:'murió',  nosotros:'morimos',  vosotros:'moristeis',ellos:'murieron'},
    imperfect:   { yo:'moría',   tu:'morías',  el:'moría',  nosotros:'moríamos', vosotros:'moríais', ellos:'morían'  },
    future:      { yo:'moriré',  tu:'morirás', el:'morirá', nosotros:'moriremos',vosotros:'moriréis',ellos:'morirán' },
    conditional: { yo:'moriría', tu:'morirías',el:'moriría',nosotros:'moriríamos',vosotros:'moriríais',ellos:'morirían'},
    subjunctive: { yo:'muera',   tu:'mueras',  el:'muera',  nosotros:'muramos',  vosotros:'muráis',  ellos:'mueran'  },
  },
  {
    infinitive: 'reír',
    meaning: 'to laugh',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'E→Í in present (yo/tú/él/ellos). Reírse de = to laugh at.',
    present:     { yo:'río',    tu:'ríes',   el:'ríe',   nosotros:'reímos', vosotros:'reís',    ellos:'ríen'   },
    preterite:   { yo:'reí',    tu:'reíste', el:'rió',   nosotros:'reímos', vosotros:'reísteis',ellos:'rieron' },
    imperfect:   { yo:'reía',   tu:'reías',  el:'reía',  nosotros:'reíamos',vosotros:'reíais',  ellos:'reían'  },
    future:      { yo:'reiré',  tu:'reirás', el:'reirá', nosotros:'reiremos',vosotros:'reiréis',ellos:'reirán' },
    conditional: { yo:'reiría', tu:'reirías',el:'reiría',nosotros:'reiríamos',vosotros:'reiríais',ellos:'reirían'},
    subjunctive: { yo:'ría',    tu:'rías',   el:'ría',   nosotros:'riamos', vosotros:'riáis',   ellos:'rían'   },
  },
  {
    infinitive: 'construir',
    meaning: 'to build / to construct',
    type: 'irregular',
    cefr: 'B1',
    note: 'I→Y before stressed vowel (like oír/huir). Common pattern for -uir verbs.',
    present:     { yo:'construyo',  tu:'construyes', el:'construye', nosotros:'construimos', vosotros:'construís', ellos:'construyen' },
    preterite:   { yo:'construí',   tu:'construiste',el:'construyó', nosotros:'construimos', vosotros:'construisteis',ellos:'construyeron'},
    imperfect:   { yo:'construía',  tu:'construías', el:'construía', nosotros:'construíamos',vosotros:'construíais',ellos:'construían' },
    future:      { yo:'construiré', tu:'construirás',el:'construirá',nosotros:'construiremos',vosotros:'construiréis',ellos:'construirán'},
    conditional: { yo:'construiría',tu:'construirías',el:'construiría',nosotros:'construiríamos',vosotros:'construiríais',ellos:'construirían'},
    subjunctive: { yo:'construya',  tu:'construyas', el:'construya', nosotros:'construyamos',vosotros:'construyáis',ellos:'construyan' },
  },
  {
    infinitive: 'producir',
    meaning: 'to produce',
    type: 'irregular',
    cefr: 'B1',
    note: 'C→ZC in yo present. Preterite: produje (like conducir, traducir).',
    present:     { yo:'produzco',  tu:'produces',  el:'produce',  nosotros:'producimos',  vosotros:'producís',  ellos:'producen' },
    preterite:   { yo:'produje',   tu:'produjiste',el:'produjo',  nosotros:'produjimos',  vosotros:'produjisteis',ellos:'produjeron'},
    imperfect:   { yo:'producía',  tu:'producías', el:'producía', nosotros:'producíamos', vosotros:'producíais',ellos:'producían' },
    future:      { yo:'produciré', tu:'producirás',el:'producirá',nosotros:'produciremos',vosotros:'produciréis',ellos:'producirán'},
    conditional: { yo:'produciría',tu:'producirías',el:'produciría',nosotros:'produciríamos',vosotros:'produciríais',ellos:'producirían'},
    subjunctive: { yo:'produzca',  tu:'produzcas', el:'produzca', nosotros:'produzcamos', vosotros:'produzcáis',ellos:'produzcan' },
  },
  {
    infinitive: 'leer',
    meaning: 'to read',
    type: 'irregular',
    cefr: 'A1',
    note: 'I→Y in preterite (3rd person). Written accent on past: leí, leíste, leímos.',
    present:     { yo:'leo',    tu:'lees',   el:'lee',   nosotros:'leemos',  vosotros:'leéis',  ellos:'leen'   },
    preterite:   { yo:'leí',    tu:'leíste', el:'leyó',  nosotros:'leímos',  vosotros:'leísteis',ellos:'leyeron'},
    imperfect:   { yo:'leía',   tu:'leías',  el:'leía',  nosotros:'leíamos', vosotros:'leíais', ellos:'leían'  },
    future:      { yo:'leeré',  tu:'leerás', el:'leerá', nosotros:'leeremos',vosotros:'leeréis',ellos:'leerán' },
    conditional: { yo:'leería', tu:'leerías',el:'leería',nosotros:'leeríamos',vosotros:'leeríais',ellos:'leerían'},
    subjunctive: { yo:'lea',    tu:'leas',   el:'lea',   nosotros:'leamos',  vosotros:'leáis',  ellos:'lean'   },
  },
  {
    infinitive: 'andar',
    meaning: 'to walk',
    type: 'irregular',
    cefr: 'A2',
    note: 'Only irregular in preterite (anduve, etc.). Common in colloquial use: ¿cómo andas?',
    present:     { yo:'ando',    tu:'andas',    el:'anda',   nosotros:'andamos',   vosotros:'andáis',   ellos:'andan'    },
    preterite:   { yo:'anduve',  tu:'anduviste',el:'anduvo', nosotros:'anduvimos', vosotros:'anduvisteis',ellos:'anduvieron'},
    imperfect:   { yo:'andaba',  tu:'andabas',  el:'andaba', nosotros:'andábamos', vosotros:'andabais', ellos:'andaban'  },
    future:      { yo:'andaré',  tu:'andarás',  el:'andará', nosotros:'andaremos', vosotros:'andaréis', ellos:'andarán'  },
    conditional: { yo:'andaría', tu:'andarías', el:'andaría',nosotros:'andaríamos',vosotros:'andaríais',ellos:'andarían' },
    subjunctive: { yo:'ande',    tu:'andes',    el:'ande',   nosotros:'andemos',   vosotros:'andéis',   ellos:'anden'    },
  },
  {
    infinitive: 'caber',
    meaning: 'to fit (inside)',
    type: 'irregular',
    cefr: 'B2',
    note: 'Highly irregular: yo cabe→quepo. Rarely taught early but very common.',
    present:     { yo:'quepo',   tu:'cabes',   el:'cabe',   nosotros:'cabemos',   vosotros:'cabéis',   ellos:'caben'   },
    preterite:   { yo:'cupe',    tu:'cupiste', el:'cupo',   nosotros:'cupimos',   vosotros:'cupisteis',ellos:'cupieron'},
    imperfect:   { yo:'cabía',   tu:'cabías',  el:'cabía',  nosotros:'cabíamos',  vosotros:'cabíais',  ellos:'cabían'  },
    future:      { yo:'cabré',   tu:'cabrás',  el:'cabrá',  nosotros:'cabremos',  vosotros:'cabréis',  ellos:'cabrán'  },
    conditional: { yo:'cabría',  tu:'cabrías', el:'cabría', nosotros:'cabríamos', vosotros:'cabríais', ellos:'cabrían' },
    subjunctive: { yo:'quepa',   tu:'quepas',  el:'quepa',  nosotros:'quepamos',  vosotros:'quepáis',  ellos:'quepan'  },
  },

  // ── Regular model verbs ─────────────────────────────────────────────────
  {
    infinitive: 'hablar',
    meaning: 'to speak / to talk',
    type: 'regular',
    cefr: 'A1',
    note: 'Canonical -ar model verb. All regular -ar verbs follow this pattern.',
    present:     { yo:'hablo',    tu:'hablas',    el:'habla',    nosotros:'hablamos',    vosotros:'habláis',    ellos:'hablan'    },
    preterite:   { yo:'hablé',    tu:'hablaste',  el:'habló',    nosotros:'hablamos',    vosotros:'hablasteis', ellos:'hablaron'  },
    imperfect:   { yo:'hablaba',  tu:'hablabas',  el:'hablaba',  nosotros:'hablábamos',  vosotros:'hablabais',  ellos:'hablaban'  },
    future:      { yo:'hablaré',  tu:'hablarás',  el:'hablará',  nosotros:'hablaremos',  vosotros:'hablaréis',  ellos:'hablarán'  },
    conditional: { yo:'hablaría', tu:'hablarías', el:'hablaría', nosotros:'hablaríamos', vosotros:'hablaríais', ellos:'hablarían' },
    subjunctive: { yo:'hable',    tu:'hables',    el:'hable',    nosotros:'hablemos',    vosotros:'habléis',    ellos:'hablen'    },
  },
  {
    infinitive: 'comer',
    meaning: 'to eat',
    type: 'regular',
    cefr: 'A1',
    note: 'Canonical -er model verb. All regular -er verbs follow this pattern.',
    present:     { yo:'como',    tu:'comes',    el:'come',    nosotros:'comemos',    vosotros:'coméis',    ellos:'comen'    },
    preterite:   { yo:'comí',    tu:'comiste',  el:'comió',   nosotros:'comimos',    vosotros:'comisteis', ellos:'comieron' },
    imperfect:   { yo:'comía',   tu:'comías',   el:'comía',   nosotros:'comíamos',   vosotros:'comíais',   ellos:'comían'   },
    future:      { yo:'comeré',  tu:'comerás',  el:'comerá',  nosotros:'comeremos',  vosotros:'comeréis',  ellos:'comerán'  },
    conditional: { yo:'comería', tu:'comerías', el:'comería', nosotros:'comeríamos', vosotros:'comeríais', ellos:'comerían' },
    subjunctive: { yo:'coma',    tu:'comas',    el:'coma',    nosotros:'comamos',    vosotros:'comáis',    ellos:'coman'    },
  },
  {
    infinitive: 'vivir',
    meaning: 'to live',
    type: 'regular',
    cefr: 'A1',
    note: 'Canonical -ir model verb. All regular -ir verbs follow this pattern.',
    present:     { yo:'vivo',    tu:'vives',    el:'vive',    nosotros:'vivimos',    vosotros:'vivís',     ellos:'viven'    },
    preterite:   { yo:'viví',    tu:'viviste',  el:'vivió',   nosotros:'vivimos',    vosotros:'vivisteis', ellos:'vivieron' },
    imperfect:   { yo:'vivía',   tu:'vivías',   el:'vivía',   nosotros:'vivíamos',   vosotros:'vivíais',   ellos:'vivían'   },
    future:      { yo:'viviré',  tu:'vivirás',  el:'vivirá',  nosotros:'viviremos',  vosotros:'viviréis',  ellos:'vivirán'  },
    conditional: { yo:'viviría', tu:'vivirías', el:'viviría', nosotros:'viviríamos', vosotros:'viviríais', ellos:'vivirían' },
    subjunctive: { yo:'viva',    tu:'vivas',    el:'viva',    nosotros:'vivamos',    vosotros:'viváis',    ellos:'vivan'    },
  },
  // ── Spelling-change verbs ────────────────────────────────────────────────
  {
    infinitive: 'llegar',
    meaning: 'to arrive',
    type: 'irregular',
    cefr: 'A1',
    note: 'Spelling change: g→gu before e in preterite (yo) and all subjunctive forms.',
    present:     { yo:'llego',    tu:'llegas',    el:'llega',    nosotros:'llegamos',    vosotros:'llegáis',    ellos:'llegan'    },
    preterite:   { yo:'llegué',   tu:'llegaste',  el:'llegó',    nosotros:'llegamos',    vosotros:'llegasteis', ellos:'llegaron'  },
    imperfect:   { yo:'llegaba',  tu:'llegabas',  el:'llegaba',  nosotros:'llegábamos',  vosotros:'llegabais',  ellos:'llegaban'  },
    future:      { yo:'llegaré',  tu:'llegarás',  el:'llegará',  nosotros:'llegaremos',  vosotros:'llegaréis',  ellos:'llegarán'  },
    conditional: { yo:'llegaría', tu:'llegarías', el:'llegaría', nosotros:'llegaríamos', vosotros:'llegaríais', ellos:'llegarían' },
    subjunctive: { yo:'llegue',   tu:'llegues',   el:'llegue',   nosotros:'lleguemos',   vosotros:'lleguéis',   ellos:'lleguen'   },
  },
  // ── Stem-changing verbs ──────────────────────────────────────────────────
  {
    infinitive: 'pensar',
    meaning: 'to think',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'e→ie in present tense (all forms except nosotros/vosotros). Pattern shared by: cerrar, empezar, entender, querer, perder.',
    present:     { yo:'pienso',   tu:'piensas',   el:'piensa',   nosotros:'pensamos',    vosotros:'pensáis',    ellos:'piensan'   },
    preterite:   { yo:'pensé',    tu:'pensaste',  el:'pensó',    nosotros:'pensamos',    vosotros:'pensasteis', ellos:'pensaron'  },
    imperfect:   { yo:'pensaba',  tu:'pensabas',  el:'pensaba',  nosotros:'pensábamos',  vosotros:'pensabais',  ellos:'pensaban'  },
    future:      { yo:'pensaré',  tu:'pensarás',  el:'pensará',  nosotros:'pensaremos',  vosotros:'pensaréis',  ellos:'pensarán'  },
    conditional: { yo:'pensaría', tu:'pensarías', el:'pensaría', nosotros:'pensaríamos', vosotros:'pensaríais', ellos:'pensarían' },
    subjunctive: { yo:'piense',   tu:'pienses',   el:'piense',   nosotros:'pensemos',    vosotros:'penséis',    ellos:'piensen'   },
  },
  {
    infinitive: 'entender',
    meaning: 'to understand',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'e→ie stem change in present (except nosotros/vosotros). Same pattern as perder, querer.',
    present:     { yo:'entiendo',   tu:'entiendes',   el:'entiende',   nosotros:'entendemos',    vosotros:'entendéis',    ellos:'entienden'   },
    preterite:   { yo:'entendí',    tu:'entendiste',  el:'entendió',   nosotros:'entendimos',    vosotros:'entendisteis', ellos:'entendieron' },
    imperfect:   { yo:'entendía',   tu:'entendías',   el:'entendía',   nosotros:'entendíamos',   vosotros:'entendíais',   ellos:'entendían'   },
    future:      { yo:'entenderé',  tu:'entenderás',  el:'entenderá',  nosotros:'entenderemos',  vosotros:'entenderéis',  ellos:'entenderán'  },
    conditional: { yo:'entendería', tu:'entenderías', el:'entendería', nosotros:'entenderíamos', vosotros:'entenderíais', ellos:'entenderían' },
    subjunctive: { yo:'entienda',   tu:'entiendas',   el:'entienda',   nosotros:'entendamos',    vosotros:'entendáis',    ellos:'entiendan'   },
  },
  {
    infinitive: 'contar',
    meaning: 'to count / to tell (a story)',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'o→ue stem change in present (except nosotros/vosotros). Same pattern as encontrar, probar, recordar, volver.',
    present:     { yo:'cuento',   tu:'cuentas',   el:'cuenta',   nosotros:'contamos',    vosotros:'contáis',    ellos:'cuentan'   },
    preterite:   { yo:'conté',    tu:'contaste',  el:'contó',    nosotros:'contamos',    vosotros:'contasteis', ellos:'contaron'  },
    imperfect:   { yo:'contaba',  tu:'contabas',  el:'contaba',  nosotros:'contábamos',  vosotros:'contabais',  ellos:'contaban'  },
    future:      { yo:'contaré',  tu:'contarás',  el:'contará',  nosotros:'contaremos',  vosotros:'contaréis',  ellos:'contarán'  },
    conditional: { yo:'contaría', tu:'contarías', el:'contaría', nosotros:'contaríamos', vosotros:'contaríais', ellos:'contarían' },
    subjunctive: { yo:'cuente',   tu:'cuentes',   el:'cuente',   nosotros:'contemos',    vosotros:'contéis',    ellos:'cuenten'   },
  },
  {
    infinitive: 'preferir',
    meaning: 'to prefer',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'Dual stem change: e→ie in present (except nosotros/vosotros); e→i in preterite 3rd person and throughout the subjunctive. Pattern shared by sentir, divertirse, mentir.',
    present:     { yo:'prefiero',   tu:'prefieres',   el:'prefiere',   nosotros:'preferimos',    vosotros:'preferís',     ellos:'prefieren'   },
    preterite:   { yo:'preferí',    tu:'preferiste',  el:'prefirió',   nosotros:'preferimos',    vosotros:'preferisteis', ellos:'prefirieron' },
    imperfect:   { yo:'prefería',   tu:'preferías',   el:'prefería',   nosotros:'preferiamos',   vosotros:'preferíais',   ellos:'preferían'   },
    future:      { yo:'preferiré',  tu:'preferirás',  el:'preferirá',  nosotros:'preferiremos',  vosotros:'preferiréis',  ellos:'preferirán'  },
    conditional: { yo:'preferiría', tu:'preferirías', el:'preferiría', nosotros:'preferiríamos', vosotros:'preferiríais', ellos:'preferirían' },
    subjunctive: { yo:'prefiera',   tu:'prefieras',   el:'prefiera',   nosotros:'prefiramos',    vosotros:'prefiráis',    ellos:'prefieran'   },
  },
  // ── More everyday verbs ──────────────────────────────────────────────────
  {
    infinitive: 'beber',
    meaning: 'to drink',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -er verb. Applies to all drinks.',
    present:     { yo:'bebo',    tu:'bebes',    el:'bebe',    nosotros:'bebemos',    vosotros:'bebéis',    ellos:'beben'    },
    preterite:   { yo:'bebí',    tu:'bebiste',  el:'bebió',   nosotros:'bebimos',    vosotros:'bebisteis', ellos:'bebieron' },
    imperfect:   { yo:'bebía',   tu:'bebías',   el:'bebía',   nosotros:'bebíamos',   vosotros:'bebíais',   ellos:'bebían'   },
    future:      { yo:'beberé',  tu:'beberás',  el:'beberá',  nosotros:'beberemos',  vosotros:'beberéis',  ellos:'beberán'  },
    conditional: { yo:'bebería', tu:'beberías', el:'bebería', nosotros:'beberíamos', vosotros:'beberíais', ellos:'beberían' },
    subjunctive: { yo:'beba',    tu:'bebas',    el:'beba',    nosotros:'bebamos',    vosotros:'bebáis',    ellos:'beban'    },
  },
  {
    infinitive: 'escribir',
    meaning: 'to write',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -ir verb. Participio is irregular: escrito (used with haber in perfect tenses).',
    present:     { yo:'escribo',    tu:'escribes',    el:'escribe',    nosotros:'escribimos',    vosotros:'escribís',     ellos:'escriben'    },
    preterite:   { yo:'escribí',    tu:'escribiste',  el:'escribió',   nosotros:'escribimos',    vosotros:'escribisteis', ellos:'escribieron' },
    imperfect:   { yo:'escribía',   tu:'escribías',   el:'escribía',   nosotros:'escribíamos',   vosotros:'escribíais',   ellos:'escribían'   },
    future:      { yo:'escribiré',  tu:'escribirás',  el:'escribirá',  nosotros:'escribiremos',  vosotros:'escribiréis',  ellos:'escribirán'  },
    conditional: { yo:'escribiría', tu:'escribirías', el:'escribiría', nosotros:'escribiríamos', vosotros:'escribiríais', ellos:'escribirían' },
    subjunctive: { yo:'escriba',    tu:'escribas',    el:'escriba',    nosotros:'escribamos',    vosotros:'escribáis',    ellos:'escriban'    },
  },
  {
    infinitive: 'trabajar',
    meaning: 'to work',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -ar verb. Used for jobs and tasks.',
    present:     { yo:'trabajo',    tu:'trabajas',    el:'trabaja',    nosotros:'trabajamos',    vosotros:'trabajáis',    ellos:'trabajan'    },
    preterite:   { yo:'trabajé',    tu:'trabajaste',  el:'trabajó',    nosotros:'trabajamos',    vosotros:'trabajasteis', ellos:'trabajaron'  },
    imperfect:   { yo:'trabajaba',  tu:'trabajabas',  el:'trabajaba',  nosotros:'trabajábamos',  vosotros:'trabajabais',  ellos:'trabajaban'  },
    future:      { yo:'trabajaré',  tu:'trabajarás',  el:'trabajará',  nosotros:'trabajaremos',  vosotros:'trabajaréis',  ellos:'trabajarán'  },
    conditional: { yo:'trabajaría', tu:'trabajarías', el:'trabajaría', nosotros:'trabajaríamos', vosotros:'trabajaríais', ellos:'trabajarían' },
    subjunctive: { yo:'trabaje',    tu:'trabajes',    el:'trabaje',    nosotros:'trabajemos',    vosotros:'trabajéis',    ellos:'trabajen'    },
  },
  {
    infinitive: 'escuchar',
    meaning: 'to listen (to)',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -ar verb. Takes a direct object without preposition: escucho música (not *escucho a música).',
    present:     { yo:'escucho',    tu:'escuchas',    el:'escucha',    nosotros:'escuchamos',    vosotros:'escucháis',    ellos:'escuchan'    },
    preterite:   { yo:'escuché',    tu:'escuchaste',  el:'escuchó',    nosotros:'escuchamos',    vosotros:'escuchasteis', ellos:'escucharon'  },
    imperfect:   { yo:'escuchaba',  tu:'escuchabas',  el:'escuchaba',  nosotros:'escuchábamos',  vosotros:'escuchabais',  ellos:'escuchaban'  },
    future:      { yo:'escucharé',  tu:'escucharás',  el:'escuchará',  nosotros:'escucharemos',  vosotros:'escucharéis',  ellos:'escucharán'  },
    conditional: { yo:'escucharía', tu:'escucharías', el:'escucharía', nosotros:'escucharíamos', vosotros:'escucharíais', ellos:'escucharían' },
    subjunctive: { yo:'escuche',    tu:'escuches',    el:'escuche',    nosotros:'escuchemos',    vosotros:'escuchéis',    ellos:'escuchen'    },
  },
  {
    infinitive: 'aprender',
    meaning: 'to learn',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -er verb. Aprender a + infinitive = to learn to do something.',
    present:     { yo:'aprendo',    tu:'aprendes',    el:'aprende',    nosotros:'aprendemos',    vosotros:'aprendéis',    ellos:'aprenden'    },
    preterite:   { yo:'aprendí',    tu:'aprendiste',  el:'aprendió',   nosotros:'aprendimos',    vosotros:'aprendisteis', ellos:'aprendieron' },
    imperfect:   { yo:'aprendía',   tu:'aprendías',   el:'aprendía',   nosotros:'aprendíamos',   vosotros:'aprendíais',   ellos:'aprendían'   },
    future:      { yo:'aprenderé',  tu:'aprenderás',  el:'aprenderá',  nosotros:'aprenderemos',  vosotros:'aprenderéis',  ellos:'aprenderán'  },
    conditional: { yo:'aprendería', tu:'aprenderías', el:'aprendería', nosotros:'aprenderíamos', vosotros:'aprenderíais', ellos:'aprenderían' },
    subjunctive: { yo:'aprenda',    tu:'aprendas',    el:'aprenda',    nosotros:'aprendamos',    vosotros:'aprendáis',    ellos:'aprendan'    },
  },
  {
    infinitive: 'llamar',
    meaning: 'to call / to name',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -ar verb. Reflexive llamarse means "to be called": Me llamo Ana.',
    present:     { yo:'llamo',    tu:'llamas',    el:'llama',    nosotros:'llamamos',    vosotros:'llamáis',    ellos:'llaman'    },
    preterite:   { yo:'llamé',    tu:'llamaste',  el:'llamó',    nosotros:'llamamos',    vosotros:'llamasteis', ellos:'llamaron'  },
    imperfect:   { yo:'llamaba',  tu:'llamabas',  el:'llamaba',  nosotros:'llamábamos',  vosotros:'llamabais',  ellos:'llamaban'  },
    future:      { yo:'llamaré',  tu:'llamarás',  el:'llamará',  nosotros:'llamaremos',  vosotros:'llamaréis',  ellos:'llamarán'  },
    conditional: { yo:'llamaría', tu:'llamarías', el:'llamaría', nosotros:'llamaríamos', vosotros:'llamaríais', ellos:'llamarían' },
    subjunctive: { yo:'llame',    tu:'llames',    el:'llame',    nosotros:'llamemos',    vosotros:'llaméis',    ellos:'llamen'    },
  },
  {
    infinitive: 'empezar',
    meaning: 'to start / to begin',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'e→ie stem change in present (except nosotros/vosotros). Spelling change z→c before e in preterite (yo) and subjunctive.',
    present:     { yo:'empiezo',   tu:'empiezas',   el:'empieza',   nosotros:'empezamos',    vosotros:'empezáis',    ellos:'empiezan'   },
    preterite:   { yo:'empecé',    tu:'empezaste',  el:'empezó',    nosotros:'empezamos',    vosotros:'empezasteis', ellos:'empezaron'  },
    imperfect:   { yo:'empezaba',  tu:'empezabas',  el:'empezaba',  nosotros:'empezábamos',  vosotros:'empezabais',  ellos:'empezaban'  },
    future:      { yo:'empezaré',  tu:'empezarás',  el:'empezará',  nosotros:'empezaremos',  vosotros:'empezaréis',  ellos:'empezarán'  },
    conditional: { yo:'empezaría', tu:'empezarías', el:'empezaría', nosotros:'empezaríamos', vosotros:'empezaríais', ellos:'empezarían' },
    subjunctive: { yo:'empiece',   tu:'empieces',   el:'empiece',   nosotros:'empecemos',    vosotros:'empecéis',    ellos:'empiecen'   },
  },
  {
    infinitive: 'encontrar',
    meaning: 'to find / to meet',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'o→ue stem change in present (except nosotros/vosotros). Same pattern as contar, recordar, probar.',
    present:     { yo:'encuentro',   tu:'encuentras',   el:'encuentra',   nosotros:'encontramos',    vosotros:'encontráis',    ellos:'encuentran'   },
    preterite:   { yo:'encontré',    tu:'encontraste',  el:'encontró',    nosotros:'encontramos',    vosotros:'encontrasteis', ellos:'encontraron'  },
    imperfect:   { yo:'encontraba',  tu:'encontrabas',  el:'encontraba',  nosotros:'encontrábamos',  vosotros:'encontrabais',  ellos:'encontraban'  },
    future:      { yo:'encontraré',  tu:'encontrarás',  el:'encontrará',  nosotros:'encontraremos',  vosotros:'encontraréis',  ellos:'encontrarán'  },
    conditional: { yo:'encontraría', tu:'encontrarías', el:'encontraría', nosotros:'encontraríamos', vosotros:'encontraríais', ellos:'encontrarían' },
    subjunctive: { yo:'encuentre',   tu:'encuentres',   el:'encuentre',   nosotros:'encontremos',    vosotros:'encontréis',    ellos:'encuentren'   },
  },
  {
    infinitive: 'perder',
    meaning: 'to lose / to miss (a bus, opportunity)',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'e→ie stem change in present (except nosotros/vosotros). Same pattern as entender, querer.',
    present:     { yo:'pierdo',   tu:'pierdes',   el:'pierde',   nosotros:'perdemos',    vosotros:'perdéis',    ellos:'pierden'   },
    preterite:   { yo:'perdí',    tu:'perdiste',  el:'perdió',   nosotros:'perdimos',    vosotros:'perdisteis', ellos:'perdieron' },
    imperfect:   { yo:'perdía',   tu:'perdías',   el:'perdía',   nosotros:'perdíamos',   vosotros:'perdíais',   ellos:'perdían'   },
    future:      { yo:'perderé',  tu:'perderás',  el:'perderá',  nosotros:'perderemos',  vosotros:'perderéis',  ellos:'perderán'  },
    conditional: { yo:'perdería', tu:'perderías', el:'perdería', nosotros:'perderíamos', vosotros:'perderíais', ellos:'perderían' },
    subjunctive: { yo:'pierda',   tu:'pierdas',   el:'pierda',   nosotros:'perdamos',    vosotros:'perdáis',    ellos:'pierdan'   },
  },
  {
    infinitive: 'necesitar',
    meaning: 'to need',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -ar verb. Very common for expressing needs. Often paired with infinitive: necesito hablar contigo.',
    present:     { yo:'necesito',    tu:'necesitas',    el:'necesita',    nosotros:'necesitamos',    vosotros:'necesitáis',    ellos:'necesitan'    },
    preterite:   { yo:'necesité',    tu:'necesitaste',  el:'necesitó',    nosotros:'necesitamos',    vosotros:'necesitasteis', ellos:'necesitaron'  },
    imperfect:   { yo:'necesitaba',  tu:'necesitabas',  el:'necesitaba',  nosotros:'necesitábamos',  vosotros:'necesitabais',  ellos:'necesitaban'  },
    future:      { yo:'necesitaré',  tu:'necesitarás',  el:'necesitará',  nosotros:'necesitaremos',  vosotros:'necesitaréis',  ellos:'necesitarán'  },
    conditional: { yo:'necesitaría', tu:'necesitarías', el:'necesitaría', nosotros:'necesitaríamos', vosotros:'necesitaríais', ellos:'necesitarían' },
    subjunctive: { yo:'necesite',    tu:'necesites',    el:'necesite',    nosotros:'necesitemos',    vosotros:'necesitéis',    ellos:'necesiten'    },
  },
  {
    infinitive: 'ayudar',
    meaning: 'to help',
    type: 'regular',
    cefr: 'A1',
    note: 'Regular -ar verb. Used with a + person: ayudar a alguien.',
    present:     { yo:'ayudo',    tu:'ayudas',    el:'ayuda',    nosotros:'ayudamos',    vosotros:'ayudáis',    ellos:'ayudan'    },
    preterite:   { yo:'ayudé',    tu:'ayudaste',  el:'ayudó',    nosotros:'ayudamos',    vosotros:'ayudasteis', ellos:'ayudaron'  },
    imperfect:   { yo:'ayudaba',  tu:'ayudabas',  el:'ayudaba',  nosotros:'ayudábamos',  vosotros:'ayudabais',  ellos:'ayudaban'  },
    future:      { yo:'ayudaré',  tu:'ayudarás',  el:'ayudará',  nosotros:'ayudaremos',  vosotros:'ayudaréis',  ellos:'ayudarán'  },
    conditional: { yo:'ayudaría', tu:'ayudarías', el:'ayudaría', nosotros:'ayudaríamos', vosotros:'ayudaríais', ellos:'ayudarían' },
    subjunctive: { yo:'ayude',    tu:'ayudes',    el:'ayude',    nosotros:'ayudemos',    vosotros:'ayudéis',    ellos:'ayuden'    },
  },
  {
    infinitive: 'buscar',
    meaning: 'to look for / to search',
    type: 'regular',
    cefr: 'A2',
    note: 'C→QU spelling change in preterite yo (busqué) and present subjunctive (busque…). Does not take a preposition unlike English "look for".',
    present:     { yo:'busco',    tu:'buscas',    el:'busca',    nosotros:'buscamos',    vosotros:'buscáis',    ellos:'buscan'    },
    preterite:   { yo:'busqué',   tu:'buscaste',  el:'buscó',    nosotros:'buscamos',    vosotros:'buscasteis', ellos:'buscaron'  },
    imperfect:   { yo:'buscaba',  tu:'buscabas',  el:'buscaba',  nosotros:'buscábamos',  vosotros:'buscabais',  ellos:'buscaban'  },
    future:      { yo:'buscaré',  tu:'buscarás',  el:'buscará',  nosotros:'buscaremos',  vosotros:'buscaréis',  ellos:'buscarán'  },
    conditional: { yo:'buscaría', tu:'buscarías', el:'buscaría', nosotros:'buscaríamos', vosotros:'buscaríais', ellos:'buscarían' },
    subjunctive: { yo:'busque',   tu:'busques',   el:'busque',   nosotros:'busquemos',   vosotros:'busquéis',   ellos:'busquen'   },
  },
  {
    infinitive: 'llevar',
    meaning: 'to carry / to wear / to take (somewhere)',
    type: 'regular',
    cefr: 'A2',
    note: 'Regular -ar verb with three core meanings: llevar ropa (to wear clothes), llevar algo a (to take something to), llevar tiempo (to have been doing something for a time).',
    present:     { yo:'llevo',    tu:'llevas',    el:'lleva',    nosotros:'llevamos',    vosotros:'lleváis',    ellos:'llevan'    },
    preterite:   { yo:'llevé',    tu:'llevaste',  el:'llevó',    nosotros:'llevamos',    vosotros:'llevasteis', ellos:'llevaron'  },
    imperfect:   { yo:'llevaba',  tu:'llevabas',  el:'llevaba',  nosotros:'llevábamos',  vosotros:'llevabais',  ellos:'llevaban'  },
    future:      { yo:'llevaré',  tu:'llevarás',  el:'llevará',  nosotros:'llevaremos',  vosotros:'llevaréis',  ellos:'llevarán'  },
    conditional: { yo:'llevaría', tu:'llevarías', el:'llevaría', nosotros:'llevaríamos', vosotros:'llevaríais', ellos:'llevarían' },
    subjunctive: { yo:'lleve',    tu:'lleves',    el:'lleve',    nosotros:'llevemos',    vosotros:'llevéis',    ellos:'lleven'    },
  },
  {
    infinitive: 'olvidar',
    meaning: 'to forget',
    type: 'regular',
    cefr: 'A2',
    note: 'Regular -ar verb. Often used reflexively: olvidarse de + infinitive (to forget to do something). Olvidé vs. se me olvidó — the latter implies accidental forgetting.',
    present:     { yo:'olvido',    tu:'olvidas',    el:'olvida',    nosotros:'olvidamos',    vosotros:'olvidáis',    ellos:'olvidan'    },
    preterite:   { yo:'olvidé',    tu:'olvidaste',  el:'olvidó',    nosotros:'olvidamos',    vosotros:'olvidasteis', ellos:'olvidaron'  },
    imperfect:   { yo:'olvidaba',  tu:'olvidabas',  el:'olvidaba',  nosotros:'olvidábamos',  vosotros:'olvidabais',  ellos:'olvidaban'  },
    future:      { yo:'olvidaré',  tu:'olvidarás',  el:'olvidará',  nosotros:'olvidaremos',  vosotros:'olvidaréis',  ellos:'olvidarán'  },
    conditional: { yo:'olvidaría', tu:'olvidarías', el:'olvidaría', nosotros:'olvidaríamos', vosotros:'olvidaríais', ellos:'olvidarían' },
    subjunctive: { yo:'olvide',    tu:'olvides',    el:'olvide',    nosotros:'olvidemos',    vosotros:'olvidéis',    ellos:'olviden'    },
  },
  {
    infinitive: 'recordar',
    meaning: 'to remember / to remind',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'O→UE stem change in present (except nosotros/vosotros). Preterite and imperfect are regular. Recordar algo = to remember; recordar a alguien algo = to remind someone of something.',
    present:     { yo:'recuerdo',   tu:'recuerdas',   el:'recuerda',   nosotros:'recordamos',    vosotros:'recordáis',    ellos:'recuerdan'   },
    preterite:   { yo:'recordé',    tu:'recordaste',  el:'recordó',    nosotros:'recordamos',    vosotros:'recordasteis', ellos:'recordaron'  },
    imperfect:   { yo:'recordaba',  tu:'recordabas',  el:'recordaba',  nosotros:'recordábamos',  vosotros:'recordabais',  ellos:'recordaban'  },
    future:      { yo:'recordaré',  tu:'recordarás',  el:'recordará',  nosotros:'recordaremos',  vosotros:'recordaréis',  ellos:'recordarán'  },
    conditional: { yo:'recordaría', tu:'recordarías', el:'recordaría', nosotros:'recordaríamos', vosotros:'recordaríais', ellos:'recordarían' },
    subjunctive: { yo:'recuerde',   tu:'recuerdes',   el:'recuerde',   nosotros:'recordemos',    vosotros:'recordéis',    ellos:'recuerden'   },
  },
  {
    infinitive: 'ganar',
    meaning: 'to win / to earn / to gain',
    type: 'regular',
    cefr: 'A2',
    note: 'Regular -ar verb. Ganar un partido = to win a match; ganar dinero = to earn money; ganar tiempo = to gain time.',
    present:     { yo:'gano',    tu:'ganas',    el:'gana',    nosotros:'ganamos',    vosotros:'ganáis',    ellos:'ganan'    },
    preterite:   { yo:'gané',    tu:'ganaste',  el:'ganó',    nosotros:'ganamos',    vosotros:'ganasteis', ellos:'ganaron'  },
    imperfect:   { yo:'ganaba',  tu:'ganabas',  el:'ganaba',  nosotros:'ganábamos',  vosotros:'ganabais',  ellos:'ganaban'  },
    future:      { yo:'ganaré',  tu:'ganarás',  el:'ganará',  nosotros:'ganaremos',  vosotros:'ganaréis',  ellos:'ganarán'  },
    conditional: { yo:'ganaría', tu:'ganarías', el:'ganaría', nosotros:'ganaríamos', vosotros:'ganaríais', ellos:'ganarían' },
    subjunctive: { yo:'gane',    tu:'ganes',    el:'gane',    nosotros:'ganemos',    vosotros:'ganéis',    ellos:'ganen'    },
  },
  {
    infinitive: 'cambiar',
    meaning: 'to change',
    type: 'regular',
    cefr: 'A2',
    note: 'Regular -ar verb (-iar type where i does not take an accent). Cambiar de + noun = to change something: cambiar de trabajo, cambiar de idea.',
    present:     { yo:'cambio',    tu:'cambias',    el:'cambia',    nosotros:'cambiamos',    vosotros:'cambiáis',    ellos:'cambian'    },
    preterite:   { yo:'cambié',    tu:'cambiaste',  el:'cambió',    nosotros:'cambiamos',    vosotros:'cambiasteis', ellos:'cambiaron'  },
    imperfect:   { yo:'cambiaba',  tu:'cambiabas',  el:'cambiaba',  nosotros:'cambiábamos',  vosotros:'cambiabais',  ellos:'cambiaban'  },
    future:      { yo:'cambiaré',  tu:'cambiarás',  el:'cambiará',  nosotros:'cambiaremos',  vosotros:'cambiaréis',  ellos:'cambiarán'  },
    conditional: { yo:'cambiaría', tu:'cambiarías', el:'cambiaría', nosotros:'cambiaríamos', vosotros:'cambiaríais', ellos:'cambiarían' },
    subjunctive: { yo:'cambie',    tu:'cambies',    el:'cambie',    nosotros:'cambiemos',    vosotros:'cambiéis',    ellos:'cambien'    },
  },
  {
    infinitive: 'cumplir',
    meaning: 'to fulfil / to carry out / to turn (an age)',
    type: 'regular',
    cefr: 'A2',
    note: 'Regular -ir verb. Cumplir años = to have a birthday (turn an age). Cumplir con = to fulfil an obligation. No spelling changes.',
    present:     { yo:'cumplo',    tu:'cumples',    el:'cumple',    nosotros:'cumplimos',    vosotros:'cumplís',    ellos:'cumplen'    },
    preterite:   { yo:'cumplí',    tu:'cumpliste',  el:'cumplió',   nosotros:'cumplimos',    vosotros:'cumplisteis', ellos:'cumplieron' },
    imperfect:   { yo:'cumplía',   tu:'cumplías',   el:'cumplía',   nosotros:'cumplíamos',   vosotros:'cumplíais',   ellos:'cumplían'   },
    future:      { yo:'cumpliré',  tu:'cumplirás',  el:'cumplirá',  nosotros:'cumpliremos',  vosotros:'cumpliréis',  ellos:'cumplirán'  },
    conditional: { yo:'cumpliría', tu:'cumplirías', el:'cumpliría', nosotros:'cumpliríamos', vosotros:'cumpliríais', ellos:'cumplirían' },
    subjunctive: { yo:'cumpla',    tu:'cumplas',    el:'cumpla',    nosotros:'cumplamos',    vosotros:'cumpláis',    ellos:'cumplan'    },
  },
  {
    infinitive: 'crecer',
    meaning: 'to grow / to grow up / to increase',
    type: 'irregular',
    cefr: 'B1',
    note: 'C→ZC spelling change only in yo present (crezco) and all present subjunctive forms. All other tenses are regular -er.',
    present:     { yo:'crezco',   tu:'creces',    el:'crece',    nosotros:'crecemos',    vosotros:'crecéis',    ellos:'crecen'    },
    preterite:   { yo:'crecí',    tu:'creciste',  el:'creció',   nosotros:'crecimos',    vosotros:'crecisteis', ellos:'crecieron' },
    imperfect:   { yo:'crecía',   tu:'crecías',   el:'crecía',   nosotros:'crecíamos',   vosotros:'crecíais',   ellos:'crecían'   },
    future:      { yo:'creceré',  tu:'crecerás',  el:'crecerá',  nosotros:'creceremos',  vosotros:'creceréis',  ellos:'crecerán'  },
    conditional: { yo:'crecería', tu:'crecerías', el:'crecería', nosotros:'creceríamos', vosotros:'creceríais', ellos:'crecerían' },
    subjunctive: { yo:'crezca',   tu:'crezcas',   el:'crezca',   nosotros:'crezcamos',   vosotros:'crezcáis',   ellos:'crezcan'   },
  },
  {
    infinitive: 'elegir',
    meaning: 'to choose / to elect',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'E→I stem change + G→J in yo present (elijo). In preterite 3rd person E→I: eligió, eligieron. Subjunctive: elija…',
    present:     { yo:'elijo',    tu:'eliges',    el:'elige',    nosotros:'elegimos',    vosotros:'elegís',     ellos:'eligen'    },
    preterite:   { yo:'elegí',    tu:'elegiste',  el:'eligió',   nosotros:'elegimos',    vosotros:'elegisteis', ellos:'eligieron' },
    imperfect:   { yo:'elegía',   tu:'elegías',   el:'elegía',   nosotros:'elegíamos',   vosotros:'elegíais',   ellos:'elegían'   },
    future:      { yo:'elegiré',  tu:'elegirás',  el:'elegirá',  nosotros:'elegiremos',  vosotros:'elegiréis',  ellos:'elegirán'  },
    conditional: { yo:'elegiría', tu:'elegirías', el:'elegiría', nosotros:'elegiríamos', vosotros:'elegiríais', ellos:'elegirían' },
    subjunctive: { yo:'elija',    tu:'elijas',    el:'elija',    nosotros:'elijamos',    vosotros:'elijáis',    ellos:'elijan'    },
  },
];

export const CEFR_LEVELS = ['A1', 'A2', 'B1', 'B2'];
export const TYPES = [...new Set(VERBS.map(v => v.type))].sort();
