// Spanish verb conjugation tables — 30 key irregular verbs, A1–B2

export const VERB_TYPES = ['irregular', 'stem-changing', 'reflexive', 'regular'];
export const TENSES = ['present', 'preterite', 'imperfect', 'future', 'conditional', 'subjunctive'];
export const TENSE_LABELS = {
  present: 'Present', preterite: 'Preterite', imperfect: 'Imperfect',
  future: 'Future', conditional: 'Conditional', subjunctive: 'Subjunctive (pres.)',
};
export const FORMS = ['yo', 'tú', 'él/ella', 'nosotros', 'vosotros', 'ellos/ellas'];
export const FORM_KEYS = ['yo', 'tu', 'el', 'nosotros', 'vosotros', 'ellos'];

export const VERBS = [
  {
    infinitive: 'ser',
    meaning: 'to be (identity/permanent)',
    type: 'irregular',
    cefr: 'A1',
    note: 'Ser and estar both mean "to be" but are not interchangeable.',
    present:     { yo:'soy',    tu:'eres',    el:'es',      nosotros:'somos',    vosotros:'sois',      ellos:'son'      },
    preterite:   { yo:'fui',    tu:'fuiste',  el:'fue',     nosotros:'fuimos',   vosotros:'fuisteis',  ellos:'fueron'   },
    imperfect:   { yo:'era',    tu:'eras',    el:'era',     nosotros:'éramos',   vosotros:'erais',     ellos:'eran'     },
    future:      { yo:'seré',   tu:'serás',   el:'será',    nosotros:'seremos',  vosotros:'seréis',    ellos:'serán'    },
    conditional: { yo:'sería',  tu:'serías',  el:'sería',   nosotros:'seríamos', vosotros:'seríais',   ellos:'serían'   },
    subjunctive: { yo:'sea',    tu:'seas',    el:'sea',     nosotros:'seamos',   vosotros:'seáis',     ellos:'sean'     },
  },
  {
    infinitive: 'estar',
    meaning: 'to be (state/location)',
    type: 'irregular',
    cefr: 'A1',
    note: 'Use estar for temporary states, emotions, locations, and progressive tenses.',
    present:     { yo:'estoy',    tu:'estás',    el:'está',    nosotros:'estamos',    vosotros:'estáis',    ellos:'están'    },
    preterite:   { yo:'estuve',   tu:'estuviste', el:'estuvo',  nosotros:'estuvimos',  vosotros:'estuvisteis', ellos:'estuvieron' },
    imperfect:   { yo:'estaba',   tu:'estabas',  el:'estaba',  nosotros:'estábamos',  vosotros:'estabais',  ellos:'estaban'  },
    future:      { yo:'estaré',   tu:'estarás',  el:'estará',  nosotros:'estaremos',  vosotros:'estaréis',  ellos:'estarán'  },
    conditional: { yo:'estaría',  tu:'estarías', el:'estaría', nosotros:'estaríamos', vosotros:'estaríais', ellos:'estarían' },
    subjunctive: { yo:'esté',     tu:'estés',    el:'esté',    nosotros:'estemos',    vosotros:'estéis',    ellos:'estén'    },
  },
  {
    infinitive: 'tener',
    meaning: 'to have',
    type: 'irregular',
    cefr: 'A1',
    note: 'Tener que + infinitive = to have to do something.',
    present:     { yo:'tengo',   tu:'tienes',   el:'tiene',   nosotros:'tenemos',   vosotros:'tenéis',   ellos:'tienen'   },
    preterite:   { yo:'tuve',    tu:'tuviste',  el:'tuvo',    nosotros:'tuvimos',   vosotros:'tuvisteis', ellos:'tuvieron' },
    imperfect:   { yo:'tenía',   tu:'tenías',   el:'tenía',   nosotros:'teníamos',  vosotros:'teníais',  ellos:'tenían'   },
    future:      { yo:'tendré',  tu:'tendrás',  el:'tendrá',  nosotros:'tendremos', vosotros:'tendréis', ellos:'tendrán'  },
    conditional: { yo:'tendría', tu:'tendrías', el:'tendría', nosotros:'tendríamos',vosotros:'tendríais',ellos:'tendrían' },
    subjunctive: { yo:'tenga',   tu:'tengas',   el:'tenga',   nosotros:'tengamos',  vosotros:'tengáis',  ellos:'tengan'   },
  },
  {
    infinitive: 'ir',
    meaning: 'to go',
    type: 'irregular',
    cefr: 'A1',
    note: 'Ir a + infinitive forms the near future. Preterite identical to ser.',
    present:     { yo:'voy',   tu:'vas',    el:'va',    nosotros:'vamos',   vosotros:'vais',     ellos:'van'     },
    preterite:   { yo:'fui',   tu:'fuiste', el:'fue',   nosotros:'fuimos',  vosotros:'fuisteis', ellos:'fueron'  },
    imperfect:   { yo:'iba',   tu:'ibas',   el:'iba',   nosotros:'íbamos',  vosotros:'ibais',    ellos:'iban'    },
    future:      { yo:'iré',   tu:'irás',   el:'irá',   nosotros:'iremos',  vosotros:'iréis',    ellos:'irán'    },
    conditional: { yo:'iría',  tu:'irías',  el:'iría',  nosotros:'iríamos', vosotros:'iríais',   ellos:'irían'   },
    subjunctive: { yo:'vaya',  tu:'vayas',  el:'vaya',  nosotros:'vayamos', vosotros:'vayáis',   ellos:'vayan'   },
  },
  {
    infinitive: 'hacer',
    meaning: 'to do / to make',
    type: 'irregular',
    cefr: 'A1',
    note: 'Hacer is used in weather expressions: hace calor, hace frío.',
    present:     { yo:'hago',   tu:'haces',   el:'hace',   nosotros:'hacemos',   vosotros:'hacéis',   ellos:'hacen'   },
    preterite:   { yo:'hice',   tu:'hiciste', el:'hizo',   nosotros:'hicimos',   vosotros:'hicisteis',ellos:'hicieron'},
    imperfect:   { yo:'hacía',  tu:'hacías',  el:'hacía',  nosotros:'hacíamos',  vosotros:'hacíais',  ellos:'hacían'  },
    future:      { yo:'haré',   tu:'harás',   el:'hará',   nosotros:'haremos',   vosotros:'haréis',   ellos:'harán'   },
    conditional: { yo:'haría',  tu:'harías',  el:'haría',  nosotros:'haríamos',  vosotros:'haríais',  ellos:'harían'  },
    subjunctive: { yo:'haga',   tu:'hagas',   el:'haga',   nosotros:'hagamos',   vosotros:'hagáis',   ellos:'hagan'   },
  },
  {
    infinitive: 'poder',
    meaning: 'to be able to / can',
    type: 'stem-changing',
    cefr: 'A1',
    note: 'O→UE stem change in present (except nosotros/vosotros).',
    present:     { yo:'puedo',    tu:'puedes',   el:'puede',   nosotros:'podemos',   vosotros:'podéis',   ellos:'pueden'   },
    preterite:   { yo:'pude',     tu:'pudiste',  el:'pudo',    nosotros:'pudimos',   vosotros:'pudisteis',ellos:'pudieron' },
    imperfect:   { yo:'podía',    tu:'podías',   el:'podía',   nosotros:'podíamos',  vosotros:'podíais',  ellos:'podían'   },
    future:      { yo:'podré',    tu:'podrás',   el:'podrá',   nosotros:'podremos',  vosotros:'podréis',  ellos:'podrán'   },
    conditional: { yo:'podría',   tu:'podrías',  el:'podría',  nosotros:'podríamos', vosotros:'podríais', ellos:'podrían'  },
    subjunctive: { yo:'pueda',    tu:'puedas',   el:'pueda',   nosotros:'podamos',   vosotros:'podáis',   ellos:'puedan'   },
  },
  {
    infinitive: 'querer',
    meaning: 'to want / to love',
    type: 'stem-changing',
    cefr: 'A1',
    note: 'E→IE stem change in present. Querer a = to love a person.',
    present:     { yo:'quiero',   tu:'quieres',  el:'quiere',  nosotros:'queremos',  vosotros:'queréis',  ellos:'quieren'  },
    preterite:   { yo:'quise',    tu:'quisiste', el:'quiso',   nosotros:'quisimos',  vosotros:'quisisteis',ellos:'quisieron'},
    imperfect:   { yo:'quería',   tu:'querías',  el:'quería',  nosotros:'queríamos', vosotros:'queríais', ellos:'querían'  },
    future:      { yo:'querré',   tu:'querrás',  el:'querrá',  nosotros:'querremos', vosotros:'querréis', ellos:'querrán'  },
    conditional: { yo:'querría',  tu:'querrías', el:'querría', nosotros:'querríamos',vosotros:'querríais',ellos:'querrían' },
    subjunctive: { yo:'quiera',   tu:'quieras',  el:'quiera',  nosotros:'queramos',  vosotros:'queráis',  ellos:'quieran'  },
  },
  {
    infinitive: 'saber',
    meaning: 'to know (facts/how to)',
    type: 'irregular',
    cefr: 'A2',
    note: 'Saber = know a fact or how to do something. Conocer = know a person/place.',
    present:     { yo:'sé',     tu:'sabes',   el:'sabe',   nosotros:'sabemos',  vosotros:'sabéis',  ellos:'saben'   },
    preterite:   { yo:'supe',   tu:'supiste', el:'supo',   nosotros:'supimos',  vosotros:'supisteis',ellos:'supieron'},
    imperfect:   { yo:'sabía',  tu:'sabías',  el:'sabía',  nosotros:'sabíamos', vosotros:'sabíais', ellos:'sabían'  },
    future:      { yo:'sabré',  tu:'sabrás',  el:'sabrá',  nosotros:'sabremos', vosotros:'sabréis', ellos:'sabrán'  },
    conditional: { yo:'sabría', tu:'sabrías', el:'sabría', nosotros:'sabríamos',vosotros:'sabríais',ellos:'sabrían' },
    subjunctive: { yo:'sepa',   tu:'sepas',   el:'sepa',   nosotros:'sepamos',  vosotros:'sepáis',  ellos:'sepan'   },
  },
  {
    infinitive: 'venir',
    meaning: 'to come',
    type: 'irregular',
    cefr: 'A2',
    note: 'Venir de = to come from. Note irregular yo form.',
    present:     { yo:'vengo',   tu:'vienes',   el:'viene',   nosotros:'venimos',   vosotros:'venís',    ellos:'vienen'   },
    preterite:   { yo:'vine',    tu:'viniste',  el:'vino',    nosotros:'vinimos',   vosotros:'vinisteis',ellos:'vinieron' },
    imperfect:   { yo:'venía',   tu:'venías',   el:'venía',   nosotros:'veníamos',  vosotros:'veníais',  ellos:'venían'   },
    future:      { yo:'vendré',  tu:'vendrás',  el:'vendrá',  nosotros:'vendremos', vosotros:'vendréis', ellos:'vendrán'  },
    conditional: { yo:'vendría', tu:'vendrías', el:'vendría', nosotros:'vendríamos',vosotros:'vendríais',ellos:'vendrían' },
    subjunctive: { yo:'venga',   tu:'vengas',   el:'venga',   nosotros:'vengamos',  vosotros:'vengáis',  ellos:'vengan'   },
  },
  {
    infinitive: 'decir',
    meaning: 'to say / to tell',
    type: 'irregular',
    cefr: 'A2',
    note: 'E→I stem change. Irregular future/conditional stem (dir-).',
    present:     { yo:'digo',   tu:'dices',   el:'dice',   nosotros:'decimos',  vosotros:'decís',   ellos:'dicen'   },
    preterite:   { yo:'dije',   tu:'dijiste', el:'dijo',   nosotros:'dijimos',  vosotros:'dijisteis',ellos:'dijeron' },
    imperfect:   { yo:'decía',  tu:'decías',  el:'decía',  nosotros:'decíamos', vosotros:'decíais', ellos:'decían'  },
    future:      { yo:'diré',   tu:'dirás',   el:'dirá',   nosotros:'diremos',  vosotros:'diréis',  ellos:'dirán'   },
    conditional: { yo:'diría',  tu:'dirías',  el:'diría',  nosotros:'diríamos', vosotros:'diríais', ellos:'dirían'  },
    subjunctive: { yo:'diga',   tu:'digas',   el:'diga',   nosotros:'digamos',  vosotros:'digáis',  ellos:'digan'   },
  },
  {
    infinitive: 'poner',
    meaning: 'to put / to place',
    type: 'irregular',
    cefr: 'A2',
    note: 'Reflexive ponerse = to put on (clothing) / to become (emotion).',
    present:     { yo:'pongo',   tu:'pones',   el:'pone',   nosotros:'ponemos',   vosotros:'ponéis',   ellos:'ponen'   },
    preterite:   { yo:'puse',    tu:'pusiste', el:'puso',   nosotros:'pusimos',   vosotros:'pusisteis',ellos:'pusieron'},
    imperfect:   { yo:'ponía',   tu:'ponías',  el:'ponía',  nosotros:'poníamos',  vosotros:'poníais',  ellos:'ponían'  },
    future:      { yo:'pondré',  tu:'pondrás', el:'pondrá', nosotros:'pondremos', vosotros:'pondréis', ellos:'pondrán' },
    conditional: { yo:'pondría', tu:'pondrías',el:'pondría',nosotros:'pondríamos',vosotros:'pondríais',ellos:'pondrían'},
    subjunctive: { yo:'ponga',   tu:'pongas',  el:'ponga',  nosotros:'pongamos',  vosotros:'pongáis',  ellos:'pongan'  },
  },
  {
    infinitive: 'traer',
    meaning: 'to bring',
    type: 'irregular',
    cefr: 'A2',
    note: 'Irregular yo present (traigo) and preterite (traje).',
    present:     { yo:'traigo',  tu:'traes',   el:'trae',   nosotros:'traemos',  vosotros:'traéis',  ellos:'traen'   },
    preterite:   { yo:'traje',   tu:'trajiste',el:'trajo',  nosotros:'trajimos', vosotros:'trajisteis',ellos:'trajeron'},
    imperfect:   { yo:'traía',   tu:'traías',  el:'traía',  nosotros:'traíamos', vosotros:'traíais', ellos:'traían'  },
    future:      { yo:'traeré',  tu:'traerás', el:'traerá', nosotros:'traeremos',vosotros:'traeréis',ellos:'traerán' },
    conditional: { yo:'traería', tu:'traerías',el:'traería',nosotros:'traeríamos',vosotros:'traeríais',ellos:'traerían'},
    subjunctive: { yo:'traiga',  tu:'traigas', el:'traiga', nosotros:'traigamos',vosotros:'traigáis',ellos:'traigan' },
  },
  {
    infinitive: 'dar',
    meaning: 'to give',
    type: 'irregular',
    cefr: 'A2',
    note: 'Monosyllabic — no accent on preterite di/dio. Used in many fixed expressions.',
    present:     { yo:'doy',  tu:'das',    el:'da',    nosotros:'damos',  vosotros:'dais',   ellos:'dan'    },
    preterite:   { yo:'di',   tu:'diste',  el:'dio',   nosotros:'dimos',  vosotros:'disteis',ellos:'dieron' },
    imperfect:   { yo:'daba', tu:'dabas',  el:'daba',  nosotros:'dábamos',vosotros:'dabais', ellos:'daban'  },
    future:      { yo:'daré', tu:'darás',  el:'dará',  nosotros:'daremos',vosotros:'daréis', ellos:'darán'  },
    conditional: { yo:'daría',tu:'darías', el:'daría', nosotros:'daríamos',vosotros:'daríais',ellos:'darían' },
    subjunctive: { yo:'dé',   tu:'des',    el:'dé',    nosotros:'demos',  vosotros:'deis',   ellos:'den'    },
  },
  {
    infinitive: 'ver',
    meaning: 'to see',
    type: 'irregular',
    cefr: 'A2',
    note: 'Unusual imperfect: veía, etc. (keeps the -e- from old form "veer").',
    present:     { yo:'veo',   tu:'ves',    el:'ve',    nosotros:'vemos',  vosotros:'veis',   ellos:'ven'    },
    preterite:   { yo:'vi',    tu:'viste',  el:'vio',   nosotros:'vimos',  vosotros:'visteis',ellos:'vieron' },
    imperfect:   { yo:'veía',  tu:'veías',  el:'veía',  nosotros:'veíamos',vosotros:'veíais', ellos:'veían'  },
    future:      { yo:'veré',  tu:'verás',  el:'verá',  nosotros:'veremos',vosotros:'veréis', ellos:'verán'  },
    conditional: { yo:'vería', tu:'verías', el:'vería', nosotros:'veríamos',vosotros:'veríais',ellos:'verían' },
    subjunctive: { yo:'vea',   tu:'veas',   el:'vea',   nosotros:'veamos', vosotros:'veáis',  ellos:'vean'   },
  },
  {
    infinitive: 'salir',
    meaning: 'to leave / to go out',
    type: 'irregular',
    cefr: 'A2',
    note: 'Irregular yo only in present (salgo). Salir con = to date someone.',
    present:     { yo:'salgo',   tu:'sales',   el:'sale',   nosotros:'salimos',   vosotros:'salís',    ellos:'salen'   },
    preterite:   { yo:'salí',    tu:'saliste', el:'salió',  nosotros:'salimos',   vosotros:'salisteis',ellos:'salieron'},
    imperfect:   { yo:'salía',   tu:'salías',  el:'salía',  nosotros:'salíamos',  vosotros:'salíais',  ellos:'salían'  },
    future:      { yo:'saldré',  tu:'saldrás', el:'saldrá', nosotros:'saldremos', vosotros:'saldréis', ellos:'saldrán' },
    conditional: { yo:'saldría', tu:'saldrías',el:'saldría',nosotros:'saldríamos',vosotros:'saldríais',ellos:'saldrían'},
    subjunctive: { yo:'salga',   tu:'salgas',  el:'salga',  nosotros:'salgamos',  vosotros:'salgáis',  ellos:'salgan'  },
  },
  {
    infinitive: 'conocer',
    meaning: 'to know (people/places)',
    type: 'irregular',
    cefr: 'A2',
    note: 'Only irregular in yo present (conozco). Conocer = acquaintance; saber = knowledge.',
    present:     { yo:'conozco',  tu:'conoces',  el:'conoce',  nosotros:'conocemos',  vosotros:'conocéis',  ellos:'conocen'  },
    preterite:   { yo:'conocí',   tu:'conociste',el:'conoció', nosotros:'conocimos',  vosotros:'conocisteis',ellos:'conocieron'},
    imperfect:   { yo:'conocía',  tu:'conocías', el:'conocía', nosotros:'conocíamos', vosotros:'conocíais', ellos:'conocían' },
    future:      { yo:'conoceré', tu:'conocerás',el:'conocerá',nosotros:'conoceremos',vosotros:'conoceréis',ellos:'conocerán'},
    conditional: { yo:'conocería',tu:'conocerías',el:'conocería',nosotros:'conoceríamos',vosotros:'conoceríais',ellos:'conocerían'},
    subjunctive: { yo:'conozca',  tu:'conozcas', el:'conozca', nosotros:'conozcamos', vosotros:'conozcáis', ellos:'conozcan' },
  },
  {
    infinitive: 'sentir',
    meaning: 'to feel / to regret',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'E→IE in present, E→I in preterite (3rd person) and subjunctive.',
    present:     { yo:'siento',  tu:'sientes',  el:'siente',  nosotros:'sentimos',  vosotros:'sentís',  ellos:'sienten' },
    preterite:   { yo:'sentí',   tu:'sentiste', el:'sintió',  nosotros:'sentimos',  vosotros:'sentisteis',ellos:'sintieron'},
    imperfect:   { yo:'sentía',  tu:'sentías',  el:'sentía',  nosotros:'sentíamos', vosotros:'sentíais',ellos:'sentían' },
    future:      { yo:'sentiré', tu:'sentirás', el:'sentirá', nosotros:'sentiremos',vosotros:'sentiréis',ellos:'sentirán'},
    conditional: { yo:'sentiría',tu:'sentirías',el:'sentiría',nosotros:'sentiríamos',vosotros:'sentiríais',ellos:'sentirían'},
    subjunctive: { yo:'sienta',  tu:'sientas',  el:'sienta',  nosotros:'sintamos',  vosotros:'sintáis', ellos:'sientan' },
  },
  {
    infinitive: 'dormir',
    meaning: 'to sleep',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'O→UE in present, O→U in preterite (3rd person) and subjunctive.',
    present:     { yo:'duermo',   tu:'duermes',  el:'duerme',  nosotros:'dormimos',  vosotros:'dormís',   ellos:'duermen' },
    preterite:   { yo:'dormí',    tu:'dormiste', el:'durmió',  nosotros:'dormimos',  vosotros:'dormisteis',ellos:'durmieron'},
    imperfect:   { yo:'dormía',   tu:'dormías',  el:'dormía',  nosotros:'dormíamos', vosotros:'dormíais', ellos:'dormían' },
    future:      { yo:'dormiré',  tu:'dormirás', el:'dormirá', nosotros:'dormiremos',vosotros:'dormiréis',ellos:'dormirán'},
    conditional: { yo:'dormiría', tu:'dormirías',el:'dormiría',nosotros:'dormiríamos',vosotros:'dormiríais',ellos:'dormirían'},
    subjunctive: { yo:'duerma',   tu:'duermas',  el:'duerma',  nosotros:'durmamos',  vosotros:'durmáis',  ellos:'duerman' },
  },
  {
    infinitive: 'jugar',
    meaning: 'to play (game/sport)',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'U→UE stem change in present. Jugar a = to play a sport.',
    present:     { yo:'juego',   tu:'juegas',  el:'juega',  nosotros:'jugamos',  vosotros:'jugáis',  ellos:'juegan'  },
    preterite:   { yo:'jugué',   tu:'jugaste', el:'jugó',   nosotros:'jugamos',  vosotros:'jugasteis',ellos:'jugaron' },
    imperfect:   { yo:'jugaba',  tu:'jugabas', el:'jugaba', nosotros:'jugábamos',vosotros:'jugabais',ellos:'jugaban' },
    future:      { yo:'jugaré',  tu:'jugarás', el:'jugará', nosotros:'jugaremos',vosotros:'jugaréis',ellos:'jugarán' },
    conditional: { yo:'jugaría', tu:'jugarías',el:'jugaría',nosotros:'jugaríamos',vosotros:'jugaríais',ellos:'jugarían'},
    subjunctive: { yo:'juegue',  tu:'juegues', el:'juegue', nosotros:'juguemos', vosotros:'juguéis', ellos:'jueguen' },
  },
  {
    infinitive: 'pedir',
    meaning: 'to ask for / to order',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'E→I in present (yo/tú/él/ellos) and preterite (3rd person). Also pedir prestado = to borrow.',
    present:     { yo:'pido',   tu:'pides',   el:'pide',   nosotros:'pedimos',  vosotros:'pedís',   ellos:'piden'   },
    preterite:   { yo:'pedí',   tu:'pediste', el:'pidió',  nosotros:'pedimos',  vosotros:'pedisteis',ellos:'pidieron'},
    imperfect:   { yo:'pedía',  tu:'pedías',  el:'pedía',  nosotros:'pedíamos', vosotros:'pedíais', ellos:'pedían'  },
    future:      { yo:'pediré', tu:'pedirás', el:'pedirá', nosotros:'pediremos',vosotros:'pediréis',ellos:'pedirán' },
    conditional: { yo:'pediría',tu:'pedirías',el:'pediría',nosotros:'pediríamos',vosotros:'pediríais',ellos:'pedirían'},
    subjunctive: { yo:'pida',   tu:'pidas',   el:'pida',   nosotros:'pidamos',  vosotros:'pidáis',  ellos:'pidan'   },
  },
  {
    infinitive: 'seguir',
    meaning: 'to follow / to continue',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'E→I. Yo present: sigo (gu→g before a/o). Seguir + gerund = to keep doing.',
    present:     { yo:'sigo',    tu:'sigues',   el:'sigue',   nosotros:'seguimos',  vosotros:'seguís',   ellos:'siguen'  },
    preterite:   { yo:'seguí',   tu:'seguiste', el:'siguió',  nosotros:'seguimos',  vosotros:'seguisteis',ellos:'siguieron'},
    imperfect:   { yo:'seguía',  tu:'seguías',  el:'seguía',  nosotros:'seguíamos', vosotros:'seguíais', ellos:'seguían' },
    future:      { yo:'seguiré', tu:'seguirás', el:'seguirá', nosotros:'seguiremos',vosotros:'seguiréis',ellos:'seguirán'},
    conditional: { yo:'seguiría',tu:'seguirías',el:'seguiría',nosotros:'seguiríamos',vosotros:'seguiríais',ellos:'seguirían'},
    subjunctive: { yo:'siga',    tu:'sigas',    el:'siga',    nosotros:'sigamos',   vosotros:'sigáis',   ellos:'sigan'   },
  },
  {
    infinitive: 'oír',
    meaning: 'to hear',
    type: 'irregular',
    cefr: 'B1',
    note: 'I→Y before stressed vowel. Oír ≠ escuchar (oír = perceive sound, escuchar = listen actively).',
    present:     { yo:'oigo',  tu:'oyes',   el:'oye',   nosotros:'oímos',  vosotros:'oís',    ellos:'oyen'   },
    preterite:   { yo:'oí',    tu:'oíste',  el:'oyó',   nosotros:'oímos',  vosotros:'oísteis',ellos:'oyeron' },
    imperfect:   { yo:'oía',   tu:'oías',   el:'oía',   nosotros:'oíamos', vosotros:'oíais',  ellos:'oían'   },
    future:      { yo:'oiré',  tu:'oirás',  el:'oirá',  nosotros:'oiremos',vosotros:'oiréis', ellos:'oirán'  },
    conditional: { yo:'oiría', tu:'oirías', el:'oiría', nosotros:'oiríamos',vosotros:'oiríais',ellos:'oirían' },
    subjunctive: { yo:'oiga',  tu:'oigas',  el:'oiga',  nosotros:'oigamos',vosotros:'oigáis', ellos:'oigan'  },
  },
  {
    infinitive: 'caer',
    meaning: 'to fall',
    type: 'irregular',
    cefr: 'B1',
    note: 'Caer bien/mal = to like/dislike (a person). Caerse = to fall over (reflexive).',
    present:     { yo:'caigo',  tu:'caes',   el:'cae',   nosotros:'caemos',  vosotros:'caéis',  ellos:'caen'   },
    preterite:   { yo:'caí',    tu:'caíste', el:'cayó',  nosotros:'caímos',  vosotros:'caísteis',ellos:'cayeron'},
    imperfect:   { yo:'caía',   tu:'caías',  el:'caía',  nosotros:'caíamos', vosotros:'caíais', ellos:'caían'  },
    future:      { yo:'caeré',  tu:'caerás', el:'caerá', nosotros:'caeremos',vosotros:'caeréis',ellos:'caerán' },
    conditional: { yo:'caería', tu:'caerías',el:'caería',nosotros:'caeríamos',vosotros:'caeríais',ellos:'caerían'},
    subjunctive: { yo:'caiga',  tu:'caigas', el:'caiga', nosotros:'caigamos',vosotros:'caigáis',ellos:'caigan' },
  },
  {
    infinitive: 'volver',
    meaning: 'to return / to come back',
    type: 'stem-changing',
    cefr: 'A2',
    note: 'O→UE in present. Volver a + infinitive = to do something again.',
    present:     { yo:'vuelvo',   tu:'vuelves',  el:'vuelve',  nosotros:'volvemos',  vosotros:'volvéis',  ellos:'vuelven' },
    preterite:   { yo:'volví',    tu:'volviste', el:'volvió',  nosotros:'volvimos',  vosotros:'volvisteis',ellos:'volvieron'},
    imperfect:   { yo:'volvía',   tu:'volvías',  el:'volvía',  nosotros:'volvíamos', vosotros:'volvíais', ellos:'volvían' },
    future:      { yo:'volveré',  tu:'volverás', el:'volverá', nosotros:'volveremos',vosotros:'volveréis',ellos:'volverán'},
    conditional: { yo:'volvería', tu:'volverías',el:'volvería',nosotros:'volveríamos',vosotros:'volveríais',ellos:'volverían'},
    subjunctive: { yo:'vuelva',   tu:'vuelvas',  el:'vuelva',  nosotros:'volvamos',  vosotros:'volváis',  ellos:'vuelvan' },
  },
  {
    infinitive: 'haber',
    meaning: 'to have (auxiliary)',
    type: 'irregular',
    cefr: 'B1',
    note: 'Used only as auxiliary (he comido = I have eaten). Hay = there is/are (impersonal).',
    present:     { yo:'he',      tu:'has',     el:'ha',     nosotros:'hemos',    vosotros:'habéis',   ellos:'han'      },
    preterite:   { yo:'hube',    tu:'hubiste', el:'hubo',   nosotros:'hubimos',  vosotros:'hubisteis',ellos:'hubieron' },
    imperfect:   { yo:'había',   tu:'habías',  el:'había',  nosotros:'habíamos', vosotros:'habíais',  ellos:'habían'   },
    future:      { yo:'habré',   tu:'habrás',  el:'habrá',  nosotros:'habremos', vosotros:'habréis',  ellos:'habrán'   },
    conditional: { yo:'habría',  tu:'habrías', el:'habría', nosotros:'habríamos',vosotros:'habríais', ellos:'habrían'  },
    subjunctive: { yo:'haya',    tu:'hayas',   el:'haya',   nosotros:'hayamos',  vosotros:'hayáis',   ellos:'hayan'    },
  },
  {
    infinitive: 'morir',
    meaning: 'to die',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'O→UE in present, O→U in preterite (3rd). Past participle: muerto.',
    present:     { yo:'muero',   tu:'mueres',  el:'muere',  nosotros:'morimos',  vosotros:'morís',   ellos:'mueren'  },
    preterite:   { yo:'morí',    tu:'moriste', el:'murió',  nosotros:'morimos',  vosotros:'moristeis',ellos:'murieron'},
    imperfect:   { yo:'moría',   tu:'morías',  el:'moría',  nosotros:'moríamos', vosotros:'moríais', ellos:'morían'  },
    future:      { yo:'moriré',  tu:'morirás', el:'morirá', nosotros:'moriremos',vosotros:'moriréis',ellos:'morirán' },
    conditional: { yo:'moriría', tu:'morirías',el:'moriría',nosotros:'moriríamos',vosotros:'moriríais',ellos:'morirían'},
    subjunctive: { yo:'muera',   tu:'mueras',  el:'muera',  nosotros:'muramos',  vosotros:'muráis',  ellos:'mueran'  },
  },
  {
    infinitive: 'reír',
    meaning: 'to laugh',
    type: 'stem-changing',
    cefr: 'B1',
    note: 'E→Í in present (yo/tú/él/ellos). Reírse de = to laugh at.',
    present:     { yo:'río',    tu:'ríes',   el:'ríe',   nosotros:'reímos', vosotros:'reís',    ellos:'ríen'   },
    preterite:   { yo:'reí',    tu:'reíste', el:'rió',   nosotros:'reímos', vosotros:'reísteis',ellos:'rieron' },
    imperfect:   { yo:'reía',   tu:'reías',  el:'reía',  nosotros:'reíamos',vosotros:'reíais',  ellos:'reían'  },
    future:      { yo:'reiré',  tu:'reirás', el:'reirá', nosotros:'reiremos',vosotros:'reiréis',ellos:'reirán' },
    conditional: { yo:'reiría', tu:'reirías',el:'reiría',nosotros:'reiríamos',vosotros:'reiríais',ellos:'reirían'},
    subjunctive: { yo:'ría',    tu:'rías',   el:'ría',   nosotros:'riamos', vosotros:'riáis',   ellos:'rían'   },
  },
  {
    infinitive: 'construir',
    meaning: 'to build / to construct',
    type: 'irregular',
    cefr: 'B1',
    note: 'I→Y before stressed vowel (like oír/huir). Common pattern for -uir verbs.',
    present:     { yo:'construyo',  tu:'construyes', el:'construye', nosotros:'construimos', vosotros:'construís', ellos:'construyen' },
    preterite:   { yo:'construí',   tu:'construiste',el:'construyó', nosotros:'construimos', vosotros:'construisteis',ellos:'construyeron'},
    imperfect:   { yo:'construía',  tu:'construías', el:'construía', nosotros:'construíamos',vosotros:'construíais',ellos:'construían' },
    future:      { yo:'construiré', tu:'construirás',el:'construirá',nosotros:'construiremos',vosotros:'construiréis',ellos:'construirán'},
    conditional: { yo:'construiría',tu:'construirías',el:'construiría',nosotros:'construiríamos',vosotros:'construiríais',ellos:'construirían'},
    subjunctive: { yo:'construya',  tu:'construyas', el:'construya', nosotros:'construyamos',vosotros:'construyáis',ellos:'construyan' },
  },
  {
    infinitive: 'producir',
    meaning: 'to produce',
    type: 'irregular',
    cefr: 'B1',
    note: 'C→ZC in yo present. Preterite: produje (like conducir, traducir).',
    present:     { yo:'produzco',  tu:'produces',  el:'produce',  nosotros:'producimos',  vosotros:'producís',  ellos:'producen' },
    preterite:   { yo:'produje',   tu:'produjiste',el:'produjo',  nosotros:'produjimos',  vosotros:'produjisteis',ellos:'produjeron'},
    imperfect:   { yo:'producía',  tu:'producías', el:'producía', nosotros:'producíamos', vosotros:'producíais',ellos:'producían' },
    future:      { yo:'produciré', tu:'producirás',el:'producirá',nosotros:'produciremos',vosotros:'produciréis',ellos:'producirán'},
    conditional: { yo:'produciría',tu:'producirías',el:'produciría',nosotros:'produciríamos',vosotros:'produciríais',ellos:'producirían'},
    subjunctive: { yo:'produzca',  tu:'produzcas', el:'produzca', nosotros:'produzcamos', vosotros:'produzcáis',ellos:'produzcan' },
  },
  {
    infinitive: 'leer',
    meaning: 'to read',
    type: 'irregular',
    cefr: 'A1',
    note: 'I→Y in preterite (3rd person). Written accent on past: leí, leíste, leímos.',
    present:     { yo:'leo',    tu:'lees',   el:'lee',   nosotros:'leemos',  vosotros:'leéis',  ellos:'leen'   },
    preterite:   { yo:'leí',    tu:'leíste', el:'leyó',  nosotros:'leímos',  vosotros:'leísteis',ellos:'leyeron'},
    imperfect:   { yo:'leía',   tu:'leías',  el:'leía',  nosotros:'leíamos', vosotros:'leíais', ellos:'leían'  },
    future:      { yo:'leeré',  tu:'leerás', el:'leerá', nosotros:'leeremos',vosotros:'leeréis',ellos:'leerán' },
    conditional: { yo:'leería', tu:'leerías',el:'leería',nosotros:'leeríamos',vosotros:'leeríais',ellos:'leerían'},
    subjunctive: { yo:'lea',    tu:'leas',   el:'lea',   nosotros:'leamos',  vosotros:'leáis',  ellos:'lean'   },
  },
  {
    infinitive: 'andar',
    meaning: 'to walk',
    type: 'irregular',
    cefr: 'A2',
    note: 'Only irregular in preterite (anduve, etc.). Common in colloquial use: ¿cómo andas?',
    present:     { yo:'ando',    tu:'andas',    el:'anda',   nosotros:'andamos',   vosotros:'andáis',   ellos:'andan'    },
    preterite:   { yo:'anduve',  tu:'anduviste',el:'anduvo', nosotros:'anduvimos', vosotros:'anduvisteis',ellos:'anduvieron'},
    imperfect:   { yo:'andaba',  tu:'andabas',  el:'andaba', nosotros:'andábamos', vosotros:'andabais', ellos:'andaban'  },
    future:      { yo:'andaré',  tu:'andarás',  el:'andará', nosotros:'andaremos', vosotros:'andaréis', ellos:'andarán'  },
    conditional: { yo:'andaría', tu:'andarías', el:'andaría',nosotros:'andaríamos',vosotros:'andaríais',ellos:'andarían' },
    subjunctive: { yo:'ande',    tu:'andes',    el:'ande',   nosotros:'andemos',   vosotros:'andéis',   ellos:'anden'    },
  },
  {
    infinitive: 'caber',
    meaning: 'to fit (inside)',
    type: 'irregular',
    cefr: 'B2',
    note: 'Highly irregular: yo cabe→quepo. Rarely taught early but very common.',
    present:     { yo:'quepo',   tu:'cabes',   el:'cabe',   nosotros:'cabemos',   vosotros:'cabéis',   ellos:'caben'   },
    preterite:   { yo:'cupe',    tu:'cupiste', el:'cupo',   nosotros:'cupimos',   vosotros:'cupisteis',ellos:'cupieron'},
    imperfect:   { yo:'cabía',   tu:'cabías',  el:'cabía',  nosotros:'cabíamos',  vosotros:'cabíais',  ellos:'cabían'  },
    future:      { yo:'cabré',   tu:'cabrás',  el:'cabrá',  nosotros:'cabremos',  vosotros:'cabréis',  ellos:'cabrán'  },
    conditional: { yo:'cabría',  tu:'cabrías', el:'cabría', nosotros:'cabríamos', vosotros:'cabríais', ellos:'cabrían' },
    subjunctive: { yo:'quepa',   tu:'quepas',  el:'quepa',  nosotros:'quepamos',  vosotros:'quepáis',  ellos:'quepan'  },
  },
];

export const CEFR_LEVELS = ['A1', 'A2', 'B1', 'B2'];
export const TYPES = [...new Set(VERBS.map(v => v.type))].sort();
