// Thematic vocabulary lists A1–B1
// Each entry: { es, en, cefr, domain, example, exampleEn, frequencyRank }
// frequencyRank: approximate rank in Spanish corpus (lower = more common)

export const VOCABULARY = [
  // ── GREETINGS & COURTESY ────────────────────────────────────────────────
  { es: 'hola', en: 'hello', cefr: 'A1', domain: 'greetings', frequencyRank: 50, example: '¡Hola! ¿Cómo estás?', exampleEn: 'Hello! How are you?' },
  { es: 'adiós', en: 'goodbye', cefr: 'A1', domain: 'greetings', frequencyRank: 200, example: 'Adiós, hasta mañana.', exampleEn: 'Goodbye, see you tomorrow.' },
  { es: 'buenos días', en: 'good morning', cefr: 'A1', domain: 'greetings', frequencyRank: 300, example: '—Buenos días. ¿Qué tal?', exampleEn: 'Good morning. How are things?' },
  { es: 'buenas tardes', en: 'good afternoon', cefr: 'A1', domain: 'greetings', frequencyRank: 350, example: 'Buenas tardes, señora García.', exampleEn: 'Good afternoon, Mrs García.' },
  { es: 'buenas noches', en: 'good evening / good night', cefr: 'A1', domain: 'greetings', frequencyRank: 360, example: '—Buenas noches. —Hasta mañana.', exampleEn: 'Good night. — See you tomorrow.' },
  { es: 'hasta luego', en: 'see you later', cefr: 'A1', domain: 'greetings', frequencyRank: 400, example: 'Hasta luego, amigo.', exampleEn: 'See you later, friend.' },
  { es: 'hasta mañana', en: 'see you tomorrow', cefr: 'A1', domain: 'greetings', frequencyRank: 420, example: '—Buenas noches. —Hasta mañana.', exampleEn: 'Good night. — See you tomorrow.' },
  { es: 'por favor', en: 'please', cefr: 'A1', domain: 'greetings', frequencyRank: 80, example: 'Un café, por favor.', exampleEn: 'A coffee, please.' },
  { es: 'gracias', en: 'thank you', cefr: 'A1', domain: 'greetings', frequencyRank: 90, example: '—Gracias. —De nada.', exampleEn: 'Thank you. — You\'re welcome.' },
  { es: 'de nada', en: 'you\'re welcome', cefr: 'A1', domain: 'greetings', frequencyRank: 350, example: '—Gracias. —De nada.', exampleEn: 'Thank you. — You\'re welcome.' },
  { es: 'perdón', en: 'excuse me / sorry', cefr: 'A1', domain: 'greetings', frequencyRank: 450, example: 'Perdón, ¿dónde está el baño?', exampleEn: 'Excuse me, where is the bathroom?' },
  { es: 'lo siento', en: 'I\'m sorry', cefr: 'A1', domain: 'greetings', frequencyRank: 500, example: 'Lo siento, llegué tarde.', exampleEn: 'I\'m sorry, I arrived late.' },

  // ── NUMBERS ──────────────────────────────────────────────────────────────
  { es: 'uno', en: 'one', cefr: 'A1', domain: 'numbers', frequencyRank: 30, example: 'Tengo un hermano.', exampleEn: 'I have one brother.' },
  { es: 'dos', en: 'two', cefr: 'A1', domain: 'numbers', frequencyRank: 35, example: 'Hay dos puertas.', exampleEn: 'There are two doors.' },
  { es: 'tres', en: 'three', cefr: 'A1', domain: 'numbers', frequencyRank: 40, example: 'Compré tres manzanas.', exampleEn: 'I bought three apples.' },
  { es: 'cuatro', en: 'four', cefr: 'A1', domain: 'numbers', frequencyRank: 55, example: 'Son las cuatro en punto.', exampleEn: 'It\'s four o\'clock exactly.' },
  { es: 'cinco', en: 'five', cefr: 'A1', domain: 'numbers', frequencyRank: 60, example: 'Cinco más cinco son diez.', exampleEn: 'Five plus five is ten.' },
  { es: 'seis', en: 'six', cefr: 'A1', domain: 'numbers', frequencyRank: 62, example: 'Hay seis días hasta el fin de semana.', exampleEn: 'There are six days until the weekend.' },
  { es: 'siete', en: 'seven', cefr: 'A1', domain: 'numbers', frequencyRank: 64, example: 'La semana tiene siete días.', exampleEn: 'A week has seven days.' },
  { es: 'ocho', en: 'eight', cefr: 'A1', domain: 'numbers', frequencyRank: 66, example: 'Trabajo ocho horas al día.', exampleEn: 'I work eight hours a day.' },
  { es: 'nueve', en: 'nine', cefr: 'A1', domain: 'numbers', frequencyRank: 68, example: 'El bebé tiene nueve meses.', exampleEn: 'The baby is nine months old.' },
  { es: 'diez', en: 'ten', cefr: 'A1', domain: 'numbers', frequencyRank: 70, example: 'Cuesta diez euros.', exampleEn: 'It costs ten euros.' },
  { es: 'veinte', en: 'twenty', cefr: 'A1', domain: 'numbers', frequencyRank: 120, example: 'Tengo veinte años.', exampleEn: 'I am twenty years old.' },
  { es: 'cien', en: 'a hundred', cefr: 'A1', domain: 'numbers', frequencyRank: 150, example: 'Cien personas vinieron.', exampleEn: 'A hundred people came.' },
  { es: 'mil', en: 'a thousand', cefr: 'A1', domain: 'numbers', frequencyRank: 180, example: 'El coche cuesta diez mil euros.', exampleEn: 'The car costs ten thousand euros.' },

  // ── DAYS & TIME ──────────────────────────────────────────────────────────
  { es: 'lunes', en: 'Monday', cefr: 'A1', domain: 'time', frequencyRank: 600, example: 'El lunes tengo clase.', exampleEn: 'On Monday I have class.' },
  { es: 'martes', en: 'Tuesday', cefr: 'A1', domain: 'time', frequencyRank: 620, example: 'El martes hay reunión.', exampleEn: 'On Tuesday there\'s a meeting.' },
  { es: 'miércoles', en: 'Wednesday', cefr: 'A1', domain: 'time', frequencyRank: 640, example: 'Miércoles es el día de la semana.', exampleEn: 'Wednesday is the middle of the week.' },
  { es: 'jueves', en: 'Thursday', cefr: 'A1', domain: 'time', frequencyRank: 660, example: 'El jueves comemos juntos.', exampleEn: 'On Thursday we eat together.' },
  { es: 'viernes', en: 'Friday', cefr: 'A1', domain: 'time', frequencyRank: 680, example: 'El viernes salimos de fiesta.', exampleEn: 'On Friday we go out.' },
  { es: 'sábado', en: 'Saturday', cefr: 'A1', domain: 'time', frequencyRank: 700, example: 'El sábado descanso.', exampleEn: 'On Saturday I rest.' },
  { es: 'domingo', en: 'Sunday', cefr: 'A1', domain: 'time', frequencyRank: 720, example: 'El domingo voy a la iglesia.', exampleEn: 'On Sunday I go to church.' },
  { es: 'hoy', en: 'today', cefr: 'A1', domain: 'time', frequencyRank: 85, example: 'Hoy es lunes.', exampleEn: 'Today is Monday.' },
  { es: 'mañana', en: 'tomorrow / morning', cefr: 'A1', domain: 'time', frequencyRank: 100, example: 'Mañana viene Ana.', exampleEn: 'Tomorrow Ana is coming.' },
  { es: 'ayer', en: 'yesterday', cefr: 'A1', domain: 'time', frequencyRank: 130, example: 'Ayer fui al médico.', exampleEn: 'Yesterday I went to the doctor.' },
  { es: 'ahora', en: 'now', cefr: 'A1', domain: 'time', frequencyRank: 45, example: '¿Puedes venir ahora?', exampleEn: 'Can you come now?' },
  { es: 'siempre', en: 'always', cefr: 'A1', domain: 'time', frequencyRank: 110, example: 'Siempre llega tarde.', exampleEn: 'He always arrives late.' },
  { es: 'nunca', en: 'never', cefr: 'A1', domain: 'time', frequencyRank: 115, example: 'Nunca como carne.', exampleEn: 'I never eat meat.' },

  // ── COLORS ──────────────────────────────────────────────────────────────
  { es: 'rojo', en: 'red', cefr: 'A1', domain: 'colors', frequencyRank: 800, example: 'El semáforo está en rojo.', exampleEn: 'The traffic light is red.' },
  { es: 'azul', en: 'blue', cefr: 'A1', domain: 'colors', frequencyRank: 820, example: 'El cielo es azul.', exampleEn: 'The sky is blue.' },
  { es: 'verde', en: 'green', cefr: 'A1', domain: 'colors', frequencyRank: 840, example: 'La hierba es verde.', exampleEn: 'The grass is green.' },
  { es: 'amarillo', en: 'yellow', cefr: 'A1', domain: 'colors', frequencyRank: 860, example: 'El sol es amarillo.', exampleEn: 'The sun is yellow.' },
  { es: 'blanco', en: 'white', cefr: 'A1', domain: 'colors', frequencyRank: 750, example: 'La nieve es blanca.', exampleEn: 'The snow is white.' },
  { es: 'negro', en: 'black', cefr: 'A1', domain: 'colors', frequencyRank: 760, example: 'Llevo un vestido negro.', exampleEn: 'I\'m wearing a black dress.' },
  { es: 'naranja', en: 'orange', cefr: 'A1', domain: 'colors', frequencyRank: 900, example: 'Le gusta el color naranja.', exampleEn: 'She likes the color orange.' },
  { es: 'morado', en: 'purple', cefr: 'A1', domain: 'colors', frequencyRank: 920, example: 'Las flores son moradas.', exampleEn: 'The flowers are purple.' },
  { es: 'rosa', en: 'pink', cefr: 'A1', domain: 'colors', frequencyRank: 910, example: 'El flamenco es rosa.', exampleEn: 'The flamingo is pink.' },
  { es: 'gris', en: 'grey', cefr: 'A1', domain: 'colors', frequencyRank: 870, example: 'El cielo está gris hoy.', exampleEn: 'The sky is grey today.' },
  { es: 'marrón', en: 'brown', cefr: 'A1', domain: 'colors', frequencyRank: 890, example: 'Tiene los ojos marrones.', exampleEn: 'She has brown eyes.' },

  // ── FAMILY ──────────────────────────────────────────────────────────────
  { es: 'madre', en: 'mother', cefr: 'A1', domain: 'family', frequencyRank: 180, example: 'Mi madre cocina muy bien.', exampleEn: 'My mother cooks very well.' },
  { es: 'padre', en: 'father', cefr: 'A1', domain: 'family', frequencyRank: 190, example: 'Mi padre trabaja en un banco.', exampleEn: 'My father works in a bank.' },
  { es: 'hermano', en: 'brother', cefr: 'A1', domain: 'family', frequencyRank: 210, example: 'Tengo un hermano mayor.', exampleEn: 'I have an older brother.' },
  { es: 'hermana', en: 'sister', cefr: 'A1', domain: 'family', frequencyRank: 215, example: 'Mi hermana vive en Barcelona.', exampleEn: 'My sister lives in Barcelona.' },
  { es: 'hijo', en: 'son', cefr: 'A1', domain: 'family', frequencyRank: 160, example: 'Mi hijo tiene cinco años.', exampleEn: 'My son is five years old.' },
  { es: 'hija', en: 'daughter', cefr: 'A1', domain: 'family', frequencyRank: 165, example: 'Su hija estudia medicina.', exampleEn: 'His daughter studies medicine.' },
  { es: 'abuelo', en: 'grandfather', cefr: 'A1', domain: 'family', frequencyRank: 300, example: 'Mi abuelo tiene ochenta años.', exampleEn: 'My grandfather is eighty years old.' },
  { es: 'abuela', en: 'grandmother', cefr: 'A1', domain: 'family', frequencyRank: 305, example: 'La abuela hace paella los domingos.', exampleEn: 'Grandma makes paella on Sundays.' },
  { es: 'esposo', en: 'husband', cefr: 'A1', domain: 'family', frequencyRank: 350, example: 'Su esposo es médico.', exampleEn: 'Her husband is a doctor.' },
  { es: 'esposa', en: 'wife', cefr: 'A1', domain: 'family', frequencyRank: 355, example: 'Mi esposa habla cuatro idiomas.', exampleEn: 'My wife speaks four languages.' },
  { es: 'amigo', en: 'friend (m)', cefr: 'A1', domain: 'family', frequencyRank: 140, example: 'Es mi mejor amigo.', exampleEn: 'He\'s my best friend.' },
  { es: 'amiga', en: 'friend (f)', cefr: 'A1', domain: 'family', frequencyRank: 145, example: 'Mi amiga vive en Madrid.', exampleEn: 'My friend lives in Madrid.' },
  { es: 'tío', en: 'uncle', cefr: 'A1', domain: 'family', frequencyRank: 360, example: 'Mi tío vive en Barcelona.', exampleEn: 'My uncle lives in Barcelona.' },
  { es: 'tía', en: 'aunt', cefr: 'A1', domain: 'family', frequencyRank: 365, example: 'Mi tía cocina muy bien.', exampleEn: 'My aunt cooks very well.' },
  { es: 'primo', en: 'cousin (m)', cefr: 'A1', domain: 'family', frequencyRank: 370, example: 'Mi primo tiene dos años más que yo.', exampleEn: 'My cousin is two years older than me.' },
  { es: 'prima', en: 'cousin (f)', cefr: 'A1', domain: 'family', frequencyRank: 375, example: 'Mis primas vienen de visita.', exampleEn: 'My cousins are coming to visit.' },
  { es: 'novio', en: 'boyfriend / fiancé', cefr: 'A1', domain: 'family', frequencyRank: 380, example: 'Te presento a mi novio.', exampleEn: 'Let me introduce you to my boyfriend.' },
  { es: 'novia', en: 'girlfriend / fiancée', cefr: 'A1', domain: 'family', frequencyRank: 385, example: 'Su novia es periodista.', exampleEn: 'His girlfriend is a journalist.' },
  { es: 'pareja', en: 'partner / couple', cefr: 'A2', domain: 'family', frequencyRank: 390, example: 'Mi pareja y yo vivimos juntos.', exampleEn: 'My partner and I live together.' },
  { es: 'sobrino', en: 'nephew', cefr: 'A2', domain: 'family', frequencyRank: 395, example: 'Tengo dos sobrinos.', exampleEn: 'I have two nephews.' },
  { es: 'cuñado', en: 'brother-in-law', cefr: 'A2', domain: 'family', frequencyRank: 400, example: 'Mi cuñado trabaja en Madrid.', exampleEn: 'My brother-in-law works in Madrid.' },

  // ── FOOD & DRINK ────────────────────────────────────────────────────────
  { es: 'agua', en: 'water', cefr: 'A1', domain: 'food', frequencyRank: 170, example: 'Quiero un vaso de agua.', exampleEn: 'I want a glass of water.' },
  { es: 'pan', en: 'bread', cefr: 'A1', domain: 'food', frequencyRank: 380, example: 'Compro pan cada mañana.', exampleEn: 'I buy bread every morning.' },
  { es: 'leche', en: 'milk', cefr: 'A1', domain: 'food', frequencyRank: 420, example: 'El niño bebe leche.', exampleEn: 'The child drinks milk.' },
  { es: 'café', en: 'coffee', cefr: 'A1', domain: 'food', frequencyRank: 440, example: 'Tomo un café con leche.', exampleEn: 'I have a coffee with milk.' },
  { es: 'vino', en: 'wine', cefr: 'A1', domain: 'food', frequencyRank: 500, example: 'Un vaso de vino tinto, por favor.', exampleEn: 'A glass of red wine, please.' },
  { es: 'cerveza', en: 'beer', cefr: 'A1', domain: 'food', frequencyRank: 520, example: 'Dos cervezas, por favor.', exampleEn: 'Two beers, please.' },
  { es: 'pollo', en: 'chicken', cefr: 'A1', domain: 'food', frequencyRank: 560, example: 'El pollo está muy rico.', exampleEn: 'The chicken is very tasty.' },
  { es: 'arroz', en: 'rice', cefr: 'A1', domain: 'food', frequencyRank: 580, example: 'Como arroz todos los días.', exampleEn: 'I eat rice every day.' },
  { es: 'manzana', en: 'apple', cefr: 'A1', domain: 'food', frequencyRank: 600, example: 'Una manzana al día.', exampleEn: 'An apple a day.' },
  { es: 'queso', en: 'cheese', cefr: 'A1', domain: 'food', frequencyRank: 620, example: 'Me gusta el queso manchego.', exampleEn: 'I like manchego cheese.' },
  { es: 'carne', en: 'meat', cefr: 'A1', domain: 'food', frequencyRank: 400, example: '¿Comes carne o eres vegetariano?', exampleEn: 'Do you eat meat or are you vegetarian?' },
  { es: 'pescado', en: 'fish', cefr: 'A1', domain: 'food', frequencyRank: 550, example: 'El pescado es muy sano.', exampleEn: 'Fish is very healthy.' },
  { es: 'verduras', en: 'vegetables', cefr: 'A1', domain: 'food', frequencyRank: 480, example: 'Como muchas verduras.', exampleEn: 'I eat lots of vegetables.' },
  { es: 'fruta', en: 'fruit', cefr: 'A1', domain: 'food', frequencyRank: 490, example: 'La fruta es buena para la salud.', exampleEn: 'Fruit is good for health.' },
  { es: 'ensalada', en: 'salad', cefr: 'A1', domain: 'food', frequencyRank: 640, example: 'Pide una ensalada mixta.', exampleEn: 'Order a mixed salad.' },
  { es: 'sopa', en: 'soup', cefr: 'A1', domain: 'food', frequencyRank: 660, example: 'La sopa está caliente.', exampleEn: 'The soup is hot.' },
  { es: 'huevo', en: 'egg', cefr: 'A1', domain: 'food', frequencyRank: 540, example: 'Me gustan los huevos fritos.', exampleEn: 'I like fried eggs.' },
  // More A1 food
  { es: 'naranja', en: 'orange (fruit)', cefr: 'A1', domain: 'food', frequencyRank: 680, example: 'Bebo zumo de naranja.', exampleEn: 'I drink orange juice.' },
  { es: 'plátano', en: 'banana', cefr: 'A1', domain: 'food', frequencyRank: 700, example: 'Como un plátano de postre.', exampleEn: 'I eat a banana for dessert.' },
  { es: 'tomate', en: 'tomato', cefr: 'A1', domain: 'food', frequencyRank: 720, example: 'La ensalada lleva tomate.', exampleEn: 'The salad has tomato.' },
  { es: 'patata', en: 'potato (Spain); papa (LatAm)', cefr: 'A1', domain: 'food', frequencyRank: 740, example: 'Me gustan las patatas fritas.', exampleEn: 'I like chips / french fries.' },
  { es: 'jamón', en: 'ham', cefr: 'A1', domain: 'food', frequencyRank: 760, example: 'Un bocadillo de jamón, por favor.', exampleEn: 'A ham sandwich, please.' },
  { es: 'aceite', en: 'oil (esp. olive oil)', cefr: 'A2', domain: 'food', frequencyRank: 780, example: 'Cocino con aceite de oliva.', exampleEn: 'I cook with olive oil.' },
  { es: 'azúcar', en: 'sugar', cefr: 'A2', domain: 'food', frequencyRank: 800, example: '¿Quieres azúcar en el café?', exampleEn: 'Do you want sugar in your coffee?' },
  { es: 'sal', en: 'salt', cefr: 'A2', domain: 'food', frequencyRank: 820, example: 'Ponle sal a la sopa.', exampleEn: 'Add salt to the soup.' },
  { es: 'desayuno', en: 'breakfast', cefr: 'A1', domain: 'food', frequencyRank: 840, example: '¿Qué desayunas normalmente?', exampleEn: 'What do you usually have for breakfast?' },
  { es: 'almuerzo', en: 'lunch', cefr: 'A1', domain: 'food', frequencyRank: 860, example: 'Comemos el almuerzo a las dos.', exampleEn: 'We have lunch at two.' },
  { es: 'cena', en: 'dinner / supper', cefr: 'A1', domain: 'food', frequencyRank: 880, example: 'La cena está lista.', exampleEn: 'Dinner is ready.' },

  // ── PLACES ──────────────────────────────────────────────────────────────
  { es: 'casa', en: 'house / home', cefr: 'A1', domain: 'places', frequencyRank: 90, example: 'Estoy en casa.', exampleEn: 'I\'m at home.' },
  { es: 'escuela', en: 'school', cefr: 'A1', domain: 'places', frequencyRank: 280, example: 'Los niños van a la escuela.', exampleEn: 'The children go to school.' },
  { es: 'trabajo', en: 'work / job', cefr: 'A1', domain: 'places', frequencyRank: 95, example: 'Voy al trabajo en metro.', exampleEn: 'I go to work by metro.' },
  { es: 'restaurante', en: 'restaurant', cefr: 'A1', domain: 'places', frequencyRank: 460, example: 'Cenamos en un restaurante italiano.', exampleEn: 'We dined at an Italian restaurant.' },
  { es: 'tienda', en: 'shop / store', cefr: 'A1', domain: 'places', frequencyRank: 400, example: 'Hay una tienda cerca de aquí.', exampleEn: 'There\'s a shop near here.' },
  { es: 'hospital', en: 'hospital', cefr: 'A1', domain: 'places', frequencyRank: 350, example: 'El médico trabaja en el hospital.', exampleEn: 'The doctor works at the hospital.' },
  { es: 'aeropuerto', en: 'airport', cefr: 'A1', domain: 'places', frequencyRank: 480, example: 'El vuelo sale del aeropuerto.', exampleEn: 'The flight departs from the airport.' },
  { es: 'ciudad', en: 'city', cefr: 'A1', domain: 'places', frequencyRank: 120, example: 'Madrid es una ciudad grande.', exampleEn: 'Madrid is a big city.' },
  { es: 'calle', en: 'street', cefr: 'A1', domain: 'places', frequencyRank: 200, example: 'Vivo en esta calle.', exampleEn: 'I live on this street.' },
  { es: 'banco', en: 'bank', cefr: 'A1', domain: 'places', frequencyRank: 310, example: 'Necesito ir al banco.', exampleEn: 'I need to go to the bank.' },
  { es: 'supermercado', en: 'supermarket', cefr: 'A1', domain: 'places', frequencyRank: 420, example: 'Compro en el supermercado.', exampleEn: 'I shop at the supermarket.' },
  { es: 'parque', en: 'park', cefr: 'A1', domain: 'places', frequencyRank: 430, example: 'Los niños juegan en el parque.', exampleEn: 'The children play in the park.' },
  { es: 'playa', en: 'beach', cefr: 'A1', domain: 'places', frequencyRank: 440, example: 'Vamos a la playa en verano.', exampleEn: 'We go to the beach in summer.' },
  // More places
  { es: 'biblioteca', en: 'library', cefr: 'A1', domain: 'places', frequencyRank: 450, example: 'Voy a la biblioteca a estudiar.', exampleEn: 'I go to the library to study.' },
  { es: 'farmacia', en: 'pharmacy / chemist', cefr: 'A1', domain: 'places', frequencyRank: 460, example: 'Necesito ir a la farmacia.', exampleEn: 'I need to go to the pharmacy.' },
  { es: 'mercado', en: 'market', cefr: 'A1', domain: 'places', frequencyRank: 470, example: 'Compramos verduras en el mercado.', exampleEn: 'We buy vegetables at the market.' },
  { es: 'iglesia', en: 'church', cefr: 'A1', domain: 'places', frequencyRank: 480, example: 'La iglesia está en el centro.', exampleEn: 'The church is in the centre.' },
  { es: 'museo', en: 'museum', cefr: 'A1', domain: 'places', frequencyRank: 490, example: 'El museo abre a las diez.', exampleEn: 'The museum opens at ten.' },
  { es: 'estación', en: 'station (train/metro)', cefr: 'A1', domain: 'places', frequencyRank: 500, example: 'Nos vemos en la estación.', exampleEn: 'We\'ll meet at the station.' },
  { es: 'hotel', en: 'hotel', cefr: 'A1', domain: 'places', frequencyRank: 510, example: 'El hotel tiene piscina.', exampleEn: 'The hotel has a pool.' },
  { es: 'cine', en: 'cinema / movie theater', cefr: 'A1', domain: 'places', frequencyRank: 520, example: '¿Vamos al cine esta tarde?', exampleEn: 'Shall we go to the cinema this afternoon?' },
  { es: 'campo', en: 'countryside / field', cefr: 'A2', domain: 'places', frequencyRank: 530, example: 'Me gusta pasar el fin de semana en el campo.', exampleEn: 'I like spending the weekend in the countryside.' },

  // ── CORE VERBS (A1) ─────────────────────────────────────────────────────
  { es: 'ser', en: 'to be (permanent)', cefr: 'A1', domain: 'verbs', frequencyRank: 2, example: 'Soy estudiante.', exampleEn: 'I am a student.' },
  { es: 'estar', en: 'to be (temporary)', cefr: 'A1', domain: 'verbs', frequencyRank: 5, example: 'Estoy cansado.', exampleEn: 'I am tired.' },
  { es: 'tener', en: 'to have', cefr: 'A1', domain: 'verbs', frequencyRank: 6, example: 'Tengo hambre.', exampleEn: 'I am hungry. (lit. I have hunger.)' },
  { es: 'ir', en: 'to go', cefr: 'A1', domain: 'verbs', frequencyRank: 7, example: 'Voy al mercado.', exampleEn: 'I\'m going to the market.' },
  { es: 'hacer', en: 'to do / to make', cefr: 'A1', domain: 'verbs', frequencyRank: 8, example: '¿Qué haces hoy?', exampleEn: 'What are you doing today?' },
  { es: 'poder', en: 'to be able to / can', cefr: 'A1', domain: 'verbs', frequencyRank: 10, example: '¿Puedes ayudarme?', exampleEn: 'Can you help me?' },
  { es: 'querer', en: 'to want / to love', cefr: 'A1', domain: 'verbs', frequencyRank: 12, example: 'Quiero aprender español.', exampleEn: 'I want to learn Spanish.' },
  { es: 'hablar', en: 'to speak', cefr: 'A1', domain: 'verbs', frequencyRank: 30, example: 'Hablo un poco de español.', exampleEn: 'I speak a little Spanish.' },
  { es: 'comer', en: 'to eat', cefr: 'A1', domain: 'verbs', frequencyRank: 45, example: 'Comemos a las dos.', exampleEn: 'We eat at two o\'clock.' },
  { es: 'vivir', en: 'to live', cefr: 'A1', domain: 'verbs', frequencyRank: 50, example: 'Vivo en Madrid.', exampleEn: 'I live in Madrid.' },
  { es: 'venir', en: 'to come', cefr: 'A1', domain: 'verbs', frequencyRank: 55, example: '¿Vienes a la fiesta?', exampleEn: 'Are you coming to the party?' },
  { es: 'saber', en: 'to know (facts/skills)', cefr: 'A1', domain: 'verbs', frequencyRank: 15, example: '¿Sabes cocinar?', exampleEn: 'Do you know how to cook?' },
  { es: 'llamarse', en: 'to be called', cefr: 'A1', domain: 'verbs', frequencyRank: 180, example: 'Me llamo Carlos.', exampleEn: 'My name is Carlos.' },
  { es: 'trabajar', en: 'to work', cefr: 'A1', domain: 'verbs', frequencyRank: 60, example: 'Trabajo en una empresa.', exampleEn: 'I work at a company.' },
  { es: 'estudiar', en: 'to study', cefr: 'A1', domain: 'verbs', frequencyRank: 65, example: 'Estudio español.', exampleEn: 'I study Spanish.' },
  { es: 'beber', en: 'to drink', cefr: 'A1', domain: 'verbs', frequencyRank: 70, example: 'Bebe mucha agua.', exampleEn: 'She drinks a lot of water.' },
  { es: 'comprar', en: 'to buy', cefr: 'A1', domain: 'verbs', frequencyRank: 75, example: 'Voy a comprar leche.', exampleEn: 'I\'m going to buy milk.' },
  { es: 'dar', en: 'to give', cefr: 'A1', domain: 'verbs', frequencyRank: 18, example: 'Te doy mi número.', exampleEn: 'I\'ll give you my number.' },
  { es: 'ver', en: 'to see / to watch', cefr: 'A1', domain: 'verbs', frequencyRank: 20, example: 'Vemos una película.', exampleEn: 'We\'re watching a movie.' },

  // ── ADJECTIVES (A1) ─────────────────────────────────────────────────────
  { es: 'grande', en: 'big / great', cefr: 'A1', domain: 'adjectives', frequencyRank: 50, example: 'Es una ciudad grande.', exampleEn: 'It\'s a big city.' },
  { es: 'pequeño', en: 'small', cefr: 'A1', domain: 'adjectives', frequencyRank: 55, example: 'Vivo en un apartamento pequeño.', exampleEn: 'I live in a small apartment.' },
  { es: 'bueno', en: 'good', cefr: 'A1', domain: 'adjectives', frequencyRank: 25, example: 'Es una buena idea.', exampleEn: 'It\'s a good idea.' },
  { es: 'malo', en: 'bad', cefr: 'A1', domain: 'adjectives', frequencyRank: 60, example: 'Tengo un día malo.', exampleEn: 'I\'m having a bad day.' },
  { es: 'nuevo', en: 'new', cefr: 'A1', domain: 'adjectives', frequencyRank: 35, example: 'Tengo un trabajo nuevo.', exampleEn: 'I have a new job.' },
  { es: 'viejo', en: 'old', cefr: 'A1', domain: 'adjectives', frequencyRank: 65, example: 'Es un edificio muy viejo.', exampleEn: 'It\'s a very old building.' },
  { es: 'bonito', en: 'pretty / nice', cefr: 'A1', domain: 'adjectives', frequencyRank: 180, example: '¡Qué bonito día!', exampleEn: 'What a nice day!' },
  { es: 'fácil', en: 'easy', cefr: 'A1', domain: 'adjectives', frequencyRank: 200, example: 'El español no es fácil.', exampleEn: 'Spanish is not easy.' },
  { es: 'difícil', en: 'difficult', cefr: 'A1', domain: 'adjectives', frequencyRank: 210, example: 'Este ejercicio es muy difícil.', exampleEn: 'This exercise is very difficult.' },
  { es: 'cansado', en: 'tired', cefr: 'A1', domain: 'adjectives', frequencyRank: 400, example: 'Estoy muy cansado.', exampleEn: 'I\'m very tired.' },
  { es: 'contento', en: 'happy / pleased', cefr: 'A1', domain: 'adjectives', frequencyRank: 350, example: 'Estoy muy contento.', exampleEn: 'I\'m very happy.' },
  { es: 'tranquilo', en: 'calm / quiet', cefr: 'A1', domain: 'adjectives', frequencyRank: 320, example: 'Es una ciudad tranquila.', exampleEn: 'It\'s a quiet city.' },

  // ── A2 WORDS ────────────────────────────────────────────────────────────

  // Months
  { es: 'enero', en: 'January', cefr: 'A2', domain: 'time', frequencyRank: 700, example: 'En enero hace mucho frío.', exampleEn: 'In January it is very cold.' },
  { es: 'febrero', en: 'February', cefr: 'A2', domain: 'time', frequencyRank: 710, example: 'Mi cumpleaños es en febrero.', exampleEn: 'My birthday is in February.' },
  { es: 'marzo', en: 'March', cefr: 'A2', domain: 'time', frequencyRank: 720, example: 'La primavera empieza en marzo.', exampleEn: 'Spring starts in March.' },
  { es: 'abril', en: 'April', cefr: 'A2', domain: 'time', frequencyRank: 730, example: 'En abril, aguas mil.', exampleEn: 'April showers bring May flowers.' },
  { es: 'mayo', en: 'May', cefr: 'A2', domain: 'time', frequencyRank: 740, example: 'Las flores brotan en mayo.', exampleEn: 'Flowers bloom in May.' },
  { es: 'junio', en: 'June', cefr: 'A2', domain: 'time', frequencyRank: 750, example: 'Las vacaciones empiezan en junio.', exampleEn: 'The holidays start in June.' },
  { es: 'julio', en: 'July', cefr: 'A2', domain: 'time', frequencyRank: 760, example: 'Julio es el mes más caluroso.', exampleEn: 'July is the hottest month.' },
  { es: 'agosto', en: 'August', cefr: 'A2', domain: 'time', frequencyRank: 770, example: 'En agosto voy a la playa.', exampleEn: 'In August I go to the beach.' },
  { es: 'septiembre', en: 'September', cefr: 'A2', domain: 'time', frequencyRank: 780, example: 'El colegio empieza en septiembre.', exampleEn: 'School starts in September.' },
  { es: 'octubre', en: 'October', cefr: 'A2', domain: 'time', frequencyRank: 790, example: 'En octubre caen las hojas.', exampleEn: 'In October the leaves fall.' },
  { es: 'noviembre', en: 'November', cefr: 'A2', domain: 'time', frequencyRank: 800, example: 'Noviembre es un mes gris.', exampleEn: 'November is a grey month.' },
  { es: 'diciembre', en: 'December', cefr: 'A2', domain: 'time', frequencyRank: 810, example: 'La Navidad es en diciembre.', exampleEn: 'Christmas is in December.' },

  // Seasons
  { es: 'primavera', en: 'spring', cefr: 'A2', domain: 'time', frequencyRank: 820, example: 'Me encanta la primavera.', exampleEn: 'I love spring.' },
  { es: 'verano', en: 'summer', cefr: 'A2', domain: 'time', frequencyRank: 825, example: 'En verano hace calor.', exampleEn: 'In summer it is hot.' },
  { es: 'otoño', en: 'autumn / fall', cefr: 'A2', domain: 'time', frequencyRank: 830, example: 'En otoño las hojas cambian de color.', exampleEn: 'In autumn the leaves change colour.' },
  { es: 'invierno', en: 'winter', cefr: 'A2', domain: 'time', frequencyRank: 835, example: 'El invierno es muy frío aquí.', exampleEn: 'Winter is very cold here.' },

  // Weather
  { es: 'lluvia', en: 'rain', cefr: 'A2', domain: 'weather', frequencyRank: 380, example: 'Hay mucha lluvia en noviembre.', exampleEn: 'There is a lot of rain in November.' },
  { es: 'sol', en: 'sun / sunshine', cefr: 'A2', domain: 'weather', frequencyRank: 290, example: 'Hoy hay mucho sol.', exampleEn: 'Today there is a lot of sunshine.' },
  { es: 'viento', en: 'wind', cefr: 'A2', domain: 'weather', frequencyRank: 400, example: 'Hace mucho viento hoy.', exampleEn: 'It is very windy today.' },
  { es: 'calor', en: 'heat / warmth', cefr: 'A2', domain: 'weather', frequencyRank: 320, example: '¡Qué calor hace hoy!', exampleEn: 'It\'s so hot today!' },
  { es: 'frío', en: 'cold', cefr: 'A2', domain: 'weather', frequencyRank: 330, example: 'Tengo mucho frío.', exampleEn: 'I\'m very cold.' },
  { es: 'nieve', en: 'snow', cefr: 'A2', domain: 'weather', frequencyRank: 450, example: 'Hay nieve en las montañas.', exampleEn: 'There is snow on the mountains.' },
  { es: 'nublado', en: 'cloudy', cefr: 'A2', domain: 'weather', frequencyRank: 480, example: 'Hoy está nublado.', exampleEn: 'Today it\'s cloudy.' },

  // Body parts
  { es: 'cabeza', en: 'head', cefr: 'A2', domain: 'body', frequencyRank: 140, example: 'Me duele la cabeza.', exampleEn: 'I have a headache.' },
  { es: 'brazo', en: 'arm', cefr: 'A2', domain: 'body', frequencyRank: 230, example: 'Me rompí el brazo.', exampleEn: 'I broke my arm.' },
  { es: 'mano', en: 'hand', cefr: 'A2', domain: 'body', frequencyRank: 110, example: 'Dame la mano.', exampleEn: 'Give me your hand.' },
  { es: 'pierna', en: 'leg', cefr: 'A2', domain: 'body', frequencyRank: 260, example: 'Me duele la pierna.', exampleEn: 'My leg hurts.' },
  { es: 'pie', en: 'foot', cefr: 'A2', domain: 'body', frequencyRank: 280, example: 'Me duele el pie derecho.', exampleEn: 'My right foot hurts.' },
  { es: 'ojo', en: 'eye', cefr: 'A2', domain: 'body', frequencyRank: 160, example: 'Tiene los ojos azules.', exampleEn: 'She has blue eyes.' },
  { es: 'oreja', en: 'ear', cefr: 'A2', domain: 'body', frequencyRank: 350, example: 'Me duele la oreja.', exampleEn: 'My ear hurts.' },
  { es: 'boca', en: 'mouth', cefr: 'A2', domain: 'body', frequencyRank: 220, example: 'Cierra la boca mientras comes.', exampleEn: 'Close your mouth while eating.' },
  { es: 'espalda', en: 'back', cefr: 'A2', domain: 'body', frequencyRank: 240, example: 'Me duele la espalda.', exampleEn: 'My back hurts.' },
  { es: 'nariz', en: 'nose', cefr: 'A2', domain: 'body', frequencyRank: 250, example: 'Tengo la nariz tapada.', exampleEn: 'My nose is blocked.' },
  { es: 'cuello', en: 'neck', cefr: 'A2', domain: 'body', frequencyRank: 260, example: 'Me duele el cuello.', exampleEn: 'My neck hurts.' },
  { es: 'hombro', en: 'shoulder', cefr: 'A2', domain: 'body', frequencyRank: 270, example: 'Se lesionó el hombro.', exampleEn: 'He injured his shoulder.' },
  { es: 'rodilla', en: 'knee', cefr: 'A2', domain: 'body', frequencyRank: 290, example: 'Me caí y me golpeé la rodilla.', exampleEn: 'I fell and hit my knee.' },
  { es: 'dedo', en: 'finger / toe', cefr: 'A2', domain: 'body', frequencyRank: 300, example: 'Me corté el dedo.', exampleEn: 'I cut my finger.' },
  { es: 'estómago', en: 'stomach', cefr: 'A2', domain: 'body', frequencyRank: 310, example: 'Me duele el estómago.', exampleEn: 'My stomach hurts.' },
  { es: 'cara', en: 'face', cefr: 'A2', domain: 'body', frequencyRank: 170, example: 'Tiene una cara bonita.', exampleEn: 'She has a pretty face.' },

  // Key A2 verbs
  { es: 'decir', en: 'to say / to tell', cefr: 'A2', domain: 'verbs', frequencyRank: 9, example: '¿Qué dice?', exampleEn: 'What is he saying?' },
  { es: 'poner', en: 'to put / to place', cefr: 'A2', domain: 'verbs', frequencyRank: 16, example: 'Pon la mesa, por favor.', exampleEn: 'Set the table, please.' },
  { es: 'conocer', en: 'to know (person/place)', cefr: 'A2', domain: 'verbs', frequencyRank: 22, example: '¿Conoces a María?', exampleEn: 'Do you know María?' },
  { es: 'leer', en: 'to read', cefr: 'A2', domain: 'verbs', frequencyRank: 55, example: 'Leo un libro cada semana.', exampleEn: 'I read a book every week.' },
  { es: 'escribir', en: 'to write', cefr: 'A2', domain: 'verbs', frequencyRank: 48, example: 'Escríbeme un correo.', exampleEn: 'Write me an email.' },
  { es: 'dormir', en: 'to sleep', cefr: 'A2', domain: 'verbs', frequencyRank: 90, example: 'Duermo ocho horas.', exampleEn: 'I sleep eight hours.' },
  { es: 'empezar', en: 'to start / to begin', cefr: 'A2', domain: 'verbs', frequencyRank: 35, example: 'La clase empieza a las nueve.', exampleEn: 'The class starts at nine.' },
  { es: 'seguir', en: 'to continue / to follow', cefr: 'A2', domain: 'verbs', frequencyRank: 30, example: 'Sigue todo recto.', exampleEn: 'Keep going straight ahead.' },
  { es: 'volver', en: 'to return / to come back', cefr: 'A2', domain: 'verbs', frequencyRank: 33, example: '¿A qué hora vuelves?', exampleEn: 'What time are you coming back?' },
  { es: 'pasar', en: 'to pass / to happen / to spend (time)', cefr: 'A2', domain: 'verbs', frequencyRank: 24, example: '¿Qué pasa?', exampleEn: 'What\'s happening?' },
  { es: 'quedar', en: 'to arrange to meet / to remain', cefr: 'A2', domain: 'verbs', frequencyRank: 26, example: '¿Quedamos a las seis?', exampleEn: 'Shall we meet at six?' },

  // Key A2 adjectives
  { es: 'diferente', en: 'different', cefr: 'A2', domain: 'adjectives', frequencyRank: 140, example: 'Son muy diferentes.', exampleEn: 'They are very different.' },
  { es: 'importante', en: 'important', cefr: 'A2', domain: 'adjectives', frequencyRank: 60, example: 'Es muy importante estudiar.', exampleEn: 'It\'s very important to study.' },
  { es: 'joven', en: 'young', cefr: 'A2', domain: 'adjectives', frequencyRank: 130, example: 'Es una chica joven.', exampleEn: 'She\'s a young girl.' },
  { es: 'mayor', en: 'older / elderly / bigger', cefr: 'A2', domain: 'adjectives', frequencyRank: 80, example: 'Mi hermano es mayor que yo.', exampleEn: 'My brother is older than me.' },
  { es: 'ocupado', en: 'busy', cefr: 'A2', domain: 'adjectives', frequencyRank: 300, example: 'Estoy muy ocupado esta semana.', exampleEn: 'I\'m very busy this week.' },
  { es: 'simpático', en: 'nice / likeable', cefr: 'A2', domain: 'adjectives', frequencyRank: 350, example: 'El profesor es muy simpático.', exampleEn: 'The teacher is very nice.' },
  { es: 'interesante', en: 'interesting', cefr: 'A2', domain: 'adjectives', frequencyRank: 150, example: 'Es un libro muy interesante.', exampleEn: 'It\'s a very interesting book.' },

  // Travel / daily life nouns (A2)
  { es: 'viaje', en: 'trip / journey', cefr: 'A2', domain: 'nouns', frequencyRank: 160, example: 'Hago un viaje a México.', exampleEn: 'I\'m taking a trip to Mexico.' },
  { es: 'billete', en: 'ticket (Spain) / banknote', cefr: 'A2', domain: 'nouns', frequencyRank: 300, example: 'Compré el billete de tren.', exampleEn: 'I bought the train ticket.' },
  { es: 'maleta', en: 'suitcase', cefr: 'A2', domain: 'nouns', frequencyRank: 400, example: 'Haz la maleta.', exampleEn: 'Pack your suitcase.' },
  { es: 'habitación', en: 'room / bedroom', cefr: 'A2', domain: 'nouns', frequencyRank: 200, example: '¿Tiene una habitación libre?', exampleEn: 'Do you have a room available?' },
  { es: 'dirección', en: 'address / direction', cefr: 'A2', domain: 'nouns', frequencyRank: 170, example: '¿Me das tu dirección?', exampleEn: 'Can you give me your address?' },
  { es: 'semana', en: 'week', cefr: 'A2', domain: 'time', frequencyRank: 105, example: 'La próxima semana tengo examen.', exampleEn: 'Next week I have an exam.' },
  { es: 'mes', en: 'month', cefr: 'A2', domain: 'time', frequencyRank: 88, example: 'Este mes tengo mucho trabajo.', exampleEn: 'This month I have a lot of work.' },
  { es: 'año', en: 'year', cefr: 'A2', domain: 'time', frequencyRank: 30, example: 'El año pasado fui a España.', exampleEn: 'Last year I went to Spain.' },
  { es: 'hora', en: 'hour / time (clock)', cefr: 'A1', domain: 'time', frequencyRank: 78, example: '¿Qué hora es?', exampleEn: 'What time is it?' },
  { es: 'noche', en: 'night / evening', cefr: 'A1', domain: 'time', frequencyRank: 82, example: 'Hasta la noche.', exampleEn: 'See you tonight.' },
  { es: 'tarde', en: 'afternoon; late (adv.)', cefr: 'A1', domain: 'time', frequencyRank: 85, example: 'Por la tarde tomo café.', exampleEn: 'In the afternoon I drink coffee.' },
  { es: 'temprano', en: 'early', cefr: 'A1', domain: 'time', frequencyRank: 200, example: 'Me levanto temprano.', exampleEn: 'I get up early.' },
  { es: 'a veces', en: 'sometimes', cefr: 'A1', domain: 'time', frequencyRank: 110, example: 'A veces como aquí.', exampleEn: 'Sometimes I eat here.' },
  { es: 'a menudo', en: 'often / frequently', cefr: 'A2', domain: 'time', frequencyRank: 180, example: 'Voy al gimnasio a menudo.', exampleEn: 'I go to the gym often.' },
  { es: 'parte', en: 'part', cefr: 'A2', domain: 'nouns', frequencyRank: 32, example: 'Esta es la mejor parte.', exampleEn: 'This is the best part.' },
  { es: 'cosa', en: 'thing', cefr: 'A2', domain: 'nouns', frequencyRank: 27, example: 'Tengo muchas cosas que hacer.', exampleEn: 'I have many things to do.' },
  { es: 'lugar', en: 'place', cefr: 'A2', domain: 'nouns', frequencyRank: 55, example: 'Es un lugar muy bonito.', exampleEn: 'It\'s a very beautiful place.' },
  { es: 'forma', en: 'way / form / shape', cefr: 'A2', domain: 'nouns', frequencyRank: 45, example: 'Hay muchas formas de aprender.', exampleEn: 'There are many ways to learn.' },

  { es: 'aunque', en: 'although / even though', cefr: 'A2', domain: 'connectors', frequencyRank: 95, example: 'Aunque llueve, salgo.', exampleEn: 'Although it rains, I\'m going out.' },
  { es: 'porque', en: 'because', cefr: 'A2', domain: 'connectors', frequencyRank: 75, example: 'No voy porque estoy enfermo.', exampleEn: 'I\'m not going because I\'m sick.' },
  { es: 'también', en: 'also / too', cefr: 'A2', domain: 'connectors', frequencyRank: 85, example: 'Yo también quiero ir.', exampleEn: 'I also want to go.' },
  { es: 'tampoco', en: 'neither / not either', cefr: 'A2', domain: 'connectors', frequencyRank: 220, example: '—No me gusta. —A mí tampoco.', exampleEn: 'I don\'t like it. — Me neither.' },
  { es: 'todavía', en: 'still / yet', cefr: 'A2', domain: 'connectors', frequencyRank: 200, example: 'Todavía no he comido.', exampleEn: 'I haven\'t eaten yet.' },
  { es: 'ya', en: 'already / now', cefr: 'A2', domain: 'connectors', frequencyRank: 25, example: 'Ya he terminado.', exampleEn: 'I\'ve already finished.' },
  { es: 'bastante', en: 'quite / enough', cefr: 'A2', domain: 'adverbs', frequencyRank: 180, example: 'Es bastante difícil.', exampleEn: 'It\'s quite difficult.' },
  { es: 'demasiado', en: 'too much / too many', cefr: 'A2', domain: 'adverbs', frequencyRank: 200, example: 'Comes demasiado rápido.', exampleEn: 'You eat too fast.' },
  { es: 'un poco', en: 'a little', cefr: 'A2', domain: 'adverbs', frequencyRank: 110, example: 'Habla un poco de inglés.', exampleEn: 'She speaks a little English.' },
  { es: 'quizás', en: 'maybe / perhaps', cefr: 'A2', domain: 'adverbs', frequencyRank: 250, example: 'Quizás llueva mañana.', exampleEn: 'Maybe it will rain tomorrow.' },
  { es: 'sin embargo', en: 'however / nevertheless', cefr: 'A2', domain: 'connectors', frequencyRank: 105, example: 'Es caro; sin embargo, lo compro.', exampleEn: 'It\'s expensive; however, I\'m buying it.' },
  { es: 'además', en: 'besides / furthermore', cefr: 'A2', domain: 'connectors', frequencyRank: 120, example: 'Habla inglés y, además, francés.', exampleEn: 'She speaks English and, besides, French.' },
  { es: 'enfermo', en: 'sick / ill', cefr: 'A2', domain: 'adjectives', frequencyRank: 380, example: 'Está enfermo en cama.', exampleEn: 'He\'s sick in bed.' },
  { es: 'libre', en: 'free / available', cefr: 'A2', domain: 'adjectives', frequencyRank: 200, example: '¿Estás libre esta tarde?', exampleEn: 'Are you free this afternoon?' },
  { es: 'seguro', en: 'sure / safe', cefr: 'A2', domain: 'adjectives', frequencyRank: 170, example: '¿Estás seguro de eso?', exampleEn: 'Are you sure about that?' },
  { es: 'llegar', en: 'to arrive', cefr: 'A2', domain: 'verbs', frequencyRank: 40, example: 'Llegamos a las tres.', exampleEn: 'We arrive at three.' },
  { es: 'salir', en: 'to leave / go out', cefr: 'A2', domain: 'verbs', frequencyRank: 42, example: 'Salgo a las ocho.', exampleEn: 'I leave at eight.' },
  { es: 'pagar', en: 'to pay', cefr: 'A2', domain: 'verbs', frequencyRank: 80, example: '¿Quién paga la cuenta?', exampleEn: 'Who pays the bill?' },
  { es: 'necesitar', en: 'to need', cefr: 'A2', domain: 'verbs', frequencyRank: 85, example: 'Necesito tu ayuda.', exampleEn: 'I need your help.' },
  { es: 'esperar', en: 'to wait / to hope', cefr: 'A2', domain: 'verbs', frequencyRank: 60, example: 'Espera un momento.', exampleEn: 'Wait a moment.' },
  { es: 'pensar', en: 'to think', cefr: 'A2', domain: 'verbs', frequencyRank: 32, example: '¿Qué piensas de esto?', exampleEn: 'What do you think about this?' },
  { es: 'creer', en: 'to believe / to think', cefr: 'A2', domain: 'verbs', frequencyRank: 28, example: 'Creo que sí.', exampleEn: 'I think so.' },
  { es: 'encontrar', en: 'to find / to meet', cefr: 'A2', domain: 'verbs', frequencyRank: 38, example: 'No encuentro mis llaves.', exampleEn: 'I can\'t find my keys.' },
  { es: 'entender', en: 'to understand', cefr: 'A2', domain: 'verbs', frequencyRank: 55, example: '¿Entiendes lo que digo?', exampleEn: 'Do you understand what I\'m saying?' },
  { es: 'preguntar', en: 'to ask', cefr: 'A2', domain: 'verbs', frequencyRank: 65, example: 'Voy a preguntar al médico.', exampleEn: 'I\'m going to ask the doctor.' },
  { es: 'ayudar', en: 'to help', cefr: 'A2', domain: 'verbs', frequencyRank: 70, example: '¿Me puedes ayudar?', exampleEn: 'Can you help me?' },
  { es: 'olvidar', en: 'to forget', cefr: 'A2', domain: 'verbs', frequencyRank: 120, example: 'Olvidé el paraguas.', exampleEn: 'I forgot the umbrella.' },
  { es: 'recordar', en: 'to remember', cefr: 'A2', domain: 'verbs', frequencyRank: 115, example: '¿Recuerdas mi nombre?', exampleEn: 'Do you remember my name?' },
  { es: 'dinero', en: 'money', cefr: 'A2', domain: 'nouns', frequencyRank: 130, example: 'No tengo dinero.', exampleEn: 'I don\'t have money.' },
  { es: 'tiempo', en: 'time / weather', cefr: 'A2', domain: 'nouns', frequencyRank: 20, example: '¿Qué tiempo hace?', exampleEn: 'What\'s the weather like?' },
  { es: 'gente', en: 'people', cefr: 'A2', domain: 'nouns', frequencyRank: 75, example: 'Hay mucha gente aquí.', exampleEn: 'There are many people here.' },
  { es: 'vida', en: 'life', cefr: 'A2', domain: 'nouns', frequencyRank: 22, example: 'La vida es bella.', exampleEn: 'Life is beautiful.' },
  { es: 'vez', en: 'time (occasion)', cefr: 'A2', domain: 'nouns', frequencyRank: 18, example: 'Es la primera vez.', exampleEn: 'It\'s the first time.' },
  { es: 'mundo', en: 'world', cefr: 'A2', domain: 'nouns', frequencyRank: 40, example: 'El mundo es pequeño.', exampleEn: 'It\'s a small world.' },
  { es: 'problema', en: 'problem', cefr: 'A2', domain: 'nouns', frequencyRank: 55, example: '¿Cuál es el problema?', exampleEn: 'What\'s the problem?' },
  { es: 'idea', en: 'idea', cefr: 'A2', domain: 'nouns', frequencyRank: 60, example: 'Es una buena idea.', exampleEn: 'It\'s a good idea.' },
  // Home
  { es: 'cocina', en: 'kitchen', cefr: 'A2', domain: 'nouns', frequencyRank: 140, example: 'Cocino en la cocina.', exampleEn: 'I cook in the kitchen.' },
  { es: 'baño', en: 'bathroom', cefr: 'A2', domain: 'nouns', frequencyRank: 145, example: 'El baño está al fondo.', exampleEn: 'The bathroom is at the end.' },
  { es: 'dormitorio', en: 'bedroom', cefr: 'A2', domain: 'nouns', frequencyRank: 150, example: 'Mi dormitorio es pequeño.', exampleEn: 'My bedroom is small.' },
  { es: 'salón', en: 'living room', cefr: 'A2', domain: 'nouns', frequencyRank: 155, example: 'Vemos la tele en el salón.', exampleEn: 'We watch TV in the living room.' },
  { es: 'comedor', en: 'dining room', cefr: 'A2', domain: 'nouns', frequencyRank: 160, example: 'Cenamos en el comedor.', exampleEn: 'We have dinner in the dining room.' },
  // Transport
  { es: 'metro', en: 'metro / subway', cefr: 'A2', domain: 'nouns', frequencyRank: 135, example: 'Tomo el metro al trabajo.', exampleEn: 'I take the metro to work.' },
  { es: 'autobús', en: 'bus', cefr: 'A2', domain: 'nouns', frequencyRank: 125, example: 'El autobús llega tarde.', exampleEn: 'The bus is late.' },
  { es: 'tren', en: 'train', cefr: 'A2', domain: 'nouns', frequencyRank: 130, example: 'Viajamos en tren.', exampleEn: 'We travel by train.' },
  { es: 'taxi', en: 'taxi', cefr: 'A2', domain: 'nouns', frequencyRank: 138, example: 'Pedí un taxi.', exampleEn: 'I ordered a taxi.' },
  { es: 'avión', en: 'plane', cefr: 'A2', domain: 'nouns', frequencyRank: 142, example: 'El avión sale a las diez.', exampleEn: 'The plane leaves at ten.' },
  // Shopping
  { es: 'precio', en: 'price', cefr: 'A2', domain: 'nouns', frequencyRank: 105, example: '¿Cuál es el precio?', exampleEn: 'What\'s the price?' },
  { es: 'caro', en: 'expensive', cefr: 'A2', domain: 'adjectives', frequencyRank: 112, example: 'Este restaurante es muy caro.', exampleEn: 'This restaurant is very expensive.' },
  { es: 'barato', en: 'cheap / inexpensive', cefr: 'A2', domain: 'adjectives', frequencyRank: 118, example: 'Es muy barato.', exampleEn: 'It\'s very cheap.' },
  { es: 'piso', en: 'flat / apartment (Spain)', cefr: 'A2', domain: 'places', frequencyRank: 148, example: 'Vivo en un piso en el centro.', exampleEn: 'I live in a flat in the city centre.' },
  // Restaurant
  { es: 'pedir', en: 'to order / to ask for', cefr: 'A2', domain: 'verbs', frequencyRank: 95, example: 'Voy a pedir la ensalada.', exampleEn: 'I\'m going to order the salad.' },
  { es: 'la carta', en: 'the menu', cefr: 'A2', domain: 'nouns', frequencyRank: 165, example: '¿Me trae la carta, por favor?', exampleEn: 'Could you bring me the menu, please?' },
  { es: 'la cuenta', en: 'the bill', cefr: 'A2', domain: 'nouns', frequencyRank: 170, example: 'La cuenta, por favor.', exampleEn: 'The bill, please.' },
  // Emotions
  { es: 'triste', en: 'sad', cefr: 'A2', domain: 'adjectives', frequencyRank: 108, example: 'Estoy triste hoy.', exampleEn: 'I\'m sad today.' },
  { es: 'nervioso', en: 'nervous', cefr: 'A2', domain: 'adjectives', frequencyRank: 122, example: 'Estoy nervioso antes del examen.', exampleEn: 'I\'m nervous before the exam.' },
  { es: 'aburrido', en: 'bored / boring', cefr: 'A2', domain: 'adjectives', frequencyRank: 128, example: 'La clase es muy aburrida.', exampleEn: 'The class is very boring.' },
  { es: 'cansado', en: 'tired', cefr: 'A2', domain: 'adjectives', frequencyRank: 110, example: 'Estoy muy cansado.', exampleEn: 'I\'m very tired.' },
  // Work
  { es: 'oficina', en: 'office', cefr: 'A2', domain: 'nouns', frequencyRank: 133, example: 'Trabajo en una oficina.', exampleEn: 'I work in an office.' },
  { es: 'jefe', en: 'boss / manager', cefr: 'A2', domain: 'nouns', frequencyRank: 136, example: 'Mi jefe es muy exigente.', exampleEn: 'My boss is very demanding.' },
  { es: 'compañero', en: 'colleague / classmate', cefr: 'A2', domain: 'nouns', frequencyRank: 143, example: 'Mi compañero de trabajo es simpático.', exampleEn: 'My work colleague is friendly.' },

  // ── B1 WORDS ────────────────────────────────────────────────────────────
  { es: 'a pesar de', en: 'in spite of / despite', cefr: 'B1', domain: 'connectors', frequencyRank: 180, example: 'Salió a pesar de la lluvia.', exampleEn: 'He went out despite the rain.' },
  { es: 'de hecho', en: 'in fact / actually', cefr: 'B1', domain: 'connectors', frequencyRank: 160, example: 'De hecho, no estaba de acuerdo.', exampleEn: 'In fact, I didn\'t agree.' },
  { es: 'en cambio', en: 'on the other hand', cefr: 'B1', domain: 'connectors', frequencyRank: 170, example: 'Él es serio; en cambio, ella es divertida.', exampleEn: 'He is serious; she, on the other hand, is fun.' },
  { es: 'por lo tanto', en: 'therefore', cefr: 'B1', domain: 'connectors', frequencyRank: 190, example: 'Llueve; por lo tanto, me quedo en casa.', exampleEn: 'It\'s raining; therefore, I\'m staying home.' },
  { es: 'darse cuenta de', en: 'to realize', cefr: 'B1', domain: 'verbs', frequencyRank: 180, example: 'Me di cuenta de mi error.', exampleEn: 'I realized my mistake.' },
  { es: 'tardar', en: 'to take time / to be late', cefr: 'B1', domain: 'verbs', frequencyRank: 200, example: '¿Cuánto tardas?', exampleEn: 'How long will you take?' },
  { es: 'lograr', en: 'to achieve / to manage to', cefr: 'B1', domain: 'verbs', frequencyRank: 150, example: 'Logré terminar a tiempo.', exampleEn: 'I managed to finish on time.' },
  { es: 'intentar', en: 'to try', cefr: 'B1', domain: 'verbs', frequencyRank: 130, example: 'Intenta no llegar tarde.', exampleEn: 'Try not to arrive late.' },
  { es: 'conseguir', en: 'to get / to manage to', cefr: 'B1', domain: 'verbs', frequencyRank: 120, example: '¿Conseguiste las entradas?', exampleEn: 'Did you get the tickets?' },
  { es: 'depender de', en: 'to depend on', cefr: 'B1', domain: 'verbs', frequencyRank: 210, example: 'Depende de ti.', exampleEn: 'It depends on you.' },
  { es: 'tratar de', en: 'to try to', cefr: 'B1', domain: 'verbs', frequencyRank: 140, example: 'Trato de mejorar mi español.', exampleEn: 'I try to improve my Spanish.' },
  { es: 'exigir', en: 'to demand / to require', cefr: 'B1', domain: 'verbs', frequencyRank: 250, example: 'El jefe exige puntualidad.', exampleEn: 'The boss demands punctuality.' },
  { es: 'compartir', en: 'to share', cefr: 'B1', domain: 'verbs', frequencyRank: 220, example: 'Compartimos el piso.', exampleEn: 'We share the flat.' },
  { es: 'desarrollar', en: 'to develop', cefr: 'B1', domain: 'verbs', frequencyRank: 100, example: 'Desarrollamos una aplicación nueva.', exampleEn: 'We\'re developing a new app.' },
  { es: 'apoyar', en: 'to support', cefr: 'B1', domain: 'verbs', frequencyRank: 160, example: 'Mis padres me apoyan.', exampleEn: 'My parents support me.' },
  { es: 'reconocer', en: 'to recognize / to acknowledge', cefr: 'B1', domain: 'verbs', frequencyRank: 140, example: 'Reconozco mi error.', exampleEn: 'I acknowledge my mistake.' },
  { es: 'ambiente', en: 'atmosphere / environment', cefr: 'B1', domain: 'nouns', frequencyRank: 200, example: 'Hay muy buen ambiente.', exampleEn: 'There\'s a great atmosphere.' },
  { es: 'nivel', en: 'level', cefr: 'B1', domain: 'nouns', frequencyRank: 130, example: 'Mi nivel de español mejora.', exampleEn: 'My Spanish level is improving.' },
  { es: 'plazo', en: 'deadline / period', cefr: 'B1', domain: 'nouns', frequencyRank: 210, example: 'El plazo termina el viernes.', exampleEn: 'The deadline is on Friday.' },
  { es: 'ventaja', en: 'advantage', cefr: 'B1', domain: 'nouns', frequencyRank: 220, example: 'Tiene muchas ventajas.', exampleEn: 'It has many advantages.' },
  { es: 'desventaja', en: 'disadvantage', cefr: 'B1', domain: 'nouns', frequencyRank: 230, example: 'La principal desventaja es el coste.', exampleEn: 'The main disadvantage is the cost.' },
  { es: 'conjunto', en: 'set / group / overall', cefr: 'B1', domain: 'nouns', frequencyRank: 130, example: 'En conjunto, salió bien.', exampleEn: 'Overall, it went well.' },

  // B1 — additional connectors
  { es: 'así que', en: 'so / therefore', cefr: 'B1', domain: 'connectors', frequencyRank: 105, example: 'No hay autobús, así que iremos a pie.', exampleEn: 'There\'s no bus, so we\'ll walk.' },
  { es: 'siempre que', en: 'whenever / as long as', cefr: 'B1', domain: 'connectors', frequencyRank: 195, example: 'Puedes venir siempre que quieras.', exampleEn: 'You can come whenever you want.' },
  { es: 'a menos que', en: 'unless', cefr: 'B1', domain: 'connectors', frequencyRank: 210, example: 'Iré, a menos que llueva.', exampleEn: 'I\'ll go, unless it rains.' },
  { es: 'dado que', en: 'given that / since', cefr: 'B1', domain: 'connectors', frequencyRank: 220, example: 'Dado que es tarde, me voy.', exampleEn: 'Given that it\'s late, I\'m leaving.' },
  { es: 'es decir', en: 'that is / in other words', cefr: 'B1', domain: 'connectors', frequencyRank: 98, example: 'Viene mañana, es decir, el martes.', exampleEn: 'She\'s coming tomorrow, that is, on Tuesday.' },
  { es: 'por otro lado', en: 'on the other hand', cefr: 'B1', domain: 'connectors', frequencyRank: 175, example: 'Por otro lado, tiene sus ventajas.', exampleEn: 'On the other hand, it has its advantages.' },

  // B1 — verbs
  { es: 'mejorar', en: 'to improve', cefr: 'B1', domain: 'verbs', frequencyRank: 125, example: 'Quiero mejorar mi pronunciación.', exampleEn: 'I want to improve my pronunciation.' },
  { es: 'resolver', en: 'to solve / to resolve', cefr: 'B1', domain: 'verbs', frequencyRank: 145, example: 'Hay que resolver este problema.', exampleEn: 'We need to solve this problem.' },
  { es: 'evitar', en: 'to avoid', cefr: 'B1', domain: 'verbs', frequencyRank: 135, example: 'Trata de evitar los errores comunes.', exampleEn: 'Try to avoid common mistakes.' },
  { es: 'superar', en: 'to overcome / to exceed', cefr: 'B1', domain: 'verbs', frequencyRank: 155, example: 'Superó el examen con buena nota.', exampleEn: 'She passed the exam with a good grade.' },
  { es: 'afectar', en: 'to affect', cefr: 'B1', domain: 'verbs', frequencyRank: 165, example: 'El estrés afecta la salud.', exampleEn: 'Stress affects your health.' },
  { es: 'incluir', en: 'to include', cefr: 'B1', domain: 'verbs', frequencyRank: 115, example: 'El precio incluye el desayuno.', exampleEn: 'The price includes breakfast.' },
  { es: 'demostrar', en: 'to show / to demonstrate', cefr: 'B1', domain: 'verbs', frequencyRank: 145, example: 'Demostró su talento en el escenario.', exampleEn: 'She showed her talent on stage.' },
  { es: 'comunicarse', en: 'to communicate', cefr: 'B1', domain: 'verbs', frequencyRank: 195, example: 'Es importante comunicarse bien.', exampleEn: 'It\'s important to communicate well.' },
  { es: 'influir', en: 'to influence', cefr: 'B1', domain: 'verbs', frequencyRank: 175, example: 'La familia influye mucho en nosotros.', exampleEn: 'Family influences us a lot.' },

  // B1 — emotional / personal vocabulary
  { es: 'miedo', en: 'fear', cefr: 'B1', domain: 'nouns', frequencyRank: 185, example: 'Tengo miedo a las alturas.', exampleEn: 'I\'m afraid of heights.' },
  { es: 'alegría', en: 'joy / happiness', cefr: 'B1', domain: 'nouns', frequencyRank: 240, example: '¡Qué alegría verte!', exampleEn: 'How lovely to see you!' },
  { es: 'tristeza', en: 'sadness', cefr: 'B1', domain: 'nouns', frequencyRank: 280, example: 'Sentí mucha tristeza.', exampleEn: 'I felt great sadness.' },
  { es: 'esperanza', en: 'hope', cefr: 'B1', domain: 'nouns', frequencyRank: 200, example: 'No pierdas la esperanza.', exampleEn: 'Don\'t lose hope.' },
  { es: 'orgullo', en: 'pride', cefr: 'B1', domain: 'nouns', frequencyRank: 260, example: 'Siento orgullo por su éxito.', exampleEn: 'I feel pride in her success.' },

  // B1 — work & professional
  { es: 'reunión', en: 'meeting', cefr: 'B1', domain: 'nouns', frequencyRank: 180, example: 'Tengo una reunión a las diez.', exampleEn: 'I have a meeting at ten.' },
  { es: 'empresa', en: 'company / firm', cefr: 'B1', domain: 'nouns', frequencyRank: 110, example: 'Trabajo en una empresa internacional.', exampleEn: 'I work at an international company.' },
  { es: 'sueldo', en: 'salary / wage', cefr: 'B1', domain: 'nouns', frequencyRank: 290, example: 'Negoció un sueldo más alto.', exampleEn: 'She negotiated a higher salary.' },
  { es: 'contrato', en: 'contract', cefr: 'B1', domain: 'nouns', frequencyRank: 230, example: 'Firmó el contrato de trabajo.', exampleEn: 'He signed the work contract.' },

  // B1 — abstract nouns (high frequency)
  { es: 'esfuerzo', en: 'effort', cefr: 'B1', domain: 'nouns', frequencyRank: 195, example: 'Hay que hacer un esfuerzo.', exampleEn: 'You need to make an effort.' },
  { es: 'resultado', en: 'result / outcome', cefr: 'B1', domain: 'nouns', frequencyRank: 125, example: 'Los resultados fueron buenos.', exampleEn: 'The results were good.' },
  { es: 'proceso', en: 'process', cefr: 'B1', domain: 'nouns', frequencyRank: 118, example: 'El proceso lleva tiempo.', exampleEn: 'The process takes time.' },
  { es: 'solución', en: 'solution', cefr: 'B1', domain: 'nouns', frequencyRank: 155, example: 'Hay que encontrar una solución.', exampleEn: 'We need to find a solution.' },
  { es: 'opinión', en: 'opinion', cefr: 'B1', domain: 'nouns', frequencyRank: 170, example: 'En mi opinión, tienes razón.', exampleEn: 'In my opinion, you are right.' },
  { es: 'experiencia', en: 'experience', cefr: 'B1', domain: 'nouns', frequencyRank: 140, example: 'Fue una experiencia increíble.', exampleEn: 'It was an incredible experience.' },
  // B1 adjectives
  { es: 'capaz', en: 'capable / able', cefr: 'B1', domain: 'adjectives', frequencyRank: 155, example: 'Es capaz de resolver cualquier problema.', exampleEn: 'She is capable of solving any problem.' },
  { es: 'dispuesto', en: 'willing / ready', cefr: 'B1', domain: 'adjectives', frequencyRank: 210, example: 'Estoy dispuesto a ayudar.', exampleEn: 'I am willing to help.' },
  { es: 'necesario', en: 'necessary', cefr: 'B1', domain: 'adjectives', frequencyRank: 120, example: 'No es necesario venir en persona.', exampleEn: 'It is not necessary to come in person.' },
  { es: 'posible', en: 'possible', cefr: 'B1', domain: 'adjectives', frequencyRank: 80, example: 'Es posible que lleguen tarde.', exampleEn: 'It is possible that they will arrive late.' },
  { es: 'adecuado', en: 'appropriate / adequate', cefr: 'B1', domain: 'adjectives', frequencyRank: 195, example: 'La respuesta no fue adecuada.', exampleEn: 'The answer was not appropriate.' },
  { es: 'agotado', en: 'exhausted / sold out', cefr: 'B1', domain: 'adjectives', frequencyRank: 270, example: 'Llegó a casa completamente agotado.', exampleEn: 'He arrived home completely exhausted.' },
  { es: 'emocionado', en: 'excited / moved', cefr: 'B1', domain: 'adjectives', frequencyRank: 285, example: 'Estoy muy emocionado por el viaje.', exampleEn: 'I am very excited about the trip.' },
  { es: 'preocupado', en: 'worried / concerned', cefr: 'B1', domain: 'adjectives', frequencyRank: 190, example: 'Está preocupado por su salud.', exampleEn: 'He is worried about his health.' },
  // B1 verbs (change of state, emotions)
  { es: 'preocuparse', en: 'to worry / to be concerned', cefr: 'B1', domain: 'verbs', frequencyRank: 145, example: 'No te preocupes, todo irá bien.', exampleEn: "Don't worry, everything will be fine." },
  { es: 'ponerse', en: 'to become (emotion) / to put on', cefr: 'B1', domain: 'verbs', frequencyRank: 65, example: 'Se puso nervioso antes del examen.', exampleEn: 'He got nervous before the exam.' },
  { es: 'volverse', en: 'to become (change over time)', cefr: 'B1', domain: 'verbs', frequencyRank: 90, example: 'Se volvió muy tímido de adulto.', exampleEn: 'He became very shy as an adult.' },
  { es: 'quedarse', en: 'to stay / to remain / to become', cefr: 'B1', domain: 'verbs', frequencyRank: 55, example: 'Se quedó sin palabras.', exampleEn: 'She was left speechless.' },
  { es: 'atreverse', en: 'to dare', cefr: 'B1', domain: 'verbs', frequencyRank: 250, example: 'No me atrevo a decírselo.', exampleEn: "I don't dare to tell him." },
  { es: 'echar de menos', en: 'to miss (someone/something)', cefr: 'B1', domain: 'verbs', frequencyRank: 300, example: 'Echo de menos a mi familia.', exampleEn: 'I miss my family.' },
  // B1 health vocabulary
  { es: 'enfermarse', en: 'to get sick / to fall ill', cefr: 'B1', domain: 'body', frequencyRank: 290, example: 'Se enfermó después de la lluvia.', exampleEn: 'He got sick after the rain.' },
  { es: 'síntoma', en: 'symptom', cefr: 'B1', domain: 'body', frequencyRank: 280, example: 'Los síntomas desaparecieron.', exampleEn: 'The symptoms disappeared.' },
  { es: 'medicamento', en: 'medicine / medication', cefr: 'B1', domain: 'body', frequencyRank: 220, example: 'Toma el medicamento dos veces al día.', exampleEn: 'Take the medication twice a day.' },
  { es: 'médico', en: 'doctor', cefr: 'B1', domain: 'body', frequencyRank: 85, example: 'Fui al médico esta mañana.', exampleEn: 'I went to the doctor this morning.' },
  // B1 travel vocabulary
  { es: 'vuelo', en: 'flight', cefr: 'B1', domain: 'places', frequencyRank: 215, example: 'El vuelo sale a las ocho.', exampleEn: 'The flight leaves at eight.' },
  { es: 'maleta', en: 'suitcase', cefr: 'B1', domain: 'places', frequencyRank: 310, example: 'Hice la maleta la noche anterior.', exampleEn: 'I packed my suitcase the night before.' },
  { es: 'reservar', en: 'to reserve / to book', cefr: 'B1', domain: 'verbs', frequencyRank: 195, example: 'Reservé una habitación para dos noches.', exampleEn: 'I booked a room for two nights.' },
  { es: 'llegada', en: 'arrival', cefr: 'B1', domain: 'places', frequencyRank: 230, example: 'La llegada estaba prevista a las tres.', exampleEn: 'The arrival was scheduled for three.' },
  { es: 'salida', en: 'departure / exit', cefr: 'B1', domain: 'places', frequencyRank: 170, example: 'La salida es a las seis de la mañana.', exampleEn: 'The departure is at six in the morning.' },
  // B1 education vocabulary
  { es: 'asignatura', en: 'subject (school)', cefr: 'B1', domain: 'nouns', frequencyRank: 320, example: 'Mi asignatura favorita es la historia.', exampleEn: 'My favourite subject is history.' },
  { es: 'aprobar', en: 'to pass (an exam)', cefr: 'B1', domain: 'verbs', frequencyRank: 260, example: 'Aprobé el examen de conducir.', exampleEn: 'I passed my driving test.' },
  { es: 'suspender', en: 'to fail (an exam / Spain)', cefr: 'B1', domain: 'verbs', frequencyRank: 310, example: 'Suspendió las matemáticas.', exampleEn: 'She failed maths.' },
  { es: 'nota', en: 'grade / mark / note', cefr: 'B1', domain: 'nouns', frequencyRank: 130, example: 'Sacó buenas notas este trimestre.', exampleEn: 'She got good grades this term.' },
  // B1 emotions / feelings
  { es: 'decepción', en: 'disappointment', cefr: 'B1', domain: 'nouns', frequencyRank: 290, example: 'Fue una gran decepción para todos.', exampleEn: 'It was a great disappointment for everyone.' },
  { es: 'frustración', en: 'frustration', cefr: 'B1', domain: 'nouns', frequencyRank: 270, example: 'Sentí mucha frustración al no entenderlo.', exampleEn: 'I felt a lot of frustration at not understanding it.' },
  { es: 'confianza', en: 'confidence / trust', cefr: 'B1', domain: 'nouns', frequencyRank: 160, example: 'Hay que tener confianza en uno mismo.', exampleEn: 'You have to have confidence in yourself.' },

  // ── B2 ──────────────────────────────────────────────────────────────────
  // Connectors & discourse markers
  { es: 'no obstante', en: 'nevertheless / however', cefr: 'B2', domain: 'connectors', frequencyRank: 280, example: 'No obstante, seguimos adelante.', exampleEn: 'Nevertheless, we pressed on.' },
  { es: 'por consiguiente', en: 'consequently / therefore', cefr: 'B2', domain: 'connectors', frequencyRank: 300, example: 'Es tarde; por consiguiente, nos vamos.', exampleEn: "It's late; consequently, we're leaving." },
  { es: 'a diferencia de', en: 'unlike / in contrast to', cefr: 'B2', domain: 'connectors', frequencyRank: 260, example: 'A diferencia de su hermano, estudia mucho.', exampleEn: 'Unlike his brother, he studies a lot.' },
  { es: 'a lo largo de', en: 'throughout / along', cefr: 'B2', domain: 'connectors', frequencyRank: 220, example: 'A lo largo de su carrera ganó varios premios.', exampleEn: 'Throughout his career he won several prizes.' },
  { es: 'en cuanto a', en: 'as for / regarding', cefr: 'B2', domain: 'connectors', frequencyRank: 250, example: 'En cuanto al precio, es razonable.', exampleEn: 'As for the price, it is reasonable.' },
  // Verbs (formal/academic)
  { es: 'destacar', en: 'to stand out / to emphasise', cefr: 'B2', domain: 'verbs', frequencyRank: 110, example: 'Quiero destacar la importancia de esto.', exampleEn: 'I want to emphasise the importance of this.' },
  { es: 'plantear', en: 'to raise / to put forward', cefr: 'B2', domain: 'verbs', frequencyRank: 120, example: 'Planteó una pregunta interesante.', exampleEn: 'He raised an interesting question.' },
  { es: 'suponer', en: 'to suppose / to entail', cefr: 'B2', domain: 'verbs', frequencyRank: 70, example: 'Eso supone un gran esfuerzo.', exampleEn: 'That entails a great effort.' },
  { es: 'abordar', en: 'to tackle / to address', cefr: 'B2', domain: 'verbs', frequencyRank: 160, example: 'Hay que abordar el problema.', exampleEn: 'We need to tackle the problem.' },
  { es: 'prevenir', en: 'to prevent / to warn', cefr: 'B2', domain: 'verbs', frequencyRank: 200, example: 'Más vale prevenir que curar.', exampleEn: 'Prevention is better than cure.' },
  { es: 'cuestionar', en: 'to question / to challenge', cefr: 'B2', domain: 'verbs', frequencyRank: 220, example: 'Nadie cuestiona su autoridad.', exampleEn: "Nobody questions his authority." },
  { es: 'surgir', en: 'to arise / to emerge', cefr: 'B2', domain: 'verbs', frequencyRank: 130, example: 'Surgieron varios problemas.', exampleEn: 'Several problems arose.' },
  { es: 'carecer', en: 'to lack', cefr: 'B2', domain: 'verbs', frequencyRank: 190, example: 'El proyecto carece de financiación.', exampleEn: 'The project lacks funding.' },
  // Nouns (abstract / academic)
  { es: 'ámbito', en: 'sphere / field / scope', cefr: 'B2', domain: 'nouns', frequencyRank: 120, example: 'En el ámbito profesional es muy respetado.', exampleEn: 'In the professional field he is highly respected.' },
  { es: 'matiz', en: 'nuance / shade', cefr: 'B2', domain: 'nouns', frequencyRank: 280, example: 'Hay que entender los matices del idioma.', exampleEn: 'You need to understand the nuances of the language.' },
  { es: 'índole', en: 'nature / kind', cefr: 'B2', domain: 'nouns', frequencyRank: 290, example: 'Es un problema de índole económica.', exampleEn: 'It is an economic problem by nature.' },
  { es: 'contraste', en: 'contrast', cefr: 'B2', domain: 'nouns', frequencyRank: 230, example: 'Hay un fuerte contraste entre los dos estilos.', exampleEn: 'There is a strong contrast between the two styles.' },
  { es: 'inquietud', en: 'concern / unease / curiosity', cefr: 'B2', domain: 'nouns', frequencyRank: 310, example: 'Tengo inquietudes sobre el futuro.', exampleEn: 'I have concerns about the future.' },
  { es: 'logro', en: 'achievement / accomplishment', cefr: 'B2', domain: 'nouns', frequencyRank: 200, example: 'Es su mayor logro profesional.', exampleEn: "It's their greatest professional achievement." },
  { es: 'vínculo', en: 'link / bond / tie', cefr: 'B2', domain: 'nouns', frequencyRank: 210, example: 'Mantiene vínculos con su país de origen.', exampleEn: 'She keeps ties with her home country.' },
  { es: 'entorno', en: 'environment / surroundings', cefr: 'B2', domain: 'nouns', frequencyRank: 140, example: 'Necesita un entorno tranquilo para trabajar.', exampleEn: 'He needs a calm environment to work.' },
  { es: 'repercusión', en: 'impact / repercussion', cefr: 'B2', domain: 'nouns', frequencyRank: 260, example: 'La decisión tuvo grandes repercusiones.', exampleEn: 'The decision had major repercussions.' },
  // Adjectives
  { es: 'imprescindible', en: 'indispensable / essential', cefr: 'B2', domain: 'adjectives', frequencyRank: 220, example: 'El agua es imprescindible para la vida.', exampleEn: 'Water is essential for life.' },
  { es: 'escaso', en: 'scarce / limited', cefr: 'B2', domain: 'adjectives', frequencyRank: 230, example: 'Los recursos son escasos.', exampleEn: 'Resources are scarce.' },
  { es: 'vigente', en: 'current / in force / valid', cefr: 'B2', domain: 'adjectives', frequencyRank: 250, example: 'La ley vigente no lo permite.', exampleEn: 'The current law does not allow it.' },
  { es: 'exhaustivo', en: 'thorough / exhaustive', cefr: 'B2', domain: 'adjectives', frequencyRank: 310, example: 'Hicieron un análisis exhaustivo.', exampleEn: 'They carried out a thorough analysis.' },
  { es: 'eficaz', en: 'effective / efficient', cefr: 'B2', domain: 'adjectives', frequencyRank: 190, example: 'Es el método más eficaz.', exampleEn: 'It is the most effective method.' },
  // Emotions
  { es: 'angustia', en: 'anguish / anxiety / distress', cefr: 'B2', domain: 'nouns', frequencyRank: 300, example: 'Le invadió una profunda angustia.', exampleEn: 'A deep anguish came over him.' },
  { es: 'añoranza', en: 'longing / nostalgia', cefr: 'B2', domain: 'nouns', frequencyRank: 400, example: 'Siente añoranza de su tierra.', exampleEn: 'She feels nostalgia for her homeland.' },
  { es: 'euforia', en: 'euphoria / elation', cefr: 'B2', domain: 'nouns', frequencyRank: 350, example: 'El triunfo provocó una gran euforia.', exampleEn: 'The victory caused great elation.' },
  // Connectors (more)
  { es: 'en cambio', en: 'on the other hand / instead', cefr: 'B2', domain: 'connectors', frequencyRank: 210, example: 'Él trabaja mucho; en cambio, ella descansa.', exampleEn: 'He works hard; she, on the other hand, rests.' },
  { es: 'con respecto a', en: 'with respect to / regarding', cefr: 'B2', domain: 'connectors', frequencyRank: 230, example: 'Con respecto a tu pregunta, no tengo respuesta.', exampleEn: 'Regarding your question, I have no answer.' },
  { es: 'pese a', en: 'despite / in spite of', cefr: 'B2', domain: 'connectors', frequencyRank: 240, example: 'Salió pese a la lluvia.', exampleEn: 'She went out despite the rain.' },
  { es: 'de manera que', en: 'so that / in such a way that', cefr: 'B2', domain: 'connectors', frequencyRank: 200, example: 'Habla de manera que todos le entiendan.', exampleEn: 'He speaks so that everyone understands him.' },
  // Verbs (formal / B2)
  { es: 'alcanzar', en: 'to reach / to achieve', cefr: 'B2', domain: 'verbs', frequencyRank: 60, example: 'Alcanzaron un acuerdo histórico.', exampleEn: 'They reached a historic agreement.' },
  { es: 'rechazar', en: 'to reject / to turn down', cefr: 'B2', domain: 'verbs', frequencyRank: 130, example: 'El comité rechazó la propuesta.', exampleEn: 'The committee rejected the proposal.' },
  { es: 'implicar', en: 'to imply / to involve', cefr: 'B2', domain: 'verbs', frequencyRank: 100, example: 'Ese cargo implica mucha responsabilidad.', exampleEn: 'That role involves a lot of responsibility.' },
  { es: 'establecer', en: 'to establish / to set up', cefr: 'B2', domain: 'verbs', frequencyRank: 80, example: 'El contrato establece las condiciones.', exampleEn: 'The contract establishes the terms.' },
  { es: 'reconocer', en: 'to recognise / to acknowledge', cefr: 'B2', domain: 'verbs', frequencyRank: 90, example: 'Hay que reconocer sus méritos.', exampleEn: "We must acknowledge his merits." },
  { es: 'proponer', en: 'to propose / to suggest', cefr: 'B2', domain: 'verbs', frequencyRank: 110, example: 'Te propongo una solución diferente.', exampleEn: 'I propose a different solution to you.' },
  { es: 'garantizar', en: 'to guarantee / to ensure', cefr: 'B2', domain: 'verbs', frequencyRank: 140, example: 'No podemos garantizar el resultado.', exampleEn: 'We cannot guarantee the result.' },
  { es: 'fomentar', en: 'to promote / to foster / to encourage', cefr: 'B2', domain: 'verbs', frequencyRank: 160, example: 'El programa fomenta la lectura.', exampleEn: 'The programme fosters reading.' },
  { es: 'valorar', en: 'to value / to assess / to appreciate', cefr: 'B2', domain: 'verbs', frequencyRank: 150, example: 'Valoran mucho su trabajo en equipo.', exampleEn: 'They highly value his teamwork.' },
  { es: 'asumir', en: 'to assume / to take on / to accept', cefr: 'B2', domain: 'verbs', frequencyRank: 120, example: 'Asumió toda la responsabilidad.', exampleEn: 'She took on all the responsibility.' },
  { es: 'exigir', en: 'to demand / to require', cefr: 'B2', domain: 'verbs', frequencyRank: 130, example: 'El trabajo exige mucha concentración.', exampleEn: 'The work demands great concentration.' },
  { es: 'conllevar', en: 'to entail / to involve / to carry with it', cefr: 'B2', domain: 'verbs', frequencyRank: 210, example: 'El puesto conlleva muchas responsabilidades.', exampleEn: 'The position entails many responsibilities.' },
  // Society & politics nouns
  { es: 'ciudadano', en: 'citizen', cefr: 'B2', domain: 'nouns', frequencyRank: 90, example: 'Los ciudadanos tienen derecho a votar.', exampleEn: 'Citizens have the right to vote.' },
  { es: 'desafío', en: 'challenge', cefr: 'B2', domain: 'nouns', frequencyRank: 150, example: 'El cambio climático es un gran desafío.', exampleEn: 'Climate change is a great challenge.' },
  { es: 'medida', en: 'measure / step (government/policy)', cefr: 'B2', domain: 'nouns', frequencyRank: 80, example: 'El gobierno tomó medidas urgentes.', exampleEn: 'The government took urgent measures.' },
  { es: 'debate', en: 'debate / discussion', cefr: 'B2', domain: 'nouns', frequencyRank: 130, example: 'El debate sobre la educación continúa.', exampleEn: 'The debate about education continues.' },
  { es: 'propuesta', en: 'proposal / suggestion', cefr: 'B2', domain: 'nouns', frequencyRank: 110, example: 'Presentaron una propuesta innovadora.', exampleEn: 'They presented an innovative proposal.' },
  { es: 'inversión', en: 'investment', cefr: 'B2', domain: 'nouns', frequencyRank: 120, example: 'La inversión en educación es fundamental.', exampleEn: 'Investment in education is fundamental.' },
  // Environment nouns
  { es: 'medioambiente', en: 'natural environment', cefr: 'B2', domain: 'nouns', frequencyRank: 170, example: 'Debemos proteger el medioambiente.', exampleEn: 'We must protect the natural environment.' },
  { es: 'contaminación', en: 'pollution / contamination', cefr: 'B2', domain: 'nouns', frequencyRank: 180, example: 'La contaminación del aire es un problema grave.', exampleEn: 'Air pollution is a serious problem.' },
  { es: 'sequía', en: 'drought', cefr: 'B2', domain: 'nouns', frequencyRank: 300, example: 'La sequía afectó a toda la región.', exampleEn: 'The drought affected the entire region.' },
  // Adjectives (B2)
  { es: 'sostenible', en: 'sustainable', cefr: 'B2', domain: 'adjectives', frequencyRank: 180, example: 'Necesitamos un modelo económico sostenible.', exampleEn: 'We need a sustainable economic model.' },
  { es: 'innovador', en: 'innovative / ground-breaking', cefr: 'B2', domain: 'adjectives', frequencyRank: 190, example: 'Es un enfoque muy innovador.', exampleEn: 'It is a very innovative approach.' },
  { es: 'influyente', en: 'influential', cefr: 'B2', domain: 'adjectives', frequencyRank: 260, example: 'Es uno de los escritores más influyentes.', exampleEn: 'He is one of the most influential writers.' },
  { es: 'relevante', en: 'relevant / significant', cefr: 'B2', domain: 'adjectives', frequencyRank: 200, example: 'Es un dato muy relevante.', exampleEn: 'It is a very relevant piece of information.' },
  { es: 'polémico', en: 'controversial', cefr: 'B2', domain: 'adjectives', frequencyRank: 270, example: 'La decisión fue muy polémica.', exampleEn: 'The decision was very controversial.' },
  { es: 'favorable', en: 'favourable / positive', cefr: 'B2', domain: 'adjectives', frequencyRank: 210, example: 'Las condiciones son favorables para invertir.', exampleEn: 'Conditions are favourable for investing.' },
  // Adverbs
  { es: 'actualmente', en: 'currently / nowadays / at present', cefr: 'B2', domain: 'adverbs', frequencyRank: 90, example: 'Actualmente vivo en Madrid.', exampleEn: 'I currently live in Madrid.' },
  { es: 'aproximadamente', en: 'approximately / about', cefr: 'B2', domain: 'adverbs', frequencyRank: 150, example: 'Tardará aproximadamente una hora.', exampleEn: 'It will take approximately one hour.' },
  { es: 'progresivamente', en: 'progressively / gradually', cefr: 'B2', domain: 'adverbs', frequencyRank: 280, example: 'El número de usuarios crece progresivamente.', exampleEn: 'The number of users grows progressively.' },
  // Additional B2 nouns
  { es: 'objetivo', en: 'objective / goal / aim', cefr: 'B2', domain: 'nouns', frequencyRank: 80, example: 'Nuestro principal objetivo es reducir costes.', exampleEn: 'Our main objective is to reduce costs.' },
  { es: 'consecuencia', en: 'consequence / result', cefr: 'B2', domain: 'nouns', frequencyRank: 100, example: 'Hay que asumir las consecuencias.', exampleEn: 'You have to face the consequences.' },
  { es: 'habilidad', en: 'skill / ability', cefr: 'B2', domain: 'nouns', frequencyRank: 155, example: 'Tiene una gran habilidad para los idiomas.', exampleEn: 'She has a great ability for languages.' },
  { es: 'campaña', en: 'campaign', cefr: 'B2', domain: 'nouns', frequencyRank: 140, example: 'Lanzaron una campaña publicitaria.', exampleEn: 'They launched an advertising campaign.' },
  { es: 'impuesto', en: 'tax', cefr: 'B2', domain: 'nouns', frequencyRank: 130, example: 'El gobierno subió los impuestos.', exampleEn: 'The government raised taxes.' },
  { es: 'tendencia', en: 'trend / tendency', cefr: 'B2', domain: 'nouns', frequencyRank: 120, example: 'La tendencia es hacia el trabajo remoto.', exampleEn: 'The trend is towards remote work.' },
  { es: 'recurso', en: 'resource / means', cefr: 'B2', domain: 'nouns', frequencyRank: 110, example: 'Hay que gestionar bien los recursos.', exampleEn: 'Resources must be managed well.' },
  { es: 'compromiso', en: 'commitment / compromise', cefr: 'B2', domain: 'nouns', frequencyRank: 115, example: 'Tengo un compromiso esta tarde.', exampleEn: 'I have a commitment this afternoon.' },
  { es: 'perspectiva', en: 'perspective / outlook', cefr: 'B2', domain: 'nouns', frequencyRank: 125, example: 'Hay que verlo desde otra perspectiva.', exampleEn: 'You have to look at it from another perspective.' },
  { es: 'contribución', en: 'contribution', cefr: 'B2', domain: 'nouns', frequencyRank: 175, example: 'Hizo una gran contribución al proyecto.', exampleEn: 'She made a great contribution to the project.' },
  { es: 'sector', en: 'sector / field / area', cefr: 'B2', domain: 'nouns', frequencyRank: 95, example: 'Trabaja en el sector privado.', exampleEn: 'He works in the private sector.' },
  { es: 'conjunto', en: 'set / combination / ensemble', cefr: 'B2', domain: 'nouns', frequencyRank: 105, example: 'Un conjunto de factores influyó en la decisión.', exampleEn: 'A combination of factors influenced the decision.' },
  { es: 'plazo', en: 'deadline / term / period', cefr: 'B2', domain: 'nouns', frequencyRank: 135, example: '¿Cuál es el plazo de entrega?', exampleEn: 'What is the delivery deadline?' },
  // Additional B2 verbs
  { es: 'evaluar', en: 'to evaluate / to assess', cefr: 'B2', domain: 'verbs', frequencyRank: 145, example: 'Hay que evaluar los resultados.', exampleEn: 'We need to evaluate the results.' },
  { es: 'generar', en: 'to generate / to create / to produce', cefr: 'B2', domain: 'verbs', frequencyRank: 105, example: 'El proyecto generó muchos empleos.', exampleEn: 'The project generated many jobs.' },
  { es: 'proporcionar', en: 'to provide / to supply / to give', cefr: 'B2', domain: 'verbs', frequencyRank: 130, example: 'El gobierno proporcionó ayuda a las familias.', exampleEn: 'The government provided help to families.' },
  { es: 'planificar', en: 'to plan / to schedule', cefr: 'B2', domain: 'verbs', frequencyRank: 165, example: 'Hay que planificar bien el viaje.', exampleEn: 'You need to plan the trip carefully.' },
  // Additional B2 adjectives
  { es: 'amplio', en: 'wide / broad / ample', cefr: 'B2', domain: 'adjectives', frequencyRank: 90, example: 'Hay una amplia variedad de opciones.', exampleEn: 'There is a wide variety of options.' },
  { es: 'concreto', en: 'concrete / specific', cefr: 'B2', domain: 'adjectives', frequencyRank: 100, example: 'Necesito ejemplos concretos.', exampleEn: 'I need specific examples.' },
  { es: 'previo', en: 'prior / previous', cefr: 'B2', domain: 'adjectives', frequencyRank: 120, example: 'Se requiere experiencia previa.', exampleEn: 'Previous experience is required.' },
  { es: 'actual', en: 'current / present (not "real"!)', cefr: 'B2', domain: 'adjectives', frequencyRank: 75, example: 'La situación actual es complicada.', exampleEn: 'The current situation is complicated.' },
  { es: 'diverso', en: 'diverse / varied', cefr: 'B2', domain: 'adjectives', frequencyRank: 150, example: 'El grupo tiene orígenes muy diversos.', exampleEn: 'The group has very diverse backgrounds.' },
  { es: 'creciente', en: 'growing / increasing', cefr: 'B2', domain: 'adjectives', frequencyRank: 160, example: 'Hay una creciente demanda de energías renovables.', exampleEn: 'There is a growing demand for renewable energy.' },

  // ── C1 ─────────────────────────────────────────────────────────────────
  // Discourse connectors
  { es: 'asimismo', en: 'likewise / also / moreover', cefr: 'C1', domain: 'connectors', frequencyRank: 260, example: 'Asimismo, cabe destacar su contribución.', exampleEn: "Likewise, his contribution deserves mention." },
  { es: 'en definitiva', en: 'in short / ultimately', cefr: 'C1', domain: 'connectors', frequencyRank: 290, example: 'En definitiva, el proyecto fue un éxito.', exampleEn: 'In short, the project was a success.' },
  { es: 'a raíz de', en: 'as a result of / following', cefr: 'C1', domain: 'connectors', frequencyRank: 320, example: 'A raíz de los cambios, surgieron nuevas oportunidades.', exampleEn: 'As a result of the changes, new opportunities arose.' },
  // Abstract nouns
  { es: 'arraigo', en: 'rootedness / deep-rooted attachment', cefr: 'C1', domain: 'nouns', frequencyRank: 420, example: 'Tiene un gran arraigo en su comunidad.', exampleEn: 'He has deep roots in his community.' },
  { es: 'desenlace', en: 'outcome / denouement', cefr: 'C1', domain: 'nouns', frequencyRank: 390, example: 'El desenlace de la historia fue inesperado.', exampleEn: 'The outcome of the story was unexpected.' },
  { es: 'conjetura', en: 'conjecture / assumption', cefr: 'C1', domain: 'nouns', frequencyRank: 430, example: 'No son más que conjeturas.', exampleEn: "They're nothing more than conjectures." },
  { es: 'indicio', en: 'sign / clue / indication', cefr: 'C1', domain: 'nouns', frequencyRank: 360, example: 'No hay ningún indicio de problemas.', exampleEn: 'There is no indication of problems.' },
  { es: 'pauta', en: 'guideline / pattern / standard', cefr: 'C1', domain: 'nouns', frequencyRank: 340, example: 'Establecieron nuevas pautas de conducta.', exampleEn: 'They established new behavioural guidelines.' },
  { es: 'trayectoria', en: 'trajectory / career path', cefr: 'C1', domain: 'nouns', frequencyRank: 370, example: 'Tiene una brillante trayectoria profesional.', exampleEn: 'She has a brilliant professional career.' },
  { es: 'sesgo', en: 'bias / slant', cefr: 'C1', domain: 'nouns', frequencyRank: 380, example: 'El estudio tiene un sesgo confirmatorio.', exampleEn: 'The study has a confirmation bias.' },
  // Advanced verbs
  { es: 'dilucidar', en: 'to elucidate / to clarify', cefr: 'C1', domain: 'verbs', frequencyRank: 480, example: 'Hay que dilucidar los hechos.', exampleEn: 'We need to clarify the facts.' },
  { es: 'paliar', en: 'to alleviate / to mitigate', cefr: 'C1', domain: 'verbs', frequencyRank: 450, example: 'Las medidas paliaron el impacto económico.', exampleEn: 'The measures alleviated the economic impact.' },
  { es: 'ceder', en: 'to yield / to give way / to hand over', cefr: 'C1', domain: 'verbs', frequencyRank: 200, example: 'No cedió ante la presión.', exampleEn: 'He did not yield to pressure.' },
  { es: 'aludir', en: 'to allude / to refer to', cefr: 'C1', domain: 'verbs', frequencyRank: 410, example: 'Aludió al problema sin nombrarlo directamente.', exampleEn: 'She alluded to the problem without naming it directly.' },
  { es: 'suscitar', en: 'to provoke / to give rise to', cefr: 'C1', domain: 'verbs', frequencyRank: 395, example: 'La propuesta suscitó un intenso debate.', exampleEn: 'The proposal gave rise to an intense debate.' },
  { es: 'discernir', en: 'to discern / to distinguish', cefr: 'C1', domain: 'verbs', frequencyRank: 460, example: 'Es difícil discernir la verdad.', exampleEn: 'It is difficult to discern the truth.' },
  // Adjectives / register
  { es: 'fehaciente', en: 'conclusive / reliable / authentic', cefr: 'C1', domain: 'adjectives', frequencyRank: 500, example: 'Hay pruebas fehacientes de ello.', exampleEn: 'There is conclusive evidence of this.' },
  { es: 'sucinto', en: 'succinct / concise', cefr: 'C1', domain: 'adjectives', frequencyRank: 470, example: 'Hizo una explicación sucinta del tema.', exampleEn: 'He gave a succinct explanation of the topic.' },
  { es: 'concluyente', en: 'conclusive / decisive', cefr: 'C1', domain: 'adjectives', frequencyRank: 440, example: 'Los resultados son concluyentes.', exampleEn: 'The results are conclusive.' },
  { es: 'subyacente', en: 'underlying', cefr: 'C1', domain: 'adjectives', frequencyRank: 415, example: 'El problema subyacente no se ha resuelto.', exampleEn: 'The underlying problem has not been solved.' },
  // More connectors (C1)
  { es: 'cabe destacar', en: 'it is worth noting / it should be highlighted', cefr: 'C1', domain: 'connectors', frequencyRank: 310, example: 'Cabe destacar que los resultados superaron las expectativas.', exampleEn: 'It is worth noting that the results exceeded expectations.' },
  { es: 'en aras de', en: 'for the sake of / in the interest of', cefr: 'C1', domain: 'connectors', frequencyRank: 350, example: 'Lo hicieron en aras de la paz.', exampleEn: 'They did it for the sake of peace.' },
  { es: 'con miras a', en: 'with a view to / with the aim of', cefr: 'C1', domain: 'connectors', frequencyRank: 360, example: 'Se reunieron con miras a firmar un acuerdo.', exampleEn: 'They met with a view to signing an agreement.' },
  // More abstract nouns (C1)
  { es: 'prerrogativa', en: 'prerogative / privilege', cefr: 'C1', domain: 'nouns', frequencyRank: 430, example: 'Es prerrogativa exclusiva del presidente.', exampleEn: "It is the president's exclusive prerogative." },
  { es: 'ambigüedad', en: 'ambiguity', cefr: 'C1', domain: 'nouns', frequencyRank: 400, example: 'La ambigüedad del texto genera confusión.', exampleEn: 'The ambiguity of the text generates confusion.' },
  { es: 'idiosincrasia', en: 'idiosyncrasy / characteristic nature', cefr: 'C1', domain: 'nouns', frequencyRank: 460, example: 'Hay que respetar la idiosincrasia de cada cultura.', exampleEn: "We must respect each culture's characteristic nature." },
  { es: 'alcance', en: 'scope / reach / implication', cefr: 'C1', domain: 'nouns', frequencyRank: 130, example: 'Todavía no conocemos el alcance del problema.', exampleEn: 'We do not yet know the full scope of the problem.' },
  { es: 'bagaje', en: 'body of knowledge / background / baggage', cefr: 'C1', domain: 'nouns', frequencyRank: 420, example: 'Tiene un amplio bagaje cultural.', exampleEn: 'She has a wide cultural background.' },
  { es: 'resquicio', en: 'loophole / chink / glimmer', cefr: 'C1', domain: 'nouns', frequencyRank: 480, example: 'Encontraron un resquicio legal para evitarlo.', exampleEn: 'They found a legal loophole to avoid it.' },
  { es: 'escisión', en: 'split / schism / division', cefr: 'C1', domain: 'nouns', frequencyRank: 450, example: 'La escisión del partido sorprendió a todos.', exampleEn: 'The party split surprised everyone.' },
  { es: 'quebranto', en: 'setback / loss / grief', cefr: 'C1', domain: 'nouns', frequencyRank: 470, example: 'Fue un gran quebranto para la familia.', exampleEn: 'It was a great setback for the family.' },
  // More verbs (C1)
  { es: 'articular', en: 'to articulate / to structure / to organise', cefr: 'C1', domain: 'verbs', frequencyRank: 180, example: 'Articuló sus argumentos con claridad.', exampleEn: 'She articulated her arguments clearly.' },
  { es: 'condicionar', en: 'to condition / to shape / to determine', cefr: 'C1', domain: 'verbs', frequencyRank: 200, example: 'El entorno condiciona el comportamiento.', exampleEn: 'The environment shapes behaviour.' },
  { es: 'esclarecer', en: 'to clarify / to shed light on', cefr: 'C1', domain: 'verbs', frequencyRank: 270, example: 'La investigación esclarecerá los hechos.', exampleEn: 'The investigation will shed light on the facts.' },
  { es: 'vulnerar', en: 'to violate / to harm / to infringe', cefr: 'C1', domain: 'verbs', frequencyRank: 290, example: 'Esta ley vulnera los derechos fundamentales.', exampleEn: 'This law infringes on fundamental rights.' },
  { es: 'desvelar', en: 'to reveal / to uncover / to unveil', cefr: 'C1', domain: 'verbs', frequencyRank: 310, example: 'El periodista desveló los detalles del escándalo.', exampleEn: 'The journalist uncovered the details of the scandal.' },
  // More adjectives (C1)
  { es: 'categórico', en: 'categorical / unequivocal', cefr: 'C1', domain: 'adjectives', frequencyRank: 380, example: 'Fue un rechazo categórico.', exampleEn: 'It was a categorical refusal.' },
  { es: 'rotundo', en: 'resounding / emphatic / complete', cefr: 'C1', domain: 'adjectives', frequencyRank: 395, example: 'El equipo consiguió una victoria rotunda.', exampleEn: 'The team achieved a resounding victory.' },
  { es: 'esclarecedor', en: 'illuminating / revealing', cefr: 'C1', domain: 'adjectives', frequencyRank: 420, example: 'Fue una charla muy esclarecedora.', exampleEn: 'It was a very illuminating talk.' },
  { es: 'acérrimo', en: 'staunch / fierce / bitter (of opponents or defenders)', cefr: 'C1', domain: 'adjectives', frequencyRank: 460, example: 'Es un acérrimo defensor de los derechos humanos.', exampleEn: 'He is a staunch defender of human rights.' },
  // More C1 abstract nouns
  { es: 'paradigma', en: 'paradigm / model / framework', cefr: 'C1', domain: 'nouns', frequencyRank: 340, example: 'La IA representa un nuevo paradigma en la industria.', exampleEn: 'AI represents a new paradigm in the industry.' },
  { es: 'prerrogativa', en: 'prerogative / privilege / right', cefr: 'C1', domain: 'nouns', frequencyRank: 430, example: 'Es prerrogativa del presidente tomarlo.', exampleEn: 'It is the president\'s prerogative to decide.' },
  { es: 'heterogeneidad', en: 'heterogeneity / diversity / variety', cefr: 'C1', domain: 'nouns', frequencyRank: 450, example: 'La heterogeneidad del grupo enriquece el debate.', exampleEn: 'The diversity of the group enriches the debate.' },
  { es: 'contingencia', en: 'contingency / eventuality', cefr: 'C1', domain: 'nouns', frequencyRank: 440, example: 'Hay que prever cualquier contingencia.', exampleEn: 'Any contingency must be anticipated.' },
  { es: 'coyuntura', en: 'juncture / situation / conjuncture', cefr: 'C1', domain: 'nouns', frequencyRank: 410, example: 'La coyuntura económica es delicada.', exampleEn: 'The economic situation is delicate.' },
  { es: 'repercusión', en: 'repercussion / impact / consequence', cefr: 'C1', domain: 'nouns', frequencyRank: 370, example: 'La decisión tuvo repercusiones inesperadas.', exampleEn: 'The decision had unexpected repercussions.' },
  { es: 'estancamiento', en: 'stagnation / standstill', cefr: 'C1', domain: 'nouns', frequencyRank: 400, example: 'La economía sufre un estancamiento preocupante.', exampleEn: 'The economy is suffering a worrying stagnation.' },
  // More C1 verbs
  { es: 'cohesionar', en: 'to unite / to bind together / to create cohesion', cefr: 'C1', domain: 'verbs', frequencyRank: 450, example: 'El proyecto cohesionó al equipo.', exampleEn: 'The project united the team.' },
  { es: 'transgredir', en: 'to transgress / to violate / to break (rules)', cefr: 'C1', domain: 'verbs', frequencyRank: 420, example: 'No se puede transgredir las normas.', exampleEn: 'You cannot break the rules.' },
  { es: 'reformular', en: 'to reformulate / to rephrase', cefr: 'C1', domain: 'verbs', frequencyRank: 390, example: 'Tuvo que reformular su argumento.', exampleEn: 'She had to rephrase her argument.' },
  { es: 'concatenar', en: 'to chain / to link / to concatenate', cefr: 'C1', domain: 'verbs', frequencyRank: 470, example: 'El texto concatena ideas de forma fluida.', exampleEn: 'The text links ideas in a fluid way.' },
  { es: 'perpetuar', en: 'to perpetuate / to preserve / to sustain', cefr: 'C1', domain: 'verbs', frequencyRank: 360, example: 'El sistema perpetúa las desigualdades.', exampleEn: 'The system perpetuates inequalities.' },
  // More C1 adjectives
  { es: 'ambiguo', en: 'ambiguous / unclear', cefr: 'C1', domain: 'adjectives', frequencyRank: 300, example: 'La respuesta fue bastante ambigua.', exampleEn: 'The answer was quite ambiguous.' },
  { es: 'inherente', en: 'inherent / intrinsic', cefr: 'C1', domain: 'adjectives', frequencyRank: 320, example: 'El riesgo es inherente a la actividad.', exampleEn: 'Risk is inherent in the activity.' },
  { es: 'latente', en: 'latent / hidden / dormant', cefr: 'C1', domain: 'adjectives', frequencyRank: 350, example: 'Hay una tensión latente en el ambiente.', exampleEn: 'There is latent tension in the atmosphere.' },
  { es: 'paradigmático', en: 'paradigmatic / exemplary / archetypal', cefr: 'C1', domain: 'adjectives', frequencyRank: 440, example: 'Es un caso paradigmático de fracaso empresarial.', exampleEn: 'It is a paradigmatic case of business failure.' },
  { es: 'recurrente', en: 'recurring / recurrent', cefr: 'C1', domain: 'adjectives', frequencyRank: 330, example: 'Es un tema recurrente en su obra.', exampleEn: 'It is a recurring theme in his work.' },
  // More C1 connectors / adverbial phrases
  { es: 'no obstante lo cual', en: 'notwithstanding which / despite which', cefr: 'C1', domain: 'connectors', frequencyRank: 480, example: 'No hubo consenso; no obstante lo cual, se tomó una decisión.', exampleEn: 'There was no consensus; notwithstanding which, a decision was made.' },
  { es: 'con todo', en: 'nonetheless / even so / all the same', cefr: 'C1', domain: 'connectors', frequencyRank: 350, example: 'Fue difícil; con todo, lo conseguimos.', exampleEn: 'It was difficult; even so, we managed it.' },
  { es: 'a tenor de', en: 'in light of / in view of / given', cefr: 'C1', domain: 'connectors', frequencyRank: 400, example: 'A tenor de los resultados, hay que cambiar la estrategia.', exampleEn: 'In light of the results, the strategy must change.' },
];

// Group by domain
export function getByDomain(domain) {
  return VOCABULARY.filter(v => v.domain === domain);
}

// Group by CEFR level
export function getByCefr(level) {
  return VOCABULARY.filter(v => v.cefr === level);
}

export const DOMAINS = [...new Set(VOCABULARY.map(v => v.domain))].sort();
export const CEFR_LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1'];

// Sorted by frequency (most common first)
export const BY_FREQUENCY = [...VOCABULARY].sort((a, b) => a.frequencyRank - b.frequencyRank);
